# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2021 Shanghai StarFive Technology Co., Ltd.
#

obj-y	:= starfive_devkits.o

obj-$(CONFIG_SPL_BUILD) += spl.o

obj-$(CONFIG_ID_EEPROM) += devkits-i2c-eeprom.o
