/* SPDX-License-Identifier: GPL-2.0 OR MIT */
/*
 * Copyright (C) 2024 StarFive Technology Co., Ltd.
 *
 */

#ifndef __JHB100_PINFUNC_H__
#define __JHB100_PINFUNC_H__

/*
 * mux bits:
 *  | 31 - 15  |  14 - 13  |   12     |   11    |   10    |  9 - 8   |  7 - 0  |
 *  | reserved |  gmacvsel |  is-vsel | gpioval | is-gpio | function | gpio nr |
 *
 * gmacvsel: RGMII GMAC pads' voltage selection, 0 = 1.8V/3.3V and 1 = 2.5V
 * is-vsel:  1 = set GMAC pads VSEL
 * gpioval:  GPIO output value if pad is GPIO, 1 = logic 1 and 0 = logic 0
 * is-gpio:  1 = set GPIO logic level
 * func:     function value: 0, 1, or 2
 * gpio nr:  gpio pad number, 0 through ngpios - 1
 */
#define GMACMUX(n, func, gmacvsel) ( \
		(((gmacvsel)  & 0x3) << 13) | \
		((1 << 12)) | \
		(((func) & 0x3) << 8) | \
		((n) & 0xff))

#define GPIOVAL(n, func, gpioval) ( \
		(((gpioval)  & 0x1) << 11) | \
		((1 << 10)) | \
		(((func) & 0x3) << 8) | \
		((n) & 0xff))

#define PINMUX(n, func) ((((func) & 0x3) << 8) | ((n) & 0xff))

/* systop sys0 pad numbers */
#define PADNUM_SYSTOP_SYS0_ESPI0_CLK			4
#define PADNUM_SYSTOP_SYS0_ESPI0_CS			5
#define PADNUM_SYSTOP_SYS0_ESPI0_DATA0			6
#define PADNUM_SYSTOP_SYS0_ESPI0_DATA1			7
#define PADNUM_SYSTOP_SYS0_ESPI0_DATA2			8
#define PADNUM_SYSTOP_SYS0_ESPI0_DATA3			9
#define PADNUM_SYSTOP_SYS0_ESPI0_RESET			10
#define PADNUM_SYSTOP_SYS0_ESPI0_ALERT			11

/* systop sys2 pad numbers */
#define PADNUM_SYSTOP_SYS2_UART4_RX			10
#define PADNUM_SYSTOP_SYS2_UART4_TX			11
#define PADNUM_SYSTOP_SYS2_UART5_RX			12
#define PADNUM_SYSTOP_SYS2_UART5_TX			13
#define PADNUM_SYSTOP_SYS2_UART6_RX			14
#define PADNUM_SYSTOP_SYS2_UART6_TX			15
#define PADNUM_SYSTOP_SYS2_UART7_RX			16
#define PADNUM_SYSTOP_SYS2_UART7_TX			17
#define PADNUM_SYSTOP_SYS2_UART8_RX			18
#define PADNUM_SYSTOP_SYS2_UART8_TX			19
#define PADNUM_SYSTOP_SYS2_UART9_RX			20
#define PADNUM_SYSTOP_SYS2_UART9_TX			21
#define PADNUM_SYSTOP_SYS2_UART10_RX			22
#define PADNUM_SYSTOP_SYS2_UART10_TX			23
#define PADNUM_SYSTOP_SYS2_UART11_RX			24
#define PADNUM_SYSTOP_SYS2_UART11_TX			25
#define PADNUM_SYSTOP_SYS2_UART12_RX			26
#define PADNUM_SYSTOP_SYS2_UART12_TX			27
#define PADNUM_SYSTOP_SYS2_UART13_RX			28
#define PADNUM_SYSTOP_SYS2_UART13_TX			29
#define PADNUM_SYSTOP_SYS2_UART14_RX			30
#define PADNUM_SYSTOP_SYS2_UART14_TX			31

/* bmcperiph1 pad numbers */
#define PADNUM_BMCPERIPH1_SFC0_N_SS_OUT_0		5
#define PADNUM_BMCPERIPH1_SFC0_N_SS_OUT_1		6
#define PADNUM_BMCPERIPH1_SFC0_SCLK_OUT			7
#define PADNUM_BMCPERIPH1_SFC0_MOSI0			8
#define PADNUM_BMCPERIPH1_SFC0_MISO0			9
#define PADNUM_BMCPERIPH1_SFC0_MOSI1			10
#define PADNUM_BMCPERIPH1_SFC0_MISO1			11
#define PADNUM_BMCPERIPH1_SFC1_N_SS_OUT_0		12
#define PADNUM_BMCPERIPH1_SFC1_N_SS_OUT_1		13
#define PADNUM_BMCPERIPH1_SFC1_N_SS_OUT_2		14
#define PADNUM_BMCPERIPH1_SFC1_SCLK_OUT			15
#define PADNUM_BMCPERIPH1_SFC1_MOSI0			16
#define PADNUM_BMCPERIPH1_SFC1_MISO0			17
#define PADNUM_BMCPERIPH1_SFC1_MOSI1			18
#define PADNUM_BMCPERIPH1_SFC1_MISO1			19
#define PADNUM_BMCPERIPH1_SFC2_N_SS_OUT_0		20
#define PADNUM_BMCPERIPH1_SFC2_N_SS_OUT_1		21
#define PADNUM_BMCPERIPH1_SFC2_SCLK_OUT			22
#define PADNUM_BMCPERIPH1_SFC2_MOSI0			23
#define PADNUM_BMCPERIPH1_SFC2_MISO0			24
#define PADNUM_BMCPERIPH1_SFC2_MOSI1			25
#define PADNUM_BMCPERIPH1_SFC2_MISO1			26
#define PADNUM_BMCPERIPH1_SGPIO0_M_CLK			27
#define PADNUM_BMCPERIPH1_SGPIO0_M_LOAD			28
#define PADNUM_BMCPERIPH1_SGPIO0_M_DATA_OUT		29
#define PADNUM_BMCPERIPH1_SGPIO0_M_DATA_IN		30
#define PADNUM_BMCPERIPH1_SGPIO1_M_CLK			31
#define PADNUM_BMCPERIPH1_SGPIO1_M_LOAD			32
#define PADNUM_BMCPERIPH1_SGPIO1_M_DATA_OUT		33
#define PADNUM_BMCPERIPH1_SGPIO1_M_DATA_IN		34

/* bmcperiph2 pad numbers */
#define PADNUM_BMCPERIPH2_GMAC2_RX_CLK			37
#define PADNUM_BMCPERIPH2_RMII_RGMII_PHY_RXDV		38
#define PADNUM_BMCPERIPH2_RMII_RGMII_PHY_RXD0		39
#define PADNUM_BMCPERIPH2_RMII_RGMII_PHY_RXD1		40
#define PADNUM_BMCPERIPH2_RMII_RGMII_PHY_RXD2		41
#define PADNUM_BMCPERIPH2_RMII_RGMII_PHY_RXD3		42
#define PADNUM_BMCPERIPH2_RMII_RGMII_PHY_CRS		41
#define PADNUM_BMCPERIPH2_RMII_RGMII_PHY_RXER		42
#define PADNUM_BMCPERIPH2_GMAC2_TX_CLK			43

/* systop sys0 pad function selection */
#define FUNC_SYSTOP_SYS0_ESPI0_CLK			1
#define FUNC_SYSTOP_SYS0_ESPI0_CS			1
#define FUNC_SYSTOP_SYS0_ESPI0_DATA0			1
#define FUNC_SYSTOP_SYS0_ESPI0_DATA1			1
#define FUNC_SYSTOP_SYS0_ESPI0_DATA2			1
#define FUNC_SYSTOP_SYS0_ESPI0_DATA3			1
#define FUNC_SYSTOP_SYS0_ESPI0_RESET			1
#define FUNC_SYSTOP_SYS0_ESPI0_ALERT			1

/* systop sys2 pad function selection */
#define FUNC_SYSTOP_SYS2_UART4_RX			1
#define FUNC_SYSTOP_SYS2_UART4_TX			1
#define FUNC_SYSTOP_SYS2_UART5_RX			1
#define FUNC_SYSTOP_SYS2_UART5_TX			1
#define FUNC_SYSTOP_SYS2_UART6_RX			1
#define FUNC_SYSTOP_SYS2_UART6_TX			1
#define FUNC_SYSTOP_SYS2_UART7_RX			1
#define FUNC_SYSTOP_SYS2_UART7_TX			1
#define FUNC_SYSTOP_SYS2_UART8_RX			1
#define FUNC_SYSTOP_SYS2_UART8_TX			1
#define FUNC_SYSTOP_SYS2_UART9_RX			1
#define FUNC_SYSTOP_SYS2_UART9_TX			1
#define FUNC_SYSTOP_SYS2_UART10_RX			1
#define FUNC_SYSTOP_SYS2_UART10_TX			1
#define FUNC_SYSTOP_SYS2_UART11_RX			1
#define FUNC_SYSTOP_SYS2_UART11_TX			1
#define FUNC_SYSTOP_SYS2_UART12_RX			1
#define FUNC_SYSTOP_SYS2_UART12_TX			1
#define FUNC_SYSTOP_SYS2_UART13_RX			1
#define FUNC_SYSTOP_SYS2_UART13_TX			1
#define FUNC_SYSTOP_SYS2_UART14_RX			1
#define FUNC_SYSTOP_SYS2_UART14_TX			1

/* bmcperiph1 pad function selection */
#define FUNC_BMCPERIPH1_SFC0_N_SS_OUT_0			0
#define FUNC_BMCPERIPH1_SFC0_N_SS_OUT_1			0
#define FUNC_BMCPERIPH1_SFC0_SCLK_OUT			0
#define FUNC_BMCPERIPH1_SFC0_MOSI0			0
#define FUNC_BMCPERIPH1_SFC0_MISO0			0
#define FUNC_BMCPERIPH1_SFC0_MOSI1			0
#define FUNC_BMCPERIPH1_SFC0_MISO1			0
#define FUNC_BMCPERIPH1_SFC1_N_SS_OUT_0			1
#define FUNC_BMCPERIPH1_SFC1_N_SS_OUT_1			1
#define FUNC_BMCPERIPH1_SFC1_N_SS_OUT_2			1
#define FUNC_BMCPERIPH1_SFC1_SCLK_OUT			1
#define FUNC_BMCPERIPH1_SFC1_MOSI0			1
#define FUNC_BMCPERIPH1_SFC1_MISO0			1
#define FUNC_BMCPERIPH1_SFC1_MOSI1			1
#define FUNC_BMCPERIPH1_SFC1_MISO1			1
#define FUNC_BMCPERIPH1_SFC2_N_SS_OUT_0			1
#define FUNC_BMCPERIPH1_SFC2_N_SS_OUT_1			1
#define FUNC_BMCPERIPH1_SFC2_SCLK_OUT			1
#define FUNC_BMCPERIPH1_SFC2_MOSI0			1
#define FUNC_BMCPERIPH1_SFC2_MISO0			1
#define FUNC_BMCPERIPH1_SFC2_MOSI1			1
#define FUNC_BMCPERIPH1_SFC2_MISO1			1
#define FUNC_BMCPERIPH1_SGPIO0_M_CLK			1
#define FUNC_BMCPERIPH1_SGPIO0_M_LOAD			1
#define FUNC_BMCPERIPH1_SGPIO0_M_DATA_OUT		1
#define FUNC_BMCPERIPH1_SGPIO0_M_DATA_IN		1
#define FUNC_BMCPERIPH1_SGPIO1_M_CLK			2
#define FUNC_BMCPERIPH1_SGPIO1_M_LOAD			2
#define FUNC_BMCPERIPH1_SGPIO1_M_DATA_OUT		2
#define FUNC_BMCPERIPH1_SGPIO1_M_DATA_IN		2

/* bmcperiph2 function selection */
#define FUNC_BMCPERIPH2_GMAC2_RX_CLK			1
#define FUNC_BMCPERIPH2_RMII_RGMII_PHY_RXDV		1
#define FUNC_BMCPERIPH2_RMII_RGMII_PHY_RXD0		1
#define FUNC_BMCPERIPH2_RMII_RGMII_PHY_RXD1		1
#define FUNC_BMCPERIPH2_RMII_RGMII_PHY_RXD2		1
#define FUNC_BMCPERIPH2_RMII_RGMII_PHY_RXD3		1
#define FUNC_BMCPERIPH2_GMAC2_TX_CLK			1
#define FUNC_BMCPERIPH2_RMII_RGMII_PHY_CRS		2
#define FUNC_BMCPERIPH2_RMII_RGMII_PHY_RXER		2

#endif
