//commit:06b6362e (HEAD -> b0.8.1_dv, origin/b0.8.1_dv)

#ifndef _BMCPERIPH1_SECURE_CRG_MACRO_H_
#define _BMCPERIPH1_SECURE_CRG_MACRO_H_

//#define BMCPERIPH1_SECURE_CRG_BASE_ADDR 0x0
#define BMCPERIPH1_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR (U0_BMCPERIPH1_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)

#define BMCPERIPH1_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR (U0_BMCPERIPH1_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)






#define RSTN_U0_BMCPERIPH1_SECURE_SYSCON_PRESETN_SHIFT               0
#define RSTN_U0_BMCPERIPH1_SECURE_SYSCON_PRESETN_MASK                (0x1 << 0)
#define RSTN_U0_BMCPERIPH1_SECURE_SYSCON_PRESETN_ASSERT              1
#define RSTN_U0_BMCPERIPH1_SECURE_SYSCON_PRESETN_CLEAR               0




#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BMCPERIPH1_SECURE_SYSCON_PRESETN_ 	itg_get_reg(BMCPERIPH1_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH1_SECURE_SYSCON_PRESETN_SHIFT, RSTN_U0_BMCPERIPH1_SECURE_SYSCON_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BMCPERIPH1_SECURE_SYSCON_PRESETN_ 	itg_assert_rst(BMCPERIPH1_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH1_SECURE_SYSCON_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BMCPERIPH1_SECURE_SYSCON_PRESETN_ 	itg_clear_rst(BMCPERIPH1_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH1_SECURE_SYSCON_PRESETN_MASK)


#endif //_BMCPERIPH1_SECURE_CRG_MACRO_H_
