#define BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_0_ADDR         (U0_BMCPERIPH1_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define U4_DCU_NCNOC_TIMEOUT_VALUE_I_WIDTH                 0x1FU
#define U4_DCU_NCNOC_TIMEOUT_VALUE_I_SHIFT                 0x0U
#define U4_DCU_NCNOC_TIMEOUT_VALUE_I_MASK                  0x7FFFFFFFU
#define BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_4_ADDR         (U0_BMCPERIPH1_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_8_ADDR         (U0_BMCPERIPH1_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_12_ADDR        (U0_BMCPERIPH1_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR + 0xcU)
#define U6_DWC_SENSORS_PD_WR_LOCK_WIDTH                    0x1U
#define U6_DWC_SENSORS_PD_WR_LOCK_SHIFT                    0x10U
#define U6_DWC_SENSORS_PD_WR_LOCK_MASK                     0x10000U
#define U4_DCU_UNSPT_POWER_REQUEST_O_WIDTH                 0x1U
#define U4_DCU_UNSPT_POWER_REQUEST_O_SHIFT                 0x11U
#define U4_DCU_UNSPT_POWER_REQUEST_O_MASK                  0x20000U
#define U4_DCU_UNSPT_POWER_REQUEST_CLEAR_I_WIDTH           0x1U
#define U4_DCU_UNSPT_POWER_REQUEST_CLEAR_I_SHIFT           0x12U
#define U4_DCU_UNSPT_POWER_REQUEST_CLEAR_I_MASK            0x40000U
#define U4_DCU_NCNOC_TIMEOUT_O_WIDTH                       0x1U
#define U4_DCU_NCNOC_TIMEOUT_O_SHIFT                       0x13U
#define U4_DCU_NCNOC_TIMEOUT_O_MASK                        0x80000U
#define U4_DCU_NCNOC_TIMEOUT_EN_I_WIDTH                    0x1U
#define U4_DCU_NCNOC_TIMEOUT_EN_I_SHIFT                    0x14U
#define U4_DCU_NCNOC_TIMEOUT_EN_I_MASK                     0x100000U
#define GET_U4_DCU_NCNOC_TIMEOUT_VALUE_I                   itg_get_reg(BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_0_ADDR,U4_DCU_NCNOC_TIMEOUT_VALUE_I_SHIFT,U4_DCU_NCNOC_TIMEOUT_VALUE_I_MASK)
#define SET_U4_DCU_NCNOC_TIMEOUT_VALUE_I(data)             itg_set_reg(BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_0_ADDR,data,U4_DCU_NCNOC_TIMEOUT_VALUE_I_SHIFT,U4_DCU_NCNOC_TIMEOUT_VALUE_I_MASK)
#define GET_U6_DWC_SENSORS_PD_WR_LOCK                      itg_get_reg(BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_12_ADDR,U6_DWC_SENSORS_PD_WR_LOCK_SHIFT,U6_DWC_SENSORS_PD_WR_LOCK_MASK)
#define SET_U6_DWC_SENSORS_PD_WR_LOCK(data)                itg_set_reg(BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_12_ADDR,data,U6_DWC_SENSORS_PD_WR_LOCK_SHIFT,U6_DWC_SENSORS_PD_WR_LOCK_MASK)
#define GET_U4_DCU_UNSPT_POWER_REQUEST_O                   itg_get_reg(BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_12_ADDR,U4_DCU_UNSPT_POWER_REQUEST_O_SHIFT,U4_DCU_UNSPT_POWER_REQUEST_O_MASK)
#define GET_U4_DCU_UNSPT_POWER_REQUEST_CLEAR_I             itg_get_reg(BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_12_ADDR,U4_DCU_UNSPT_POWER_REQUEST_CLEAR_I_SHIFT,U4_DCU_UNSPT_POWER_REQUEST_CLEAR_I_MASK)
#define SET_U4_DCU_UNSPT_POWER_REQUEST_CLEAR_I(data)       itg_set_reg(BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_12_ADDR,data,U4_DCU_UNSPT_POWER_REQUEST_CLEAR_I_SHIFT,U4_DCU_UNSPT_POWER_REQUEST_CLEAR_I_MASK)
#define GET_U4_DCU_NCNOC_TIMEOUT_O                         itg_get_reg(BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_12_ADDR,U4_DCU_NCNOC_TIMEOUT_O_SHIFT,U4_DCU_NCNOC_TIMEOUT_O_MASK)
#define GET_U4_DCU_NCNOC_TIMEOUT_EN_I                      itg_get_reg(BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_12_ADDR,U4_DCU_NCNOC_TIMEOUT_EN_I_SHIFT,U4_DCU_NCNOC_TIMEOUT_EN_I_MASK)
#define SET_U4_DCU_NCNOC_TIMEOUT_EN_I(data)                itg_set_reg(BMCPERIPH1_SECURE_SYSCONITG__SYSCFG_12_ADDR,data,U4_DCU_NCNOC_TIMEOUT_EN_I_SHIFT,U4_DCU_NCNOC_TIMEOUT_EN_I_MASK)
