//commit:8ece02821 (HEAD -> b0.8.1_dv, origin/b0.8.1_dv)
#define BMCPERIPH1_SYSCONITG__SYSCFG_0_ADDR                (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define U22_APBX_RST_ADAPTOR_CFG_TO_THRESH_I_WIDTH         0x8U
#define U22_APBX_RST_ADAPTOR_CFG_TO_THRESH_I_SHIFT         0x0U
#define U22_APBX_RST_ADAPTOR_CFG_TO_THRESH_I_MASK          0xFFU
#define U22_APBX_RST_ADAPTOR_RSTEXIT_TIMEOUT_CLEAR_I_WIDTH 0x1U
#define U22_APBX_RST_ADAPTOR_RSTEXIT_TIMEOUT_CLEAR_I_SHIFT 0x8U
#define U22_APBX_RST_ADAPTOR_RSTEXIT_TIMEOUT_CLEAR_I_MASK  0x100U
#define BMCPERIPH1_SYSCONITG__SYSCFG_4_ADDR                (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_8_ADDR                (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define U0_DWC_SSI_SFC_DBG_SPI_DTR_EN_WIDTH                0x1U
#define U0_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT                0x0U
#define U0_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK                 0x1U
#define U0_DWC_SSI_SFC_SSI_BUSY_WIDTH                      0x1U
#define U0_DWC_SSI_SFC_SSI_BUSY_SHIFT                      0x1U
#define U0_DWC_SSI_SFC_SSI_BUSY_MASK                       0x2U
#define BMCPERIPH1_SYSCONITG__SYSCFG_12_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0xcU)
#define U1_DWC_SSI_SFC_DBG_SPI_DTR_EN_WIDTH                0x1U
#define U1_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT                0x0U
#define U1_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK                 0x1U
#define U1_DWC_SSI_SFC_SSI_BUSY_WIDTH                      0x1U
#define U1_DWC_SSI_SFC_SSI_BUSY_SHIFT                      0x1U
#define U1_DWC_SSI_SFC_SSI_BUSY_MASK                       0x2U
#define BMCPERIPH1_SYSCONITG__SYSCFG_16_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define U2_DWC_SSI_SFC_DBG_SPI_DTR_EN_WIDTH                0x1U
#define U2_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT                0x0U
#define U2_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK                 0x1U
#define U2_DWC_SSI_SFC_SSI_BUSY_WIDTH                      0x1U
#define U2_DWC_SSI_SFC_SSI_BUSY_SHIFT                      0x1U
#define U2_DWC_SSI_SFC_SSI_BUSY_MASK                       0x2U
#define BMCPERIPH1_SYSCONITG__SYSCFG_20_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define U0_DWC_SSI_SPI_SS_IN_N_WIDTH                       0x1U
#define U0_DWC_SSI_SPI_SS_IN_N_SHIFT                       0x0U
#define U0_DWC_SSI_SPI_SS_IN_N_MASK                        0x1U
#define U0_DWC_SSI_SPI_SSI_BUSY_WIDTH                      0x1U
#define U0_DWC_SSI_SPI_SSI_BUSY_SHIFT                      0x1U
#define U0_DWC_SSI_SPI_SSI_BUSY_MASK                       0x2U
#define BMCPERIPH1_SYSCONITG__SYSCFG_24_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_28_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x1cU)
#define BMCPERIPH1_SYSCONITG__SYSCFG_32_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x20U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_36_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x24U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_40_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x28U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_44_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x2cU)
#define BMCPERIPH1_SYSCONITG__SYSCFG_48_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x30U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_52_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x34U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_56_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x38U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_60_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x3cU)
#define BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x40U)
#define U0_PLL7_PLL_BYPASS_WIDTH                           0x1U
#define U0_PLL7_PLL_BYPASS_SHIFT                           0x0U
#define U0_PLL7_PLL_BYPASS_MASK                            0x1U
#define U0_PLL7_PLL_DSMPD_WIDTH                            0x1U
#define U0_PLL7_PLL_DSMPD_SHIFT                            0x1U
#define U0_PLL7_PLL_DSMPD_MASK                             0x2U
#define U0_PLL7_PLL_FBDIV_WIDTH                            0xCU
#define U0_PLL7_PLL_FBDIV_SHIFT                            0x2U
#define U0_PLL7_PLL_FBDIV_MASK                             0x3FFCU
#define U0_PLL7_PLL_FOUTPOSTDIV_EN_WIDTH                   0x1U
#define U0_PLL7_PLL_FOUTPOSTDIV_EN_SHIFT                   0xEU
#define U0_PLL7_PLL_FOUTPOSTDIV_EN_MASK                    0x4000U
#define U0_PLL7_PLL_FOUTPOSTDIVPD_WIDTH                    0x1U
#define U0_PLL7_PLL_FOUTPOSTDIVPD_SHIFT                    0xFU
#define U0_PLL7_PLL_FOUTPOSTDIVPD_MASK                     0x8000U
#define U0_PLL7_PLL_FOUTVCOP_EN_WIDTH                      0x1U
#define U0_PLL7_PLL_FOUTVCOP_EN_SHIFT                      0x10U
#define U0_PLL7_PLL_FOUTVCOP_EN_MASK                       0x10000U
#define BMCPERIPH1_SYSCONITG__SYSCFG_68_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x44U)
#define U0_PLL7_PLL_FRAC_WIDTH                             0x18U
#define U0_PLL7_PLL_FRAC_SHIFT                             0x0U
#define U0_PLL7_PLL_FRAC_MASK                              0xFFFFFFU
#define U0_PLL7_PLL_LOCK_WIDTH                             0x1U
#define U0_PLL7_PLL_LOCK_SHIFT                             0x18U
#define U0_PLL7_PLL_LOCK_MASK                              0x1000000U
#define U0_PLL7_PLL_OFFSETCALCNT_WIDTH                     0x3U
#define U0_PLL7_PLL_OFFSETCALCNT_SHIFT                     0x19U
#define U0_PLL7_PLL_OFFSETCALCNT_MASK                      0xE000000U
#define U0_PLL7_PLL_OFFSETCALLOCK_WIDTH                    0x1U
#define U0_PLL7_PLL_OFFSETCALLOCK_SHIFT                    0x1DU
#define U0_PLL7_PLL_OFFSETCALLOCK_MASK                     0x20000000U
#define BMCPERIPH1_SYSCONITG__SYSCFG_72_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x48U)
#define U0_PLL7_PLL_OFFSETCALOUT_WIDTH                     0xCU
#define U0_PLL7_PLL_OFFSETCALOUT_SHIFT                     0x0U
#define U0_PLL7_PLL_OFFSETCALOUT_MASK                      0xFFFU
#define U0_PLL7_PLL_OFFSETFASTCAL_WIDTH                    0x1U
#define U0_PLL7_PLL_OFFSETFASTCAL_SHIFT                    0xCU
#define U0_PLL7_PLL_OFFSETFASTCAL_MASK                     0x1000U
#define U0_PLL7_PLL_PD_WIDTH                               0x1U
#define U0_PLL7_PLL_PD_SHIFT                               0xDU
#define U0_PLL7_PLL_PD_MASK                                0x2000U
#define U0_PLL7_PLL_POSTDIV_WIDTH                          0x2U
#define U0_PLL7_PLL_POSTDIV_SHIFT                          0xEU
#define U0_PLL7_PLL_POSTDIV_MASK                           0xC000U
#define U0_PLL7_PLL_REFDIV_WIDTH                           0x6U
#define U0_PLL7_PLL_REFDIV_SHIFT                           0x12U
#define U0_PLL7_PLL_REFDIV_MASK                            0xFC0000U
#define BMCPERIPH1_SYSCONITG__SYSCFG_76_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x4cU)
#define U3_RAS_ELS_EP_CONN_TIMEOUT_EN_I_WIDTH              0x1U
#define U3_RAS_ELS_EP_CONN_TIMEOUT_EN_I_SHIFT              0x0U
#define U3_RAS_ELS_EP_CONN_TIMEOUT_EN_I_MASK               0x1U
#define U3_RAS_ELS_EP_CONN_TIMEOUT_O_WIDTH                 0x1U
#define U3_RAS_ELS_EP_CONN_TIMEOUT_O_SHIFT                 0x1U
#define U3_RAS_ELS_EP_CONN_TIMEOUT_O_MASK                  0x2U
#define BMCPERIPH1_SYSCONITG__SYSCFG_80_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x50U)
#define U3_RAS_ELS_EP_CONN_TIMEOUT_VALUE_I_WIDTH           0x1FU
#define U3_RAS_ELS_EP_CONN_TIMEOUT_VALUE_I_SHIFT           0x0U
#define U3_RAS_ELS_EP_CONN_TIMEOUT_VALUE_I_MASK            0x7FFFFFFFU
#define BMCPERIPH1_SYSCONITG__SYSCFG_84_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x54U)
#define U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_EN_I_WIDTH       0x1U
#define U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_EN_I_SHIFT       0x0U
#define U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_EN_I_MASK        0x1U
#define U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_VALUE_I_WIDTH    0x7U
#define U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_VALUE_I_SHIFT    0x1U
#define U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_VALUE_I_MASK     0xFEU
#define U3_RAS_ELS_EP_DISCONN_TIMEOUT_EN_I_WIDTH           0x1U
#define U3_RAS_ELS_EP_DISCONN_TIMEOUT_EN_I_SHIFT           0x9U
#define U3_RAS_ELS_EP_DISCONN_TIMEOUT_EN_I_MASK            0x200U
#define U3_RAS_ELS_EP_DISCONN_TIMEOUT_O_WIDTH              0x1U
#define U3_RAS_ELS_EP_DISCONN_TIMEOUT_O_SHIFT              0xAU
#define U3_RAS_ELS_EP_DISCONN_TIMEOUT_O_MASK               0x400U
#define BMCPERIPH1_SYSCONITG__SYSCFG_88_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x58U)
#define U3_RAS_ELS_EP_DISCONN_TIMEOUT_VALUE_I_WIDTH        0x1FU
#define U3_RAS_ELS_EP_DISCONN_TIMEOUT_VALUE_I_SHIFT        0x0U
#define U3_RAS_ELS_EP_DISCONN_TIMEOUT_VALUE_I_MASK         0x7FFFFFFFU
#define BMCPERIPH1_SYSCONITG__SYSCFG_92_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x5cU)
#define U3_RAS_ELS_EP_IDISCONN_TIMEOUT_O_WIDTH             0x1U
#define U3_RAS_ELS_EP_IDISCONN_TIMEOUT_O_SHIFT             0x0U
#define U3_RAS_ELS_EP_IDISCONN_TIMEOUT_O_MASK              0x1U
#define U3_RAS_ELS_EP_RENABLE_WIDTH                        0x1U
#define U3_RAS_ELS_EP_RENABLE_SHIFT                        0x1U
#define U3_RAS_ELS_EP_RENABLE_MASK                         0x2U
#define BMCPERIPH1_SYSCONITG__SYSCFG_96_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x60U)
#define U12_RCSUB_SWHW_RST_ACK_O_WIDTH                     0x1U
#define U12_RCSUB_SWHW_RST_ACK_O_SHIFT                     0x0U
#define U12_RCSUB_SWHW_RST_ACK_O_MASK                      0x1U
#define U12_RCSUB_SWHW_RST_REQ_I_WIDTH                     0x1U
#define U12_RCSUB_SWHW_RST_REQ_I_SHIFT                     0x1U
#define U12_RCSUB_SWHW_RST_REQ_I_MASK                      0x2U
#define GET_U22_APBX_RST_ADAPTOR_CFG_TO_THRESH_I           itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_0_ADDR,U22_APBX_RST_ADAPTOR_CFG_TO_THRESH_I_SHIFT,U22_APBX_RST_ADAPTOR_CFG_TO_THRESH_I_MASK)
#define SET_U22_APBX_RST_ADAPTOR_CFG_TO_THRESH_I(data)     itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_0_ADDR,data,U22_APBX_RST_ADAPTOR_CFG_TO_THRESH_I_SHIFT,U22_APBX_RST_ADAPTOR_CFG_TO_THRESH_I_MASK)
#define GET_U22_APBX_RST_ADAPTOR_RSTEXIT_TIMEOUT_CLEAR_I   itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_0_ADDR,U22_APBX_RST_ADAPTOR_RSTEXIT_TIMEOUT_CLEAR_I_SHIFT,U22_APBX_RST_ADAPTOR_RSTEXIT_TIMEOUT_CLEAR_I_MASK)
#define SET_U22_APBX_RST_ADAPTOR_RSTEXIT_TIMEOUT_CLEAR_I(data) itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_0_ADDR,data,U22_APBX_RST_ADAPTOR_RSTEXIT_TIMEOUT_CLEAR_I_SHIFT,U22_APBX_RST_ADAPTOR_RSTEXIT_TIMEOUT_CLEAR_I_MASK)
#define GET_U0_DWC_SSI_SFC_DBG_SPI_DTR_EN                  itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_8_ADDR,U0_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT,U0_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK)
#define GET_U0_DWC_SSI_SFC_SSI_BUSY                        itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_8_ADDR,U0_DWC_SSI_SFC_SSI_BUSY_SHIFT,U0_DWC_SSI_SFC_SSI_BUSY_MASK)
#define GET_U1_DWC_SSI_SFC_DBG_SPI_DTR_EN                  itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_12_ADDR,U1_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT,U1_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK)
#define GET_U1_DWC_SSI_SFC_SSI_BUSY                        itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_12_ADDR,U1_DWC_SSI_SFC_SSI_BUSY_SHIFT,U1_DWC_SSI_SFC_SSI_BUSY_MASK)
#define GET_U2_DWC_SSI_SFC_DBG_SPI_DTR_EN                  itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_16_ADDR,U2_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT,U2_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK)
#define GET_U2_DWC_SSI_SFC_SSI_BUSY                        itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_16_ADDR,U2_DWC_SSI_SFC_SSI_BUSY_SHIFT,U2_DWC_SSI_SFC_SSI_BUSY_MASK)
#define GET_U0_DWC_SSI_SPI_SS_IN_N                         itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_20_ADDR,U0_DWC_SSI_SPI_SS_IN_N_SHIFT,U0_DWC_SSI_SPI_SS_IN_N_MASK)
#define SET_U0_DWC_SSI_SPI_SS_IN_N(data)                   itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_20_ADDR,data,U0_DWC_SSI_SPI_SS_IN_N_SHIFT,U0_DWC_SSI_SPI_SS_IN_N_MASK)
#define GET_U0_DWC_SSI_SPI_SSI_BUSY                        itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_20_ADDR,U0_DWC_SSI_SPI_SSI_BUSY_SHIFT,U0_DWC_SSI_SPI_SSI_BUSY_MASK)
#define GET_U0_PLL7_PLL_BYPASS                             itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,U0_PLL7_PLL_BYPASS_SHIFT,U0_PLL7_PLL_BYPASS_MASK)
#define SET_U0_PLL7_PLL_BYPASS(data)                       itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,data,U0_PLL7_PLL_BYPASS_SHIFT,U0_PLL7_PLL_BYPASS_MASK)
#define GET_U0_PLL7_PLL_DSMPD                              itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,U0_PLL7_PLL_DSMPD_SHIFT,U0_PLL7_PLL_DSMPD_MASK)
#define SET_U0_PLL7_PLL_DSMPD(data)                        itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,data,U0_PLL7_PLL_DSMPD_SHIFT,U0_PLL7_PLL_DSMPD_MASK)
#define GET_U0_PLL7_PLL_FBDIV                              itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,U0_PLL7_PLL_FBDIV_SHIFT,U0_PLL7_PLL_FBDIV_MASK)
#define SET_U0_PLL7_PLL_FBDIV(data)                        itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,data,U0_PLL7_PLL_FBDIV_SHIFT,U0_PLL7_PLL_FBDIV_MASK)
#define GET_U0_PLL7_PLL_FOUTPOSTDIV_EN                     itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,U0_PLL7_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL7_PLL_FOUTPOSTDIV_EN_MASK)
#define SET_U0_PLL7_PLL_FOUTPOSTDIV_EN(data)               itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,data,U0_PLL7_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL7_PLL_FOUTPOSTDIV_EN_MASK)
#define GET_U0_PLL7_PLL_FOUTPOSTDIVPD                      itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,U0_PLL7_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL7_PLL_FOUTPOSTDIVPD_MASK)
#define SET_U0_PLL7_PLL_FOUTPOSTDIVPD(data)                itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,data,U0_PLL7_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL7_PLL_FOUTPOSTDIVPD_MASK)
#define GET_U0_PLL7_PLL_FOUTVCOP_EN                        itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,U0_PLL7_PLL_FOUTVCOP_EN_SHIFT,U0_PLL7_PLL_FOUTVCOP_EN_MASK)
#define SET_U0_PLL7_PLL_FOUTVCOP_EN(data)                  itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_64_ADDR,data,U0_PLL7_PLL_FOUTVCOP_EN_SHIFT,U0_PLL7_PLL_FOUTVCOP_EN_MASK)
#define GET_U0_PLL7_PLL_FRAC                               itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_68_ADDR,U0_PLL7_PLL_FRAC_SHIFT,U0_PLL7_PLL_FRAC_MASK)
#define SET_U0_PLL7_PLL_FRAC(data)                         itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_68_ADDR,data,U0_PLL7_PLL_FRAC_SHIFT,U0_PLL7_PLL_FRAC_MASK)
#define GET_U0_PLL7_PLL_LOCK                               itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_68_ADDR,U0_PLL7_PLL_LOCK_SHIFT,U0_PLL7_PLL_LOCK_MASK)
#define GET_U0_PLL7_PLL_OFFSETCALCNT                       itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_68_ADDR,U0_PLL7_PLL_OFFSETCALCNT_SHIFT,U0_PLL7_PLL_OFFSETCALCNT_MASK)
#define SET_U0_PLL7_PLL_OFFSETCALCNT(data)                 itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_68_ADDR,data,U0_PLL7_PLL_OFFSETCALCNT_SHIFT,U0_PLL7_PLL_OFFSETCALCNT_MASK)
#define GET_U0_PLL7_PLL_OFFSETCALLOCK                      itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_68_ADDR,U0_PLL7_PLL_OFFSETCALLOCK_SHIFT,U0_PLL7_PLL_OFFSETCALLOCK_MASK)
#define GET_U0_PLL7_PLL_OFFSETCALOUT                       itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_72_ADDR,U0_PLL7_PLL_OFFSETCALOUT_SHIFT,U0_PLL7_PLL_OFFSETCALOUT_MASK)
#define GET_U0_PLL7_PLL_OFFSETFASTCAL                      itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_72_ADDR,U0_PLL7_PLL_OFFSETFASTCAL_SHIFT,U0_PLL7_PLL_OFFSETFASTCAL_MASK)
#define SET_U0_PLL7_PLL_OFFSETFASTCAL(data)                itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL7_PLL_OFFSETFASTCAL_SHIFT,U0_PLL7_PLL_OFFSETFASTCAL_MASK)
#define GET_U0_PLL7_PLL_PD                                 itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_72_ADDR,U0_PLL7_PLL_PD_SHIFT,U0_PLL7_PLL_PD_MASK)
#define SET_U0_PLL7_PLL_PD(data)                           itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL7_PLL_PD_SHIFT,U0_PLL7_PLL_PD_MASK)
#define GET_U0_PLL7_PLL_POSTDIV                            itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_72_ADDR,U0_PLL7_PLL_POSTDIV_SHIFT,U0_PLL7_PLL_POSTDIV_MASK)
#define SET_U0_PLL7_PLL_POSTDIV(data)                      itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL7_PLL_POSTDIV_SHIFT,U0_PLL7_PLL_POSTDIV_MASK)
#define GET_U0_PLL7_PLL_REFDIV                             itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_72_ADDR,U0_PLL7_PLL_REFDIV_SHIFT,U0_PLL7_PLL_REFDIV_MASK)
#define SET_U0_PLL7_PLL_REFDIV(data)                       itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL7_PLL_REFDIV_SHIFT,U0_PLL7_PLL_REFDIV_MASK)
#define GET_U3_RAS_ELS_EP_CONN_TIMEOUT_EN_I                itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_76_ADDR,U3_RAS_ELS_EP_CONN_TIMEOUT_EN_I_SHIFT,U3_RAS_ELS_EP_CONN_TIMEOUT_EN_I_MASK)
#define SET_U3_RAS_ELS_EP_CONN_TIMEOUT_EN_I(data)          itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_76_ADDR,data,U3_RAS_ELS_EP_CONN_TIMEOUT_EN_I_SHIFT,U3_RAS_ELS_EP_CONN_TIMEOUT_EN_I_MASK)
#define GET_U3_RAS_ELS_EP_CONN_TIMEOUT_O                   itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_76_ADDR,U3_RAS_ELS_EP_CONN_TIMEOUT_O_SHIFT,U3_RAS_ELS_EP_CONN_TIMEOUT_O_MASK)
#define GET_U3_RAS_ELS_EP_CONN_TIMEOUT_VALUE_I             itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_80_ADDR,U3_RAS_ELS_EP_CONN_TIMEOUT_VALUE_I_SHIFT,U3_RAS_ELS_EP_CONN_TIMEOUT_VALUE_I_MASK)
#define SET_U3_RAS_ELS_EP_CONN_TIMEOUT_VALUE_I(data)       itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_80_ADDR,data,U3_RAS_ELS_EP_CONN_TIMEOUT_VALUE_I_SHIFT,U3_RAS_ELS_EP_CONN_TIMEOUT_VALUE_I_MASK)
#define GET_U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_EN_I         itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_84_ADDR,U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_EN_I_SHIFT,U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_EN_I_MASK)
#define SET_U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_EN_I(data)   itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_84_ADDR,data,U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_EN_I_SHIFT,U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_EN_I_MASK)
#define GET_U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_VALUE_I      itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_84_ADDR,U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_VALUE_I_SHIFT,U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_VALUE_I_MASK)
#define SET_U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_VALUE_I(data) itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_84_ADDR,data,U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_VALUE_I_SHIFT,U3_RAS_ELS_EP_COUNT2DISCONN_TIMER_VALUE_I_MASK)
#define GET_U3_RAS_ELS_EP_DISCONN_TIMEOUT_EN_I             itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_84_ADDR,U3_RAS_ELS_EP_DISCONN_TIMEOUT_EN_I_SHIFT,U3_RAS_ELS_EP_DISCONN_TIMEOUT_EN_I_MASK)
#define SET_U3_RAS_ELS_EP_DISCONN_TIMEOUT_EN_I(data)       itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_84_ADDR,data,U3_RAS_ELS_EP_DISCONN_TIMEOUT_EN_I_SHIFT,U3_RAS_ELS_EP_DISCONN_TIMEOUT_EN_I_MASK)
#define GET_U3_RAS_ELS_EP_DISCONN_TIMEOUT_O                itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_84_ADDR,U3_RAS_ELS_EP_DISCONN_TIMEOUT_O_SHIFT,U3_RAS_ELS_EP_DISCONN_TIMEOUT_O_MASK)
#define GET_U3_RAS_ELS_EP_DISCONN_TIMEOUT_VALUE_I          itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_88_ADDR,U3_RAS_ELS_EP_DISCONN_TIMEOUT_VALUE_I_SHIFT,U3_RAS_ELS_EP_DISCONN_TIMEOUT_VALUE_I_MASK)
#define SET_U3_RAS_ELS_EP_DISCONN_TIMEOUT_VALUE_I(data)    itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_88_ADDR,data,U3_RAS_ELS_EP_DISCONN_TIMEOUT_VALUE_I_SHIFT,U3_RAS_ELS_EP_DISCONN_TIMEOUT_VALUE_I_MASK)
#define GET_U3_RAS_ELS_EP_IDISCONN_TIMEOUT_O               itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_92_ADDR,U3_RAS_ELS_EP_IDISCONN_TIMEOUT_O_SHIFT,U3_RAS_ELS_EP_IDISCONN_TIMEOUT_O_MASK)
#define GET_U3_RAS_ELS_EP_RENABLE                          itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_92_ADDR,U3_RAS_ELS_EP_RENABLE_SHIFT,U3_RAS_ELS_EP_RENABLE_MASK)
#define SET_U3_RAS_ELS_EP_RENABLE(data)                    itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_92_ADDR,data,U3_RAS_ELS_EP_RENABLE_SHIFT,U3_RAS_ELS_EP_RENABLE_MASK)
#define GET_U12_RCSUB_SWHW_RST_ACK_O                       itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_96_ADDR,U12_RCSUB_SWHW_RST_ACK_O_SHIFT,U12_RCSUB_SWHW_RST_ACK_O_MASK)
#define GET_U12_RCSUB_SWHW_RST_REQ_I                       itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_96_ADDR,U12_RCSUB_SWHW_RST_REQ_I_SHIFT,U12_RCSUB_SWHW_RST_REQ_I_MASK)
#define SET_U12_RCSUB_SWHW_RST_REQ_I(data)                 itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_96_ADDR,data,U12_RCSUB_SWHW_RST_REQ_I_SHIFT,U12_RCSUB_SWHW_RST_REQ_I_MASK)
