#define BMCPERIPH1_SYSCONITG__SYSCFG_0_ADDR                (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_4_ADDR                (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_8_ADDR                (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_12_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0xcU)
#define BMCPERIPH1_SYSCONITG__SYSCFG_16_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_20_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_24_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define BMCPERIPH1_SYSCONITG__SYSCFG_28_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x1cU)
#define U2_DWC_SSI_SFC_SSI_BUSY_WIDTH                      0x1U
#define U2_DWC_SSI_SFC_SSI_BUSY_SHIFT                      0x1CU
#define U2_DWC_SSI_SFC_SSI_BUSY_MASK                       0x10000000U
#define U2_DWC_SSI_SFC_DBG_SPI_DTR_EN_WIDTH                0x1U
#define U2_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT                0x1DU
#define U2_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK                 0x20000000U
#define U1_DWC_SSI_SFC_SSI_BUSY_WIDTH                      0x1U
#define U1_DWC_SSI_SFC_SSI_BUSY_SHIFT                      0x1EU
#define U1_DWC_SSI_SFC_SSI_BUSY_MASK                       0x40000000U
#define U1_DWC_SSI_SFC_DBG_SPI_DTR_EN_WIDTH                0x1U
#define U1_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT                0x1FU
#define U1_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK                 0x80000000U
#define BMCPERIPH1_SYSCONITG__SYSCFG_32_ADDR               (U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x20U)
#define U0_DWC_SSI_SPI_SSI_BUSY_WIDTH                      0x1U
#define U0_DWC_SSI_SPI_SSI_BUSY_SHIFT                      0x7U
#define U0_DWC_SSI_SPI_SSI_BUSY_MASK                       0x80U
#define U0_DWC_SSI_SPI_SS_IN_N_WIDTH                       0x1U
#define U0_DWC_SSI_SPI_SS_IN_N_SHIFT                       0x8U
#define U0_DWC_SSI_SPI_SS_IN_N_MASK                        0x100U
#define U0_DWC_SSI_SFC_SSI_BUSY_WIDTH                      0x1U
#define U0_DWC_SSI_SFC_SSI_BUSY_SHIFT                      0x9U
#define U0_DWC_SSI_SFC_SSI_BUSY_MASK                       0x200U
#define U0_DWC_SSI_SFC_DBG_SPI_DTR_EN_WIDTH                0x1U
#define U0_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT                0xAU
#define U0_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK                 0x400U
#define GET_U2_DWC_SSI_SFC_SSI_BUSY                        itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_28_ADDR,U2_DWC_SSI_SFC_SSI_BUSY_SHIFT,U2_DWC_SSI_SFC_SSI_BUSY_MASK)
#define GET_U2_DWC_SSI_SFC_DBG_SPI_DTR_EN                  itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_28_ADDR,U2_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT,U2_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK)
#define GET_U1_DWC_SSI_SFC_SSI_BUSY                        itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_28_ADDR,U1_DWC_SSI_SFC_SSI_BUSY_SHIFT,U1_DWC_SSI_SFC_SSI_BUSY_MASK)
#define GET_U1_DWC_SSI_SFC_DBG_SPI_DTR_EN                  itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_28_ADDR,U1_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT,U1_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK)
#define GET_U0_DWC_SSI_SPI_SSI_BUSY                        itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_32_ADDR,U0_DWC_SSI_SPI_SSI_BUSY_SHIFT,U0_DWC_SSI_SPI_SSI_BUSY_MASK)
#define GET_U0_DWC_SSI_SPI_SS_IN_N                         itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_32_ADDR,U0_DWC_SSI_SPI_SS_IN_N_SHIFT,U0_DWC_SSI_SPI_SS_IN_N_MASK)
#define SET_U0_DWC_SSI_SPI_SS_IN_N(data)                   itg_set_reg(BMCPERIPH1_SYSCONITG__SYSCFG_32_ADDR,data,U0_DWC_SSI_SPI_SS_IN_N_SHIFT,U0_DWC_SSI_SPI_SS_IN_N_MASK)
#define GET_U0_DWC_SSI_SFC_SSI_BUSY                        itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_32_ADDR,U0_DWC_SSI_SFC_SSI_BUSY_SHIFT,U0_DWC_SSI_SFC_SSI_BUSY_MASK)
#define GET_U0_DWC_SSI_SFC_DBG_SPI_DTR_EN                  itg_get_reg(BMCPERIPH1_SYSCONITG__SYSCFG_32_ADDR,U0_DWC_SSI_SFC_DBG_SPI_DTR_EN_SHIFT,U0_DWC_SSI_SFC_DBG_SPI_DTR_EN_MASK)
