//commit:8ece02821 (HEAD -> b0.8.1_dv, origin/b0.8.1_dv)

#ifndef _BMCPERIPH1_CRG_MACRO_H_
#define _BMCPERIPH1_CRG_MACRO_H_

//#define BMCPERIPH1_CRG_BASE_ADDR 0x0
#define CLK_BMCPERIPH1_100_CTRL_REG_ADDR                             (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_BMCPERIPH1_1_CTRL_REG_ADDR                               (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define CLK_BMCPERIPH1_200_DIVN0_CTRL_REG_ADDR                       (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define CLK_BMCPERIPH1_200_DIVN1_CTRL_REG_ADDR                       (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)
#define CLK_BMCPERIPH1_200_DIVN2_CTRL_REG_ADDR                       (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define CLK_BMCPERIPH1_200_DIVN3_CTRL_REG_ADDR                       (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define CLK_BMCPERIPH1_200_CCLK_DIV_CTRL_REG_ADDR                    (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define CLK_U0_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR                        (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x1CU)
#define CLK_U0_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR                     (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x20U)
#define CLK_U1_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR                        (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x24U)
#define CLK_U1_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR                     (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x28U)
#define CLK_U2_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR                        (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x2CU)
#define CLK_U2_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR                     (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x30U)
#define CLK_U0_DWC_SSI_SPI_HCLK_CTRL_REG_ADDR                        (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x34U)
#define CLK_U0_DWC_SSI_SPI_SSI_CLK_CTRL_REG_ADDR                     (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x38U)
#define CLK_U0_SGPIO_PCLK_CTRL_REG_ADDR                              (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x3CU)
#define CLK_U0_SGPIO_DCLK_CTRL_REG_ADDR                              (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x40U)
#define CLK_U1_SGPIO_PCLK_CTRL_REG_ADDR                              (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x44U)
#define CLK_U1_SGPIO_DCLK_CTRL_REG_ADDR                              (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x48U)
#define CLK_U6_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR                  (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x4CU)
#define CLK_U1_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR                    (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x70U)
#define CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR         (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x74U)
#define CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR                  (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x78U)
#define CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR                 (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x7CU)
#define CLK_U2_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR                    (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x80U)
#define CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR         (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x84U)
#define CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR                  (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x88U)
#define CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR                 (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x8CU)
#define CLK_U3_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR                    (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x90U)
#define CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR         (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x94U)
#define CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR                  (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x98U)
#define CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR                 (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x9CU)
#define CLK_U4_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR                    (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0xA0U)
#define CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR         (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0xA4U)
#define CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR                  (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0xA8U)
#define CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR                 (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0xACU)
#define CLK_U3_RAS_ELS_EP_M_ACLK_CTRL_REG_ADDR                       (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0xB0U)


#define MAIN_ICG_EN_SFC0_CTRL_REG_ADDR                               (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0xFCU)
#define MAIN_ICG_EN_SFC1_CTRL_REG_ADDR                               (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x100U)
#define MAIN_ICG_EN_SFC2_CTRL_REG_ADDR                               (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x104U)
#define MAIN_ICG_EN_SPI0_CTRL_REG_ADDR                               (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x108U)
#define MAIN_ICG_EN_SGPIO0_CTRL_REG_ADDR                             (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x10CU)
#define MAIN_ICG_EN_SGPIO1_CTRL_REG_ADDR                             (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x110U)
#define MAIN_ICG_EN_SENSOR_CTRL_REG_ADDR                             (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x114U)
#define MAIN_ICG_EN_DMAC_SFC0_CTRL_REG_ADDR                          (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x11CU)
#define MAIN_ICG_EN_DMAC_SFC1_CTRL_REG_ADDR                          (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x120U)
#define MAIN_ICG_EN_DMAC_SFC2_CTRL_REG_ADDR                          (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x124U)
#define MAIN_ICG_EN_DMAC_SPI0_CTRL_REG_ADDR                          (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x128U)
#define MAIN_ICG_EN_PERIPH1_RAS_CTRL_REG_ADDR                        (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x12CU)


#define BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR        (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x134U)

#define BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR        (U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR + 0x138U)


#define CLK_BMCPERIPH1_100_DIV_SHIFT                                 0
#define CLK_BMCPERIPH1_100_DIV_MASK                                  0xFU
#define CLK_BMCPERIPH1_1_DIV_SHIFT                                   0
#define CLK_BMCPERIPH1_1_DIV_MASK                                    0x7FU
#define CLK_BMCPERIPH1_200_DIVN0_DIV_SHIFT                           0
#define CLK_BMCPERIPH1_200_DIVN0_DIV_MASK                            0x1FFU
#define CLK_BMCPERIPH1_200_DIVN1_DIV_SHIFT                           0
#define CLK_BMCPERIPH1_200_DIVN1_DIV_MASK                            0x1FFU
#define CLK_BMCPERIPH1_200_DIVN2_DIV_SHIFT                           0
#define CLK_BMCPERIPH1_200_DIVN2_DIV_MASK                            0x1FFU
#define CLK_BMCPERIPH1_200_DIVN3_DIV_SHIFT                           0
#define CLK_BMCPERIPH1_200_DIVN3_DIV_MASK                            0x1FFU
#define CLK_BMCPERIPH1_200_CCLK_DIV_DIV_SHIFT                        0
#define CLK_BMCPERIPH1_200_CCLK_DIV_DIV_MASK                         0x7FFU
#define CLK_U0_DWC_SSI_SFC_HCLK_ENABLE_DATA                          1
#define CLK_U0_DWC_SSI_SFC_HCLK_DISABLE_DATA                         0
#define CLK_U0_DWC_SSI_SFC_HCLK_EN_SHIFT                             31
#define CLK_U0_DWC_SSI_SFC_HCLK_EN_MASK                              0x80000000U
#define CLK_U0_DWC_SSI_SFC_SSI_CLK_ENABLE_DATA                       1
#define CLK_U0_DWC_SSI_SFC_SSI_CLK_DISABLE_DATA                      0
#define CLK_U0_DWC_SSI_SFC_SSI_CLK_EN_SHIFT                          31
#define CLK_U0_DWC_SSI_SFC_SSI_CLK_EN_MASK                           0x80000000U
#define CLK_U1_DWC_SSI_SFC_HCLK_ENABLE_DATA                          1
#define CLK_U1_DWC_SSI_SFC_HCLK_DISABLE_DATA                         0
#define CLK_U1_DWC_SSI_SFC_HCLK_EN_SHIFT                             31
#define CLK_U1_DWC_SSI_SFC_HCLK_EN_MASK                              0x80000000U
#define CLK_U1_DWC_SSI_SFC_SSI_CLK_ENABLE_DATA                       1
#define CLK_U1_DWC_SSI_SFC_SSI_CLK_DISABLE_DATA                      0
#define CLK_U1_DWC_SSI_SFC_SSI_CLK_EN_SHIFT                          31
#define CLK_U1_DWC_SSI_SFC_SSI_CLK_EN_MASK                           0x80000000U
#define CLK_U2_DWC_SSI_SFC_HCLK_ENABLE_DATA                          1
#define CLK_U2_DWC_SSI_SFC_HCLK_DISABLE_DATA                         0
#define CLK_U2_DWC_SSI_SFC_HCLK_EN_SHIFT                             31
#define CLK_U2_DWC_SSI_SFC_HCLK_EN_MASK                              0x80000000U
#define CLK_U2_DWC_SSI_SFC_SSI_CLK_ENABLE_DATA                       1
#define CLK_U2_DWC_SSI_SFC_SSI_CLK_DISABLE_DATA                      0
#define CLK_U2_DWC_SSI_SFC_SSI_CLK_EN_SHIFT                          31
#define CLK_U2_DWC_SSI_SFC_SSI_CLK_EN_MASK                           0x80000000U
#define CLK_U0_DWC_SSI_SPI_HCLK_ENABLE_DATA                          1
#define CLK_U0_DWC_SSI_SPI_HCLK_DISABLE_DATA                         0
#define CLK_U0_DWC_SSI_SPI_HCLK_EN_SHIFT                             31
#define CLK_U0_DWC_SSI_SPI_HCLK_EN_MASK                              0x80000000U
#define CLK_U0_DWC_SSI_SPI_SSI_CLK_ENABLE_DATA                       1
#define CLK_U0_DWC_SSI_SPI_SSI_CLK_DISABLE_DATA                      0
#define CLK_U0_DWC_SSI_SPI_SSI_CLK_EN_SHIFT                          31
#define CLK_U0_DWC_SSI_SPI_SSI_CLK_EN_MASK                           0x80000000U
#define CLK_U0_SGPIO_PCLK_ENABLE_DATA                                1
#define CLK_U0_SGPIO_PCLK_DISABLE_DATA                               0
#define CLK_U0_SGPIO_PCLK_EN_SHIFT                                   31
#define CLK_U0_SGPIO_PCLK_EN_MASK                                    0x80000000U
#define CLK_U0_SGPIO_DCLK_ENABLE_DATA                                1
#define CLK_U0_SGPIO_DCLK_DISABLE_DATA                               0
#define CLK_U0_SGPIO_DCLK_EN_SHIFT                                   31
#define CLK_U0_SGPIO_DCLK_EN_MASK                                    0x80000000U
#define CLK_U1_SGPIO_PCLK_ENABLE_DATA                                1
#define CLK_U1_SGPIO_PCLK_DISABLE_DATA                               0
#define CLK_U1_SGPIO_PCLK_EN_SHIFT                                   31
#define CLK_U1_SGPIO_PCLK_EN_MASK                                    0x80000000U
#define CLK_U1_SGPIO_DCLK_ENABLE_DATA                                1
#define CLK_U1_SGPIO_DCLK_DISABLE_DATA                               0
#define CLK_U1_SGPIO_DCLK_EN_SHIFT                                   31
#define CLK_U1_SGPIO_DCLK_EN_MASK                                    0x80000000U
#define CLK_U6_DWC_SENSORS_PD_CLK_SYS_ENABLE_DATA                    1
#define CLK_U6_DWC_SENSORS_PD_CLK_SYS_DISABLE_DATA                   0
#define CLK_U6_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT                       31
#define CLK_U6_DWC_SENSORS_PD_CLK_SYS_EN_MASK                        0x80000000U
#define CLK_U1_DW_AXI_DMAC_1CH_PCLK_ENABLE_DATA                      1
#define CLK_U1_DW_AXI_DMAC_1CH_PCLK_DISABLE_DATA                     0
#define CLK_U1_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT                         31
#define CLK_U1_DW_AXI_DMAC_1CH_PCLK_EN_MASK                          0x80000000U
#define CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ENABLE_DATA           1
#define CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_DISABLE_DATA          0
#define CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT              31
#define CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK               0x80000000U
#define CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_ENABLE_DATA                    1
#define CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_DISABLE_DATA                   0
#define CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT                       31
#define CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK                        0x80000000U
#define CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_ENABLE_DATA                   1
#define CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_DISABLE_DATA                  0
#define CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT                      31
#define CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK                       0x80000000U
#define CLK_U2_DW_AXI_DMAC_1CH_PCLK_ENABLE_DATA                      1
#define CLK_U2_DW_AXI_DMAC_1CH_PCLK_DISABLE_DATA                     0
#define CLK_U2_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT                         31
#define CLK_U2_DW_AXI_DMAC_1CH_PCLK_EN_MASK                          0x80000000U
#define CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ENABLE_DATA           1
#define CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_DISABLE_DATA          0
#define CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT              31
#define CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK               0x80000000U
#define CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_ENABLE_DATA                    1
#define CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_DISABLE_DATA                   0
#define CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT                       31
#define CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK                        0x80000000U
#define CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_ENABLE_DATA                   1
#define CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_DISABLE_DATA                  0
#define CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT                      31
#define CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK                       0x80000000U
#define CLK_U3_DW_AXI_DMAC_1CH_PCLK_ENABLE_DATA                      1
#define CLK_U3_DW_AXI_DMAC_1CH_PCLK_DISABLE_DATA                     0
#define CLK_U3_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT                         31
#define CLK_U3_DW_AXI_DMAC_1CH_PCLK_EN_MASK                          0x80000000U
#define CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ENABLE_DATA           1
#define CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_DISABLE_DATA          0
#define CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT              31
#define CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK               0x80000000U
#define CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_ENABLE_DATA                    1
#define CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_DISABLE_DATA                   0
#define CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT                       31
#define CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK                        0x80000000U
#define CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_ENABLE_DATA                   1
#define CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_DISABLE_DATA                  0
#define CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT                      31
#define CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK                       0x80000000U
#define CLK_U4_DW_AXI_DMAC_1CH_PCLK_ENABLE_DATA                      1
#define CLK_U4_DW_AXI_DMAC_1CH_PCLK_DISABLE_DATA                     0
#define CLK_U4_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT                         31
#define CLK_U4_DW_AXI_DMAC_1CH_PCLK_EN_MASK                          0x80000000U
#define CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ENABLE_DATA           1
#define CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_DISABLE_DATA          0
#define CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT              31
#define CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK               0x80000000U
#define CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_ENABLE_DATA                    1
#define CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_DISABLE_DATA                   0
#define CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT                       31
#define CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK                        0x80000000U
#define CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_ENABLE_DATA                   1
#define CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_DISABLE_DATA                  0
#define CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT                      31
#define CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK                       0x80000000U
#define CLK_U3_RAS_ELS_EP_M_ACLK_ENABLE_DATA                         1
#define CLK_U3_RAS_ELS_EP_M_ACLK_DISABLE_DATA                        0
#define CLK_U3_RAS_ELS_EP_M_ACLK_EN_SHIFT                            31
#define CLK_U3_RAS_ELS_EP_M_ACLK_EN_MASK                             0x80000000U

#define MAIN_ICG_EN_SFC0_ENABLE_DATA                                 1
#define MAIN_ICG_EN_SFC0_DISABLE_DATA                                0
#define MAIN_ICG_EN_SFC0_EN_SHIFT                                    31
#define MAIN_ICG_EN_SFC0_EN_MASK                                     0x80000000U
#define MAIN_ICG_EN_SFC1_ENABLE_DATA                                 1
#define MAIN_ICG_EN_SFC1_DISABLE_DATA                                0
#define MAIN_ICG_EN_SFC1_EN_SHIFT                                    31
#define MAIN_ICG_EN_SFC1_EN_MASK                                     0x80000000U
#define MAIN_ICG_EN_SFC2_ENABLE_DATA                                 1
#define MAIN_ICG_EN_SFC2_DISABLE_DATA                                0
#define MAIN_ICG_EN_SFC2_EN_SHIFT                                    31
#define MAIN_ICG_EN_SFC2_EN_MASK                                     0x80000000U
#define MAIN_ICG_EN_SPI0_ENABLE_DATA                                 1
#define MAIN_ICG_EN_SPI0_DISABLE_DATA                                0
#define MAIN_ICG_EN_SPI0_EN_SHIFT                                    31
#define MAIN_ICG_EN_SPI0_EN_MASK                                     0x80000000U
#define MAIN_ICG_EN_SGPIO0_ENABLE_DATA                               1
#define MAIN_ICG_EN_SGPIO0_DISABLE_DATA                              0
#define MAIN_ICG_EN_SGPIO0_EN_SHIFT                                  31
#define MAIN_ICG_EN_SGPIO0_EN_MASK                                   0x80000000U
#define MAIN_ICG_EN_SGPIO1_ENABLE_DATA                               1
#define MAIN_ICG_EN_SGPIO1_DISABLE_DATA                              0
#define MAIN_ICG_EN_SGPIO1_EN_SHIFT                                  31
#define MAIN_ICG_EN_SGPIO1_EN_MASK                                   0x80000000U
#define MAIN_ICG_EN_SENSOR_ENABLE_DATA                               1
#define MAIN_ICG_EN_SENSOR_DISABLE_DATA                              0
#define MAIN_ICG_EN_SENSOR_EN_SHIFT                                  31
#define MAIN_ICG_EN_SENSOR_EN_MASK                                   0x80000000U
#define MAIN_ICG_EN_DMAC_SFC0_ENABLE_DATA                            1
#define MAIN_ICG_EN_DMAC_SFC0_DISABLE_DATA                           0
#define MAIN_ICG_EN_DMAC_SFC0_EN_SHIFT                               31
#define MAIN_ICG_EN_DMAC_SFC0_EN_MASK                                0x80000000U
#define MAIN_ICG_EN_DMAC_SFC1_ENABLE_DATA                            1
#define MAIN_ICG_EN_DMAC_SFC1_DISABLE_DATA                           0
#define MAIN_ICG_EN_DMAC_SFC1_EN_SHIFT                               31
#define MAIN_ICG_EN_DMAC_SFC1_EN_MASK                                0x80000000U
#define MAIN_ICG_EN_DMAC_SFC2_ENABLE_DATA                            1
#define MAIN_ICG_EN_DMAC_SFC2_DISABLE_DATA                           0
#define MAIN_ICG_EN_DMAC_SFC2_EN_SHIFT                               31
#define MAIN_ICG_EN_DMAC_SFC2_EN_MASK                                0x80000000U
#define MAIN_ICG_EN_DMAC_SPI0_ENABLE_DATA                            1
#define MAIN_ICG_EN_DMAC_SPI0_DISABLE_DATA                           0
#define MAIN_ICG_EN_DMAC_SPI0_EN_SHIFT                               31
#define MAIN_ICG_EN_DMAC_SPI0_EN_MASK                                0x80000000U
#define MAIN_ICG_EN_PERIPH1_RAS_ENABLE_DATA                          1
#define MAIN_ICG_EN_PERIPH1_RAS_DISABLE_DATA                         0
#define MAIN_ICG_EN_PERIPH1_RAS_EN_SHIFT                             31
#define MAIN_ICG_EN_PERIPH1_RAS_EN_MASK                              0x80000000U



#define RSTN_U0_BMCPERIPH1_IOMUX_PRESETN_SHIFT                       0
#define RSTN_U0_BMCPERIPH1_IOMUX_PRESETN_MASK                        (0x1 << 0)
#define RSTN_U0_BMCPERIPH1_IOMUX_PRESETN_ASSERT                      1
#define RSTN_U0_BMCPERIPH1_IOMUX_PRESETN_CLEAR                       0
#define RSTN_U0_BMCPERIPH1_SYSCON_PRESETN_SHIFT                      1
#define RSTN_U0_BMCPERIPH1_SYSCON_PRESETN_MASK                       (0x1 << 1)
#define RSTN_U0_BMCPERIPH1_SYSCON_PRESETN_ASSERT                     1
#define RSTN_U0_BMCPERIPH1_SYSCON_PRESETN_CLEAR                      0
#define MAIN_RSTN_SFC0_SHIFT                                         2
#define MAIN_RSTN_SFC0_MASK                                          (0x1 << 2)
#define MAIN_RSTN_SFC0_ASSERT                                        1
#define MAIN_RSTN_SFC0_CLEAR                                         0
#define MAIN_RSTN_SFC1_SHIFT                                         3
#define MAIN_RSTN_SFC1_MASK                                          (0x1 << 3)
#define MAIN_RSTN_SFC1_ASSERT                                        1
#define MAIN_RSTN_SFC1_CLEAR                                         0
#define MAIN_RSTN_SFC2_SHIFT                                         4
#define MAIN_RSTN_SFC2_MASK                                          (0x1 << 4)
#define MAIN_RSTN_SFC2_ASSERT                                        1
#define MAIN_RSTN_SFC2_CLEAR                                         0
#define MAIN_RSTN_SPI0_SHIFT                                         5
#define MAIN_RSTN_SPI0_MASK                                          (0x1 << 5)
#define MAIN_RSTN_SPI0_ASSERT                                        1
#define MAIN_RSTN_SPI0_CLEAR                                         0
#define MAIN_RSTN_SENSOR_SHIFT                                       6
#define MAIN_RSTN_SENSOR_MASK                                        (0x1 << 6)
#define MAIN_RSTN_SENSOR_ASSERT                                      1
#define MAIN_RSTN_SENSOR_CLEAR                                       0
#define MAIN_RSTN_SGPIO0_SHIFT                                       7
#define MAIN_RSTN_SGPIO0_MASK                                        (0x1 << 7)
#define MAIN_RSTN_SGPIO0_ASSERT                                      1
#define MAIN_RSTN_SGPIO0_CLEAR                                       0
#define MAIN_RSTN_SGPIO1_SHIFT                                       8
#define MAIN_RSTN_SGPIO1_MASK                                        (0x1 << 8)
#define MAIN_RSTN_SGPIO1_ASSERT                                      1
#define MAIN_RSTN_SGPIO1_CLEAR                                       0
#define MAIN_RSTN_DMAC_SFC0_SHIFT                                    13
#define MAIN_RSTN_DMAC_SFC0_MASK                                     (0x1 << 13)
#define MAIN_RSTN_DMAC_SFC0_ASSERT                                   1
#define MAIN_RSTN_DMAC_SFC0_CLEAR                                    0
#define MAIN_RSTN_DMAC_SFC1_SHIFT                                    14
#define MAIN_RSTN_DMAC_SFC1_MASK                                     (0x1 << 14)
#define MAIN_RSTN_DMAC_SFC1_ASSERT                                   1
#define MAIN_RSTN_DMAC_SFC1_CLEAR                                    0
#define MAIN_RSTN_DMAC_SFC2_SHIFT                                    15
#define MAIN_RSTN_DMAC_SFC2_MASK                                     (0x1 << 15)
#define MAIN_RSTN_DMAC_SFC2_ASSERT                                   1
#define MAIN_RSTN_DMAC_SFC2_CLEAR                                    0
#define MAIN_RSTN_DMAC_SPI0_SHIFT                                    16
#define MAIN_RSTN_DMAC_SPI0_MASK                                     (0x1 << 16)
#define MAIN_RSTN_DMAC_SPI0_ASSERT                                   1
#define MAIN_RSTN_DMAC_SPI0_CLEAR                                    0
#define MAIN_RSTN_PERIPH1_RAS_SHIFT                                  17
#define MAIN_RSTN_PERIPH1_RAS_MASK                                   (0x1 << 17)
#define MAIN_RSTN_PERIPH1_RAS_ASSERT                                 1
#define MAIN_RSTN_PERIPH1_RAS_CLEAR                                  0

#define _DIVIDE_CLOCK_CLK_BMCPERIPH1_100_(div) 			itg_set_reg(CLK_BMCPERIPH1_100_CTRL_REG_ADDR, div, CLK_BMCPERIPH1_100_DIV_SHIFT, CLK_BMCPERIPH1_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH1_100_ 		itg_get_reg(CLK_BMCPERIPH1_100_CTRL_REG_ADDR, CLK_BMCPERIPH1_100_DIV_SHIFT, CLK_BMCPERIPH1_100_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH1_1_(div) 			itg_set_reg(CLK_BMCPERIPH1_1_CTRL_REG_ADDR, div, CLK_BMCPERIPH1_1_DIV_SHIFT, CLK_BMCPERIPH1_1_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH1_1_ 		itg_get_reg(CLK_BMCPERIPH1_1_CTRL_REG_ADDR, CLK_BMCPERIPH1_1_DIV_SHIFT, CLK_BMCPERIPH1_1_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH1_200_DIVN0_(div) 			itg_set_reg(CLK_BMCPERIPH1_200_DIVN0_CTRL_REG_ADDR, div, CLK_BMCPERIPH1_200_DIVN0_DIV_SHIFT, CLK_BMCPERIPH1_200_DIVN0_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH1_200_DIVN0_ 		itg_get_reg(CLK_BMCPERIPH1_200_DIVN0_CTRL_REG_ADDR, CLK_BMCPERIPH1_200_DIVN0_DIV_SHIFT, CLK_BMCPERIPH1_200_DIVN0_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH1_200_DIVN1_(div) 			itg_set_reg(CLK_BMCPERIPH1_200_DIVN1_CTRL_REG_ADDR, div, CLK_BMCPERIPH1_200_DIVN1_DIV_SHIFT, CLK_BMCPERIPH1_200_DIVN1_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH1_200_DIVN1_ 		itg_get_reg(CLK_BMCPERIPH1_200_DIVN1_CTRL_REG_ADDR, CLK_BMCPERIPH1_200_DIVN1_DIV_SHIFT, CLK_BMCPERIPH1_200_DIVN1_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH1_200_DIVN2_(div) 			itg_set_reg(CLK_BMCPERIPH1_200_DIVN2_CTRL_REG_ADDR, div, CLK_BMCPERIPH1_200_DIVN2_DIV_SHIFT, CLK_BMCPERIPH1_200_DIVN2_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH1_200_DIVN2_ 		itg_get_reg(CLK_BMCPERIPH1_200_DIVN2_CTRL_REG_ADDR, CLK_BMCPERIPH1_200_DIVN2_DIV_SHIFT, CLK_BMCPERIPH1_200_DIVN2_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH1_200_DIVN3_(div) 			itg_set_reg(CLK_BMCPERIPH1_200_DIVN3_CTRL_REG_ADDR, div, CLK_BMCPERIPH1_200_DIVN3_DIV_SHIFT, CLK_BMCPERIPH1_200_DIVN3_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH1_200_DIVN3_ 		itg_get_reg(CLK_BMCPERIPH1_200_DIVN3_CTRL_REG_ADDR, CLK_BMCPERIPH1_200_DIVN3_DIV_SHIFT, CLK_BMCPERIPH1_200_DIVN3_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH1_200_CCLK_DIV_(div) 			itg_set_reg(CLK_BMCPERIPH1_200_CCLK_DIV_CTRL_REG_ADDR, div, CLK_BMCPERIPH1_200_CCLK_DIV_DIV_SHIFT, CLK_BMCPERIPH1_200_CCLK_DIV_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH1_200_CCLK_DIV_ 		itg_get_reg(CLK_BMCPERIPH1_200_CCLK_DIV_CTRL_REG_ADDR, CLK_BMCPERIPH1_200_CCLK_DIV_DIV_SHIFT, CLK_BMCPERIPH1_200_CCLK_DIV_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_SSI_SFC_HCLK_ 			itg_set_reg(CLK_U0_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SFC_HCLK_ENABLE_DATA, CLK_U0_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U0_DWC_SSI_SFC_HCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_SSI_SFC_HCLK_ 			itg_set_reg(CLK_U0_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SFC_HCLK_DISABLE_DATA, CLK_U0_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U0_DWC_SSI_SFC_HCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_SSI_SFC_HCLK_ 		itg_get_reg(CLK_U0_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U0_DWC_SSI_SFC_HCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_SSI_SFC_HCLK_(x) 		itg_set_reg(CLK_U0_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, x, CLK_U0_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U0_DWC_SSI_SFC_HCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_SSI_SFC_SSI_CLK_ 			itg_set_reg(CLK_U0_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SFC_SSI_CLK_ENABLE_DATA, CLK_U0_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U0_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_SSI_SFC_SSI_CLK_ 			itg_set_reg(CLK_U0_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SFC_SSI_CLK_DISABLE_DATA, CLK_U0_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U0_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_SSI_SFC_SSI_CLK_ 		itg_get_reg(CLK_U0_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U0_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_SSI_SFC_SSI_CLK_(x) 		itg_set_reg(CLK_U0_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, x, CLK_U0_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U0_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DWC_SSI_SFC_HCLK_ 			itg_set_reg(CLK_U1_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, CLK_U1_DWC_SSI_SFC_HCLK_ENABLE_DATA, CLK_U1_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U1_DWC_SSI_SFC_HCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DWC_SSI_SFC_HCLK_ 			itg_set_reg(CLK_U1_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, CLK_U1_DWC_SSI_SFC_HCLK_DISABLE_DATA, CLK_U1_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U1_DWC_SSI_SFC_HCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_SSI_SFC_HCLK_ 		itg_get_reg(CLK_U1_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, CLK_U1_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U1_DWC_SSI_SFC_HCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_SSI_SFC_HCLK_(x) 		itg_set_reg(CLK_U1_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, x, CLK_U1_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U1_DWC_SSI_SFC_HCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DWC_SSI_SFC_SSI_CLK_ 			itg_set_reg(CLK_U1_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, CLK_U1_DWC_SSI_SFC_SSI_CLK_ENABLE_DATA, CLK_U1_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U1_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DWC_SSI_SFC_SSI_CLK_ 			itg_set_reg(CLK_U1_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, CLK_U1_DWC_SSI_SFC_SSI_CLK_DISABLE_DATA, CLK_U1_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U1_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_SSI_SFC_SSI_CLK_ 		itg_get_reg(CLK_U1_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, CLK_U1_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U1_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_SSI_SFC_SSI_CLK_(x) 		itg_set_reg(CLK_U1_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, x, CLK_U1_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U1_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U2_DWC_SSI_SFC_HCLK_ 			itg_set_reg(CLK_U2_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, CLK_U2_DWC_SSI_SFC_HCLK_ENABLE_DATA, CLK_U2_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U2_DWC_SSI_SFC_HCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U2_DWC_SSI_SFC_HCLK_ 			itg_set_reg(CLK_U2_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, CLK_U2_DWC_SSI_SFC_HCLK_DISABLE_DATA, CLK_U2_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U2_DWC_SSI_SFC_HCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U2_DWC_SSI_SFC_HCLK_ 		itg_get_reg(CLK_U2_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, CLK_U2_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U2_DWC_SSI_SFC_HCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U2_DWC_SSI_SFC_HCLK_(x) 		itg_set_reg(CLK_U2_DWC_SSI_SFC_HCLK_CTRL_REG_ADDR, x, CLK_U2_DWC_SSI_SFC_HCLK_EN_SHIFT, CLK_U2_DWC_SSI_SFC_HCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U2_DWC_SSI_SFC_SSI_CLK_ 			itg_set_reg(CLK_U2_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, CLK_U2_DWC_SSI_SFC_SSI_CLK_ENABLE_DATA, CLK_U2_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U2_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U2_DWC_SSI_SFC_SSI_CLK_ 			itg_set_reg(CLK_U2_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, CLK_U2_DWC_SSI_SFC_SSI_CLK_DISABLE_DATA, CLK_U2_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U2_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U2_DWC_SSI_SFC_SSI_CLK_ 		itg_get_reg(CLK_U2_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, CLK_U2_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U2_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U2_DWC_SSI_SFC_SSI_CLK_(x) 		itg_set_reg(CLK_U2_DWC_SSI_SFC_SSI_CLK_CTRL_REG_ADDR, x, CLK_U2_DWC_SSI_SFC_SSI_CLK_EN_SHIFT, CLK_U2_DWC_SSI_SFC_SSI_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_SSI_SPI_HCLK_ 			itg_set_reg(CLK_U0_DWC_SSI_SPI_HCLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SPI_HCLK_ENABLE_DATA, CLK_U0_DWC_SSI_SPI_HCLK_EN_SHIFT, CLK_U0_DWC_SSI_SPI_HCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_SSI_SPI_HCLK_ 			itg_set_reg(CLK_U0_DWC_SSI_SPI_HCLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SPI_HCLK_DISABLE_DATA, CLK_U0_DWC_SSI_SPI_HCLK_EN_SHIFT, CLK_U0_DWC_SSI_SPI_HCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_SSI_SPI_HCLK_ 		itg_get_reg(CLK_U0_DWC_SSI_SPI_HCLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SPI_HCLK_EN_SHIFT, CLK_U0_DWC_SSI_SPI_HCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_SSI_SPI_HCLK_(x) 		itg_set_reg(CLK_U0_DWC_SSI_SPI_HCLK_CTRL_REG_ADDR, x, CLK_U0_DWC_SSI_SPI_HCLK_EN_SHIFT, CLK_U0_DWC_SSI_SPI_HCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_SSI_SPI_SSI_CLK_ 			itg_set_reg(CLK_U0_DWC_SSI_SPI_SSI_CLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SPI_SSI_CLK_ENABLE_DATA, CLK_U0_DWC_SSI_SPI_SSI_CLK_EN_SHIFT, CLK_U0_DWC_SSI_SPI_SSI_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_SSI_SPI_SSI_CLK_ 			itg_set_reg(CLK_U0_DWC_SSI_SPI_SSI_CLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SPI_SSI_CLK_DISABLE_DATA, CLK_U0_DWC_SSI_SPI_SSI_CLK_EN_SHIFT, CLK_U0_DWC_SSI_SPI_SSI_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_SSI_SPI_SSI_CLK_ 		itg_get_reg(CLK_U0_DWC_SSI_SPI_SSI_CLK_CTRL_REG_ADDR, CLK_U0_DWC_SSI_SPI_SSI_CLK_EN_SHIFT, CLK_U0_DWC_SSI_SPI_SSI_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_SSI_SPI_SSI_CLK_(x) 		itg_set_reg(CLK_U0_DWC_SSI_SPI_SSI_CLK_CTRL_REG_ADDR, x, CLK_U0_DWC_SSI_SPI_SSI_CLK_EN_SHIFT, CLK_U0_DWC_SSI_SPI_SSI_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_SGPIO_PCLK_ 			itg_set_reg(CLK_U0_SGPIO_PCLK_CTRL_REG_ADDR, CLK_U0_SGPIO_PCLK_ENABLE_DATA, CLK_U0_SGPIO_PCLK_EN_SHIFT, CLK_U0_SGPIO_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_SGPIO_PCLK_ 			itg_set_reg(CLK_U0_SGPIO_PCLK_CTRL_REG_ADDR, CLK_U0_SGPIO_PCLK_DISABLE_DATA, CLK_U0_SGPIO_PCLK_EN_SHIFT, CLK_U0_SGPIO_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_SGPIO_PCLK_ 		itg_get_reg(CLK_U0_SGPIO_PCLK_CTRL_REG_ADDR, CLK_U0_SGPIO_PCLK_EN_SHIFT, CLK_U0_SGPIO_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_SGPIO_PCLK_(x) 		itg_set_reg(CLK_U0_SGPIO_PCLK_CTRL_REG_ADDR, x, CLK_U0_SGPIO_PCLK_EN_SHIFT, CLK_U0_SGPIO_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_SGPIO_DCLK_ 			itg_set_reg(CLK_U0_SGPIO_DCLK_CTRL_REG_ADDR, CLK_U0_SGPIO_DCLK_ENABLE_DATA, CLK_U0_SGPIO_DCLK_EN_SHIFT, CLK_U0_SGPIO_DCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_SGPIO_DCLK_ 			itg_set_reg(CLK_U0_SGPIO_DCLK_CTRL_REG_ADDR, CLK_U0_SGPIO_DCLK_DISABLE_DATA, CLK_U0_SGPIO_DCLK_EN_SHIFT, CLK_U0_SGPIO_DCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_SGPIO_DCLK_ 		itg_get_reg(CLK_U0_SGPIO_DCLK_CTRL_REG_ADDR, CLK_U0_SGPIO_DCLK_EN_SHIFT, CLK_U0_SGPIO_DCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_SGPIO_DCLK_(x) 		itg_set_reg(CLK_U0_SGPIO_DCLK_CTRL_REG_ADDR, x, CLK_U0_SGPIO_DCLK_EN_SHIFT, CLK_U0_SGPIO_DCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_SGPIO_PCLK_ 			itg_set_reg(CLK_U1_SGPIO_PCLK_CTRL_REG_ADDR, CLK_U1_SGPIO_PCLK_ENABLE_DATA, CLK_U1_SGPIO_PCLK_EN_SHIFT, CLK_U1_SGPIO_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_SGPIO_PCLK_ 			itg_set_reg(CLK_U1_SGPIO_PCLK_CTRL_REG_ADDR, CLK_U1_SGPIO_PCLK_DISABLE_DATA, CLK_U1_SGPIO_PCLK_EN_SHIFT, CLK_U1_SGPIO_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_SGPIO_PCLK_ 		itg_get_reg(CLK_U1_SGPIO_PCLK_CTRL_REG_ADDR, CLK_U1_SGPIO_PCLK_EN_SHIFT, CLK_U1_SGPIO_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_SGPIO_PCLK_(x) 		itg_set_reg(CLK_U1_SGPIO_PCLK_CTRL_REG_ADDR, x, CLK_U1_SGPIO_PCLK_EN_SHIFT, CLK_U1_SGPIO_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_SGPIO_DCLK_ 			itg_set_reg(CLK_U1_SGPIO_DCLK_CTRL_REG_ADDR, CLK_U1_SGPIO_DCLK_ENABLE_DATA, CLK_U1_SGPIO_DCLK_EN_SHIFT, CLK_U1_SGPIO_DCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_SGPIO_DCLK_ 			itg_set_reg(CLK_U1_SGPIO_DCLK_CTRL_REG_ADDR, CLK_U1_SGPIO_DCLK_DISABLE_DATA, CLK_U1_SGPIO_DCLK_EN_SHIFT, CLK_U1_SGPIO_DCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_SGPIO_DCLK_ 		itg_get_reg(CLK_U1_SGPIO_DCLK_CTRL_REG_ADDR, CLK_U1_SGPIO_DCLK_EN_SHIFT, CLK_U1_SGPIO_DCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_SGPIO_DCLK_(x) 		itg_set_reg(CLK_U1_SGPIO_DCLK_CTRL_REG_ADDR, x, CLK_U1_SGPIO_DCLK_EN_SHIFT, CLK_U1_SGPIO_DCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U6_DWC_SENSORS_PD_CLK_SYS_ 			itg_set_reg(CLK_U6_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U6_DWC_SENSORS_PD_CLK_SYS_ENABLE_DATA, CLK_U6_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U6_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _DISABLE_CLOCK_CLK_U6_DWC_SENSORS_PD_CLK_SYS_ 			itg_set_reg(CLK_U6_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U6_DWC_SENSORS_PD_CLK_SYS_DISABLE_DATA, CLK_U6_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U6_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U6_DWC_SENSORS_PD_CLK_SYS_ 		itg_get_reg(CLK_U6_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U6_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U6_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U6_DWC_SENSORS_PD_CLK_SYS_(x) 		itg_set_reg(CLK_U6_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, x, CLK_U6_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U6_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DW_AXI_DMAC_1CH_PCLK_ 			itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_PCLK_ENABLE_DATA, CLK_U1_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DW_AXI_DMAC_1CH_PCLK_ 			itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_PCLK_DISABLE_DATA, CLK_U1_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DW_AXI_DMAC_1CH_PCLK_ 		itg_get_reg(CLK_U1_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DW_AXI_DMAC_1CH_PCLK_(x) 		itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, x, CLK_U1_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 			itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ENABLE_DATA, CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 			itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_DISABLE_DATA, CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 		itg_get_reg(CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_(x) 		itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, x, CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_ 			itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_ENABLE_DATA, CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_ 			itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_DISABLE_DATA, CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_ 		itg_get_reg(CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_(x) 		itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, x, CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_ 			itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_ENABLE_DATA, CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_ 			itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_DISABLE_DATA, CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_ 		itg_get_reg(CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_(x) 		itg_set_reg(CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, x, CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U1_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _ENABLE_CLOCK_CLK_U2_DW_AXI_DMAC_1CH_PCLK_ 			itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_PCLK_ENABLE_DATA, CLK_U2_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U2_DW_AXI_DMAC_1CH_PCLK_ 			itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_PCLK_DISABLE_DATA, CLK_U2_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U2_DW_AXI_DMAC_1CH_PCLK_ 		itg_get_reg(CLK_U2_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U2_DW_AXI_DMAC_1CH_PCLK_(x) 		itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, x, CLK_U2_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 			itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ENABLE_DATA, CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 			itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_DISABLE_DATA, CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 		itg_get_reg(CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_(x) 		itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, x, CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_ 			itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_ENABLE_DATA, CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_ 			itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_DISABLE_DATA, CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_ 		itg_get_reg(CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_(x) 		itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, x, CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_ 			itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_ENABLE_DATA, CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _DISABLE_CLOCK_CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_ 			itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_DISABLE_DATA, CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_ 		itg_get_reg(CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_(x) 		itg_set_reg(CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, x, CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U2_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _ENABLE_CLOCK_CLK_U3_DW_AXI_DMAC_1CH_PCLK_ 			itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_PCLK_ENABLE_DATA, CLK_U3_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U3_DW_AXI_DMAC_1CH_PCLK_ 			itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_PCLK_DISABLE_DATA, CLK_U3_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U3_DW_AXI_DMAC_1CH_PCLK_ 		itg_get_reg(CLK_U3_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U3_DW_AXI_DMAC_1CH_PCLK_(x) 		itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, x, CLK_U3_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 			itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ENABLE_DATA, CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 			itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_DISABLE_DATA, CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 		itg_get_reg(CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_(x) 		itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, x, CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_ 			itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_ENABLE_DATA, CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_ 			itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_DISABLE_DATA, CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_ 		itg_get_reg(CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_(x) 		itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, x, CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_ 			itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_ENABLE_DATA, CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _DISABLE_CLOCK_CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_ 			itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_DISABLE_DATA, CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_ 		itg_get_reg(CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_(x) 		itg_set_reg(CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, x, CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U3_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _ENABLE_CLOCK_CLK_U4_DW_AXI_DMAC_1CH_PCLK_ 			itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_PCLK_ENABLE_DATA, CLK_U4_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U4_DW_AXI_DMAC_1CH_PCLK_ 			itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_PCLK_DISABLE_DATA, CLK_U4_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U4_DW_AXI_DMAC_1CH_PCLK_ 		itg_get_reg(CLK_U4_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U4_DW_AXI_DMAC_1CH_PCLK_(x) 		itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_PCLK_CTRL_REG_ADDR, x, CLK_U4_DW_AXI_DMAC_1CH_PCLK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 			itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ENABLE_DATA, CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 			itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_DISABLE_DATA, CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_ 		itg_get_reg(CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_(x) 		itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, x, CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_DMAC_CORE_CLOCK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_ 			itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_ENABLE_DATA, CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_ 			itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_DISABLE_DATA, CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_ 		itg_get_reg(CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_(x) 		itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_CTRL_REG_ADDR, x, CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_HS_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_ 			itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_ENABLE_DATA, CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _DISABLE_CLOCK_CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_ 			itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_DISABLE_DATA, CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_ 		itg_get_reg(CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_(x) 		itg_set_reg(CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_CTRL_REG_ADDR, x, CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_EN_SHIFT, CLK_U4_DW_AXI_DMAC_1CH_ACLK_M1_EN_MASK)
#define _ENABLE_CLOCK_CLK_U3_RAS_ELS_EP_M_ACLK_ 			itg_set_reg(CLK_U3_RAS_ELS_EP_M_ACLK_CTRL_REG_ADDR, CLK_U3_RAS_ELS_EP_M_ACLK_ENABLE_DATA, CLK_U3_RAS_ELS_EP_M_ACLK_EN_SHIFT, CLK_U3_RAS_ELS_EP_M_ACLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U3_RAS_ELS_EP_M_ACLK_ 			itg_set_reg(CLK_U3_RAS_ELS_EP_M_ACLK_CTRL_REG_ADDR, CLK_U3_RAS_ELS_EP_M_ACLK_DISABLE_DATA, CLK_U3_RAS_ELS_EP_M_ACLK_EN_SHIFT, CLK_U3_RAS_ELS_EP_M_ACLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U3_RAS_ELS_EP_M_ACLK_ 		itg_get_reg(CLK_U3_RAS_ELS_EP_M_ACLK_CTRL_REG_ADDR, CLK_U3_RAS_ELS_EP_M_ACLK_EN_SHIFT, CLK_U3_RAS_ELS_EP_M_ACLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U3_RAS_ELS_EP_M_ACLK_(x) 		itg_set_reg(CLK_U3_RAS_ELS_EP_M_ACLK_CTRL_REG_ADDR, x, CLK_U3_RAS_ELS_EP_M_ACLK_EN_SHIFT, CLK_U3_RAS_ELS_EP_M_ACLK_EN_MASK)

#define _ENABLE_CLOCK_MAIN_ICG_EN_SFC0_ 			itg_set_reg(MAIN_ICG_EN_SFC0_CTRL_REG_ADDR, MAIN_ICG_EN_SFC0_ENABLE_DATA, MAIN_ICG_EN_SFC0_EN_SHIFT, MAIN_ICG_EN_SFC0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_SFC0_ 			itg_set_reg(MAIN_ICG_EN_SFC0_CTRL_REG_ADDR, MAIN_ICG_EN_SFC0_DISABLE_DATA, MAIN_ICG_EN_SFC0_EN_SHIFT, MAIN_ICG_EN_SFC0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SFC0_ 		itg_get_reg(MAIN_ICG_EN_SFC0_CTRL_REG_ADDR, MAIN_ICG_EN_SFC0_EN_SHIFT, MAIN_ICG_EN_SFC0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SFC0_(x) 		itg_set_reg(MAIN_ICG_EN_SFC0_CTRL_REG_ADDR, x, MAIN_ICG_EN_SFC0_EN_SHIFT, MAIN_ICG_EN_SFC0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_SFC1_ 			itg_set_reg(MAIN_ICG_EN_SFC1_CTRL_REG_ADDR, MAIN_ICG_EN_SFC1_ENABLE_DATA, MAIN_ICG_EN_SFC1_EN_SHIFT, MAIN_ICG_EN_SFC1_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_SFC1_ 			itg_set_reg(MAIN_ICG_EN_SFC1_CTRL_REG_ADDR, MAIN_ICG_EN_SFC1_DISABLE_DATA, MAIN_ICG_EN_SFC1_EN_SHIFT, MAIN_ICG_EN_SFC1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SFC1_ 		itg_get_reg(MAIN_ICG_EN_SFC1_CTRL_REG_ADDR, MAIN_ICG_EN_SFC1_EN_SHIFT, MAIN_ICG_EN_SFC1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SFC1_(x) 		itg_set_reg(MAIN_ICG_EN_SFC1_CTRL_REG_ADDR, x, MAIN_ICG_EN_SFC1_EN_SHIFT, MAIN_ICG_EN_SFC1_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_SFC2_ 			itg_set_reg(MAIN_ICG_EN_SFC2_CTRL_REG_ADDR, MAIN_ICG_EN_SFC2_ENABLE_DATA, MAIN_ICG_EN_SFC2_EN_SHIFT, MAIN_ICG_EN_SFC2_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_SFC2_ 			itg_set_reg(MAIN_ICG_EN_SFC2_CTRL_REG_ADDR, MAIN_ICG_EN_SFC2_DISABLE_DATA, MAIN_ICG_EN_SFC2_EN_SHIFT, MAIN_ICG_EN_SFC2_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SFC2_ 		itg_get_reg(MAIN_ICG_EN_SFC2_CTRL_REG_ADDR, MAIN_ICG_EN_SFC2_EN_SHIFT, MAIN_ICG_EN_SFC2_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SFC2_(x) 		itg_set_reg(MAIN_ICG_EN_SFC2_CTRL_REG_ADDR, x, MAIN_ICG_EN_SFC2_EN_SHIFT, MAIN_ICG_EN_SFC2_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_SPI0_ 			itg_set_reg(MAIN_ICG_EN_SPI0_CTRL_REG_ADDR, MAIN_ICG_EN_SPI0_ENABLE_DATA, MAIN_ICG_EN_SPI0_EN_SHIFT, MAIN_ICG_EN_SPI0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_SPI0_ 			itg_set_reg(MAIN_ICG_EN_SPI0_CTRL_REG_ADDR, MAIN_ICG_EN_SPI0_DISABLE_DATA, MAIN_ICG_EN_SPI0_EN_SHIFT, MAIN_ICG_EN_SPI0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SPI0_ 		itg_get_reg(MAIN_ICG_EN_SPI0_CTRL_REG_ADDR, MAIN_ICG_EN_SPI0_EN_SHIFT, MAIN_ICG_EN_SPI0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SPI0_(x) 		itg_set_reg(MAIN_ICG_EN_SPI0_CTRL_REG_ADDR, x, MAIN_ICG_EN_SPI0_EN_SHIFT, MAIN_ICG_EN_SPI0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_SGPIO0_ 			itg_set_reg(MAIN_ICG_EN_SGPIO0_CTRL_REG_ADDR, MAIN_ICG_EN_SGPIO0_ENABLE_DATA, MAIN_ICG_EN_SGPIO0_EN_SHIFT, MAIN_ICG_EN_SGPIO0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_SGPIO0_ 			itg_set_reg(MAIN_ICG_EN_SGPIO0_CTRL_REG_ADDR, MAIN_ICG_EN_SGPIO0_DISABLE_DATA, MAIN_ICG_EN_SGPIO0_EN_SHIFT, MAIN_ICG_EN_SGPIO0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SGPIO0_ 		itg_get_reg(MAIN_ICG_EN_SGPIO0_CTRL_REG_ADDR, MAIN_ICG_EN_SGPIO0_EN_SHIFT, MAIN_ICG_EN_SGPIO0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SGPIO0_(x) 		itg_set_reg(MAIN_ICG_EN_SGPIO0_CTRL_REG_ADDR, x, MAIN_ICG_EN_SGPIO0_EN_SHIFT, MAIN_ICG_EN_SGPIO0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_SGPIO1_ 			itg_set_reg(MAIN_ICG_EN_SGPIO1_CTRL_REG_ADDR, MAIN_ICG_EN_SGPIO1_ENABLE_DATA, MAIN_ICG_EN_SGPIO1_EN_SHIFT, MAIN_ICG_EN_SGPIO1_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_SGPIO1_ 			itg_set_reg(MAIN_ICG_EN_SGPIO1_CTRL_REG_ADDR, MAIN_ICG_EN_SGPIO1_DISABLE_DATA, MAIN_ICG_EN_SGPIO1_EN_SHIFT, MAIN_ICG_EN_SGPIO1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SGPIO1_ 		itg_get_reg(MAIN_ICG_EN_SGPIO1_CTRL_REG_ADDR, MAIN_ICG_EN_SGPIO1_EN_SHIFT, MAIN_ICG_EN_SGPIO1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SGPIO1_(x) 		itg_set_reg(MAIN_ICG_EN_SGPIO1_CTRL_REG_ADDR, x, MAIN_ICG_EN_SGPIO1_EN_SHIFT, MAIN_ICG_EN_SGPIO1_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_SENSOR_ 			itg_set_reg(MAIN_ICG_EN_SENSOR_CTRL_REG_ADDR, MAIN_ICG_EN_SENSOR_ENABLE_DATA, MAIN_ICG_EN_SENSOR_EN_SHIFT, MAIN_ICG_EN_SENSOR_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_SENSOR_ 			itg_set_reg(MAIN_ICG_EN_SENSOR_CTRL_REG_ADDR, MAIN_ICG_EN_SENSOR_DISABLE_DATA, MAIN_ICG_EN_SENSOR_EN_SHIFT, MAIN_ICG_EN_SENSOR_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SENSOR_ 		itg_get_reg(MAIN_ICG_EN_SENSOR_CTRL_REG_ADDR, MAIN_ICG_EN_SENSOR_EN_SHIFT, MAIN_ICG_EN_SENSOR_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SENSOR_(x) 		itg_set_reg(MAIN_ICG_EN_SENSOR_CTRL_REG_ADDR, x, MAIN_ICG_EN_SENSOR_EN_SHIFT, MAIN_ICG_EN_SENSOR_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_DMAC_SFC0_ 			itg_set_reg(MAIN_ICG_EN_DMAC_SFC0_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SFC0_ENABLE_DATA, MAIN_ICG_EN_DMAC_SFC0_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_DMAC_SFC0_ 			itg_set_reg(MAIN_ICG_EN_DMAC_SFC0_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SFC0_DISABLE_DATA, MAIN_ICG_EN_DMAC_SFC0_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_DMAC_SFC0_ 		itg_get_reg(MAIN_ICG_EN_DMAC_SFC0_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SFC0_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_DMAC_SFC0_(x) 		itg_set_reg(MAIN_ICG_EN_DMAC_SFC0_CTRL_REG_ADDR, x, MAIN_ICG_EN_DMAC_SFC0_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_DMAC_SFC1_ 			itg_set_reg(MAIN_ICG_EN_DMAC_SFC1_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SFC1_ENABLE_DATA, MAIN_ICG_EN_DMAC_SFC1_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC1_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_DMAC_SFC1_ 			itg_set_reg(MAIN_ICG_EN_DMAC_SFC1_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SFC1_DISABLE_DATA, MAIN_ICG_EN_DMAC_SFC1_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_DMAC_SFC1_ 		itg_get_reg(MAIN_ICG_EN_DMAC_SFC1_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SFC1_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_DMAC_SFC1_(x) 		itg_set_reg(MAIN_ICG_EN_DMAC_SFC1_CTRL_REG_ADDR, x, MAIN_ICG_EN_DMAC_SFC1_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC1_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_DMAC_SFC2_ 			itg_set_reg(MAIN_ICG_EN_DMAC_SFC2_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SFC2_ENABLE_DATA, MAIN_ICG_EN_DMAC_SFC2_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC2_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_DMAC_SFC2_ 			itg_set_reg(MAIN_ICG_EN_DMAC_SFC2_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SFC2_DISABLE_DATA, MAIN_ICG_EN_DMAC_SFC2_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC2_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_DMAC_SFC2_ 		itg_get_reg(MAIN_ICG_EN_DMAC_SFC2_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SFC2_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC2_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_DMAC_SFC2_(x) 		itg_set_reg(MAIN_ICG_EN_DMAC_SFC2_CTRL_REG_ADDR, x, MAIN_ICG_EN_DMAC_SFC2_EN_SHIFT, MAIN_ICG_EN_DMAC_SFC2_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_DMAC_SPI0_ 			itg_set_reg(MAIN_ICG_EN_DMAC_SPI0_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SPI0_ENABLE_DATA, MAIN_ICG_EN_DMAC_SPI0_EN_SHIFT, MAIN_ICG_EN_DMAC_SPI0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_DMAC_SPI0_ 			itg_set_reg(MAIN_ICG_EN_DMAC_SPI0_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SPI0_DISABLE_DATA, MAIN_ICG_EN_DMAC_SPI0_EN_SHIFT, MAIN_ICG_EN_DMAC_SPI0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_DMAC_SPI0_ 		itg_get_reg(MAIN_ICG_EN_DMAC_SPI0_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_SPI0_EN_SHIFT, MAIN_ICG_EN_DMAC_SPI0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_DMAC_SPI0_(x) 		itg_set_reg(MAIN_ICG_EN_DMAC_SPI0_CTRL_REG_ADDR, x, MAIN_ICG_EN_DMAC_SPI0_EN_SHIFT, MAIN_ICG_EN_DMAC_SPI0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_PERIPH1_RAS_ 			itg_set_reg(MAIN_ICG_EN_PERIPH1_RAS_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH1_RAS_ENABLE_DATA, MAIN_ICG_EN_PERIPH1_RAS_EN_SHIFT, MAIN_ICG_EN_PERIPH1_RAS_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_PERIPH1_RAS_ 			itg_set_reg(MAIN_ICG_EN_PERIPH1_RAS_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH1_RAS_DISABLE_DATA, MAIN_ICG_EN_PERIPH1_RAS_EN_SHIFT, MAIN_ICG_EN_PERIPH1_RAS_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PERIPH1_RAS_ 		itg_get_reg(MAIN_ICG_EN_PERIPH1_RAS_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH1_RAS_EN_SHIFT, MAIN_ICG_EN_PERIPH1_RAS_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PERIPH1_RAS_(x) 		itg_set_reg(MAIN_ICG_EN_PERIPH1_RAS_CTRL_REG_ADDR, x, MAIN_ICG_EN_PERIPH1_RAS_EN_SHIFT, MAIN_ICG_EN_PERIPH1_RAS_EN_MASK)


#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BMCPERIPH1_IOMUX_PRESETN_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH1_IOMUX_PRESETN_SHIFT, RSTN_U0_BMCPERIPH1_IOMUX_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BMCPERIPH1_IOMUX_PRESETN_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH1_IOMUX_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BMCPERIPH1_IOMUX_PRESETN_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH1_IOMUX_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BMCPERIPH1_SYSCON_PRESETN_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH1_SYSCON_PRESETN_SHIFT, RSTN_U0_BMCPERIPH1_SYSCON_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BMCPERIPH1_SYSCON_PRESETN_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH1_SYSCON_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BMCPERIPH1_SYSCON_PRESETN_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH1_SYSCON_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_SFC0_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SFC0_SHIFT, MAIN_RSTN_SFC0_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_SFC0_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SFC0_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_SFC0_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SFC0_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_SFC1_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SFC1_SHIFT, MAIN_RSTN_SFC1_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_SFC1_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SFC1_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_SFC1_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SFC1_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_SFC2_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SFC2_SHIFT, MAIN_RSTN_SFC2_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_SFC2_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SFC2_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_SFC2_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SFC2_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_SPI0_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SPI0_SHIFT, MAIN_RSTN_SPI0_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_SPI0_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SPI0_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_SPI0_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SPI0_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_SENSOR_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SENSOR_SHIFT, MAIN_RSTN_SENSOR_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_SENSOR_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SENSOR_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_SENSOR_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SENSOR_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_SGPIO0_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SGPIO0_SHIFT, MAIN_RSTN_SGPIO0_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_SGPIO0_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SGPIO0_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_SGPIO0_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SGPIO0_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_SGPIO1_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SGPIO1_SHIFT, MAIN_RSTN_SGPIO1_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_SGPIO1_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SGPIO1_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_SGPIO1_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SGPIO1_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_DMAC_SFC0_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SFC0_SHIFT, MAIN_RSTN_DMAC_SFC0_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_DMAC_SFC0_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SFC0_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_DMAC_SFC0_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SFC0_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_DMAC_SFC1_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SFC1_SHIFT, MAIN_RSTN_DMAC_SFC1_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_DMAC_SFC1_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SFC1_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_DMAC_SFC1_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SFC1_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_DMAC_SFC2_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SFC2_SHIFT, MAIN_RSTN_DMAC_SFC2_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_DMAC_SFC2_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SFC2_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_DMAC_SFC2_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SFC2_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_DMAC_SPI0_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SPI0_SHIFT, MAIN_RSTN_DMAC_SPI0_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_DMAC_SPI0_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SPI0_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_DMAC_SPI0_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_SPI0_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_PERIPH1_RAS_ 	itg_get_reg(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PERIPH1_RAS_SHIFT, MAIN_RSTN_PERIPH1_RAS_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_PERIPH1_RAS_ 	itg_assert_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PERIPH1_RAS_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_PERIPH1_RAS_ 	itg_clear_rst(BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PERIPH1_RAS_MASK)


#endif //_BMCPERIPH1_CRG_MACRO_H_
