#define  U1_DW_AXI_DMAC_1CH__ITG_BD_APB__BASE_ADDR                                                            0x0011A80000
#define  U2_DW_AXI_DMAC_1CH__ITG_BD_APB__BASE_ADDR                                                            0x0011A80400
#define  U3_DW_AXI_DMAC_1CH__ITG_BD_APB__BASE_ADDR                                                            0x0011A80800
#define  U0_DW_AXI_DMAC_2CH__ITG_BD_APB__BASE_ADDR                                                            0x0011A80C00
#define  U0_SGPIO__ITG_BD_APBS__BASE_ADDR                                                                     0x0011A81000
#define  U1_SGPIO__ITG_BD_APBS__BASE_ADDR                                                                     0x0011A81400
#define  U6_DWC_SENSORS_PD__ITG_BD_APBS__BASE_ADDR                                                            0x0011B20000
#define  U0_BMCPERIPH1_CRG__ITG_BD_APBS__BASE_ADDR                                                            0x0011B40000
#define  U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__BASE_ADDR                                                         0x0011B41000
#define  U0_BMCPERIPH1_IOMUX__ITG_BD_APBS__BASE_ADDR                                                          0x0011B42000
#define  U0_NCNOC_BMCPERIPH1__ITG_BD_NCNOC_INIT__BASE_ADDR                                                    0x001402E000 
#define  U0_DWC_SSI_SFC__ITG_BD_AHB_FILTER__BASE_ADDR                                                         0x0014090000
#define  U1_DWC_SSI_SFC__ITG_BD_AHB_FILTER__BASE_ADDR                                                         0x0014091000
#define  U2_DWC_SSI_SFC__ITG_BD_AHB_FILTER__BASE_ADDR                                                         0x0014092000
#define  U0_BMCPERIPH1_SECURE_CRG__ITG_BD_APBS__BASE_ADDR                                                     0x001413A000 
#define  U0_BMCPERIPH1_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR                                                  0x001413B000 
#define  U1_DWC_SSI_SFC__ITG_BD_AHB__BASE_ADDR                                                                0x0017F00000 
#define  U2_DWC_SSI_SFC__ITG_BD_AHB__BASE_ADDR                                                                0x0017F10000 
#define  U0_DWC_SSI_SPI__ITG_BD_AHB__BASE_ADDR                                                                0x0017F20000 
#define  U0_DWC_SSI_SFC__ITG_BD_AHB__BASE_ADDR                                                                0x0018000000 


#define  U1_DW_AXI_DMAC_1CH__ITG_BD_APB__END_ADDR                                                             0x0011A803FF
#define  U2_DW_AXI_DMAC_1CH__ITG_BD_APB__END_ADDR                                                             0x0011A807FF
#define  U3_DW_AXI_DMAC_1CH__ITG_BD_APB__END_ADDR                                                             0x0011A80BFF
#define  U0_DW_AXI_DMAC_2CH__ITG_BD_APB__END_ADDR                                                             0x0011A80FFF
#define  U0_SGPIO__ITG_BD_APBS__END_ADDR                                                                      0x0011A813FF
#define  U1_SGPIO__ITG_BD_APBS__END_ADDR                                                                      0x0011A817FF
#define  U6_DWC_SENSORS_PD__ITG_BD_APBS__END_ADDR                                                             0x0011B33FFF
#define  U0_BMCPERIPH1_CRG__ITG_BD_APBS__END_ADDR                                                             0x0011B40FFF
#define  U0_BMCPERIPH1_SYSCON__ITG_BD_APBS__END_ADDR                                                          0x0011B41FFF
#define  U0_BMCPERIPH1_IOMUX__ITG_BD_APBS__END_ADDR                                                           0x0011B427FF
#define  U0_NCNOC_BMCPERIPH1__ITG_BD_NCNOC_INIT__END_ADDR                                                     0x001402EFFF
#define  U0_DWC_SSI_SFC__ITG_BD_AHB_FILTER__END_ADDR                                                          0x0014090FFF
#define  U1_DWC_SSI_SFC__ITG_BD_AHB_FILTER__END_ADDR                                                          0x0014091FFF
#define  U2_DWC_SSI_SFC__ITG_BD_AHB_FILTER__END_ADDR                                                          0x0014092FFF
#define  U0_BMCPERIPH1_SECURE_CRG__ITG_BD_APBS__END_ADDR                                                      0x001413AFFF
#define  U0_BMCPERIPH1_SECURE_SYSCON__ITG_BD_APBS__END_ADDR                                                   0x001413BFFF
#define  U1_DWC_SSI_SFC__ITG_BD_AHB__END_ADDR                                                                 0x0017F0FFFF
#define  U2_DWC_SSI_SFC__ITG_BD_AHB__END_ADDR                                                                 0x0017F1FFFF
#define  U0_DWC_SSI_SPI__ITG_BD_AHB__END_ADDR                                                                 0x0017F2FFFF
#define  U0_DWC_SSI_SFC__ITG_BD_AHB__END_ADDR                                                                 0x001FFFFFFF
