//commit:8ece02821 (HEAD -> b0.8.1_dv, origin/b0.8.1_dv)

#ifndef _BMCPERIPH0_SECURE_CRG_MACRO_H_
#define _BMCPERIPH0_SECURE_CRG_MACRO_H_

//#define BMCPERIPH0_SECURE_CRG_BASE_ADDR 0x0
#define CLK_BMCPERIPH0_600_DIV6_SECURE_CTRL_REG_ADDR                 (U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)


#define BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR (U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)

#define BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR (U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)


#define CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_SHIFT                     0
#define CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_MASK                      0x7U




#define RSTN_U0_BMCPERIPH0_SECURE_SYSCON_PRESETN_SHIFT               0
#define RSTN_U0_BMCPERIPH0_SECURE_SYSCON_PRESETN_MASK                (0x1 << 0)
#define RSTN_U0_BMCPERIPH0_SECURE_SYSCON_PRESETN_ASSERT              1
#define RSTN_U0_BMCPERIPH0_SECURE_SYSCON_PRESETN_CLEAR               0

#define _DIVIDE_CLOCK_CLK_BMCPERIPH0_600_DIV6_SECURE_(div) 			itg_set_reg(CLK_BMCPERIPH0_600_DIV6_SECURE_CTRL_REG_ADDR, div, CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_SHIFT, CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH0_600_DIV6_SECURE_ 		itg_get_reg(CLK_BMCPERIPH0_600_DIV6_SECURE_CTRL_REG_ADDR, CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_SHIFT, CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_MASK)



#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BMCPERIPH0_SECURE_SYSCON_PRESETN_ 	itg_get_reg(BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH0_SECURE_SYSCON_PRESETN_SHIFT, RSTN_U0_BMCPERIPH0_SECURE_SYSCON_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BMCPERIPH0_SECURE_SYSCON_PRESETN_ 	itg_assert_rst(BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH0_SECURE_SYSCON_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BMCPERIPH0_SECURE_SYSCON_PRESETN_ 	itg_clear_rst(BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH0_SECURE_SYSCON_PRESETN_MASK)


#endif //_BMCPERIPH0_SECURE_CRG_MACRO_H_
