//commit:06b6362e (HEAD -> b0.8.1_dv, origin/b0.8.1_dv)

#ifndef _BMCPERIPH0_SECURE_CRG_MACRO_H_
#define _BMCPERIPH0_SECURE_CRG_MACRO_H_

//#define BMCPERIPH0_SECURE_CRG_BASE_ADDR 0x0
#define CLK_BMCPERIPH0_600_DIV6_SECURE_CTRL_REG_ADDR                 (U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)


#define BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR (U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT1_REG_ADDR (U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT2_REG_ADDR (U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)

#define BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR (U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS1_REG_ADDR (U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define BMCPERIPH0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS2_REG_ADDR (U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x18U)


#define CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_SHIFT                     0
#define CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_MASK                      0x7U





#define _DIVIDE_CLOCK_CLK_BMCPERIPH0_600_DIV6_SECURE_(div) 			itg_set_reg(CLK_BMCPERIPH0_600_DIV6_SECURE_CTRL_REG_ADDR, div, CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_SHIFT, CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH0_600_DIV6_SECURE_ 		itg_get_reg(CLK_BMCPERIPH0_600_DIV6_SECURE_CTRL_REG_ADDR, CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_SHIFT, CLK_BMCPERIPH0_600_DIV6_SECURE_DIV_MASK)





#endif //_BMCPERIPH0_SECURE_CRG_MACRO_H_
