#define  U0_DW_APB_UART__ITG_BD_APB_UART4__BASE_ADDR                                                          0x0011A14000
#define  U0_DW_APB_UART__ITG_BD_APB_UART5__BASE_ADDR                                                          0x0011A14400
#define  U0_DW_APB_UART__ITG_BD_APB_UART6__BASE_ADDR                                                          0x0011A14800
#define  U0_DW_APB_UART__ITG_BD_APB_UART7__BASE_ADDR                                                          0x0011A14C00
#define  U0_DW_APB_UART__ITG_BD_APB_UART8__BASE_ADDR                                                          0x0011A15000
#define  U0_DW_APB_UART__ITG_BD_APB_UART9__BASE_ADDR                                                          0x0011A15400
#define  U0_DW_APB_UART__ITG_BD_APB_UART10__BASE_ADDR                                                         0x0011A15800
#define  U0_DW_APB_UART__ITG_BD_APB_UART11__BASE_ADDR                                                         0x0011A15C00
#define  U0_DW_APB_UART__ITG_BD_APB_UART12__BASE_ADDR                                                         0x0011A16000
#define  U0_DW_APB_UART__ITG_BD_APB_UART13__BASE_ADDR                                                         0x0011A16400
#define  U0_DW_APB_UART__ITG_BD_APB_UART14__BASE_ADDR                                                         0x0011A16800
#define  U0_RESERVED_APB__ITG_BD_APBS_RESERVED__BASE_ADDR                                                     0x0011A16C00
#define  U1_RESERVED_APB__ITG_BD_APBS_RESERVED__BASE_ADDR                                                     0x0011A17000
#define  U0_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                               0x0011A18000
#define  U1_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                               0x0011A18800
#define  U2_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                               0x0011A19000
#define  U3_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                               0x0011A19800
#define  U4_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                               0x0011A1A000
#define  U5_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                               0x0011A1A800
#define  U6_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                               0x0011A1B000
#define  U7_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                               0x0011A1B800
#define  U8_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                               0x0011A1C000
#define  U9_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                               0x0011A1C800
#define  U10_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                              0x0011A1D000
#define  U11_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                              0x0011A1D800
#define  U12_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                              0x0011A1E000
#define  U13_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                              0x0011A1E800
#define  U14_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                              0x0011A1F000
#define  U15_DWC_MIPI_I3C__ITG_BD_APB__BASE_ADDR                                                              0x0011A1F800
#define  U0_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                              0x0011A20000
#define  U1_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                              0x0011A20800
#define  U2_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                              0x0011A21000
#define  U3_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                              0x0011A21800
#define  U4_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                              0x0011A22000
#define  U5_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                              0x0011A22800
#define  U6_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                              0x0011A23000
#define  U7_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                              0x0011A23800
#define  U8_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                              0x0011A24000
#define  U9_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                              0x0011A24800
#define  U10_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                             0x0011A25000
#define  U11_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                             0x0011A25800
#define  U12_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                             0x0011A26000
#define  U13_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                             0x0011A26800
#define  U14_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                             0x0011A27000
#define  U15_DWC_I2C_SMBUS__ITG_BD_APB__BASE_ADDR                                                             0x0011A27800
#define  U4_SOL__ITG_BD_APB_SOL_APB_S__BASE_ADDR                                                              0x0011A40000
#define  U5_SOL__ITG_BD_APB_SOL_APB_S__BASE_ADDR                                                              0x0011A40400
#define  U6_SOL__ITG_BD_APB_SOL_APB_S__BASE_ADDR                                                              0x0011A40800
#define  U7_SOL__ITG_BD_APB_SOL_APB_S__BASE_ADDR                                                              0x0011A40C00
#define  U8_SOL__ITG_BD_APB_SOL_APB_S__BASE_ADDR                                                              0x0011A41000
#define  U9_SOL__ITG_BD_APB_SOL_APB_S__BASE_ADDR                                                              0x0011A41400
#define  U10_SOL__ITG_BD_APB_SOL_APB_S__BASE_ADDR                                                             0x0011A41800
#define  U11_SOL__ITG_BD_APB_SOL_APB_S__BASE_ADDR                                                             0x0011A41C00
#define  U12_SOL__ITG_BD_APB_SOL_APB_S__BASE_ADDR                                                             0x0011A42000
#define  U13_SOL__ITG_BD_APB_SOL_APB_S__BASE_ADDR                                                             0x0011A42400
#define  U14_SOL__ITG_BD_APB_SOL_APB_S__BASE_ADDR                                                             0x0011A42800
#define  U2_RESERVED_APB__ITG_BD_APBS_RESERVED__BASE_ADDR                                                     0x0011A42C00
#define  U0_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                            0x0014080000
#define  U1_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                            0x0014081000
#define  U2_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                            0x0014082000
#define  U3_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                            0x0014083000
#define  U4_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                            0x0014084000
#define  U5_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                            0x0014085000
#define  U6_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                            0x0014086000
#define  U7_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                            0x0014087000
#define  U8_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                            0x0014088000
#define  U9_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                            0x0014089000
#define  U10_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                           0x001408A000
#define  U11_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                           0x001408B000
#define  U12_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                           0x001408C000
#define  U13_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                           0x001408D000
#define  U14_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                           0x001408E000
#define  U15_DWC_I2C_SMBUS__ITG_BD_APB_F__BASE_ADDR                                                           0x001408F000
#define  U0_LTPI_SCM_WRAP__ITG_BD_APB__BASE_ADDR                                                              0x0011900000
#define  U1_LTPI_SCM_WRAP__ITG_BD_APB__BASE_ADDR                                                              0x0011910000
#define  U0_TRNG__ITG_BD_AHB__BASE_ADDR                                                                       0x0011A00000
#define  U8_DWC_SENSORS_PD__ITG_BD_APBS__BASE_ADDR                                                            0x0011A04000
#define  U0_BMCPERIPH0_CRG__ITG_BD_APBS__BASE_ADDR                                                            0x0011A08000
#define  U0_BMCPERIPH0_SYSCON__ITG_BD_APBS__BASE_ADDR                                                         0x0011A09000
#define  U0_BMCPERIPH0_GPIO_IOMUX__ITG_BD_APB__BASE_ADDR                                                      0x0011A0A000
#define  U0_DMAC_AXI_PERIPH0__ITG_BD_APB_UART__BASE_ADDR                                                      0x0011A0B000
#define  U0_DMAC_AXI_PERIPH0__ITG_BD_APB_I3C__BASE_ADDR                                                       0x0011A0B400
#define  U0_DMAC_AXI_PERIPH0__ITG_BD_APB_I2C__BASE_ADDR                                                       0x0011A0B800
#define  U0_DUAL_TIMER__ITG_BD_APB__BASE_ADDR                                                                 0x0011A10000
#define  U1_DUAL_TIMER__ITG_BD_APB__BASE_ADDR                                                                 0x0011A10400
#define  U2_DUAL_TIMER__ITG_BD_APB__BASE_ADDR                                                                 0x0011A10800
#define  U0_NCNOC_BMCPERIPH0__ITG_BD_NCNOC_INIT__BASE_ADDR                                                    0x001402D000 
#define  U0_WDT__ITG_BD_APB__BASE_ADDR                                                                        0x00140B0000
#define  U1_WDT__ITG_BD_APB__BASE_ADDR                                                                        0x00140B0400
#define  U2_WDT__ITG_BD_APB__BASE_ADDR                                                                        0x00140B0800
#define  U3_WDT__ITG_BD_APB__BASE_ADDR                                                                        0x00140B0C00
#define  U4_WDT__ITG_BD_APB__BASE_ADDR                                                                        0x00140B1000
#define  U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR                                                     0x0014138000 
#define  U0_BMCPERIPH0_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR                                                  0x0014139000 


#define  U0_DW_APB_UART__ITG_BD_APB_UART4__END_ADDR                                                           0x0011A143FF
#define  U0_DW_APB_UART__ITG_BD_APB_UART5__END_ADDR                                                           0x0011A147FF
#define  U0_DW_APB_UART__ITG_BD_APB_UART6__END_ADDR                                                           0x0011A14BFF
#define  U0_DW_APB_UART__ITG_BD_APB_UART7__END_ADDR                                                           0x0011A14FFF
#define  U0_DW_APB_UART__ITG_BD_APB_UART8__END_ADDR                                                           0x0011A153FF
#define  U0_DW_APB_UART__ITG_BD_APB_UART9__END_ADDR                                                           0x0011A157FF
#define  U0_DW_APB_UART__ITG_BD_APB_UART10__END_ADDR                                                          0x0011A15BFF
#define  U0_DW_APB_UART__ITG_BD_APB_UART11__END_ADDR                                                          0x0011A15FFF
#define  U0_DW_APB_UART__ITG_BD_APB_UART12__END_ADDR                                                          0x0011A163FF
#define  U0_DW_APB_UART__ITG_BD_APB_UART13__END_ADDR                                                          0x0011A167FF
#define  U0_DW_APB_UART__ITG_BD_APB_UART14__END_ADDR                                                          0x0011A16BFF
#define  U0_RESERVED_APB__ITG_BD_APBS_RESERVED__END_ADDR                                                      0x0011A16FFF
#define  U1_RESERVED_APB__ITG_BD_APBS_RESERVED__END_ADDR                                                      0x0011A17FFF
#define  U0_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                                0x0011A187FF
#define  U1_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                                0x0011A18FFF
#define  U2_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                                0x0011A197FF
#define  U3_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                                0x0011A19FFF
#define  U4_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                                0x0011A1A7FF
#define  U5_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                                0x0011A1AFFF
#define  U6_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                                0x0011A1B7FF
#define  U7_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                                0x0011A1BFFF
#define  U8_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                                0x0011A1C7FF
#define  U9_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                                0x0011A1CFFF
#define  U10_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                               0x0011A1D7FF
#define  U11_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                               0x0011A1DFFF
#define  U12_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                               0x0011A1E7FF
#define  U13_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                               0x0011A1EFFF
#define  U14_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                               0x0011A1F7FF
#define  U15_DWC_MIPI_I3C__ITG_BD_APB__END_ADDR                                                               0x0011A1FFFF
#define  U0_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                               0x0011A207FF
#define  U1_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                               0x0011A20FFF
#define  U2_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                               0x0011A217FF
#define  U3_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                               0x0011A21FFF
#define  U4_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                               0x0011A227FF
#define  U5_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                               0x0011A22FFF
#define  U6_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                               0x0011A237FF
#define  U7_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                               0x0011A23FFF
#define  U8_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                               0x0011A247FF
#define  U9_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                               0x0011A24FFF
#define  U10_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                              0x0011A257FF
#define  U11_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                              0x0011A25FFF
#define  U12_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                              0x0011A267FF
#define  U13_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                              0x0011A26FFF
#define  U14_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                              0x0011A277FF
#define  U15_DWC_I2C_SMBUS__ITG_BD_APB__END_ADDR                                                              0x0011A37FFF
#define  U4_SOL__ITG_BD_APB_SOL_APB_S__END_ADDR                                                               0x0011A403FF
#define  U5_SOL__ITG_BD_APB_SOL_APB_S__END_ADDR                                                               0x0011A407FF
#define  U6_SOL__ITG_BD_APB_SOL_APB_S__END_ADDR                                                               0x0011A40BFF
#define  U7_SOL__ITG_BD_APB_SOL_APB_S__END_ADDR                                                               0x0011A40FFF
#define  U8_SOL__ITG_BD_APB_SOL_APB_S__END_ADDR                                                               0x0011A413FF
#define  U9_SOL__ITG_BD_APB_SOL_APB_S__END_ADDR                                                               0x0011A417FF
#define  U10_SOL__ITG_BD_APB_SOL_APB_S__END_ADDR                                                              0x0011A41BFF
#define  U11_SOL__ITG_BD_APB_SOL_APB_S__END_ADDR                                                              0x0011A41FFF
#define  U12_SOL__ITG_BD_APB_SOL_APB_S__END_ADDR                                                              0x0011A423FF
#define  U13_SOL__ITG_BD_APB_SOL_APB_S__END_ADDR                                                              0x0011A427FF
#define  U14_SOL__ITG_BD_APB_SOL_APB_S__END_ADDR                                                              0x0011A42BFF
#define  U2_RESERVED_APB__ITG_BD_APBS_RESERVED__END_ADDR                                                      0x0011A43FFF
#define  U0_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                             0x0014080FFF
#define  U1_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                             0x0014081FFF
#define  U2_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                             0x0014082FFF
#define  U3_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                             0x0014083FFF
#define  U4_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                             0x0014084FFF
#define  U5_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                             0x0014085FFF
#define  U6_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                             0x0014086FFF
#define  U7_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                             0x0014087FFF
#define  U8_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                             0x0014088FFF
#define  U9_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                             0x0014089FFF
#define  U10_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                            0x001408AFFF
#define  U11_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                            0x001408BFFF
#define  U12_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                            0x001408CFFF
#define  U13_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                            0x001408DFFF
#define  U14_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                            0x001408EFFF
#define  U15_DWC_I2C_SMBUS__ITG_BD_APB_F__END_ADDR                                                            0x001408FFFF
#define  U0_LTPI_SCM_WRAP__ITG_BD_APB__END_ADDR                                                               0x001190FFFF
#define  U1_LTPI_SCM_WRAP__ITG_BD_APB__END_ADDR                                                               0x001191FFFF
#define  U0_TRNG__ITG_BD_AHB__END_ADDR                                                                        0x0011A003FF
#define  U8_DWC_SENSORS_PD__ITG_BD_APBS__END_ADDR                                                             0x0011A07FFF
#define  U0_BMCPERIPH0_CRG__ITG_BD_APBS__END_ADDR                                                             0x0011A08FFF
#define  U0_BMCPERIPH0_SYSCON__ITG_BD_APBS__END_ADDR                                                          0x0011A09FFF
#define  U0_BMCPERIPH0_GPIO_IOMUX__ITG_BD_APB__END_ADDR                                                       0x0011A0AFFF
#define  U0_DMAC_AXI_PERIPH0__ITG_BD_APB_UART__END_ADDR                                                       0x0011A0B3FF
#define  U0_DMAC_AXI_PERIPH0__ITG_BD_APB_I3C__END_ADDR                                                        0x0011A0B7FF
#define  U0_DMAC_AXI_PERIPH0__ITG_BD_APB_I2C__END_ADDR                                                        0x0011A0BBFF
#define  U0_DUAL_TIMER__ITG_BD_APB__END_ADDR                                                                  0x0011A103FF
#define  U1_DUAL_TIMER__ITG_BD_APB__END_ADDR                                                                  0x0011A107FF
#define  U2_DUAL_TIMER__ITG_BD_APB__END_ADDR                                                                  0x0011A10BFF
#define  U0_NCNOC_BMCPERIPH0__ITG_BD_NCNOC_INIT__END_ADDR                                                     0x001402DFFF
#define  U0_WDT__ITG_BD_APB__END_ADDR                                                                         0x00140B03FF
#define  U1_WDT__ITG_BD_APB__END_ADDR                                                                         0x00140B07FF
#define  U2_WDT__ITG_BD_APB__END_ADDR                                                                         0x00140B0BFF
#define  U3_WDT__ITG_BD_APB__END_ADDR                                                                         0x00140B0FFF
#define  U4_WDT__ITG_BD_APB__END_ADDR                                                                         0x00140B13FF
#define  U0_BMCPERIPH0_SECURE_CRG__ITG_BD_APBS__END_ADDR                                                      0x0014138FFF
#define  U0_BMCPERIPH0_SECURE_SYSCON__ITG_BD_APBS__END_ADDR                                                   0x0014139FFF
