# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2024 StarFive Technology Co., Ltd.

obj-$(CONFIG_$(SPL_TPL_)CMD_STARFIVE_SEC) += starfive_sec.o
obj-$(CONFIG_$(SPL_TPL_)CMD_STARFIVE_LTPI) += starfive_ltpi.o
