# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2024 StarFive Technology Co., Ltd.

obj-$(CONFIG_$(SPL_TPL_)CMD_STARFIVE_SEC) += starfive_sec.o
obj-$(CONFIG_$(SPL_TPL_)CMD_STARFIVE_LTPI) += starfive_ltpi.o
obj-$(CONFIG_CMD_JHB100_DP) += jhb100_dp.o
obj-$(CONFIG_CMD_JHB100_NETTEST) += jhb100_nettest.o
