obj-$(CONFIG_$(SPL_)DM_RPMI_SRV_GRP) += rpmi-srvgrp-uclass.o
obj-$(CONFIG_RPMI_SHMEM_MBOX)	+= mailbox_rpmi_shmem.o
obj-$(CONFIG_RPMI_STARFIVE_SEC_SERVICE_RUNTIME_GRP)	+= rpmi_service_group_starfive_bmc_sec_rt.o
