
# SPDX-License-Identifier: GPL-2.0
# Core
obj-$(CONFIG_$(SPL_TPL_)PINCTRL_STARFIVE_JH7110) += pinctrl-starfive-jh7110.o
# SoC Drivers
obj-$(CONFIG_$(SPL_TPL_)PINCTRL_STARFIVE_JH7110) += pinctrl-starfive-jh7110-sys.o
obj-$(CONFIG_$(SPL_TPL_)PINCTRL_STARFIVE_JH7110) += pinctrl-starfive-jh7110-aon.o
