/* SPDX-License-Identifier: GPL-2.0-or-later */
/* Copyright (c) 2021 StarFive Technology Co., Ltd. */

/******************************************************************
*
* audio_clk_gen controller C MACRO generated by ezchip
*
******************************************************************/

#ifndef _AUDIO_CLK_GEN_MACRO_H_
#define _AUDIO_CLK_GEN_MACRO_H_

//#define AUDIO_CLK_GEN_BASE_ADDR 0x0
#define clk_adc_mclk_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x0
#define clk_i2s1_mclk_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x4
#define clk_apb_i2sadc_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x8
#define clk_i2sadc_bclk_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0xC
#define clk_i2sadc_bclk_n_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x10
#define clk_i2sadc_lrclk_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x14
#define clk_apb_pdm_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x18
#define clk_pdm_mclk_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x1C
#define clk_apb_i2svad_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x20
#define clk_spdif_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x24
#define clk_apb_spdif_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x28
#define clk_apb_pwmdac_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x2C
#define clk_dac_mclk_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x30
#define clk_apb_i2sdac_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x34
#define clk_i2sdac_bclk_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x38
#define clk_i2sdac_bclk_n_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x3C
#define clk_i2sdac_lrclk_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x40
#define clk_apb_i2s1_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x44
#define clk_i2s1_bclk_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x48
#define clk_i2s1_bclk_n_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x4C
#define clk_i2s1_lrclk_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x50
#define clk_apb_i2sdac16k_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x54
#define clk_apb0_bus_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x58
#define clk_dma1p_ahb_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x5C
#define clk_apb_usb_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x60
#define clk_usb_lpm_clk_predft_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x64
#define clk_usb_stb_clk_predft_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x68
#define clk_apb_en_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x6C
#define clk_vad_mem_ctrl_REG_ADDR  AUDIO_CLK_GEN_BASE_ADDR + 0x70

#define _ENABLE_CLOCK_clk_adc_mclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_adc_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_adc_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_adc_mclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_adc_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_adc_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_adc_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_adc_mclk_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SWITCH_CLOCK_clk_adc_mclk_SOURCE_clk_audio_src_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_adc_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<24; \
	MA_OUTW(clk_adc_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_adc_mclk_SOURCE_clk_audio_12288_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_adc_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<24; \
	MA_OUTW(clk_adc_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_adc_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_adc_mclk_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _DIVIDE_CLOCK_clk_adc_mclk_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_adc_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xF); \
	_ezchip_macro_read_value_ |= (div&0xF); \
	MA_OUTW(clk_adc_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_adc_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_adc_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xf;\
}

#define _ENABLE_CLOCK_clk_i2s1_mclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_i2s1_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_i2s1_mclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_i2s1_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_i2s1_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2s1_mclk_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SWITCH_CLOCK_clk_i2s1_mclk_SOURCE_clk_audio_src_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<24; \
	MA_OUTW(clk_i2s1_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_i2s1_mclk_SOURCE_clk_audio_12288_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<24; \
	MA_OUTW(clk_i2s1_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_i2s1_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2s1_mclk_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _DIVIDE_CLOCK_clk_i2s1_mclk_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xF); \
	_ezchip_macro_read_value_ |= (div&0xF); \
	MA_OUTW(clk_i2s1_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_i2s1_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2s1_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xf;\
}

#define _ENABLE_CLOCK_clk_apb_i2sadc_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_i2sadc_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_apb_i2sadc_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_apb_i2sadc_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_i2sadc_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_apb_i2sadc_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_apb_i2sadc_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_apb_i2sadc_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_i2sadc_bclk_ {}

#define _SWITCH_CLOCK_clk_i2sadc_bclk_SOURCE_clk_adc_mclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sadc_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<24; \
	MA_OUTW(clk_i2sadc_bclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_i2sadc_bclk_SOURCE_clk_i2sadc_bclk_iopad_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sadc_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<24; \
	MA_OUTW(clk_i2sadc_bclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_i2sadc_bclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2sadc_bclk_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _DIVIDE_CLOCK_clk_i2sadc_bclk_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sadc_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F); \
	_ezchip_macro_read_value_ |= (div&0x1F); \
	MA_OUTW(clk_i2sadc_bclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_i2sadc_bclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2sadc_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _ENABLE_CLOCK_clk_i2sadc_bclk_n_ {}

#define _SET_CLOCK_clk_i2sadc_bclk_n_POLARITY_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sadc_bclk_n_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<30); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<30; \
	MA_OUTW(clk_i2sadc_bclk_n_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _UNSET_CLOCK_clk_i2sadc_bclk_n_POLARITY_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sadc_bclk_n_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<30); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<30; \
	MA_OUTW(clk_i2sadc_bclk_n_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_POLARITY_STATUS_clk_i2sadc_bclk_n_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2sadc_bclk_n_ctrl_REG_ADDR) >> 30; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_i2sadc_lrclk_ {}

#define _SWITCH_CLOCK_clk_i2sadc_lrclk_SOURCE_clk_i2sadc_bclk_n_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sadc_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x3)<<24; \
	MA_OUTW(clk_i2sadc_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_i2sadc_lrclk_SOURCE_clk_i2sadc_lrclk_iopad_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sadc_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x3)<<24; \
	MA_OUTW(clk_i2sadc_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_i2sadc_lrclk_SOURCE_clk_i2sadc_bclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sadc_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3<<24); \
	_ezchip_macro_read_value_ |= (0x2&0x3)<<24; \
	MA_OUTW(clk_i2sadc_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_i2sadc_lrclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2sadc_lrclk_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x3;\
}

#define _DIVIDE_CLOCK_clk_i2sadc_lrclk_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sadc_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3F); \
	_ezchip_macro_read_value_ |= (div&0x3F); \
	MA_OUTW(clk_i2sadc_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_i2sadc_lrclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2sadc_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x3f;\
}

#define _ENABLE_CLOCK_clk_apb_pdm_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_pdm_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_apb_pdm_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_apb_pdm_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_pdm_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_apb_pdm_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_apb_pdm_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_apb_pdm_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_pdm_mclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_pdm_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_pdm_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_pdm_mclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_pdm_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_pdm_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_pdm_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_pdm_mclk_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SWITCH_CLOCK_clk_pdm_mclk_SOURCE_clk_audio_src_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_pdm_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<24; \
	MA_OUTW(clk_pdm_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_pdm_mclk_SOURCE_clk_audio_12288_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_pdm_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<24; \
	MA_OUTW(clk_pdm_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_pdm_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_pdm_mclk_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _DIVIDE_CLOCK_clk_pdm_mclk_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_pdm_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xF); \
	_ezchip_macro_read_value_ |= (div&0xF); \
	MA_OUTW(clk_pdm_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_pdm_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_pdm_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xf;\
}

#define _ENABLE_CLOCK_clk_apb_i2svad_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_i2svad_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_apb_i2svad_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_apb_i2svad_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_i2svad_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_apb_i2svad_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_apb_i2svad_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_apb_i2svad_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_spdif_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_spdif_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_spdif_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_spdif_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_spdif_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_spdif_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_spdif_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_spdif_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SWITCH_CLOCK_clk_spdif_SOURCE_clk_audio_src_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_spdif_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<24; \
	MA_OUTW(clk_spdif_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_spdif_SOURCE_clk_audio_12288_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_spdif_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<24; \
	MA_OUTW(clk_spdif_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_spdif_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_spdif_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _DIVIDE_CLOCK_clk_spdif_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_spdif_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xF); \
	_ezchip_macro_read_value_ |= (div&0xF); \
	MA_OUTW(clk_spdif_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_spdif_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_spdif_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xf;\
}

#define _ENABLE_CLOCK_clk_apb_spdif_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_spdif_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_apb_spdif_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_apb_spdif_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_spdif_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_apb_spdif_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_apb_spdif_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_apb_spdif_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_apb_pwmdac_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_pwmdac_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_apb_pwmdac_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_apb_pwmdac_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_pwmdac_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_apb_pwmdac_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_apb_pwmdac_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_apb_pwmdac_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_dac_mclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_dac_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_dac_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_dac_mclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_dac_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_dac_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_dac_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_dac_mclk_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SWITCH_CLOCK_clk_dac_mclk_SOURCE_clk_audio_src_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_dac_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<24; \
	MA_OUTW(clk_dac_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_dac_mclk_SOURCE_clk_audio_12288_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_dac_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<24; \
	MA_OUTW(clk_dac_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_dac_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_dac_mclk_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _DIVIDE_CLOCK_clk_dac_mclk_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_dac_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xF); \
	_ezchip_macro_read_value_ |= (div&0xF); \
	MA_OUTW(clk_dac_mclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_dac_mclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_dac_mclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xf;\
}

#define _ENABLE_CLOCK_clk_apb_i2sdac_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_i2sdac_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_apb_i2sdac_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_apb_i2sdac_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_i2sdac_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_apb_i2sdac_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_apb_i2sdac_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_apb_i2sdac_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_i2sdac_bclk_ {}

#define _SWITCH_CLOCK_clk_i2sdac_bclk_SOURCE_clk_dac_mclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sdac_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<24; \
	MA_OUTW(clk_i2sdac_bclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_i2sdac_bclk_SOURCE_clk_i2sdac_bclk_iopad_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sdac_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<24; \
	MA_OUTW(clk_i2sdac_bclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_i2sdac_bclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2sdac_bclk_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _DIVIDE_CLOCK_clk_i2sdac_bclk_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sdac_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F); \
	_ezchip_macro_read_value_ |= (div&0x1F); \
	MA_OUTW(clk_i2sdac_bclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_i2sdac_bclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2sdac_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _ENABLE_CLOCK_clk_i2sdac_bclk_n_ {}

#define _SET_CLOCK_clk_i2sdac_bclk_n_POLARITY_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sdac_bclk_n_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<30); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<30; \
	MA_OUTW(clk_i2sdac_bclk_n_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _UNSET_CLOCK_clk_i2sdac_bclk_n_POLARITY_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sdac_bclk_n_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<30); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<30; \
	MA_OUTW(clk_i2sdac_bclk_n_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_POLARITY_STATUS_clk_i2sdac_bclk_n_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2sdac_bclk_n_ctrl_REG_ADDR) >> 30; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_i2sdac_lrclk_ {}

#define _SWITCH_CLOCK_clk_i2sdac_lrclk_SOURCE_clk_i2sdac_bclk_n_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sdac_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x3)<<24; \
	MA_OUTW(clk_i2sdac_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_i2sdac_lrclk_SOURCE_clk_i2sdac_lrclk_iopad_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sdac_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x3)<<24; \
	MA_OUTW(clk_i2sdac_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_i2sdac_lrclk_SOURCE_clk_i2sdac_bclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sdac_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3<<24); \
	_ezchip_macro_read_value_ |= (0x2&0x3)<<24; \
	MA_OUTW(clk_i2sdac_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_i2sdac_lrclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2sdac_lrclk_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x3;\
}

#define _DIVIDE_CLOCK_clk_i2sdac_lrclk_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2sdac_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3F); \
	_ezchip_macro_read_value_ |= (div&0x3F); \
	MA_OUTW(clk_i2sdac_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_i2sdac_lrclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2sdac_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x3f;\
}

#define _ENABLE_CLOCK_clk_apb_i2s1_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_i2s1_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_apb_i2s1_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_apb_i2s1_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_i2s1_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_apb_i2s1_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_apb_i2s1_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_apb_i2s1_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_i2s1_bclk_ {}

#define _SWITCH_CLOCK_clk_i2s1_bclk_SOURCE_clk_i2s1_mclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<24; \
	MA_OUTW(clk_i2s1_bclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_i2s1_bclk_SOURCE_clk_i2sdac_bclk_iopad_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<24; \
	MA_OUTW(clk_i2s1_bclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_i2s1_bclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2s1_bclk_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _DIVIDE_CLOCK_clk_i2s1_bclk_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F); \
	_ezchip_macro_read_value_ |= (div&0x1F); \
	MA_OUTW(clk_i2s1_bclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_i2s1_bclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2s1_bclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _ENABLE_CLOCK_clk_i2s1_bclk_n_ {}

#define _SET_CLOCK_clk_i2s1_bclk_n_POLARITY_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_bclk_n_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<30); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<30; \
	MA_OUTW(clk_i2s1_bclk_n_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _UNSET_CLOCK_clk_i2s1_bclk_n_POLARITY_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_bclk_n_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<30); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<30; \
	MA_OUTW(clk_i2s1_bclk_n_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_POLARITY_STATUS_clk_i2s1_bclk_n_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2s1_bclk_n_ctrl_REG_ADDR) >> 30; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_i2s1_lrclk_ {}

#define _SWITCH_CLOCK_clk_i2s1_lrclk_SOURCE_clk_i2s1_bclk_n_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x3)<<24; \
	MA_OUTW(clk_i2s1_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_i2s1_lrclk_SOURCE_clk_i2sdac_lrclk_iopad_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x3)<<24; \
	MA_OUTW(clk_i2s1_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_i2s1_lrclk_SOURCE_clk_i2s1_bclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3<<24); \
	_ezchip_macro_read_value_ |= (0x2&0x3)<<24; \
	MA_OUTW(clk_i2s1_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_i2s1_lrclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2s1_lrclk_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x3;\
}

#define _DIVIDE_CLOCK_clk_i2s1_lrclk_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_i2s1_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3F); \
	_ezchip_macro_read_value_ |= (div&0x3F); \
	MA_OUTW(clk_i2s1_lrclk_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_i2s1_lrclk_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_i2s1_lrclk_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x3f;\
}

#define _ENABLE_CLOCK_clk_apb_i2sdac16k_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_i2sdac16k_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_apb_i2sdac16k_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_apb_i2sdac16k_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_i2sdac16k_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_apb_i2sdac16k_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_apb_i2sdac16k_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_apb_i2sdac16k_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_apb0_bus_ {}

#define _DIVIDE_CLOCK_clk_apb0_bus_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb0_bus_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xF); \
	_ezchip_macro_read_value_ |= (div&0xF); \
	MA_OUTW(clk_apb0_bus_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_apb0_bus_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_apb0_bus_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xf;\
}

#define _ENABLE_CLOCK_clk_dma1p_ahb_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_dma1p_ahb_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_dma1p_ahb_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_dma1p_ahb_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_dma1p_ahb_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_dma1p_ahb_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_dma1p_ahb_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_dma1p_ahb_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_apb_usb_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_usb_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_apb_usb_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_apb_usb_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_usb_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_apb_usb_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_apb_usb_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_apb_usb_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _ENABLE_CLOCK_clk_usb_lpm_clk_predft_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_usb_lpm_clk_predft_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_usb_lpm_clk_predft_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_usb_lpm_clk_predft_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_usb_lpm_clk_predft_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_usb_lpm_clk_predft_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_usb_lpm_clk_predft_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_usb_lpm_clk_predft_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _DIVIDE_CLOCK_clk_usb_lpm_clk_predft_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_usb_lpm_clk_predft_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7); \
	_ezchip_macro_read_value_ |= (div&0x7); \
	MA_OUTW(clk_usb_lpm_clk_predft_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_usb_lpm_clk_predft_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_usb_lpm_clk_predft_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7;\
}

#define _ENABLE_CLOCK_clk_usb_stb_clk_predft_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_usb_stb_clk_predft_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<31; \
	MA_OUTW(clk_usb_stb_clk_predft_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _DISABLE_CLOCK_clk_usb_stb_clk_predft_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_usb_stb_clk_predft_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<31); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<31; \
	MA_OUTW(clk_usb_stb_clk_predft_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_ENABLE_STATUS_clk_usb_stb_clk_predft_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_usb_stb_clk_predft_ctrl_REG_ADDR) >> 31; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _DIVIDE_CLOCK_clk_usb_stb_clk_predft_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_usb_stb_clk_predft_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3); \
	_ezchip_macro_read_value_ |= (div&0x3); \
	MA_OUTW(clk_usb_stb_clk_predft_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_usb_stb_clk_predft_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_usb_stb_clk_predft_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x3;\
}

#define _ENABLE_CLOCK_clk_apb_en_ {}

#define _DIVIDE_CLOCK_clk_apb_en_(div) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_apb_en_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xF); \
	_ezchip_macro_read_value_ |= (div&0xF); \
	MA_OUTW(clk_apb_en_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_DIVIDE_STATUS_clk_apb_en_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_apb_en_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xf;\
}

#define _ENABLE_CLOCK_clk_vad_mem_ {}

#define _SWITCH_CLOCK_clk_vad_mem_SOURCE_clk_vad_intmem_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_vad_mem_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x0&0x1)<<24; \
	MA_OUTW(clk_vad_mem_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _SWITCH_CLOCK_clk_vad_mem_SOURCE_clk_i2svad_bclk_ { \
	uint32_t _ezchip_macro_read_value_=MA_INW(clk_vad_mem_ctrl_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<24); \
	_ezchip_macro_read_value_ |= (0x1&0x1)<<24; \
	MA_OUTW(clk_vad_mem_ctrl_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_CLOCK_SOURCE_STATUS_clk_vad_mem_(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(clk_vad_mem_ctrl_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#endif //_AUDIO_CLK_GEN_MACRO_H_
