/* SPDX-License-Identifier: GPL-2.0-or-later */
/* Copyright (c) 2021 StarFive Technology Co., Ltd. */

/******************************************************************
*
* syscon_remap_vp6_noc_top C MACRO generated by ezchip
*
******************************************************************/

#ifndef _SYSCON_REMAP_VP6_NOC_MACRO_H_
#define _SYSCON_REMAP_VP6_NOC_MACRO_H_

//#define SYSCON_REMAP_VP6_NOC_BASE_ADDR 0x0
#define syscon_remap_vp6_noc_SCFG_vdec_remap_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x38
#define syscon_remap_vp6_noc_SCFG_vdec_remap_bound_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x3C
#define syscon_remap_vp6_noc_SCFG_venc_remap_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x40
#define syscon_remap_vp6_noc_SCFG_venc_remap_bound_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x44
#define syscon_remap_vp6_noc_SCFG_isp0_remap_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x48
#define syscon_remap_vp6_noc_SCFG_isp0_remap_bound_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x4C
#define syscon_remap_vp6_noc_SCFG_isp1_remap_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x50
#define syscon_remap_vp6_noc_SCFG_isp1_remap_bound_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x54
#define syscon_remap_vp6_noc_SCFG_vin_remap_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x58
#define syscon_remap_vp6_noc_SCFG_vin_remap_bound_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x5C
#define syscon_remap_vp6_noc_SCFG_disp0_remap_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x60
#define syscon_remap_vp6_noc_SCFG_disp0_remap_bound_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x64
#define syscon_remap_vp6_noc_SCFG_disp1_remap_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x68
#define syscon_remap_vp6_noc_SCFG_disp1_remap_bound_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x6C
#define syscon_remap_vp6_noc_SCFG_usb_remap_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x70
#define syscon_remap_vp6_noc_SCFG_usb_remap_bound_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x74
#define syscon_remap_vp6_noc_register29_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x78
#define syscon_remap_vp6_noc_register30_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x7C
#define syscon_remap_vp6_noc_register31_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x80
#define syscon_remap_vp6_noc_register32_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x84
#define syscon_remap_vp6_noc_register33_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x88
#define syscon_remap_vp6_noc_register34_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x8C
#define syscon_remap_vp6_noc_register35_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x90
#define syscon_remap_vp6_noc_register36_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x94
#define syscon_remap_vp6_noc_register37_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x98
#define syscon_remap_vp6_noc_register38_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x9C
#define syscon_remap_vp6_noc_register39_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xA0
#define syscon_remap_vp6_noc_register40_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xA4
#define syscon_remap_vp6_noc_register41_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xA8
#define syscon_remap_vp6_noc_register42_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xAC
#define syscon_remap_vp6_noc_register43_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xB0
#define syscon_remap_vp6_noc_SCFG_jpeg_remap_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xB4
#define syscon_remap_vp6_noc_SCFG_jpeg_remap_bound_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xB8
#define syscon_remap_vp6_noc_SCFG_gc300_remap_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xBC
#define syscon_remap_vp6_noc_SCFG_gc300_remap_bound_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xC0
#define syscon_remap_vp6_noc_register51_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xD0
#define syscon_remap_vp6_noc_register52_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xD4
#define syscon_remap_vp6_noc_register53_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xD8
#define syscon_remap_vp6_noc_register54_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xDC
#define syscon_remap_vp6_noc_register55_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xE0
#define syscon_remap_vp6_noc_register56_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xE4
#define syscon_remap_vp6_noc_register57_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xE8
#define syscon_remap_vp6_noc_register58_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xEC
#define syscon_remap_vp6_noc_register59_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xF0
#define syscon_remap_vp6_noc_register60_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xF4
#define syscon_remap_vp6_noc_register61_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xF8
#define syscon_remap_vp6_noc_register62_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0xFC
#define syscon_remap_vp6_noc_register63_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x100
#define syscon_remap_vp6_noc_register64_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x104
#define syscon_remap_vp6_noc_register65_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x108
#define syscon_remap_vp6_noc_register66_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x10C
#define syscon_remap_vp6_noc_register67_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x110
#define syscon_remap_vp6_noc_register68_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x114
#define syscon_remap_vp6_noc_register69_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x118
#define syscon_remap_vp6_noc_register70_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x11C
#define syscon_remap_vp6_noc_register71_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x120
#define syscon_remap_vp6_noc_register72_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x124
#define syscon_remap_vp6_noc_register75_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x130
#define syscon_remap_vp6_noc_register76_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x134
#define syscon_remap_vp6_noc_register77_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x138
#define syscon_remap_vp6_noc_register78_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x13C
#define syscon_remap_vp6_noc_register79_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x140
#define syscon_remap_vp6_noc_register81_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x148
#define syscon_remap_vp6_noc_register82_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x14C
#define syscon_remap_vp6_noc_register83_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x150
#define syscon_remap_vp6_noc_register84_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x154
#define syscon_remap_vp6_noc_register85_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x15C
#define syscon_remap_vp6_noc_register87_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x164
#define syscon_remap_vp6_noc_register88_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x168
#define syscon_remap_vp6_noc_register89_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x16C
#define syscon_remap_vp6_noc_register90_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x170
#define syscon_remap_vp6_noc_register91_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x174
#define syscon_remap_vp6_noc_register92_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x178
#define syscon_remap_vp6_noc_register93_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x17C
#define syscon_remap_vp6_noc_register94_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x180
#define syscon_remap_vp6_noc_register95_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x184
#define syscon_remap_vp6_noc_register96_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x188
#define syscon_remap_vp6_noc_register97_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x18C
#define syscon_remap_vp6_noc_register98_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x190
#define syscon_remap_vp6_noc_register99_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x194
#define syscon_remap_vp6_noc_register100_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x198
#define syscon_remap_vp6_noc_register101_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x19C
#define syscon_remap_vp6_noc_register102_REG_ADDR  SYSCON_REMAP_VP6_NOC_BASE_ADDR + 0x1A0

#define _SET_SYSCON_REG_SCFG_vdec_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vdec_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_vdec_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_vdec_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vdec_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_SCFG_vdec_remap_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vdec_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_vdec_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_vdec_remap_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vdec_remap_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_SCFG_vdec_remap_offset_addr(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vdec_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_vdec_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_vdec_remap_offset_addr(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vdec_remap_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_SCFG_vdec_remap_bound_addr0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vdec_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_vdec_remap_bound_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_vdec_remap_bound_addr0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vdec_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_SCFG_venc_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_venc_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_venc_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_venc_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_venc_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_SCFG_venc_remap_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_venc_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_venc_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_venc_remap_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_venc_remap_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_SCFG_venc_remap_offset_addr(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_venc_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_venc_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_venc_remap_offset_addr(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_venc_remap_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_SCFG_venc_remap_bound_addr0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_venc_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_venc_remap_bound_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_venc_remap_bound_addr0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_venc_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_SCFG_isp0_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp0_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_isp0_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_isp0_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp0_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_SCFG_isp0_remap_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp0_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_isp0_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_isp0_remap_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp0_remap_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_SCFG_isp0_remap_offset_addr(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp0_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_isp0_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_isp0_remap_offset_addr(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp0_remap_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_SCFG_isp0_remap_bound_addr0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp0_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_isp0_remap_bound_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_isp0_remap_bound_addr0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp0_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_SCFG_isp1_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp1_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_isp1_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_isp1_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp1_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_SCFG_isp1_remap_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp1_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_isp1_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_isp1_remap_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp1_remap_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_SCFG_isp1_remap_offset_addr(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp1_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_isp1_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_isp1_remap_offset_addr(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp1_remap_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_SCFG_isp1_remap_bound_addr0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp1_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_isp1_remap_bound_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_isp1_remap_bound_addr0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_isp1_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_SCFG_vin_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vin_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_vin_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_vin_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vin_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_SCFG_vin_remap_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vin_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_vin_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_vin_remap_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vin_remap_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_SCFG_vin_remap_offset_addr(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vin_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_vin_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_vin_remap_offset_addr(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vin_remap_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_SCFG_vin_remap_bound_addr0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vin_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_vin_remap_bound_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_vin_remap_bound_addr0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_vin_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_SCFG_disp0_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp0_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_disp0_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_disp0_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp0_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_SCFG_disp0_remap_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp0_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_disp0_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_disp0_remap_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp0_remap_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_SCFG_disp0_remap_offset_addr(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp0_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_disp0_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_disp0_remap_offset_addr(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp0_remap_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_SCFG_disp0_remap_bound_addr0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp0_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_disp0_remap_bound_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_disp0_remap_bound_addr0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp0_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_SCFG_disp1_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp1_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_disp1_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_disp1_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp1_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_SCFG_disp1_remap_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp1_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_disp1_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_disp1_remap_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp1_remap_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_SCFG_disp1_remap_offset_addr(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp1_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_disp1_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_disp1_remap_offset_addr(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp1_remap_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_SCFG_disp1_remap_bound_addr0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp1_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_disp1_remap_bound_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_disp1_remap_bound_addr0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_disp1_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_SCFG_usb_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_usb_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_usb_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_usb_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_usb_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_SCFG_usb_remap_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_usb_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_usb_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_usb_remap_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_usb_remap_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_SCFG_usb_remap_offset_addr(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_usb_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_usb_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_usb_remap_offset_addr(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_usb_remap_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_SCFG_usb_remap_bound_addr0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_usb_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_usb_remap_bound_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_usb_remap_bound_addr0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_usb_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_register29_SCFG_sdio0_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register29_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register29_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register29_SCFG_sdio0_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register29_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register29_sdio0_remap_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register29_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_register29_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register29_sdio0_remap_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register29_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register29_SCFG_sdio0_remap_offset(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register29_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_register29_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register29_SCFG_sdio0_remap_offset(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register29_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_register30_SCFG_sdio0_remap_upbound(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register30_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_register30_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register30_SCFG_sdio0_remap_upbound(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register30_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_register31_SCFG_sdio1_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register31_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register31_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register31_SCFG_sdio1_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register31_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register31_sdio1_remap_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register31_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_register31_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register31_sdio1_remap_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register31_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register31_SCFG_sdio1_remap_offset(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register31_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_register31_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register31_SCFG_sdio1_remap_offset(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register31_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_register32_SCFG_sdio1_remap_upbound(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register32_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_register32_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register32_SCFG_sdio1_remap_upbound(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register32_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_register33_SCFG_gmac_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register33_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register33_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register33_SCFG_gmac_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register33_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register33_gmac_remap_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register33_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_register33_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register33_gmac_remap_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register33_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register33_SCFG_gmac_remap_offset(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register33_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_register33_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register33_SCFG_gmac_remap_offset(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register33_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_register34_SCFG_gmac_remap_upbound(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register34_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_register34_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register34_SCFG_gmac_remap_upbound(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register34_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_register35_SCFG_spi2ahb_maddr_offset(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register35_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register35_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register35_SCFG_spi2ahb_maddr_offset(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register35_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_register36_SCFG_e24_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register36_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register36_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register36_SCFG_e24_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register36_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register37_SCFG_e24_remap_start0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register37_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF); \
	_ezchip_macro_read_value_ |= (v&0xFF); \
	MA_OUTW(syscon_remap_vp6_noc_register37_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register37_SCFG_e24_remap_start0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register37_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register37_SCFG_e24_remap_offset0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register37_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3FFF<<8); \
	_ezchip_macro_read_value_ |= (v&0x3FFF)<<8; \
	MA_OUTW(syscon_remap_vp6_noc_register37_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register37_SCFG_e24_remap_offset0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register37_REG_ADDR) >> 8; \
	_ezchip_macro_read_value_ &= 0x3fff;\
}

#define _SET_SYSCON_REG_register38_SCFG_e24_remap_start1(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register38_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF); \
	_ezchip_macro_read_value_ |= (v&0xFF); \
	MA_OUTW(syscon_remap_vp6_noc_register38_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register38_SCFG_e24_remap_start1(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register38_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register38_SCFG_e24_remap_offset1(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register38_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3FFF<<8); \
	_ezchip_macro_read_value_ |= (v&0x3FFF)<<8; \
	MA_OUTW(syscon_remap_vp6_noc_register38_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register38_SCFG_e24_remap_offset1(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register38_REG_ADDR) >> 8; \
	_ezchip_macro_read_value_ &= 0x3fff;\
}

#define _SET_SYSCON_REG_register39_SCFG_e24_remap_upbound0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register39_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_register39_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register39_SCFG_e24_remap_upbound0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register39_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_register39_SCFG_e24_remap_upbound1(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register39_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF<<16); \
	_ezchip_macro_read_value_ |= (v&0x7FFF)<<16; \
	MA_OUTW(syscon_remap_vp6_noc_register39_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register39_SCFG_e24_remap_upbound1(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register39_REG_ADDR) >> 16; \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_register40_SCFG_ezmst_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register40_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register40_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register40_SCFG_ezmst_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register40_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register41_ezmst_remap_start0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register41_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF); \
	_ezchip_macro_read_value_ |= (v&0xFF); \
	MA_OUTW(syscon_remap_vp6_noc_register41_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register41_ezmst_remap_start0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register41_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register41_SCFG_ezmst_remap_offset0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register41_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3FFF<<8); \
	_ezchip_macro_read_value_ |= (v&0x3FFF)<<8; \
	MA_OUTW(syscon_remap_vp6_noc_register41_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register41_SCFG_ezmst_remap_offset0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register41_REG_ADDR) >> 8; \
	_ezchip_macro_read_value_ &= 0x3fff;\
}

#define _SET_SYSCON_REG_register42_ezmst_remap_start1(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register42_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF); \
	_ezchip_macro_read_value_ |= (v&0xFF); \
	MA_OUTW(syscon_remap_vp6_noc_register42_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register42_ezmst_remap_start1(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register42_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register42_SCFG_ezmst_remap_offset1(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register42_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3FFF<<8); \
	_ezchip_macro_read_value_ |= (v&0x3FFF)<<8; \
	MA_OUTW(syscon_remap_vp6_noc_register42_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register42_SCFG_ezmst_remap_offset1(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register42_REG_ADDR) >> 8; \
	_ezchip_macro_read_value_ &= 0x3fff;\
}

#define _SET_SYSCON_REG_register43_SCFG_ezmst_remap_upbound0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register43_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_register43_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register43_SCFG_ezmst_remap_upbound0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register43_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_register43_SCFG_ezmst_upbound_addr1(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register43_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF<<16); \
	_ezchip_macro_read_value_ |= (v&0x7FFF)<<16; \
	MA_OUTW(syscon_remap_vp6_noc_register43_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register43_SCFG_ezmst_upbound_addr1(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register43_REG_ADDR) >> 16; \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_SCFG_jpeg_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_jpeg_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_jpeg_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_jpeg_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_jpeg_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_SCFG_jpeg_remap_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_jpeg_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_jpeg_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_jpeg_remap_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_jpeg_remap_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_SCFG_jpeg_remap_offset_addr(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_jpeg_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_jpeg_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_jpeg_remap_offset_addr(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_jpeg_remap_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_SCFG_jpeg_remap_bound_addr0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_jpeg_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_jpeg_remap_bound_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_jpeg_remap_bound_addr0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_jpeg_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_SCFG_gc300_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_gc300_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_gc300_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_gc300_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_gc300_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_SCFG_gc300_remap_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_gc300_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<4); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_gc300_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_gc300_remap_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_gc300_remap_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_SCFG_gc300_remap_offset_addr(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_gc300_remap_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFF<<12); \
	_ezchip_macro_read_value_ |= (v&0xFFF)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_gc300_remap_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_gc300_remap_offset_addr(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_gc300_remap_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0xfff;\
}

#define _SET_SYSCON_REG_SCFG_gc300_remap_bound_addr0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_gc300_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FFF); \
	_ezchip_macro_read_value_ |= (v&0x7FFF); \
	MA_OUTW(syscon_remap_vp6_noc_SCFG_gc300_remap_bound_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_SCFG_gc300_remap_bound_addr0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_SCFG_gc300_remap_bound_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7fff;\
}

#define _SET_SYSCON_REG_register51_CLOCK_GATING_OFF(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register51_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register51_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register51_CLOCK_GATING_OFF(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register51_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register52_ddrc0_preq(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register52_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register52_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register52_ddrc0_preq(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register52_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register52_ddrc0_pstate(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register52_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7<<1); \
	_ezchip_macro_read_value_ |= (v&0x7)<<1; \
	MA_OUTW(syscon_remap_vp6_noc_register52_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register52_ddrc0_pstate(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register52_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x7;\
}

#define _GET_SYSCON_REG_register53_ddrc0_paccept(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register53_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register53_ddrc0_pactive(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register53_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register53_ddrc0_pdeny(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register53_REG_ADDR) >> 2; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register54_ddrc1_pstate(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register54_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7); \
	_ezchip_macro_read_value_ |= (v&0x7); \
	MA_OUTW(syscon_remap_vp6_noc_register54_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register54_ddrc1_pstate(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register54_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7;\
}

#define _SET_SYSCON_REG_register54_ddrc1_preq(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register54_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<3); \
	_ezchip_macro_read_value_ |= (v&0x1)<<3; \
	MA_OUTW(syscon_remap_vp6_noc_register54_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register54_ddrc1_preq(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register54_REG_ADDR) >> 3; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register55_ddrc1_paccept(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register55_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register55_ddrc1_pactive(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register55_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register55_ddrc1_pdeny(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register55_REG_ADDR) >> 2; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_0_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_0_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_1_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<1); \
	_ezchip_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_1_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_2_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<2); \
	_ezchip_macro_read_value_ |= (v&0x1)<<2; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_2_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 2; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_3_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<3); \
	_ezchip_macro_read_value_ |= (v&0x1)<<3; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_3_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 3; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_4_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<4); \
	_ezchip_macro_read_value_ |= (v&0x1)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_4_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_5_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<5); \
	_ezchip_macro_read_value_ |= (v&0x1)<<5; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_5_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 5; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_6_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<6); \
	_ezchip_macro_read_value_ |= (v&0x1)<<6; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_6_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 6; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_7_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<7); \
	_ezchip_macro_read_value_ |= (v&0x1)<<7; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_7_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 7; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_8_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<8); \
	_ezchip_macro_read_value_ |= (v&0x1)<<8; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_8_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 8; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_9_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<9); \
	_ezchip_macro_read_value_ |= (v&0x1)<<9; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_9_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 9; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_10_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<10); \
	_ezchip_macro_read_value_ |= (v&0x1)<<10; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_10_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 10; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_11_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<11); \
	_ezchip_macro_read_value_ |= (v&0x1)<<11; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_11_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 11; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_12_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<12); \
	_ezchip_macro_read_value_ |= (v&0x1)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_12_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register56_oic_evemon_13_start(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<13); \
	_ezchip_macro_read_value_ |= (v&0x1)<<13; \
	MA_OUTW(syscon_remap_vp6_noc_register56_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register56_oic_evemon_13_start(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register56_REG_ADDR) >> 13; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_0_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_1_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_2_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 2; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_3_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 3; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_4_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_5_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 5; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_6_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 6; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_7_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 7; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_8_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 8; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_9_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 9; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_10_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 10; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_11_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 11; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_12_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register57_oic_evemon_13_trigger(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register57_REG_ADDR) >> 13; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_1(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<1); \
	_ezchip_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_1(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_2(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<2); \
	_ezchip_macro_read_value_ |= (v&0x1)<<2; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_2(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 2; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_3(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<3); \
	_ezchip_macro_read_value_ |= (v&0x1)<<3; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_3(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 3; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_4(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<4); \
	_ezchip_macro_read_value_ |= (v&0x1)<<4; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_4(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_5(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<5); \
	_ezchip_macro_read_value_ |= (v&0x1)<<5; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_5(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 5; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_6(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<6); \
	_ezchip_macro_read_value_ |= (v&0x1)<<6; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_6(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 6; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_7(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<7); \
	_ezchip_macro_read_value_ |= (v&0x1)<<7; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_7(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 7; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_8(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<8); \
	_ezchip_macro_read_value_ |= (v&0x1)<<8; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_8(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 8; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_9(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<9); \
	_ezchip_macro_read_value_ |= (v&0x1)<<9; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_9(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 9; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_10(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<10); \
	_ezchip_macro_read_value_ |= (v&0x1)<<10; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_10(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 10; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_11(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<11); \
	_ezchip_macro_read_value_ |= (v&0x1)<<11; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_11(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 11; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_12(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<12); \
	_ezchip_macro_read_value_ |= (v&0x1)<<12; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_12(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_13(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<13); \
	_ezchip_macro_read_value_ |= (v&0x1)<<13; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_13(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 13; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register58_oic_ignore_modifiable_14(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<14); \
	_ezchip_macro_read_value_ |= (v&0x1)<<14; \
	MA_OUTW(syscon_remap_vp6_noc_register58_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register58_oic_ignore_modifiable_14(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register58_REG_ADDR) >> 14; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register59_oic_preq(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register59_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register59_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register59_oic_preq(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register59_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register59_oic_pstate(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register59_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F<<1); \
	_ezchip_macro_read_value_ |= (v&0x1F)<<1; \
	MA_OUTW(syscon_remap_vp6_noc_register59_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register59_oic_pstate(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register59_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _GET_SYSCON_REG_register60_oic_paccept(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register60_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register60_oic_pactive(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register60_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x3ff;\
}

#define _GET_SYSCON_REG_register60_oic_pdeny(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register60_REG_ADDR) >> 11; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register61_oic_qch_clock_stop_threshold_0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register61_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register61_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register61_oic_qch_clock_stop_threshold_0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register61_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register62_oic_qch_clock_stop_threshold_1(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register62_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register62_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register62_oic_qch_clock_stop_threshold_1(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register62_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register63_oic_qch_clock_stop_threshold_2(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register63_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register63_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register63_oic_qch_clock_stop_threshold_2(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register63_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register64_oic_qch_clock_stop_threshold_3(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register64_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register64_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register64_oic_qch_clock_stop_threshold_3(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register64_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register65_oic_qch_clock_stop_threshold_4(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register65_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register65_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register65_oic_qch_clock_stop_threshold_4(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register65_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register66_oic_qch_clock_stop_threshold_5(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register66_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register66_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register66_oic_qch_clock_stop_threshold_5(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register66_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register67_oic_qch_clock_stop_threshold_6(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register67_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register67_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register67_oic_qch_clock_stop_threshold_6(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register67_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register68_oic_qch_clock_stop_threshold_7(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register68_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register68_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register68_oic_qch_clock_stop_threshold_7(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register68_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register69_oic_qch_clock_stop_threshold_8(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register69_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register69_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register69_oic_qch_clock_stop_threshold_8(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register69_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register70_oic_qch_clock_stop_threshold_9(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register70_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register70_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register70_oic_qch_clock_stop_threshold_9(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register70_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _GET_SYSCON_REG_register71_SCFG_vp6_PWaitMode(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register71_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register72_u0_syscon_162_SCFG_vp6_PSO_PsoShutProcOffOnPWait(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register72_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register72_u0_syscon_162_SCFG_vp6_PSO_PsoDomainOffMem(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register72_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register72_u0_syscon_162_SCFG_vp6_PSO_PsoDomainoffDebug(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register72_REG_ADDR) >> 2; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register72_u0_syscon_162_SCFG_vp6_PSO_PsoDomainOffProc(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register72_REG_ADDR) >> 3; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register75_SCFG_vp6_PRID(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register75_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register75_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register75_SCFG_vp6_PRID(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register75_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffff;\
}

#define _SET_SYSCON_REG_register76_SCFG_vp6_RunStall(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register76_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register76_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register76_SCFG_vp6_RunStall(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register76_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register76_SCFG_vp6_StatVectorSel(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register76_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<1); \
	_ezchip_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(syscon_remap_vp6_noc_register76_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register76_SCFG_vp6_StatVectorSel(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register76_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register76_SCFG_vp6_OCDHaltOnReset(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register76_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<2); \
	_ezchip_macro_read_value_ |= (v&0x1)<<2; \
	MA_OUTW(syscon_remap_vp6_noc_register76_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register76_SCFG_vp6_OCDHaltOnReset(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register76_REG_ADDR) >> 2; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register77_u0_syscon_162_SCFG_vp6_rstVec_AltResetVec(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register77_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register77_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register77_u0_syscon_162_SCFG_vp6_rstVec_AltResetVec(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register77_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register78_SCFG_vp6_TrigIn_iDMA(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register78_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register78_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register78_SCFG_vp6_TrigIn_iDMA(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register78_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register79_SCFG_vp6_TrigOut_iDMA(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register79_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register81_SCFG_vp6_BreakIn(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register81_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register81_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register81_SCFG_vp6_BreakIn(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register81_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register81_SCFG_vp6_BreakOutAck(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register81_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<1); \
	_ezchip_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(syscon_remap_vp6_noc_register81_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register81_SCFG_vp6_BreakOutAck(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register81_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register82_SCFG_vp6_BreakInAck(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register82_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register82_SCFG_vp6_BreakOut(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register82_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register83_SCFG_vp6_DoubleExceptionError(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register83_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register83_SCFG_vp6_PFatalInfoValid(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register83_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register83_SCFG_vp6_PFatalError(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register83_REG_ADDR) >> 2; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register83_SCFG_vp6_ArithmeticException(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register83_REG_ADDR) >> 3; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register83_SCFG_vp6_debug_mode(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register83_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register83_SCFG_vp6_XOCDMode(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register83_REG_ADDR) >> 5; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register84_SCFG_vp6_PFatalInfo(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register84_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register85_oic_qch_clock_stop_threshold_10(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register85_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register85_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register85_oic_qch_clock_stop_threshold_10(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register85_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register87_oic_qch_clock_stop_threshold_11(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register87_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register87_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register87_oic_qch_clock_stop_threshold_11(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register87_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register88_SCFG_vp6sys_offset(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register88_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register88_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register88_SCFG_vp6sys_offset(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register88_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xfffff;\
}

#define _SET_SYSCON_REG_register89_SCFG_vp6sys_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register89_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register89_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register89_SCFG_vp6sys_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register89_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffff;\
}

#define _SET_SYSCON_REG_register90_SCFG_sys_remapped_upbound(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register90_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register90_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register90_SCFG_sys_remapped_upbound(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register90_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xfffff;\
}

#define _SET_SYSCON_REG_register91_SCFG_vp6idma_offset(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register91_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register91_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register91_SCFG_vp6idma_offset(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register91_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xfffff;\
}

#define _SET_SYSCON_REG_register92_SCFG_vp6idma_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register92_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register92_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register92_SCFG_vp6idma_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register92_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffff;\
}

#define _SET_SYSCON_REG_register93_SCFG_idma_remapped_upbound(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register93_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register93_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register93_SCFG_idma_remapped_upbound(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register93_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xfffff;\
}

#define _SET_SYSCON_REG_register94_SCFG_vp6sys_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register94_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register94_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register94_SCFG_vp6sys_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register94_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register94_SCFG_vp6idma_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register94_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<1); \
	_ezchip_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(syscon_remap_vp6_noc_register94_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register94_SCFG_vp6idma_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register94_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register95_SCFG_hifi4_remap_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register95_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register95_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register95_SCFG_hifi4_remap_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register95_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register96_SCFG_hifi4_remap_start_point(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register96_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register96_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register96_SCFG_hifi4_remap_start_point(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register96_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffff;\
}

#define _SET_SYSCON_REG_register97_SCFG_hifi4_remap_offset(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register97_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register97_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register97_SCFG_hifi4_remap_offset(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register97_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xfffff;\
}

#define _SET_SYSCON_REG_register98_SCFG_hifi4_remap_upbound(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register98_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFF); \
	MA_OUTW(syscon_remap_vp6_noc_register98_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register98_SCFG_hifi4_remap_upbound(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register98_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xfffff;\
}

#define _SET_SYSCON_REG_register99_dsp0_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register99_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register99_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register99_dsp0_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register99_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register100_dsp1_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register100_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register100_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register100_dsp1_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register100_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register101_BreakIn_0_syscon(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register101_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register101_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register101_BreakIn_0_syscon(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register101_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register101_BreakOutAck_0_syscon(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register101_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<1); \
	_ezchip_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(syscon_remap_vp6_noc_register101_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register101_BreakOutAck_0_syscon(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register101_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register102_BreakIn_1_syscon(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register102_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(syscon_remap_vp6_noc_register102_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register102_BreakIn_1_syscon(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register102_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register102_BreakOutAck_1_syscon(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register102_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<1); \
	_ezchip_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(syscon_remap_vp6_noc_register102_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register102_BreakOutAck_1_syscon(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(syscon_remap_vp6_noc_register102_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#endif //_SYSCON_REMAP_VP6_NOC_MACRO_H_
