/* SPDX-License-Identifier: GPL-2.0-or-later */
/* Copyright (c) 2021 StarFive Technology Co., Ltd. */

/******************************************************************
*
* vout_sys_syscon_top C MACRO generated by ezchip
*
******************************************************************/

#ifndef _VOUT_SYS_SYSCON_MACRO_H_
#define _VOUT_SYS_SYSCON_MACRO_H_

//#define VOUT_SYS_SYSCON_BASE_ADDR 0x0
#define vout_sys_syscon_register0_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x0
#define vout_sys_syscon_register1_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x4
#define vout_sys_syscon_register2_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x8
#define vout_sys_syscon_register3_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xC
#define vout_sys_syscon_register4_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x10
#define vout_sys_syscon_register5_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x14
#define vout_sys_syscon_register7_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x1C
#define vout_sys_syscon_register8_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x20
#define vout_sys_syscon_register9_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x24
#define vout_sys_syscon_register11_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x2C
#define vout_sys_syscon_register12_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x30
#define vout_sys_syscon_register13_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x34
#define vout_sys_syscon_register14_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x38
#define vout_sys_syscon_register15_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x3C
#define vout_sys_syscon_register16_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x40
#define vout_sys_syscon_register17_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x44
#define vout_sys_syscon_register18_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x48
#define vout_sys_syscon_register19_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x4C
#define vout_sys_syscon_register20_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x50
#define vout_sys_syscon_register21_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x54
#define vout_sys_syscon_register22_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x58
#define vout_sys_syscon_register23_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x5C
#define vout_sys_syscon_register24_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x60
#define vout_sys_syscon_register25_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x64
#define vout_sys_syscon_register26_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x68
#define vout_sys_syscon_register27_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x6C
#define vout_sys_syscon_register28_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x70
#define vout_sys_syscon_register29_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x74
#define vout_sys_syscon_register30_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x78
#define vout_sys_syscon_register32_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x80
#define vout_sys_syscon_register33_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x84
#define vout_sys_syscon_register34_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x88
#define vout_sys_syscon_register35_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x8C
#define vout_sys_syscon_register36_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x90
#define vout_sys_syscon_register37_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x94
#define vout_sys_syscon_register38_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x98
#define vout_sys_syscon_register39_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0x9C
#define vout_sys_syscon_register40_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xA0
#define vout_sys_syscon_register41_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xA4
#define vout_sys_syscon_register42_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xA8
#define vout_sys_syscon_register43_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xAC
#define vout_sys_syscon_register44_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xB0
#define vout_sys_syscon_register45_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xB4
#define vout_sys_syscon_register44_dsi_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xBC
#define vout_sys_syscon_register45_dsi_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xC0
#define vout_sys_syscon_register46_dsi_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xC4
#define vout_sys_syscon_register47_dsi_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xC8
#define vout_sys_syscon_register48_csi_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xCC
#define vout_sys_syscon_register49_csi_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xD0
#define vout_sys_syscon_register50_csi_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xD4
#define vout_sys_syscon_register51_csi_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xD8
#define vout_sys_syscon_register54_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xDC
#define vout_sys_syscon_register52_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xE0
#define vout_sys_syscon_register53_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xE4
#define vout_sys_syscon_register55_REG_ADDR  VOUT_SYS_SYSCON_BASE_ADDR + 0xE8

#define _SET_SYSCON_REG_register0_SCFG_sram_config_lcdc(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register0_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF); \
	_ezchip_macro_read_value_ |= (v&0xFF); \
	MA_OUTW(vout_sys_syscon_register0_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register0_SCFG_sram_config_lcdc(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register0_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register1_SCFG_sram_config_vpp0(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register1_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF); \
	_ezchip_macro_read_value_ |= (v&0xFF); \
	MA_OUTW(vout_sys_syscon_register1_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register1_SCFG_sram_config_vpp0(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register1_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register1_SCFG_sram_config_vpp1(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register1_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<8); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<8; \
	MA_OUTW(vout_sys_syscon_register1_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register1_SCFG_sram_config_vpp1(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register1_REG_ADDR) >> 8; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register1_SCFG_sram_config_vpp2(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register1_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<16); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<16; \
	MA_OUTW(vout_sys_syscon_register1_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register1_SCFG_sram_config_vpp2(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register1_REG_ADDR) >> 16; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register2_map_conv_enable(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register2_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(vout_sys_syscon_register2_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register2_map_conv_enable(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register2_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register2_map_conv_y_mode(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register2_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<1); \
	_ezchip_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(vout_sys_syscon_register2_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register2_map_conv_y_mode(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register2_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register2_map_conv_c_mode(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register2_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7<<2); \
	_ezchip_macro_read_value_ |= (v&0x7)<<2; \
	MA_OUTW(vout_sys_syscon_register2_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register2_map_conv_c_mode(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register2_REG_ADDR) >> 2; \
	_ezchip_macro_read_value_ &= 0x7;\
}

#define _SET_SYSCON_REG_register3_SCFG_sram_config(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register3_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF); \
	_ezchip_macro_read_value_ |= (v&0xFF); \
	MA_OUTW(vout_sys_syscon_register3_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register3_SCFG_sram_config(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register3_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _GET_SYSCON_REG_register4_dsi_test_generic_ctrl(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register4_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffff;\
}

#define _SET_SYSCON_REG_register5_dsi_test_generic_status(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register5_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFF); \
	MA_OUTW(vout_sys_syscon_register5_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register5_dsi_test_generic_status(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register5_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffff;\
}

#define _SET_SYSCON_REG_register7_SCFG_sram_config(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register7_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF); \
	_ezchip_macro_read_value_ |= (v&0xFF); \
	MA_OUTW(vout_sys_syscon_register7_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register7_SCFG_sram_config(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register7_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _GET_SYSCON_REG_register8_generic_ctrl(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register8_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffff;\
}

#define _SET_SYSCON_REG_register9_generic_status(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register9_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFF); \
	MA_OUTW(vout_sys_syscon_register9_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register9_generic_status(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register9_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffff;\
}

#define _SET_SYSCON_REG_register11_SCFG_csi_dsi_sel(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register11_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(vout_sys_syscon_register11_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register11_SCFG_csi_dsi_sel(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register11_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register12_SCFG_phy_resetb(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register12_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(vout_sys_syscon_register12_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register12_SCFG_phy_resetb(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register12_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register13_refclk_in_sel(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register13_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7); \
	_ezchip_macro_read_value_ |= (v&0x7); \
	MA_OUTW(vout_sys_syscon_register13_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register13_refclk_in_sel(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register13_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7;\
}

#define _SET_SYSCON_REG_register14_SCFG_cfg_databus16_sel(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register14_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(vout_sys_syscon_register14_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register14_SCFG_cfg_databus16_sel(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register14_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register14_SCFG_pwron_ready_n(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register14_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<1); \
	_ezchip_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(vout_sys_syscon_register14_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register14_SCFG_pwron_ready_n(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register14_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register14_RG_CDTX_PLL_FM_EN(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register14_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<2); \
	_ezchip_macro_read_value_ |= (v&0x1)<<2; \
	MA_OUTW(vout_sys_syscon_register14_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register14_RG_CDTX_PLL_FM_EN(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register14_REG_ADDR) >> 2; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register14_SCFG_pllssc_en(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register14_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<3); \
	_ezchip_macro_read_value_ |= (v&0x1)<<3; \
	MA_OUTW(vout_sys_syscon_register14_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register14_SCFG_pllssc_en(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register14_REG_ADDR) >> 3; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register14_RG_CDTX_PLL_LDO_STB_X2_EN(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register14_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1<<4); \
	_ezchip_macro_read_value_ |= (v&0x1)<<4; \
	MA_OUTW(vout_sys_syscon_register14_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register14_RG_CDTX_PLL_LDO_STB_X2_EN(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register14_REG_ADDR) >> 4; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register15_RGS_CDTX_PLL_FM_CPLT(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register15_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register15_RGS_CDTX_PLL_FM_OVER(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register15_REG_ADDR) >> 1; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register15_RGS_CDTX_PLL_FM_UNDER(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register15_REG_ADDR) >> 2; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _GET_SYSCON_REG_register15_RGS_CDTX_PLL_UNLOCK(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register15_REG_ADDR) >> 3; \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register16_RG_CDTX_PLL_FBK_FRA(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register16_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFF); \
	MA_OUTW(vout_sys_syscon_register16_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register16_RG_CDTX_PLL_FBK_FRA(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register16_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffffff;\
}

#define _SET_SYSCON_REG_register17_RG_CDTX_PLL_FBK_INT(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register17_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1FF); \
	_ezchip_macro_read_value_ |= (v&0x1FF); \
	MA_OUTW(vout_sys_syscon_register17_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register17_RG_CDTX_PLL_FBK_INT(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register17_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1ff;\
}

#define _SET_SYSCON_REG_register17_RG_CDTX_PLL_PRE_DIV(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register17_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3<<9); \
	_ezchip_macro_read_value_ |= (v&0x3)<<9; \
	MA_OUTW(vout_sys_syscon_register17_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register17_RG_CDTX_PLL_PRE_DIV(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register17_REG_ADDR) >> 9; \
	_ezchip_macro_read_value_ &= 0x3;\
}

#define _SET_SYSCON_REG_register18_RG_CDTX_PLL_SSC_DELTA(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register18_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3FFFF); \
	_ezchip_macro_read_value_ |= (v&0x3FFFF); \
	MA_OUTW(vout_sys_syscon_register18_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register18_RG_CDTX_PLL_SSC_DELTA(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register18_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x3ffff;\
}

#define _SET_SYSCON_REG_register19_RG_CDTX_PLL_SSC_DELTA_INIT(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register19_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3FFFF); \
	_ezchip_macro_read_value_ |= (v&0x3FFFF); \
	MA_OUTW(vout_sys_syscon_register19_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register19_RG_CDTX_PLL_SSC_DELTA_INIT(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register19_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x3ffff;\
}

#define _SET_SYSCON_REG_register20_RG_CDTX_PLL_SSC_PRD(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register20_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3FF); \
	_ezchip_macro_read_value_ |= (v&0x3FF); \
	MA_OUTW(vout_sys_syscon_register20_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register20_RG_CDTX_PLL_SSC_PRD(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register20_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x3ff;\
}

#define _SET_SYSCON_REG_register21_RG_CLANE_HS_CLK_POST_TIME(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register21_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF); \
	_ezchip_macro_read_value_ |= (v&0xFF); \
	MA_OUTW(vout_sys_syscon_register21_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register21_RG_CLANE_HS_CLK_POST_TIME(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register21_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register21_RG_CLANE_HS_CLK_PRE_TIME(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register21_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<8); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<8; \
	MA_OUTW(vout_sys_syscon_register21_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register21_RG_CLANE_HS_CLK_PRE_TIME(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register21_REG_ADDR) >> 8; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register21_RG_CLANE_HS_PRE_TIME(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register21_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<16); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<16; \
	MA_OUTW(vout_sys_syscon_register21_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register21_RG_CLANE_HS_PRE_TIME(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register21_REG_ADDR) >> 16; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register21_RG_CLANE_HS_TRAIL_TIME(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register21_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<24); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<24; \
	MA_OUTW(vout_sys_syscon_register21_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register21_RG_CLANE_HS_TRAIL_TIME(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register21_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register22_RG_CLANE_HS_ZERO_TIME(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register22_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF); \
	_ezchip_macro_read_value_ |= (v&0xFF); \
	MA_OUTW(vout_sys_syscon_register22_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register22_RG_CLANE_HS_ZERO_TIME(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register22_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register22_RG_DLANE_HS_PRE_TIME(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register22_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<8); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<8; \
	MA_OUTW(vout_sys_syscon_register22_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register22_RG_DLANE_HS_PRE_TIME(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register22_REG_ADDR) >> 8; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register22_RG_DLANE_HS_TRAIL_TIME(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register22_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<16); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<16; \
	MA_OUTW(vout_sys_syscon_register22_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register22_RG_DLANE_HS_TRAIL_TIME(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register22_REG_ADDR) >> 16; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register22_RG_DLANE_HS_ZERO_TIME(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register22_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF<<24); \
	_ezchip_macro_read_value_ |= (v&0xFF)<<24; \
	MA_OUTW(vout_sys_syscon_register22_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register22_RG_DLANE_HS_ZERO_TIME(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register22_REG_ADDR) >> 24; \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register23_RG_EXTD_CYCLE_SEL(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register23_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7); \
	_ezchip_macro_read_value_ |= (v&0x7); \
	MA_OUTW(vout_sys_syscon_register23_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register23_RG_EXTD_CYCLE_SEL(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register23_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7;\
}

#define _SET_SYSCON_REG_register24_RG_CDTX_L0N_HSTX_RES(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register24_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F); \
	_ezchip_macro_read_value_ |= (v&0x1F); \
	MA_OUTW(vout_sys_syscon_register24_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register24_RG_CDTX_L0N_HSTX_RES(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register24_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register24_RG_CDTX_L0P_HSTX_RES(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register24_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F<<5); \
	_ezchip_macro_read_value_ |= (v&0x1F)<<5; \
	MA_OUTW(vout_sys_syscon_register24_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register24_RG_CDTX_L0P_HSTX_RES(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register24_REG_ADDR) >> 5; \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register25_RG_CDTX_L1N_HSTX_RES(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register25_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F); \
	_ezchip_macro_read_value_ |= (v&0x1F); \
	MA_OUTW(vout_sys_syscon_register25_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register25_RG_CDTX_L1N_HSTX_RES(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register25_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register25_RG_CDTX_L1P_HSTX_RES(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register25_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F<<5); \
	_ezchip_macro_read_value_ |= (v&0x1F)<<5; \
	MA_OUTW(vout_sys_syscon_register25_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register25_RG_CDTX_L1P_HSTX_RES(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register25_REG_ADDR) >> 5; \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register26_RG_CDTX_L2N_HSTX_RES(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register26_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F); \
	_ezchip_macro_read_value_ |= (v&0x1F); \
	MA_OUTW(vout_sys_syscon_register26_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register26_RG_CDTX_L2N_HSTX_RES(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register26_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register26_RG_CDTX_L2P_HSTX_RES(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register26_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F<<5); \
	_ezchip_macro_read_value_ |= (v&0x1F)<<5; \
	MA_OUTW(vout_sys_syscon_register26_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register26_RG_CDTX_L2P_HSTX_RES(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register26_REG_ADDR) >> 5; \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register27_RG_CDTX_L3N_HSTX_RES(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register27_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F); \
	_ezchip_macro_read_value_ |= (v&0x1F); \
	MA_OUTW(vout_sys_syscon_register27_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register27_RG_CDTX_L3N_HSTX_RES(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register27_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register27_RG_CDTX_L3P_HSTX_RES(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register27_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F<<5); \
	_ezchip_macro_read_value_ |= (v&0x1F)<<5; \
	MA_OUTW(vout_sys_syscon_register27_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register27_RG_CDTX_L3P_HSTX_RES(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register27_REG_ADDR) >> 5; \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register28_RG_CDTX_L4N_HSTX_RES(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register28_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F); \
	_ezchip_macro_read_value_ |= (v&0x1F); \
	MA_OUTW(vout_sys_syscon_register28_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register28_RG_CDTX_L4N_HSTX_RES(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register28_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register28_RG_CDTX_L4P_HSTX_RES(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register28_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F<<5); \
	_ezchip_macro_read_value_ |= (v&0x1F)<<5; \
	MA_OUTW(vout_sys_syscon_register28_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register28_RG_CDTX_L4P_HSTX_RES(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register28_REG_ADDR) >> 5; \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register29_CFG_DPDN_SWAP(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register29_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F); \
	_ezchip_macro_read_value_ |= (v&0x1F); \
	MA_OUTW(vout_sys_syscon_register29_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register29_CFG_DPDN_SWAP(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register29_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register30_CFG_L0_SWAP_SEL(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register30_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7); \
	_ezchip_macro_read_value_ |= (v&0x7); \
	MA_OUTW(vout_sys_syscon_register30_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register30_CFG_L0_SWAP_SEL(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register30_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7;\
}

#define _SET_SYSCON_REG_register30_CFG_L1_SWAP_SEL(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register30_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7<<3); \
	_ezchip_macro_read_value_ |= (v&0x7)<<3; \
	MA_OUTW(vout_sys_syscon_register30_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register30_CFG_L1_SWAP_SEL(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register30_REG_ADDR) >> 3; \
	_ezchip_macro_read_value_ &= 0x7;\
}

#define _SET_SYSCON_REG_register30_CFG_L2_SWAP_SEL(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register30_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7<<6); \
	_ezchip_macro_read_value_ |= (v&0x7)<<6; \
	MA_OUTW(vout_sys_syscon_register30_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register30_CFG_L2_SWAP_SEL(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register30_REG_ADDR) >> 6; \
	_ezchip_macro_read_value_ &= 0x7;\
}

#define _SET_SYSCON_REG_register30_CFG_L3_SWAP_SEL(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register30_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7<<9); \
	_ezchip_macro_read_value_ |= (v&0x7)<<9; \
	MA_OUTW(vout_sys_syscon_register30_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register30_CFG_L3_SWAP_SEL(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register30_REG_ADDR) >> 9; \
	_ezchip_macro_read_value_ &= 0x7;\
}

#define _SET_SYSCON_REG_register30_CFG_L4_SWAP_SEL(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register30_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7<<12); \
	_ezchip_macro_read_value_ |= (v&0x7)<<12; \
	MA_OUTW(vout_sys_syscon_register30_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register30_CFG_L4_SWAP_SEL(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register30_REG_ADDR) >> 12; \
	_ezchip_macro_read_value_ &= 0x7;\
}

#define _SET_SYSCON_REG_register32_XCFGI_DW00(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register32_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register32_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register32_XCFGI_DW00(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register32_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register33_XCFGI_DW01(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register33_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register33_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register33_XCFGI_DW01(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register33_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register34_XCFGI_DW02(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register34_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register34_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register34_XCFGI_DW02(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register34_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register35_XCFGI_DW03(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register35_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register35_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register35_XCFGI_DW03(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register35_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register36_XCFGI_DW04(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register36_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register36_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register36_XCFGI_DW04(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register36_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register37_XCFGI_DW05(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register37_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register37_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register37_XCFGI_DW05(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register37_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register38_XCFGI_DW06(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register38_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register38_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register38_XCFGI_DW06(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register38_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register39_XCFGI_DW07(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register39_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register39_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register39_XCFGI_DW07(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register39_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register40_XCFGI_DW08(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register40_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register40_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register40_XCFGI_DW08(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register40_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register41_XCFGI_DW09(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register41_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register41_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register41_XCFGI_DW09(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register41_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register42_XCFGI_DW0A(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register42_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register42_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register42_XCFGI_DW0A(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register42_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register43_XCFGI_DW0B(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register43_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFFFF); \
	MA_OUTW(vout_sys_syscon_register43_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register43_XCFGI_DW0B(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register43_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xFFFFFFFF;\
}

#define _SET_SYSCON_REG_register44_dbg1_mux_sel(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register44_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F); \
	_ezchip_macro_read_value_ |= (v&0x1F); \
	MA_OUTW(vout_sys_syscon_register44_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register44_dbg1_mux_sel(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register44_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register45_dbg2_mux_sel(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register45_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1F); \
	_ezchip_macro_read_value_ |= (v&0x1F); \
	MA_OUTW(vout_sys_syscon_register45_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register45_dbg2_mux_sel(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register45_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1f;\
}

#define _SET_SYSCON_REG_register44_dsi_SCFG_c_hs_prepare_time(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register44_dsi_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFF); \
	MA_OUTW(vout_sys_syscon_register44_dsi_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register44_dsi_SCFG_c_hs_prepare_time(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register44_dsi_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffffff;\
}

#define _SET_SYSCON_REG_register45_dsi_SCFG_c_hs_zero_time(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register45_dsi_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFF); \
	MA_OUTW(vout_sys_syscon_register45_dsi_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register45_dsi_SCFG_c_hs_zero_time(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register45_dsi_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffffff;\
}

#define _SET_SYSCON_REG_register46_dsi_SCFG_c_hs_pre_zero_time(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register46_dsi_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFF); \
	MA_OUTW(vout_sys_syscon_register46_dsi_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register46_dsi_SCFG_c_hs_pre_zero_time(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register46_dsi_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffffff;\
}

#define _SET_SYSCON_REG_register47_dsi_SCFG_txready_source_sel(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register47_dsi_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3); \
	_ezchip_macro_read_value_ |= (v&0x3); \
	MA_OUTW(vout_sys_syscon_register47_dsi_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register47_dsi_SCFG_txready_source_sel(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register47_dsi_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x3;\
}

#define _SET_SYSCON_REG_register48_csi_SCFG_c_hs_prepare_time(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register48_csi_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFF); \
	MA_OUTW(vout_sys_syscon_register48_csi_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register48_csi_SCFG_c_hs_prepare_time(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register48_csi_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffffff;\
}

#define _SET_SYSCON_REG_register49_csi_SCFG_c_hs_zero_time(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register49_csi_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFF); \
	MA_OUTW(vout_sys_syscon_register49_csi_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register49_csi_SCFG_c_hs_zero_time(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register49_csi_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffffff;\
}

#define _SET_SYSCON_REG_register50_csi_SCFG_c_hs_pre_zero_time(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register50_csi_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFFFFFF); \
	_ezchip_macro_read_value_ |= (v&0xFFFFFF); \
	MA_OUTW(vout_sys_syscon_register50_csi_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register50_csi_SCFG_c_hs_pre_zero_time(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register50_csi_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xffffff;\
}

#define _SET_SYSCON_REG_register51_csi_SCFG_txready_source_sel(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register51_csi_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3); \
	_ezchip_macro_read_value_ |= (v&0x3); \
	MA_OUTW(vout_sys_syscon_register51_csi_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register51_csi_SCFG_txready_source_sel(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register51_csi_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x3;\
}

#define _SET_SYSCON_REG_register54_SCFG_mapadp_sram_config(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register54_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0xFF); \
	_ezchip_macro_read_value_ |= (v&0xFF); \
	MA_OUTW(vout_sys_syscon_register54_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register54_SCFG_mapadp_sram_config(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register54_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0xff;\
}

#define _SET_SYSCON_REG_register52_SCFG_mapadp_linebuf_bypass(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register52_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x1); \
	_ezchip_macro_read_value_ |= (v&0x1); \
	MA_OUTW(vout_sys_syscon_register52_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register52_SCFG_mapadp_linebuf_bypass(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register52_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x1;\
}

#define _SET_SYSCON_REG_register53_SCFG_mapadp_linebuf_size(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register53_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x7FF); \
	_ezchip_macro_read_value_ |= (v&0x7FF); \
	MA_OUTW(vout_sys_syscon_register53_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register53_SCFG_mapadp_linebuf_size(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register53_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x7ff;\
}

#define _SET_SYSCON_REG_register55_SCFG_txreadyesc_sel(v) { \
	uint32_t _ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register55_REG_ADDR); \
	_ezchip_macro_read_value_ &= ~(0x3); \
	_ezchip_macro_read_value_ |= (v&0x3); \
	MA_OUTW(vout_sys_syscon_register55_REG_ADDR,_ezchip_macro_read_value_); \
}

#define _GET_SYSCON_REG_register55_SCFG_txreadyesc_sel(_ezchip_macro_read_value_) { \
	_ezchip_macro_read_value_=MA_INW(vout_sys_syscon_register55_REG_ADDR); \
	_ezchip_macro_read_value_ &= 0x3;\
}

#endif //_VOUT_SYS_SYSCON_MACRO_H_
