//commit:8ece02821 (HEAD -> b0.8.1_dv, origin/b0.8.1_dv)

#ifndef _BMCPERIPH3_CRG_SECURE_MACRO_H_
#define _BMCPERIPH3_CRG_SECURE_MACRO_H_

//#define BMCPERIPH3_CRG_SECURE_BASE_ADDR 0x0
#define BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR (U0_BMCPERIPH3_CRG_SECURE__ITG_BD_APBS__BASE_ADDR + 0x0U)

#define BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR (U0_BMCPERIPH3_CRG_SECURE__ITG_BD_APBS__BASE_ADDR + 0x4U)






#define RSTN_U0_BMCPERIPH3_SECURE_SYSREG_RSTN_SHIFT                  0
#define RSTN_U0_BMCPERIPH3_SECURE_SYSREG_RSTN_MASK                   (0x1 << 0)
#define RSTN_U0_BMCPERIPH3_SECURE_SYSREG_RSTN_ASSERT                 1
#define RSTN_U0_BMCPERIPH3_SECURE_SYSREG_RSTN_CLEAR                  0
#define RSTN_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_SHIFT               1
#define RSTN_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_MASK                (0x1 << 1)
#define RSTN_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_ASSERT              1
#define RSTN_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_CLEAR               0




#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BMCPERIPH3_SECURE_SYSREG_RSTN_ 	itg_get_reg(BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH3_SECURE_SYSREG_RSTN_SHIFT, RSTN_U0_BMCPERIPH3_SECURE_SYSREG_RSTN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BMCPERIPH3_SECURE_SYSREG_RSTN_ 	itg_assert_rst(BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH3_SECURE_SYSREG_RSTN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BMCPERIPH3_SECURE_SYSREG_RSTN_ 	itg_clear_rst(BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH3_SECURE_SYSREG_RSTN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_ 	itg_get_reg(BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_SHIFT, RSTN_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_ 	itg_assert_rst(BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_ 	itg_clear_rst(BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_SECURE_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_MASK)


#endif //_BMCPERIPH3_CRG_SECURE_MACRO_H_
