//commit:06b6362e (HEAD -> b0.8.1_dv, origin/b0.8.1_dv)

#ifndef _BMCPERIPH3_CRG_MACRO_H_
#define _BMCPERIPH3_CRG_MACRO_H_

//#define BMCPERIPH3_CRG_BASE_ADDR 0x0
#define CLK_BMCPERIPH3_300_CTRL_REG_ADDR                             (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_BMCPERIPH3_200_CTRL_REG_ADDR                             (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define CLK_BMCPERIPH3_GMAC1_PTP_REF_CTRL_REG_ADDR                   (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define CLK_BMCPERIPH3_GMAC1_TX_125_MUX_CTRL_REG_ADDR                (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)
#define CLK_BMCPERIPH3_GMAC1_TX_CTRL_REG_ADDR                        (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define CLK_BMCPERIPH3_GMAC1_RX_125_MUX_CTRL_REG_ADDR                (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define CLK_BMCPERIPH3_GMAC1_RX_CTRL_REG_ADDR                        (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define CLK_BMCPERIPH3_GMAC0_PTP_REF_CTRL_REG_ADDR                   (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x1CU)
#define CLK_BMCPERIPH3_GMAC0_RMII_PLL_CTRL_REG_ADDR                  (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x20U)
#define CLK_BMCPERIPH3_GMAC0_RMII_MUX_CTRL_REG_ADDR                  (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x24U)
#define CLK_BMCPERIPH3_GMAC0_RMII_MUX_DIV2_CTRL_REG_ADDR             (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x28U)
#define CLK_BMCPERIPH3_GMAC0_TXCK_CTRL_REG_ADDR                      (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x2CU)
#define CLK_U11_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR                 (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x30U)
#define CLK_U0_PECI_PCLK_I_CTRL_REG_ADDR                             (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x34U)
#define CLK_U0_PECI_PECI_CLK_I_CTRL_REG_ADDR                         (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x38U)
#define CLK_U1_PECI_PCLK_I_CTRL_REG_ADDR                             (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x3CU)
#define CLK_U1_PECI_PECI_CLK_I_CTRL_REG_ADDR                         (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x40U)
#define CLK_U0_DWC_ETHER_RMII_CLK_TX_I_CTRL_REG_ADDR                 (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x44U)
#define CLK_U0_DWC_ETHER_RMII_CLK_RX_I_CTRL_REG_ADDR                 (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x48U)
#define CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_CTRL_REG_ADDR            (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x4CU)
#define CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_CTRL_REG_ADDR               (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x50U)
#define CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_CTRL_REG_ADDR                (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x54U)
#define CLK_U0_DWC_ETHER_RMII_ACLK_I_CTRL_REG_ADDR                   (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x58U)
#define CLK_GMAC0_RMII_RCLKO_CTRL_REG_ADDR                           (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x5CU)
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_CTRL_REG_ADDR                (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x60U)
#define CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_CTRL_REG_ADDR                (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x64U)
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR            (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x68U)
#define CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_CTRL_REG_ADDR            (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x6CU)
#define CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_CTRL_REG_ADDR           (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x70U)
#define CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR               (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x74U)
#define CLK_U0_DWC_ETHER_SGMII_ACLK_I_CTRL_REG_ADDR                  (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x78U)
#define CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_CTRL_REG_ADDR        (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x7CU)


#define MAIN_ICG_EN_SENSOR_CTRL_REG_ADDR                             (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x80U)
#define MAIN_ICG_EN_PECI0_CTRL_REG_ADDR                              (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x84U)
#define MAIN_ICG_EN_PECI1_CTRL_REG_ADDR                              (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x88U)
#define MAIN_ICG_EN_GMAC0_CTRL_REG_ADDR                              (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x8CU)
#define MAIN_ICG_EN_GMAC1_CTRL_REG_ADDR                              (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x90U)


#define BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR        (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x94U)

#define BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR        (U0_BMCPERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x98U)


#define CLK_BMCPERIPH3_300_DIV_SHIFT                                 0
#define CLK_BMCPERIPH3_300_DIV_MASK                                  0x1FFU
#define CLK_BMCPERIPH3_200_DIV_SHIFT                                 0
#define CLK_BMCPERIPH3_200_DIV_MASK                                  0x1FFU
#define CLK_BMCPERIPH3_GMAC1_PTP_REF_DIV_SHIFT                       0
#define CLK_BMCPERIPH3_GMAC1_PTP_REF_DIV_MASK                        0x3U
#define CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_SHIFT                     24
#define CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_MASK                      0x1000000U
#define CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_CLK_BMCPERIPH3_GMAC1_TX_125_DATA 0
#define CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_CLK_BMCPERIPH3_GMAC1_PLL_TX125_DATA 1
#define CLK_BMCPERIPH3_GMAC1_TX_DIV_SHIFT                            0
#define CLK_BMCPERIPH3_GMAC1_TX_DIV_MASK                             0x3FU
#define CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_SHIFT                     24
#define CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_MASK                      0x1000000U
#define CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_CLK_BMCPERIPH3_GMAC1_RX_125_DATA 0
#define CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_CLK_BMCPERIPH3_GMAC1_PLL_RX125_DATA 1
#define CLK_BMCPERIPH3_GMAC1_RX_DIV_SHIFT                            0
#define CLK_BMCPERIPH3_GMAC1_RX_DIV_MASK                             0x3FU
#define CLK_BMCPERIPH3_GMAC0_PTP_REF_DIV_SHIFT                       0
#define CLK_BMCPERIPH3_GMAC0_PTP_REF_DIV_MASK                        0x3U
#define CLK_BMCPERIPH3_GMAC0_RMII_PLL_DIV_SHIFT                      0
#define CLK_BMCPERIPH3_GMAC0_RMII_PLL_DIV_MASK                       0x3U
#define CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_SHIFT                       24
#define CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_MASK                        0x1000000U
#define CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_CLK_BMCPERIPH3_GMAC0_RMII_PLL_DATA 0
#define CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_CLK_BMCPERIPH3_GMAC0_RMII_REFIN_DATA 1
#define CLK_BMCPERIPH3_GMAC0_RMII_MUX_DLY_SHIFT                      0
#define CLK_BMCPERIPH3_GMAC0_RMII_MUX_DLY_MASK                       0x1FU
#define CLK_BMCPERIPH3_GMAC0_RMII_MUX_DIV2_DIV_SHIFT                 0
#define CLK_BMCPERIPH3_GMAC0_RMII_MUX_DIV2_DIV_MASK                  0x1FU
#define CLK_BMCPERIPH3_GMAC0_TXCK_DLY_SHIFT                          0
#define CLK_BMCPERIPH3_GMAC0_TXCK_DLY_MASK                           0x1FU
#define CLK_U11_DWC_SENSORS_PD_CLK_SYS_ENABLE_DATA                   1
#define CLK_U11_DWC_SENSORS_PD_CLK_SYS_DISABLE_DATA                  0
#define CLK_U11_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT                      31
#define CLK_U11_DWC_SENSORS_PD_CLK_SYS_EN_MASK                       0x80000000U
#define CLK_U0_PECI_PCLK_I_ENABLE_DATA                               1
#define CLK_U0_PECI_PCLK_I_DISABLE_DATA                              0
#define CLK_U0_PECI_PCLK_I_EN_SHIFT                                  31
#define CLK_U0_PECI_PCLK_I_EN_MASK                                   0x80000000U
#define CLK_U0_PECI_PECI_CLK_I_ENABLE_DATA                           1
#define CLK_U0_PECI_PECI_CLK_I_DISABLE_DATA                          0
#define CLK_U0_PECI_PECI_CLK_I_EN_SHIFT                              31
#define CLK_U0_PECI_PECI_CLK_I_EN_MASK                               0x80000000U
#define CLK_U1_PECI_PCLK_I_ENABLE_DATA                               1
#define CLK_U1_PECI_PCLK_I_DISABLE_DATA                              0
#define CLK_U1_PECI_PCLK_I_EN_SHIFT                                  31
#define CLK_U1_PECI_PCLK_I_EN_MASK                                   0x80000000U
#define CLK_U1_PECI_PECI_CLK_I_ENABLE_DATA                           1
#define CLK_U1_PECI_PECI_CLK_I_DISABLE_DATA                          0
#define CLK_U1_PECI_PECI_CLK_I_EN_SHIFT                              31
#define CLK_U1_PECI_PECI_CLK_I_EN_MASK                               0x80000000U
#define CLK_U0_DWC_ETHER_RMII_CLK_TX_I_ENABLE_DATA                   1
#define CLK_U0_DWC_ETHER_RMII_CLK_TX_I_DISABLE_DATA                  0
#define CLK_U0_DWC_ETHER_RMII_CLK_TX_I_EN_SHIFT                      31
#define CLK_U0_DWC_ETHER_RMII_CLK_TX_I_EN_MASK                       0x80000000U
#define CLK_U0_DWC_ETHER_RMII_CLK_RX_I_ENABLE_DATA                   1
#define CLK_U0_DWC_ETHER_RMII_CLK_RX_I_DISABLE_DATA                  0
#define CLK_U0_DWC_ETHER_RMII_CLK_RX_I_EN_SHIFT                      31
#define CLK_U0_DWC_ETHER_RMII_CLK_RX_I_EN_MASK                       0x80000000U
#define CLK_U0_DWC_ETHER_RMII_CLK_RX_I_DLY_SHIFT                     0
#define CLK_U0_DWC_ETHER_RMII_CLK_RX_I_DLY_MASK                      0x1FU
#define CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_ENABLE_DATA              1
#define CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_DISABLE_DATA             0
#define CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_EN_SHIFT                 31
#define CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_EN_MASK                  0x80000000U
#define CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_ENABLE_DATA                 1
#define CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_DISABLE_DATA                0
#define CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_EN_SHIFT                    31
#define CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_EN_MASK                     0x80000000U
#define CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_ENABLE_DATA                  1
#define CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_DISABLE_DATA                 0
#define CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_EN_SHIFT                     31
#define CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_EN_MASK                      0x80000000U
#define CLK_U0_DWC_ETHER_RMII_ACLK_I_ENABLE_DATA                     1
#define CLK_U0_DWC_ETHER_RMII_ACLK_I_DISABLE_DATA                    0
#define CLK_U0_DWC_ETHER_RMII_ACLK_I_EN_SHIFT                        31
#define CLK_U0_DWC_ETHER_RMII_ACLK_I_EN_MASK                         0x80000000U
#define CLK_GMAC0_RMII_RCLKO_ENABLE_DATA                             1
#define CLK_GMAC0_RMII_RCLKO_DISABLE_DATA                            0
#define CLK_GMAC0_RMII_RCLKO_EN_SHIFT                                31
#define CLK_GMAC0_RMII_RCLKO_EN_MASK                                 0x80000000U
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_ENABLE_DATA                  1
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_DISABLE_DATA                 0
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_EN_SHIFT                     31
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_EN_MASK                      0x80000000U
#define CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_ENABLE_DATA                  1
#define CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_DISABLE_DATA                 0
#define CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_EN_SHIFT                     31
#define CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_EN_MASK                      0x80000000U
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_ENABLE_DATA              1
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_DISABLE_DATA             0
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_EN_SHIFT                 31
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_EN_MASK                  0x80000000U
#define CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_ENABLE_DATA              1
#define CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_DISABLE_DATA             0
#define CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_EN_SHIFT                 31
#define CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_EN_MASK                  0x80000000U
#define CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_ENABLE_DATA             1
#define CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_DISABLE_DATA            0
#define CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_SHIFT                31
#define CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_MASK                 0x80000000U
#define CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_ENABLE_DATA                 1
#define CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_DISABLE_DATA                0
#define CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_EN_SHIFT                    31
#define CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_EN_MASK                     0x80000000U
#define CLK_U0_DWC_ETHER_SGMII_ACLK_I_ENABLE_DATA                    1
#define CLK_U0_DWC_ETHER_SGMII_ACLK_I_DISABLE_DATA                   0
#define CLK_U0_DWC_ETHER_SGMII_ACLK_I_EN_SHIFT                       31
#define CLK_U0_DWC_ETHER_SGMII_ACLK_I_EN_MASK                        0x80000000U
#define CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_ENABLE_DATA          1
#define CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_DISABLE_DATA         0
#define CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_SHIFT             31
#define CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_MASK              0x80000000U

#define MAIN_ICG_EN_SENSOR_ENABLE_DATA                               1
#define MAIN_ICG_EN_SENSOR_DISABLE_DATA                              0
#define MAIN_ICG_EN_SENSOR_EN_SHIFT                                  31
#define MAIN_ICG_EN_SENSOR_EN_MASK                                   0x80000000U
#define MAIN_ICG_EN_PECI0_ENABLE_DATA                                1
#define MAIN_ICG_EN_PECI0_DISABLE_DATA                               0
#define MAIN_ICG_EN_PECI0_EN_SHIFT                                   31
#define MAIN_ICG_EN_PECI0_EN_MASK                                    0x80000000U
#define MAIN_ICG_EN_PECI1_ENABLE_DATA                                1
#define MAIN_ICG_EN_PECI1_DISABLE_DATA                               0
#define MAIN_ICG_EN_PECI1_EN_SHIFT                                   31
#define MAIN_ICG_EN_PECI1_EN_MASK                                    0x80000000U
#define MAIN_ICG_EN_GMAC0_ENABLE_DATA                                1
#define MAIN_ICG_EN_GMAC0_DISABLE_DATA                               0
#define MAIN_ICG_EN_GMAC0_EN_SHIFT                                   31
#define MAIN_ICG_EN_GMAC0_EN_MASK                                    0x80000000U
#define MAIN_ICG_EN_GMAC1_ENABLE_DATA                                1
#define MAIN_ICG_EN_GMAC1_DISABLE_DATA                               0
#define MAIN_ICG_EN_GMAC1_EN_SHIFT                                   31
#define MAIN_ICG_EN_GMAC1_EN_MASK                                    0x80000000U



#define RSTN_U0_BMCPERIPH3_SYSREG_RSTN_SHIFT                         0
#define RSTN_U0_BMCPERIPH3_SYSREG_RSTN_MASK                          (0x1 << 0)
#define RSTN_U0_BMCPERIPH3_SYSREG_RSTN_ASSERT                        1
#define RSTN_U0_BMCPERIPH3_SYSREG_RSTN_CLEAR                         0
#define MAIN_RSTN_GMAC0_SHIFT                                        1
#define MAIN_RSTN_GMAC0_MASK                                         (0x1 << 1)
#define MAIN_RSTN_GMAC0_ASSERT                                       1
#define MAIN_RSTN_GMAC0_CLEAR                                        0
#define MAIN_RSTN_GMAC1_SHIFT                                        2
#define MAIN_RSTN_GMAC1_MASK                                         (0x1 << 2)
#define MAIN_RSTN_GMAC1_ASSERT                                       1
#define MAIN_RSTN_GMAC1_CLEAR                                        0
#define MAIN_RSTN_PECI0_SHIFT                                        3
#define MAIN_RSTN_PECI0_MASK                                         (0x1 << 3)
#define MAIN_RSTN_PECI0_ASSERT                                       1
#define MAIN_RSTN_PECI0_CLEAR                                        0
#define MAIN_RSTN_PECI1_SHIFT                                        4
#define MAIN_RSTN_PECI1_MASK                                         (0x1 << 4)
#define MAIN_RSTN_PECI1_ASSERT                                       1
#define MAIN_RSTN_PECI1_CLEAR                                        0
#define MAIN_RSTN_DWC_SENSORS_PD_SHIFT                               5
#define MAIN_RSTN_DWC_SENSORS_PD_MASK                                (0x1 << 5)
#define MAIN_RSTN_DWC_SENSORS_PD_ASSERT                              1
#define MAIN_RSTN_DWC_SENSORS_PD_CLEAR                               0
#define RSTN_U0_BMCPERIPH3_IOMUX_PRESETN_SHIFT                       6
#define RSTN_U0_BMCPERIPH3_IOMUX_PRESETN_MASK                        (0x1 << 6)
#define RSTN_U0_BMCPERIPH3_IOMUX_PRESETN_ASSERT                      1
#define RSTN_U0_BMCPERIPH3_IOMUX_PRESETN_CLEAR                       0

#define _DIVIDE_CLOCK_CLK_BMCPERIPH3_300_(div) 			itg_set_reg(CLK_BMCPERIPH3_300_CTRL_REG_ADDR, div, CLK_BMCPERIPH3_300_DIV_SHIFT, CLK_BMCPERIPH3_300_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH3_300_ 		itg_get_reg(CLK_BMCPERIPH3_300_CTRL_REG_ADDR, CLK_BMCPERIPH3_300_DIV_SHIFT, CLK_BMCPERIPH3_300_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH3_200_(div) 			itg_set_reg(CLK_BMCPERIPH3_200_CTRL_REG_ADDR, div, CLK_BMCPERIPH3_200_DIV_SHIFT, CLK_BMCPERIPH3_200_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH3_200_ 		itg_get_reg(CLK_BMCPERIPH3_200_CTRL_REG_ADDR, CLK_BMCPERIPH3_200_DIV_SHIFT, CLK_BMCPERIPH3_200_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH3_GMAC1_PTP_REF_(div) 			itg_set_reg(CLK_BMCPERIPH3_GMAC1_PTP_REF_CTRL_REG_ADDR, div, CLK_BMCPERIPH3_GMAC1_PTP_REF_DIV_SHIFT, CLK_BMCPERIPH3_GMAC1_PTP_REF_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH3_GMAC1_PTP_REF_ 		itg_get_reg(CLK_BMCPERIPH3_GMAC1_PTP_REF_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC1_PTP_REF_DIV_SHIFT, CLK_BMCPERIPH3_GMAC1_PTP_REF_DIV_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SOURCE_CLK_BMCPERIPH3_GMAC1_TX_125_ 	itg_set_reg(CLK_BMCPERIPH3_GMAC1_TX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_CLK_BMCPERIPH3_GMAC1_TX_125_DATA, CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SOURCE_CLK_BMCPERIPH3_GMAC1_PLL_TX125_ 	itg_set_reg(CLK_BMCPERIPH3_GMAC1_TX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_CLK_BMCPERIPH3_GMAC1_PLL_TX125_DATA, CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH3_GMAC1_TX_125_MUX_ 		itg_get_reg(CLK_BMCPERIPH3_GMAC1_TX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH3_GMAC1_TX_125_MUX_(x) 		itg_set_reg(CLK_BMCPERIPH3_GMAC1_TX_125_MUX_CTRL_REG_ADDR, x, CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC1_TX_125_MUX_SW_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH3_GMAC1_TX_(div) 			itg_set_reg(CLK_BMCPERIPH3_GMAC1_TX_CTRL_REG_ADDR, div, CLK_BMCPERIPH3_GMAC1_TX_DIV_SHIFT, CLK_BMCPERIPH3_GMAC1_TX_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH3_GMAC1_TX_ 		itg_get_reg(CLK_BMCPERIPH3_GMAC1_TX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC1_TX_DIV_SHIFT, CLK_BMCPERIPH3_GMAC1_TX_DIV_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SOURCE_CLK_BMCPERIPH3_GMAC1_RX_125_ 	itg_set_reg(CLK_BMCPERIPH3_GMAC1_RX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_CLK_BMCPERIPH3_GMAC1_RX_125_DATA, CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SOURCE_CLK_BMCPERIPH3_GMAC1_PLL_RX125_ 	itg_set_reg(CLK_BMCPERIPH3_GMAC1_RX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_CLK_BMCPERIPH3_GMAC1_PLL_RX125_DATA, CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH3_GMAC1_RX_125_MUX_ 		itg_get_reg(CLK_BMCPERIPH3_GMAC1_RX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH3_GMAC1_RX_125_MUX_(x) 		itg_set_reg(CLK_BMCPERIPH3_GMAC1_RX_125_MUX_CTRL_REG_ADDR, x, CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC1_RX_125_MUX_SW_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH3_GMAC1_RX_(div) 			itg_set_reg(CLK_BMCPERIPH3_GMAC1_RX_CTRL_REG_ADDR, div, CLK_BMCPERIPH3_GMAC1_RX_DIV_SHIFT, CLK_BMCPERIPH3_GMAC1_RX_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH3_GMAC1_RX_ 		itg_get_reg(CLK_BMCPERIPH3_GMAC1_RX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC1_RX_DIV_SHIFT, CLK_BMCPERIPH3_GMAC1_RX_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH3_GMAC0_PTP_REF_(div) 			itg_set_reg(CLK_BMCPERIPH3_GMAC0_PTP_REF_CTRL_REG_ADDR, div, CLK_BMCPERIPH3_GMAC0_PTP_REF_DIV_SHIFT, CLK_BMCPERIPH3_GMAC0_PTP_REF_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH3_GMAC0_PTP_REF_ 		itg_get_reg(CLK_BMCPERIPH3_GMAC0_PTP_REF_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC0_PTP_REF_DIV_SHIFT, CLK_BMCPERIPH3_GMAC0_PTP_REF_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH3_GMAC0_RMII_PLL_(div) 			itg_set_reg(CLK_BMCPERIPH3_GMAC0_RMII_PLL_CTRL_REG_ADDR, div, CLK_BMCPERIPH3_GMAC0_RMII_PLL_DIV_SHIFT, CLK_BMCPERIPH3_GMAC0_RMII_PLL_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH3_GMAC0_RMII_PLL_ 		itg_get_reg(CLK_BMCPERIPH3_GMAC0_RMII_PLL_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC0_RMII_PLL_DIV_SHIFT, CLK_BMCPERIPH3_GMAC0_RMII_PLL_DIV_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH3_GMAC0_RMII_MUX_SOURCE_CLK_BMCPERIPH3_GMAC0_RMII_PLL_ 	itg_set_reg(CLK_BMCPERIPH3_GMAC0_RMII_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_CLK_BMCPERIPH3_GMAC0_RMII_PLL_DATA, CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH3_GMAC0_RMII_MUX_SOURCE_CLK_BMCPERIPH3_GMAC0_RMII_REFIN_ 	itg_set_reg(CLK_BMCPERIPH3_GMAC0_RMII_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_CLK_BMCPERIPH3_GMAC0_RMII_REFIN_DATA, CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH3_GMAC0_RMII_MUX_ 		itg_get_reg(CLK_BMCPERIPH3_GMAC0_RMII_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH3_GMAC0_RMII_MUX_(x) 		itg_set_reg(CLK_BMCPERIPH3_GMAC0_RMII_MUX_CTRL_REG_ADDR, x, CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_SHIFT, CLK_BMCPERIPH3_GMAC0_RMII_MUX_SW_MASK)
#define _SET_CLOCK_CLK_BMCPERIPH3_GMAC0_RMII_MUX_(dly) 			itg_set_reg(CLK_BMCPERIPH3_GMAC0_RMII_MUX_CTRL_REG_ADDR, dly, CLK_BMCPERIPH3_GMAC0_RMII_MUX_DLY_SHIFT, CLK_BMCPERIPH3_GMAC0_RMII_MUX_DLY_MASK)
#define _GET_CLOCK_DELAY_STATUS_CLK_BMCPERIPH3_GMAC0_RMII_MUX_ 		itg_get_reg(CLK_BMCPERIPH3_GMAC0_RMII_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC0_RMII_MUX_DLY_SHIFT, CLK_BMCPERIPH3_GMAC0_RMII_MUX_DLY_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH3_GMAC0_RMII_MUX_DIV2_(div) 			itg_set_reg(CLK_BMCPERIPH3_GMAC0_RMII_MUX_DIV2_CTRL_REG_ADDR, div, CLK_BMCPERIPH3_GMAC0_RMII_MUX_DIV2_DIV_SHIFT, CLK_BMCPERIPH3_GMAC0_RMII_MUX_DIV2_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH3_GMAC0_RMII_MUX_DIV2_ 		itg_get_reg(CLK_BMCPERIPH3_GMAC0_RMII_MUX_DIV2_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC0_RMII_MUX_DIV2_DIV_SHIFT, CLK_BMCPERIPH3_GMAC0_RMII_MUX_DIV2_DIV_MASK)
#define _SET_CLOCK_CLK_BMCPERIPH3_GMAC0_TXCK_(dly) 			itg_set_reg(CLK_BMCPERIPH3_GMAC0_TXCK_CTRL_REG_ADDR, dly, CLK_BMCPERIPH3_GMAC0_TXCK_DLY_SHIFT, CLK_BMCPERIPH3_GMAC0_TXCK_DLY_MASK)
#define _GET_CLOCK_DELAY_STATUS_CLK_BMCPERIPH3_GMAC0_TXCK_ 		itg_get_reg(CLK_BMCPERIPH3_GMAC0_TXCK_CTRL_REG_ADDR, CLK_BMCPERIPH3_GMAC0_TXCK_DLY_SHIFT, CLK_BMCPERIPH3_GMAC0_TXCK_DLY_MASK)
#define _ENABLE_CLOCK_CLK_U11_DWC_SENSORS_PD_CLK_SYS_ 			itg_set_reg(CLK_U11_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U11_DWC_SENSORS_PD_CLK_SYS_ENABLE_DATA, CLK_U11_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U11_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _DISABLE_CLOCK_CLK_U11_DWC_SENSORS_PD_CLK_SYS_ 			itg_set_reg(CLK_U11_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U11_DWC_SENSORS_PD_CLK_SYS_DISABLE_DATA, CLK_U11_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U11_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U11_DWC_SENSORS_PD_CLK_SYS_ 		itg_get_reg(CLK_U11_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U11_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U11_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U11_DWC_SENSORS_PD_CLK_SYS_(x) 		itg_set_reg(CLK_U11_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, x, CLK_U11_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U11_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_PECI_PCLK_I_ 			itg_set_reg(CLK_U0_PECI_PCLK_I_CTRL_REG_ADDR, CLK_U0_PECI_PCLK_I_ENABLE_DATA, CLK_U0_PECI_PCLK_I_EN_SHIFT, CLK_U0_PECI_PCLK_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_PECI_PCLK_I_ 			itg_set_reg(CLK_U0_PECI_PCLK_I_CTRL_REG_ADDR, CLK_U0_PECI_PCLK_I_DISABLE_DATA, CLK_U0_PECI_PCLK_I_EN_SHIFT, CLK_U0_PECI_PCLK_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_PECI_PCLK_I_ 		itg_get_reg(CLK_U0_PECI_PCLK_I_CTRL_REG_ADDR, CLK_U0_PECI_PCLK_I_EN_SHIFT, CLK_U0_PECI_PCLK_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_PECI_PCLK_I_(x) 		itg_set_reg(CLK_U0_PECI_PCLK_I_CTRL_REG_ADDR, x, CLK_U0_PECI_PCLK_I_EN_SHIFT, CLK_U0_PECI_PCLK_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_PECI_PECI_CLK_I_ 			itg_set_reg(CLK_U0_PECI_PECI_CLK_I_CTRL_REG_ADDR, CLK_U0_PECI_PECI_CLK_I_ENABLE_DATA, CLK_U0_PECI_PECI_CLK_I_EN_SHIFT, CLK_U0_PECI_PECI_CLK_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_PECI_PECI_CLK_I_ 			itg_set_reg(CLK_U0_PECI_PECI_CLK_I_CTRL_REG_ADDR, CLK_U0_PECI_PECI_CLK_I_DISABLE_DATA, CLK_U0_PECI_PECI_CLK_I_EN_SHIFT, CLK_U0_PECI_PECI_CLK_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_PECI_PECI_CLK_I_ 		itg_get_reg(CLK_U0_PECI_PECI_CLK_I_CTRL_REG_ADDR, CLK_U0_PECI_PECI_CLK_I_EN_SHIFT, CLK_U0_PECI_PECI_CLK_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_PECI_PECI_CLK_I_(x) 		itg_set_reg(CLK_U0_PECI_PECI_CLK_I_CTRL_REG_ADDR, x, CLK_U0_PECI_PECI_CLK_I_EN_SHIFT, CLK_U0_PECI_PECI_CLK_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_PECI_PCLK_I_ 			itg_set_reg(CLK_U1_PECI_PCLK_I_CTRL_REG_ADDR, CLK_U1_PECI_PCLK_I_ENABLE_DATA, CLK_U1_PECI_PCLK_I_EN_SHIFT, CLK_U1_PECI_PCLK_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_PECI_PCLK_I_ 			itg_set_reg(CLK_U1_PECI_PCLK_I_CTRL_REG_ADDR, CLK_U1_PECI_PCLK_I_DISABLE_DATA, CLK_U1_PECI_PCLK_I_EN_SHIFT, CLK_U1_PECI_PCLK_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_PECI_PCLK_I_ 		itg_get_reg(CLK_U1_PECI_PCLK_I_CTRL_REG_ADDR, CLK_U1_PECI_PCLK_I_EN_SHIFT, CLK_U1_PECI_PCLK_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_PECI_PCLK_I_(x) 		itg_set_reg(CLK_U1_PECI_PCLK_I_CTRL_REG_ADDR, x, CLK_U1_PECI_PCLK_I_EN_SHIFT, CLK_U1_PECI_PCLK_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_PECI_PECI_CLK_I_ 			itg_set_reg(CLK_U1_PECI_PECI_CLK_I_CTRL_REG_ADDR, CLK_U1_PECI_PECI_CLK_I_ENABLE_DATA, CLK_U1_PECI_PECI_CLK_I_EN_SHIFT, CLK_U1_PECI_PECI_CLK_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_PECI_PECI_CLK_I_ 			itg_set_reg(CLK_U1_PECI_PECI_CLK_I_CTRL_REG_ADDR, CLK_U1_PECI_PECI_CLK_I_DISABLE_DATA, CLK_U1_PECI_PECI_CLK_I_EN_SHIFT, CLK_U1_PECI_PECI_CLK_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_PECI_PECI_CLK_I_ 		itg_get_reg(CLK_U1_PECI_PECI_CLK_I_CTRL_REG_ADDR, CLK_U1_PECI_PECI_CLK_I_EN_SHIFT, CLK_U1_PECI_PECI_CLK_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_PECI_PECI_CLK_I_(x) 		itg_set_reg(CLK_U1_PECI_PECI_CLK_I_CTRL_REG_ADDR, x, CLK_U1_PECI_PECI_CLK_I_EN_SHIFT, CLK_U1_PECI_PECI_CLK_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_CLK_TX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_TX_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_TX_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_CLK_TX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_TX_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_TX_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_CLK_TX_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_TX_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_CLK_TX_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_TX_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_TX_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_CLK_RX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_CLK_RX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_CLK_RX_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_CLK_RX_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_RX_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_EN_MASK)
#define _SET_CLOCK_CLK_U0_DWC_ETHER_RMII_CLK_RX_I_(dly) 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_RX_I_CTRL_REG_ADDR, dly, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_DLY_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_DLY_MASK)
#define _GET_CLOCK_DELAY_STATUS_CLK_U0_DWC_ETHER_RMII_CLK_RX_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_DLY_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_RX_I_DLY_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_PTP_REF_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_RMII_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_CLK_CSR_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_ACLK_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_ACLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_ACLK_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_ACLK_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMII_ACLK_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMII_ACLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_ACLK_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_ACLK_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_ACLK_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMII_ACLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_ACLK_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMII_ACLK_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMII_ACLK_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMII_ACLK_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_GMAC0_RMII_RCLKO_ 			itg_set_reg(CLK_GMAC0_RMII_RCLKO_CTRL_REG_ADDR, CLK_GMAC0_RMII_RCLKO_ENABLE_DATA, CLK_GMAC0_RMII_RCLKO_EN_SHIFT, CLK_GMAC0_RMII_RCLKO_EN_MASK)
#define _DISABLE_CLOCK_CLK_GMAC0_RMII_RCLKO_ 			itg_set_reg(CLK_GMAC0_RMII_RCLKO_CTRL_REG_ADDR, CLK_GMAC0_RMII_RCLKO_DISABLE_DATA, CLK_GMAC0_RMII_RCLKO_EN_SHIFT, CLK_GMAC0_RMII_RCLKO_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_GMAC0_RMII_RCLKO_ 		itg_get_reg(CLK_GMAC0_RMII_RCLKO_CTRL_REG_ADDR, CLK_GMAC0_RMII_RCLKO_EN_SHIFT, CLK_GMAC0_RMII_RCLKO_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_GMAC0_RMII_RCLKO_(x) 		itg_set_reg(CLK_GMAC0_RMII_RCLKO_CTRL_REG_ADDR, x, CLK_GMAC0_RMII_RCLKO_EN_SHIFT, CLK_GMAC0_RMII_RCLKO_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_ENABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_DISABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_TX_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_ENABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_DISABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_RX_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_ENABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_DISABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_ENABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_DISABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_RX_125_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_ENABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_DISABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_ENABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_DISABLE_DATA, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_ACLK_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_ACLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_ACLK_I_ENABLE_DATA, CLK_U0_DWC_ETHER_SGMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_ACLK_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_ACLK_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_ACLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_ACLK_I_DISABLE_DATA, CLK_U0_DWC_ETHER_SGMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_ACLK_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_ACLK_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_SGMII_ACLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_ACLK_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_ACLK_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_SGMII_ACLK_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_SGMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_ACLK_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_ENABLE_DATA, CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_DISABLE_DATA, CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_MASK)

#define _ENABLE_CLOCK_MAIN_ICG_EN_SENSOR_ 			itg_set_reg(MAIN_ICG_EN_SENSOR_CTRL_REG_ADDR, MAIN_ICG_EN_SENSOR_ENABLE_DATA, MAIN_ICG_EN_SENSOR_EN_SHIFT, MAIN_ICG_EN_SENSOR_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_SENSOR_ 			itg_set_reg(MAIN_ICG_EN_SENSOR_CTRL_REG_ADDR, MAIN_ICG_EN_SENSOR_DISABLE_DATA, MAIN_ICG_EN_SENSOR_EN_SHIFT, MAIN_ICG_EN_SENSOR_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SENSOR_ 		itg_get_reg(MAIN_ICG_EN_SENSOR_CTRL_REG_ADDR, MAIN_ICG_EN_SENSOR_EN_SHIFT, MAIN_ICG_EN_SENSOR_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_SENSOR_(x) 		itg_set_reg(MAIN_ICG_EN_SENSOR_CTRL_REG_ADDR, x, MAIN_ICG_EN_SENSOR_EN_SHIFT, MAIN_ICG_EN_SENSOR_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_PECI0_ 			itg_set_reg(MAIN_ICG_EN_PECI0_CTRL_REG_ADDR, MAIN_ICG_EN_PECI0_ENABLE_DATA, MAIN_ICG_EN_PECI0_EN_SHIFT, MAIN_ICG_EN_PECI0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_PECI0_ 			itg_set_reg(MAIN_ICG_EN_PECI0_CTRL_REG_ADDR, MAIN_ICG_EN_PECI0_DISABLE_DATA, MAIN_ICG_EN_PECI0_EN_SHIFT, MAIN_ICG_EN_PECI0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PECI0_ 		itg_get_reg(MAIN_ICG_EN_PECI0_CTRL_REG_ADDR, MAIN_ICG_EN_PECI0_EN_SHIFT, MAIN_ICG_EN_PECI0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PECI0_(x) 		itg_set_reg(MAIN_ICG_EN_PECI0_CTRL_REG_ADDR, x, MAIN_ICG_EN_PECI0_EN_SHIFT, MAIN_ICG_EN_PECI0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_PECI1_ 			itg_set_reg(MAIN_ICG_EN_PECI1_CTRL_REG_ADDR, MAIN_ICG_EN_PECI1_ENABLE_DATA, MAIN_ICG_EN_PECI1_EN_SHIFT, MAIN_ICG_EN_PECI1_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_PECI1_ 			itg_set_reg(MAIN_ICG_EN_PECI1_CTRL_REG_ADDR, MAIN_ICG_EN_PECI1_DISABLE_DATA, MAIN_ICG_EN_PECI1_EN_SHIFT, MAIN_ICG_EN_PECI1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PECI1_ 		itg_get_reg(MAIN_ICG_EN_PECI1_CTRL_REG_ADDR, MAIN_ICG_EN_PECI1_EN_SHIFT, MAIN_ICG_EN_PECI1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PECI1_(x) 		itg_set_reg(MAIN_ICG_EN_PECI1_CTRL_REG_ADDR, x, MAIN_ICG_EN_PECI1_EN_SHIFT, MAIN_ICG_EN_PECI1_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_GMAC0_ 			itg_set_reg(MAIN_ICG_EN_GMAC0_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC0_ENABLE_DATA, MAIN_ICG_EN_GMAC0_EN_SHIFT, MAIN_ICG_EN_GMAC0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_GMAC0_ 			itg_set_reg(MAIN_ICG_EN_GMAC0_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC0_DISABLE_DATA, MAIN_ICG_EN_GMAC0_EN_SHIFT, MAIN_ICG_EN_GMAC0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC0_ 		itg_get_reg(MAIN_ICG_EN_GMAC0_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC0_EN_SHIFT, MAIN_ICG_EN_GMAC0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC0_(x) 		itg_set_reg(MAIN_ICG_EN_GMAC0_CTRL_REG_ADDR, x, MAIN_ICG_EN_GMAC0_EN_SHIFT, MAIN_ICG_EN_GMAC0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_GMAC1_ 			itg_set_reg(MAIN_ICG_EN_GMAC1_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_ENABLE_DATA, MAIN_ICG_EN_GMAC1_EN_SHIFT, MAIN_ICG_EN_GMAC1_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_GMAC1_ 			itg_set_reg(MAIN_ICG_EN_GMAC1_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_DISABLE_DATA, MAIN_ICG_EN_GMAC1_EN_SHIFT, MAIN_ICG_EN_GMAC1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC1_ 		itg_get_reg(MAIN_ICG_EN_GMAC1_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_EN_SHIFT, MAIN_ICG_EN_GMAC1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC1_(x) 		itg_set_reg(MAIN_ICG_EN_GMAC1_CTRL_REG_ADDR, x, MAIN_ICG_EN_GMAC1_EN_SHIFT, MAIN_ICG_EN_GMAC1_EN_MASK)


#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BMCPERIPH3_SYSREG_RSTN_ 	itg_get_reg(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH3_SYSREG_RSTN_SHIFT, RSTN_U0_BMCPERIPH3_SYSREG_RSTN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BMCPERIPH3_SYSREG_RSTN_ 	itg_assert_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH3_SYSREG_RSTN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BMCPERIPH3_SYSREG_RSTN_ 	itg_clear_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH3_SYSREG_RSTN_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_GMAC0_ 	itg_get_reg(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC0_SHIFT, MAIN_RSTN_GMAC0_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_GMAC0_ 	itg_assert_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC0_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_GMAC0_ 	itg_clear_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC0_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_GMAC1_ 	itg_get_reg(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC1_SHIFT, MAIN_RSTN_GMAC1_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_GMAC1_ 	itg_assert_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC1_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_GMAC1_ 	itg_clear_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC1_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_PECI0_ 	itg_get_reg(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PECI0_SHIFT, MAIN_RSTN_PECI0_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_PECI0_ 	itg_assert_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PECI0_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_PECI0_ 	itg_clear_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PECI0_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_PECI1_ 	itg_get_reg(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PECI1_SHIFT, MAIN_RSTN_PECI1_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_PECI1_ 	itg_assert_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PECI1_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_PECI1_ 	itg_clear_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PECI1_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_DWC_SENSORS_PD_ 	itg_get_reg(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DWC_SENSORS_PD_SHIFT, MAIN_RSTN_DWC_SENSORS_PD_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_DWC_SENSORS_PD_ 	itg_assert_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DWC_SENSORS_PD_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_DWC_SENSORS_PD_ 	itg_clear_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DWC_SENSORS_PD_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BMCPERIPH3_IOMUX_PRESETN_ 	itg_get_reg(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH3_IOMUX_PRESETN_SHIFT, RSTN_U0_BMCPERIPH3_IOMUX_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BMCPERIPH3_IOMUX_PRESETN_ 	itg_assert_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH3_IOMUX_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BMCPERIPH3_IOMUX_PRESETN_ 	itg_clear_rst(BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH3_IOMUX_PRESETN_MASK)


#endif //_BMCPERIPH3_CRG_MACRO_H_
