
#ifndef _PERIPH3_CRG_MACRO_H_
#define _PERIPH3_CRG_MACRO_H_

//#define PERIPH3_CRG_BASE_ADDR 0x0
#define PERIPH3_BUS_CLK_CTRL_REG_ADDR                                (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define PERIPH3_125M_CLK_CTRL_REG_ADDR                               (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define PERIPH3_BUS_100M_CLK_CTRL_REG_ADDR                           (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define CLK_CRG_SECURE_CTRL_REG_ADDR                                 (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)
#define CLK_RMII_GMAC0_CTRL_REG_ADDR                                 (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define CLK_RMII_GMAC1_CTRL_REG_ADDR                                 (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define CLK_GMAC0_AXI_CTRL_REG_ADDR                                  (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define CLK_GMAC1_AXI_CTRL_REG_ADDR                                  (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x1CU)
#define CLK_PECI_I_CTRL_REG_ADDR                                     (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x20U)
#define CLK_APB_GMAC0_CTRL_REG_ADDR                                  (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x24U)
#define CLK_APB_GMAC1_CTRL_REG_ADDR                                  (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x28U)
#define CLK_APB_PECI_CTRL_REG_ADDR                                   (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x2CU)
#define CLK_APB_SENSORS_PD_CTRL_REG_ADDR                             (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x30U)
#define CLK_SGMII_GMAC1_RX_CTRL_REG_ADDR                             (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x34U)
#define CLK_SGMII_GMAC1_TX_CTRL_REG_ADDR                             (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x38U)
#define CLK_APB_SYSCON_CTRL_REG_ADDR                                 (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x3CU)
#define CLK_APB_SECURE_SYSCON_CTRL_REG_ADDR                          (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x40U)
#define CLK_BMCPERIPH3_IOMUX_CTRL_REG_ADDR                           (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x44U)
#define CLK_RMII_MUXED_50M_CTRL_REG_ADDR                             (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x48U)
#define CLK_RMII_DIV2_CTRL_REG_ADDR                                  (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x4CU)
#define CLK_U0_PERIPH3_CRG_PCLK_CTRL_REG_ADDR                        (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x50U)
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR            (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x54U)
#define CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR               (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x58U)


#define MAIN_ICG_EN_PERIPH3_BUS_CTRL_REG_ADDR                        (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x5CU)
#define MAIN_ICG_EN_PERIPH3_125M_CTRL_REG_ADDR                       (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x60U)
#define MAIN_ICG_EN_PERIPH3_BUS_100M_CTRL_REG_ADDR                   (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x64U)
#define MAIN_ICG_EN_CLK_CRG_SECURE_I_CTRL_REG_ADDR                   (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x68U)
#define MAIN_ICG_EN_GMAC0_CLK_RMII_I_CTRL_REG_ADDR                   (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x6CU)
#define MAIN_ICG_EN_GMAC1_CLK_RMII_I_CTRL_REG_ADDR                   (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x70U)
#define MAIN_ICG_EN_GMAC0_CLK_AXI_I_CTRL_REG_ADDR                    (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x74U)
#define MAIN_ICG_EN_GMAC1_CLK_AXI_I_CTRL_REG_ADDR                    (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x78U)
#define MAIN_ICG_EN_CLK_PECI0_I_CTRL_REG_ADDR                        (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x7CU)
#define MAIN_ICG_EN_CLK_APB_GMAC0_CTRL_REG_ADDR                      (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x80U)
#define MAIN_ICG_EN_CLK_APB_GMAC1_CTRL_REG_ADDR                      (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x84U)
#define MAIN_ICG_EN_CLK_APB_PECI0_CTRL_REG_ADDR                      (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x88U)
#define MAIN_ICG_EN_CLK_APB_SENSORS_PD_CTRL_REG_ADDR                 (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x8CU)
#define MAIN_ICG_EN_GMAC1_CLK_RX_I_CTRL_REG_ADDR                     (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x90U)
#define MAIN_ICG_EN_GMAC1_CLK_TX_I_CTRL_REG_ADDR                     (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x94U)


#define PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR           (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x98U)

#define PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR           (U0_PERIPH3_CRG__ITG_BD_APBS__BASE_ADDR + 0x9CU)


#define PERIPH3_BUS_CLK_ENABLE_DATA                                  1
#define PERIPH3_BUS_CLK_DISABLE_DATA                                 0
#define PERIPH3_BUS_CLK_EN_SHIFT                                     31
#define PERIPH3_BUS_CLK_EN_MASK                                      0x80000000U
#define PERIPH3_125M_CLK_ENABLE_DATA                                 1
#define PERIPH3_125M_CLK_DISABLE_DATA                                0
#define PERIPH3_125M_CLK_EN_SHIFT                                    31
#define PERIPH3_125M_CLK_EN_MASK                                     0x80000000U
#define PERIPH3_BUS_100M_CLK_ENABLE_DATA                             1
#define PERIPH3_BUS_100M_CLK_DISABLE_DATA                            0
#define PERIPH3_BUS_100M_CLK_EN_SHIFT                                31
#define PERIPH3_BUS_100M_CLK_EN_MASK                                 0x80000000U
#define CLK_CRG_SECURE_ENABLE_DATA                                   1
#define CLK_CRG_SECURE_DISABLE_DATA                                  0
#define CLK_CRG_SECURE_EN_SHIFT                                      31
#define CLK_CRG_SECURE_EN_MASK                                       0x80000000U
#define CLK_CRG_SECURE_DIV_SHIFT                                     0
#define CLK_CRG_SECURE_DIV_MASK                                      0x7U
#define CLK_RMII_GMAC0_ENABLE_DATA                                   1
#define CLK_RMII_GMAC0_DISABLE_DATA                                  0
#define CLK_RMII_GMAC0_EN_SHIFT                                      31
#define CLK_RMII_GMAC0_EN_MASK                                       0x80000000U
#define CLK_RMII_GMAC0_DIV_SHIFT                                     0
#define CLK_RMII_GMAC0_DIV_MASK                                      0xFU
#define CLK_RMII_GMAC1_ENABLE_DATA                                   1
#define CLK_RMII_GMAC1_DISABLE_DATA                                  0
#define CLK_RMII_GMAC1_EN_SHIFT                                      31
#define CLK_RMII_GMAC1_EN_MASK                                       0x80000000U
#define CLK_RMII_GMAC1_DIV_SHIFT                                     0
#define CLK_RMII_GMAC1_DIV_MASK                                      0xFU
#define CLK_GMAC0_AXI_ENABLE_DATA                                    1
#define CLK_GMAC0_AXI_DISABLE_DATA                                   0
#define CLK_GMAC0_AXI_EN_SHIFT                                       31
#define CLK_GMAC0_AXI_EN_MASK                                        0x80000000U
#define CLK_GMAC0_AXI_DIV_SHIFT                                      0
#define CLK_GMAC0_AXI_DIV_MASK                                       0x3U
#define CLK_GMAC1_AXI_ENABLE_DATA                                    1
#define CLK_GMAC1_AXI_DISABLE_DATA                                   0
#define CLK_GMAC1_AXI_EN_SHIFT                                       31
#define CLK_GMAC1_AXI_EN_MASK                                        0x80000000U
#define CLK_GMAC1_AXI_DIV_SHIFT                                      0
#define CLK_GMAC1_AXI_DIV_MASK                                       0x3U
#define CLK_PECI_I_ENABLE_DATA                                       1
#define CLK_PECI_I_DISABLE_DATA                                      0
#define CLK_PECI_I_EN_SHIFT                                          31
#define CLK_PECI_I_EN_MASK                                           0x80000000U
#define CLK_PECI_I_DIV_SHIFT                                         0
#define CLK_PECI_I_DIV_MASK                                          0x3U
#define CLK_APB_GMAC0_ENABLE_DATA                                    1
#define CLK_APB_GMAC0_DISABLE_DATA                                   0
#define CLK_APB_GMAC0_EN_SHIFT                                       31
#define CLK_APB_GMAC0_EN_MASK                                        0x80000000U
#define CLK_APB_GMAC0_DIV_SHIFT                                      0
#define CLK_APB_GMAC0_DIV_MASK                                       0x7U
#define CLK_APB_GMAC1_ENABLE_DATA                                    1
#define CLK_APB_GMAC1_DISABLE_DATA                                   0
#define CLK_APB_GMAC1_EN_SHIFT                                       31
#define CLK_APB_GMAC1_EN_MASK                                        0x80000000U
#define CLK_APB_GMAC1_DIV_SHIFT                                      0
#define CLK_APB_GMAC1_DIV_MASK                                       0x7U
#define CLK_APB_PECI_ENABLE_DATA                                     1
#define CLK_APB_PECI_DISABLE_DATA                                    0
#define CLK_APB_PECI_EN_SHIFT                                        31
#define CLK_APB_PECI_EN_MASK                                         0x80000000U
#define CLK_APB_PECI_DIV_SHIFT                                       0
#define CLK_APB_PECI_DIV_MASK                                        0x7U
#define CLK_APB_SENSORS_PD_ENABLE_DATA                               1
#define CLK_APB_SENSORS_PD_DISABLE_DATA                              0
#define CLK_APB_SENSORS_PD_EN_SHIFT                                  31
#define CLK_APB_SENSORS_PD_EN_MASK                                   0x80000000U
#define CLK_APB_SENSORS_PD_DIV_SHIFT                                 0
#define CLK_APB_SENSORS_PD_DIV_MASK                                  0x7U
#define CLK_SGMII_GMAC1_RX_ENABLE_DATA                               1
#define CLK_SGMII_GMAC1_RX_DISABLE_DATA                              0
#define CLK_SGMII_GMAC1_RX_EN_SHIFT                                  31
#define CLK_SGMII_GMAC1_RX_EN_MASK                                   0x80000000U
#define CLK_SGMII_GMAC1_TX_ENABLE_DATA                               1
#define CLK_SGMII_GMAC1_TX_DISABLE_DATA                              0
#define CLK_SGMII_GMAC1_TX_EN_SHIFT                                  31
#define CLK_SGMII_GMAC1_TX_EN_MASK                                   0x80000000U
#define CLK_APB_SYSCON_DIV_SHIFT                                     0
#define CLK_APB_SYSCON_DIV_MASK                                      0x7U
#define CLK_APB_SECURE_SYSCON_DIV_SHIFT                              0
#define CLK_APB_SECURE_SYSCON_DIV_MASK                               0x7U
#define CLK_BMCPERIPH3_IOMUX_DIV_SHIFT                               0
#define CLK_BMCPERIPH3_IOMUX_DIV_MASK                                0x7U
#define CLK_RMII_MUXED_50M_SW_SHIFT                                  24
#define CLK_RMII_MUXED_50M_SW_MASK                                   0x1000000U
#define CLK_RMII_MUXED_50M_SW_CLK_RMII_GMAC0_DATA                    0
#define CLK_RMII_MUXED_50M_SW_CLK_PERIPH3_GMAC_RMII_RCLKI_DATA       1
#define CLK_RMII_DIV2_DIV_SHIFT                                      0
#define CLK_RMII_DIV2_DIV_MASK                                       0x3U
#define CLK_U0_PERIPH3_CRG_PCLK_DIV_SHIFT                            0
#define CLK_U0_PERIPH3_CRG_PCLK_DIV_MASK                             0x7U
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_DIV_SHIFT                0
#define CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_DIV_MASK                 0x3FU
#define CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_DIV_SHIFT                   0
#define CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_DIV_MASK                    0x3FU

#define MAIN_ICG_EN_PERIPH3_BUS_ENABLE_DATA                          1
#define MAIN_ICG_EN_PERIPH3_BUS_DISABLE_DATA                         0
#define MAIN_ICG_EN_PERIPH3_BUS_EN_SHIFT                             31
#define MAIN_ICG_EN_PERIPH3_BUS_EN_MASK                              0x80000000U
#define MAIN_ICG_EN_PERIPH3_125M_ENABLE_DATA                         1
#define MAIN_ICG_EN_PERIPH3_125M_DISABLE_DATA                        0
#define MAIN_ICG_EN_PERIPH3_125M_EN_SHIFT                            31
#define MAIN_ICG_EN_PERIPH3_125M_EN_MASK                             0x80000000U
#define MAIN_ICG_EN_PERIPH3_BUS_100M_ENABLE_DATA                     1
#define MAIN_ICG_EN_PERIPH3_BUS_100M_DISABLE_DATA                    0
#define MAIN_ICG_EN_PERIPH3_BUS_100M_EN_SHIFT                        31
#define MAIN_ICG_EN_PERIPH3_BUS_100M_EN_MASK                         0x80000000U
#define MAIN_ICG_EN_CLK_CRG_SECURE_I_ENABLE_DATA                     1
#define MAIN_ICG_EN_CLK_CRG_SECURE_I_DISABLE_DATA                    0
#define MAIN_ICG_EN_CLK_CRG_SECURE_I_EN_SHIFT                        31
#define MAIN_ICG_EN_CLK_CRG_SECURE_I_EN_MASK                         0x80000000U
#define MAIN_ICG_EN_GMAC0_CLK_RMII_I_ENABLE_DATA                     1
#define MAIN_ICG_EN_GMAC0_CLK_RMII_I_DISABLE_DATA                    0
#define MAIN_ICG_EN_GMAC0_CLK_RMII_I_EN_SHIFT                        31
#define MAIN_ICG_EN_GMAC0_CLK_RMII_I_EN_MASK                         0x80000000U
#define MAIN_ICG_EN_GMAC1_CLK_RMII_I_ENABLE_DATA                     1
#define MAIN_ICG_EN_GMAC1_CLK_RMII_I_DISABLE_DATA                    0
#define MAIN_ICG_EN_GMAC1_CLK_RMII_I_EN_SHIFT                        31
#define MAIN_ICG_EN_GMAC1_CLK_RMII_I_EN_MASK                         0x80000000U
#define MAIN_ICG_EN_GMAC0_CLK_AXI_I_ENABLE_DATA                      1
#define MAIN_ICG_EN_GMAC0_CLK_AXI_I_DISABLE_DATA                     0
#define MAIN_ICG_EN_GMAC0_CLK_AXI_I_EN_SHIFT                         31
#define MAIN_ICG_EN_GMAC0_CLK_AXI_I_EN_MASK                          0x80000000U
#define MAIN_ICG_EN_GMAC1_CLK_AXI_I_ENABLE_DATA                      1
#define MAIN_ICG_EN_GMAC1_CLK_AXI_I_DISABLE_DATA                     0
#define MAIN_ICG_EN_GMAC1_CLK_AXI_I_EN_SHIFT                         31
#define MAIN_ICG_EN_GMAC1_CLK_AXI_I_EN_MASK                          0x80000000U
#define MAIN_ICG_EN_CLK_PECI0_I_ENABLE_DATA                          1
#define MAIN_ICG_EN_CLK_PECI0_I_DISABLE_DATA                         0
#define MAIN_ICG_EN_CLK_PECI0_I_EN_SHIFT                             31
#define MAIN_ICG_EN_CLK_PECI0_I_EN_MASK                              0x80000000U
#define MAIN_ICG_EN_CLK_APB_GMAC0_ENABLE_DATA                        1
#define MAIN_ICG_EN_CLK_APB_GMAC0_DISABLE_DATA                       0
#define MAIN_ICG_EN_CLK_APB_GMAC0_EN_SHIFT                           31
#define MAIN_ICG_EN_CLK_APB_GMAC0_EN_MASK                            0x80000000U
#define MAIN_ICG_EN_CLK_APB_GMAC1_ENABLE_DATA                        1
#define MAIN_ICG_EN_CLK_APB_GMAC1_DISABLE_DATA                       0
#define MAIN_ICG_EN_CLK_APB_GMAC1_EN_SHIFT                           31
#define MAIN_ICG_EN_CLK_APB_GMAC1_EN_MASK                            0x80000000U
#define MAIN_ICG_EN_CLK_APB_PECI0_ENABLE_DATA                        1
#define MAIN_ICG_EN_CLK_APB_PECI0_DISABLE_DATA                       0
#define MAIN_ICG_EN_CLK_APB_PECI0_EN_SHIFT                           31
#define MAIN_ICG_EN_CLK_APB_PECI0_EN_MASK                            0x80000000U
#define MAIN_ICG_EN_CLK_APB_SENSORS_PD_ENABLE_DATA                   1
#define MAIN_ICG_EN_CLK_APB_SENSORS_PD_DISABLE_DATA                  0
#define MAIN_ICG_EN_CLK_APB_SENSORS_PD_EN_SHIFT                      31
#define MAIN_ICG_EN_CLK_APB_SENSORS_PD_EN_MASK                       0x80000000U
#define MAIN_ICG_EN_GMAC1_CLK_RX_I_ENABLE_DATA                       1
#define MAIN_ICG_EN_GMAC1_CLK_RX_I_DISABLE_DATA                      0
#define MAIN_ICG_EN_GMAC1_CLK_RX_I_EN_SHIFT                          31
#define MAIN_ICG_EN_GMAC1_CLK_RX_I_EN_MASK                           0x80000000U
#define MAIN_ICG_EN_GMAC1_CLK_TX_I_ENABLE_DATA                       1
#define MAIN_ICG_EN_GMAC1_CLK_TX_I_DISABLE_DATA                      0
#define MAIN_ICG_EN_GMAC1_CLK_TX_I_EN_SHIFT                          31
#define MAIN_ICG_EN_GMAC1_CLK_TX_I_EN_MASK                           0x80000000U



#define MAIN_RSTN_GMAC0_SHIFT                                        0
#define MAIN_RSTN_GMAC0_MASK                                         (0x1 << 0)
#define MAIN_RSTN_GMAC0_ASSERT                                       1
#define MAIN_RSTN_GMAC0_CLEAR                                        0
#define MAIN_RSTN_GMAC1_SHIFT                                        1
#define MAIN_RSTN_GMAC1_MASK                                         (0x1 << 1)
#define MAIN_RSTN_GMAC1_ASSERT                                       1
#define MAIN_RSTN_GMAC1_CLEAR                                        0
#define MAIN_RSTN_PECI_SHIFT                                         2
#define MAIN_RSTN_PECI_MASK                                          (0x1 << 2)
#define MAIN_RSTN_PECI_ASSERT                                        1
#define MAIN_RSTN_PECI_CLEAR                                         0
#define MAIN_RSTN_DWC_SENSORS_PD_SHIFT                               3
#define MAIN_RSTN_DWC_SENSORS_PD_MASK                                (0x1 << 3)
#define MAIN_RSTN_DWC_SENSORS_PD_ASSERT                              1
#define MAIN_RSTN_DWC_SENSORS_PD_CLEAR                               0
#define MAIN_RSTN_NCNOC_SHIFT                                        4
#define MAIN_RSTN_NCNOC_MASK                                         (0x1 << 4)
#define MAIN_RSTN_NCNOC_ASSERT                                       1
#define MAIN_RSTN_NCNOC_CLEAR                                        0
#define RST_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_SHIFT                5
#define RST_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_MASK                 (0x1 << 5)
#define RST_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_ASSERT               1
#define RST_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_CLEAR                0
#define MAIN_RSTN_IOMUX_SHIFT                                        6
#define MAIN_RSTN_IOMUX_MASK                                         (0x1 << 6)
#define MAIN_RSTN_IOMUX_ASSERT                                       1
#define MAIN_RSTN_IOMUX_CLEAR                                        0

#define _ENABLE_CLOCK_PERIPH3_BUS_CLK_ 			itg_set_reg(PERIPH3_BUS_CLK_CTRL_REG_ADDR, PERIPH3_BUS_CLK_ENABLE_DATA, PERIPH3_BUS_CLK_EN_SHIFT, PERIPH3_BUS_CLK_EN_MASK)
#define _DISABLE_CLOCK_PERIPH3_BUS_CLK_ 			itg_set_reg(PERIPH3_BUS_CLK_CTRL_REG_ADDR, PERIPH3_BUS_CLK_DISABLE_DATA, PERIPH3_BUS_CLK_EN_SHIFT, PERIPH3_BUS_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_PERIPH3_BUS_CLK_ 		itg_get_reg(PERIPH3_BUS_CLK_CTRL_REG_ADDR, PERIPH3_BUS_CLK_EN_SHIFT, PERIPH3_BUS_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_PERIPH3_BUS_CLK_(x) 		itg_set_reg(PERIPH3_BUS_CLK_CTRL_REG_ADDR, x, PERIPH3_BUS_CLK_EN_SHIFT, PERIPH3_BUS_CLK_EN_MASK)
#define _ENABLE_CLOCK_PERIPH3_125M_CLK_ 			itg_set_reg(PERIPH3_125M_CLK_CTRL_REG_ADDR, PERIPH3_125M_CLK_ENABLE_DATA, PERIPH3_125M_CLK_EN_SHIFT, PERIPH3_125M_CLK_EN_MASK)
#define _DISABLE_CLOCK_PERIPH3_125M_CLK_ 			itg_set_reg(PERIPH3_125M_CLK_CTRL_REG_ADDR, PERIPH3_125M_CLK_DISABLE_DATA, PERIPH3_125M_CLK_EN_SHIFT, PERIPH3_125M_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_PERIPH3_125M_CLK_ 		itg_get_reg(PERIPH3_125M_CLK_CTRL_REG_ADDR, PERIPH3_125M_CLK_EN_SHIFT, PERIPH3_125M_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_PERIPH3_125M_CLK_(x) 		itg_set_reg(PERIPH3_125M_CLK_CTRL_REG_ADDR, x, PERIPH3_125M_CLK_EN_SHIFT, PERIPH3_125M_CLK_EN_MASK)
#define _ENABLE_CLOCK_PERIPH3_BUS_100M_CLK_ 			itg_set_reg(PERIPH3_BUS_100M_CLK_CTRL_REG_ADDR, PERIPH3_BUS_100M_CLK_ENABLE_DATA, PERIPH3_BUS_100M_CLK_EN_SHIFT, PERIPH3_BUS_100M_CLK_EN_MASK)
#define _DISABLE_CLOCK_PERIPH3_BUS_100M_CLK_ 			itg_set_reg(PERIPH3_BUS_100M_CLK_CTRL_REG_ADDR, PERIPH3_BUS_100M_CLK_DISABLE_DATA, PERIPH3_BUS_100M_CLK_EN_SHIFT, PERIPH3_BUS_100M_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_PERIPH3_BUS_100M_CLK_ 		itg_get_reg(PERIPH3_BUS_100M_CLK_CTRL_REG_ADDR, PERIPH3_BUS_100M_CLK_EN_SHIFT, PERIPH3_BUS_100M_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_PERIPH3_BUS_100M_CLK_(x) 		itg_set_reg(PERIPH3_BUS_100M_CLK_CTRL_REG_ADDR, x, PERIPH3_BUS_100M_CLK_EN_SHIFT, PERIPH3_BUS_100M_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_CRG_SECURE_ 			itg_set_reg(CLK_CRG_SECURE_CTRL_REG_ADDR, CLK_CRG_SECURE_ENABLE_DATA, CLK_CRG_SECURE_EN_SHIFT, CLK_CRG_SECURE_EN_MASK)
#define _DISABLE_CLOCK_CLK_CRG_SECURE_ 			itg_set_reg(CLK_CRG_SECURE_CTRL_REG_ADDR, CLK_CRG_SECURE_DISABLE_DATA, CLK_CRG_SECURE_EN_SHIFT, CLK_CRG_SECURE_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_CRG_SECURE_ 		itg_get_reg(CLK_CRG_SECURE_CTRL_REG_ADDR, CLK_CRG_SECURE_EN_SHIFT, CLK_CRG_SECURE_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_CRG_SECURE_(x) 		itg_set_reg(CLK_CRG_SECURE_CTRL_REG_ADDR, x, CLK_CRG_SECURE_EN_SHIFT, CLK_CRG_SECURE_EN_MASK)
#define _DIVIDE_CLOCK_CLK_CRG_SECURE_(div) 			itg_set_reg(CLK_CRG_SECURE_CTRL_REG_ADDR, div, CLK_CRG_SECURE_DIV_SHIFT, CLK_CRG_SECURE_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_CRG_SECURE_ 		itg_get_reg(CLK_CRG_SECURE_CTRL_REG_ADDR, CLK_CRG_SECURE_DIV_SHIFT, CLK_CRG_SECURE_DIV_MASK)
#define _ENABLE_CLOCK_CLK_RMII_GMAC0_ 			itg_set_reg(CLK_RMII_GMAC0_CTRL_REG_ADDR, CLK_RMII_GMAC0_ENABLE_DATA, CLK_RMII_GMAC0_EN_SHIFT, CLK_RMII_GMAC0_EN_MASK)
#define _DISABLE_CLOCK_CLK_RMII_GMAC0_ 			itg_set_reg(CLK_RMII_GMAC0_CTRL_REG_ADDR, CLK_RMII_GMAC0_DISABLE_DATA, CLK_RMII_GMAC0_EN_SHIFT, CLK_RMII_GMAC0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_RMII_GMAC0_ 		itg_get_reg(CLK_RMII_GMAC0_CTRL_REG_ADDR, CLK_RMII_GMAC0_EN_SHIFT, CLK_RMII_GMAC0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_RMII_GMAC0_(x) 		itg_set_reg(CLK_RMII_GMAC0_CTRL_REG_ADDR, x, CLK_RMII_GMAC0_EN_SHIFT, CLK_RMII_GMAC0_EN_MASK)
#define _DIVIDE_CLOCK_CLK_RMII_GMAC0_(div) 			itg_set_reg(CLK_RMII_GMAC0_CTRL_REG_ADDR, div, CLK_RMII_GMAC0_DIV_SHIFT, CLK_RMII_GMAC0_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_RMII_GMAC0_ 		itg_get_reg(CLK_RMII_GMAC0_CTRL_REG_ADDR, CLK_RMII_GMAC0_DIV_SHIFT, CLK_RMII_GMAC0_DIV_MASK)
#define _ENABLE_CLOCK_CLK_RMII_GMAC1_ 			itg_set_reg(CLK_RMII_GMAC1_CTRL_REG_ADDR, CLK_RMII_GMAC1_ENABLE_DATA, CLK_RMII_GMAC1_EN_SHIFT, CLK_RMII_GMAC1_EN_MASK)
#define _DISABLE_CLOCK_CLK_RMII_GMAC1_ 			itg_set_reg(CLK_RMII_GMAC1_CTRL_REG_ADDR, CLK_RMII_GMAC1_DISABLE_DATA, CLK_RMII_GMAC1_EN_SHIFT, CLK_RMII_GMAC1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_RMII_GMAC1_ 		itg_get_reg(CLK_RMII_GMAC1_CTRL_REG_ADDR, CLK_RMII_GMAC1_EN_SHIFT, CLK_RMII_GMAC1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_RMII_GMAC1_(x) 		itg_set_reg(CLK_RMII_GMAC1_CTRL_REG_ADDR, x, CLK_RMII_GMAC1_EN_SHIFT, CLK_RMII_GMAC1_EN_MASK)
#define _DIVIDE_CLOCK_CLK_RMII_GMAC1_(div) 			itg_set_reg(CLK_RMII_GMAC1_CTRL_REG_ADDR, div, CLK_RMII_GMAC1_DIV_SHIFT, CLK_RMII_GMAC1_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_RMII_GMAC1_ 		itg_get_reg(CLK_RMII_GMAC1_CTRL_REG_ADDR, CLK_RMII_GMAC1_DIV_SHIFT, CLK_RMII_GMAC1_DIV_MASK)
#define _ENABLE_CLOCK_CLK_GMAC0_AXI_ 			itg_set_reg(CLK_GMAC0_AXI_CTRL_REG_ADDR, CLK_GMAC0_AXI_ENABLE_DATA, CLK_GMAC0_AXI_EN_SHIFT, CLK_GMAC0_AXI_EN_MASK)
#define _DISABLE_CLOCK_CLK_GMAC0_AXI_ 			itg_set_reg(CLK_GMAC0_AXI_CTRL_REG_ADDR, CLK_GMAC0_AXI_DISABLE_DATA, CLK_GMAC0_AXI_EN_SHIFT, CLK_GMAC0_AXI_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_GMAC0_AXI_ 		itg_get_reg(CLK_GMAC0_AXI_CTRL_REG_ADDR, CLK_GMAC0_AXI_EN_SHIFT, CLK_GMAC0_AXI_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_GMAC0_AXI_(x) 		itg_set_reg(CLK_GMAC0_AXI_CTRL_REG_ADDR, x, CLK_GMAC0_AXI_EN_SHIFT, CLK_GMAC0_AXI_EN_MASK)
#define _DIVIDE_CLOCK_CLK_GMAC0_AXI_(div) 			itg_set_reg(CLK_GMAC0_AXI_CTRL_REG_ADDR, div, CLK_GMAC0_AXI_DIV_SHIFT, CLK_GMAC0_AXI_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_GMAC0_AXI_ 		itg_get_reg(CLK_GMAC0_AXI_CTRL_REG_ADDR, CLK_GMAC0_AXI_DIV_SHIFT, CLK_GMAC0_AXI_DIV_MASK)
#define _ENABLE_CLOCK_CLK_GMAC1_AXI_ 			itg_set_reg(CLK_GMAC1_AXI_CTRL_REG_ADDR, CLK_GMAC1_AXI_ENABLE_DATA, CLK_GMAC1_AXI_EN_SHIFT, CLK_GMAC1_AXI_EN_MASK)
#define _DISABLE_CLOCK_CLK_GMAC1_AXI_ 			itg_set_reg(CLK_GMAC1_AXI_CTRL_REG_ADDR, CLK_GMAC1_AXI_DISABLE_DATA, CLK_GMAC1_AXI_EN_SHIFT, CLK_GMAC1_AXI_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_GMAC1_AXI_ 		itg_get_reg(CLK_GMAC1_AXI_CTRL_REG_ADDR, CLK_GMAC1_AXI_EN_SHIFT, CLK_GMAC1_AXI_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_GMAC1_AXI_(x) 		itg_set_reg(CLK_GMAC1_AXI_CTRL_REG_ADDR, x, CLK_GMAC1_AXI_EN_SHIFT, CLK_GMAC1_AXI_EN_MASK)
#define _DIVIDE_CLOCK_CLK_GMAC1_AXI_(div) 			itg_set_reg(CLK_GMAC1_AXI_CTRL_REG_ADDR, div, CLK_GMAC1_AXI_DIV_SHIFT, CLK_GMAC1_AXI_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_GMAC1_AXI_ 		itg_get_reg(CLK_GMAC1_AXI_CTRL_REG_ADDR, CLK_GMAC1_AXI_DIV_SHIFT, CLK_GMAC1_AXI_DIV_MASK)
#define _ENABLE_CLOCK_CLK_PECI_I_ 			itg_set_reg(CLK_PECI_I_CTRL_REG_ADDR, CLK_PECI_I_ENABLE_DATA, CLK_PECI_I_EN_SHIFT, CLK_PECI_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_PECI_I_ 			itg_set_reg(CLK_PECI_I_CTRL_REG_ADDR, CLK_PECI_I_DISABLE_DATA, CLK_PECI_I_EN_SHIFT, CLK_PECI_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_PECI_I_ 		itg_get_reg(CLK_PECI_I_CTRL_REG_ADDR, CLK_PECI_I_EN_SHIFT, CLK_PECI_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_PECI_I_(x) 		itg_set_reg(CLK_PECI_I_CTRL_REG_ADDR, x, CLK_PECI_I_EN_SHIFT, CLK_PECI_I_EN_MASK)
#define _DIVIDE_CLOCK_CLK_PECI_I_(div) 			itg_set_reg(CLK_PECI_I_CTRL_REG_ADDR, div, CLK_PECI_I_DIV_SHIFT, CLK_PECI_I_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_PECI_I_ 		itg_get_reg(CLK_PECI_I_CTRL_REG_ADDR, CLK_PECI_I_DIV_SHIFT, CLK_PECI_I_DIV_MASK)
#define _ENABLE_CLOCK_CLK_APB_GMAC0_ 			itg_set_reg(CLK_APB_GMAC0_CTRL_REG_ADDR, CLK_APB_GMAC0_ENABLE_DATA, CLK_APB_GMAC0_EN_SHIFT, CLK_APB_GMAC0_EN_MASK)
#define _DISABLE_CLOCK_CLK_APB_GMAC0_ 			itg_set_reg(CLK_APB_GMAC0_CTRL_REG_ADDR, CLK_APB_GMAC0_DISABLE_DATA, CLK_APB_GMAC0_EN_SHIFT, CLK_APB_GMAC0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_APB_GMAC0_ 		itg_get_reg(CLK_APB_GMAC0_CTRL_REG_ADDR, CLK_APB_GMAC0_EN_SHIFT, CLK_APB_GMAC0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_APB_GMAC0_(x) 		itg_set_reg(CLK_APB_GMAC0_CTRL_REG_ADDR, x, CLK_APB_GMAC0_EN_SHIFT, CLK_APB_GMAC0_EN_MASK)
#define _DIVIDE_CLOCK_CLK_APB_GMAC0_(div) 			itg_set_reg(CLK_APB_GMAC0_CTRL_REG_ADDR, div, CLK_APB_GMAC0_DIV_SHIFT, CLK_APB_GMAC0_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_GMAC0_ 		itg_get_reg(CLK_APB_GMAC0_CTRL_REG_ADDR, CLK_APB_GMAC0_DIV_SHIFT, CLK_APB_GMAC0_DIV_MASK)
#define _ENABLE_CLOCK_CLK_APB_GMAC1_ 			itg_set_reg(CLK_APB_GMAC1_CTRL_REG_ADDR, CLK_APB_GMAC1_ENABLE_DATA, CLK_APB_GMAC1_EN_SHIFT, CLK_APB_GMAC1_EN_MASK)
#define _DISABLE_CLOCK_CLK_APB_GMAC1_ 			itg_set_reg(CLK_APB_GMAC1_CTRL_REG_ADDR, CLK_APB_GMAC1_DISABLE_DATA, CLK_APB_GMAC1_EN_SHIFT, CLK_APB_GMAC1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_APB_GMAC1_ 		itg_get_reg(CLK_APB_GMAC1_CTRL_REG_ADDR, CLK_APB_GMAC1_EN_SHIFT, CLK_APB_GMAC1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_APB_GMAC1_(x) 		itg_set_reg(CLK_APB_GMAC1_CTRL_REG_ADDR, x, CLK_APB_GMAC1_EN_SHIFT, CLK_APB_GMAC1_EN_MASK)
#define _DIVIDE_CLOCK_CLK_APB_GMAC1_(div) 			itg_set_reg(CLK_APB_GMAC1_CTRL_REG_ADDR, div, CLK_APB_GMAC1_DIV_SHIFT, CLK_APB_GMAC1_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_GMAC1_ 		itg_get_reg(CLK_APB_GMAC1_CTRL_REG_ADDR, CLK_APB_GMAC1_DIV_SHIFT, CLK_APB_GMAC1_DIV_MASK)
#define _ENABLE_CLOCK_CLK_APB_PECI_ 			itg_set_reg(CLK_APB_PECI_CTRL_REG_ADDR, CLK_APB_PECI_ENABLE_DATA, CLK_APB_PECI_EN_SHIFT, CLK_APB_PECI_EN_MASK)
#define _DISABLE_CLOCK_CLK_APB_PECI_ 			itg_set_reg(CLK_APB_PECI_CTRL_REG_ADDR, CLK_APB_PECI_DISABLE_DATA, CLK_APB_PECI_EN_SHIFT, CLK_APB_PECI_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_APB_PECI_ 		itg_get_reg(CLK_APB_PECI_CTRL_REG_ADDR, CLK_APB_PECI_EN_SHIFT, CLK_APB_PECI_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_APB_PECI_(x) 		itg_set_reg(CLK_APB_PECI_CTRL_REG_ADDR, x, CLK_APB_PECI_EN_SHIFT, CLK_APB_PECI_EN_MASK)
#define _DIVIDE_CLOCK_CLK_APB_PECI_(div) 			itg_set_reg(CLK_APB_PECI_CTRL_REG_ADDR, div, CLK_APB_PECI_DIV_SHIFT, CLK_APB_PECI_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_PECI_ 		itg_get_reg(CLK_APB_PECI_CTRL_REG_ADDR, CLK_APB_PECI_DIV_SHIFT, CLK_APB_PECI_DIV_MASK)
#define _ENABLE_CLOCK_CLK_APB_SENSORS_PD_ 			itg_set_reg(CLK_APB_SENSORS_PD_CTRL_REG_ADDR, CLK_APB_SENSORS_PD_ENABLE_DATA, CLK_APB_SENSORS_PD_EN_SHIFT, CLK_APB_SENSORS_PD_EN_MASK)
#define _DISABLE_CLOCK_CLK_APB_SENSORS_PD_ 			itg_set_reg(CLK_APB_SENSORS_PD_CTRL_REG_ADDR, CLK_APB_SENSORS_PD_DISABLE_DATA, CLK_APB_SENSORS_PD_EN_SHIFT, CLK_APB_SENSORS_PD_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_APB_SENSORS_PD_ 		itg_get_reg(CLK_APB_SENSORS_PD_CTRL_REG_ADDR, CLK_APB_SENSORS_PD_EN_SHIFT, CLK_APB_SENSORS_PD_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_APB_SENSORS_PD_(x) 		itg_set_reg(CLK_APB_SENSORS_PD_CTRL_REG_ADDR, x, CLK_APB_SENSORS_PD_EN_SHIFT, CLK_APB_SENSORS_PD_EN_MASK)
#define _DIVIDE_CLOCK_CLK_APB_SENSORS_PD_(div) 			itg_set_reg(CLK_APB_SENSORS_PD_CTRL_REG_ADDR, div, CLK_APB_SENSORS_PD_DIV_SHIFT, CLK_APB_SENSORS_PD_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_SENSORS_PD_ 		itg_get_reg(CLK_APB_SENSORS_PD_CTRL_REG_ADDR, CLK_APB_SENSORS_PD_DIV_SHIFT, CLK_APB_SENSORS_PD_DIV_MASK)
#define _ENABLE_CLOCK_CLK_SGMII_GMAC1_RX_ 			itg_set_reg(CLK_SGMII_GMAC1_RX_CTRL_REG_ADDR, CLK_SGMII_GMAC1_RX_ENABLE_DATA, CLK_SGMII_GMAC1_RX_EN_SHIFT, CLK_SGMII_GMAC1_RX_EN_MASK)
#define _DISABLE_CLOCK_CLK_SGMII_GMAC1_RX_ 			itg_set_reg(CLK_SGMII_GMAC1_RX_CTRL_REG_ADDR, CLK_SGMII_GMAC1_RX_DISABLE_DATA, CLK_SGMII_GMAC1_RX_EN_SHIFT, CLK_SGMII_GMAC1_RX_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_SGMII_GMAC1_RX_ 		itg_get_reg(CLK_SGMII_GMAC1_RX_CTRL_REG_ADDR, CLK_SGMII_GMAC1_RX_EN_SHIFT, CLK_SGMII_GMAC1_RX_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_SGMII_GMAC1_RX_(x) 		itg_set_reg(CLK_SGMII_GMAC1_RX_CTRL_REG_ADDR, x, CLK_SGMII_GMAC1_RX_EN_SHIFT, CLK_SGMII_GMAC1_RX_EN_MASK)
#define _ENABLE_CLOCK_CLK_SGMII_GMAC1_TX_ 			itg_set_reg(CLK_SGMII_GMAC1_TX_CTRL_REG_ADDR, CLK_SGMII_GMAC1_TX_ENABLE_DATA, CLK_SGMII_GMAC1_TX_EN_SHIFT, CLK_SGMII_GMAC1_TX_EN_MASK)
#define _DISABLE_CLOCK_CLK_SGMII_GMAC1_TX_ 			itg_set_reg(CLK_SGMII_GMAC1_TX_CTRL_REG_ADDR, CLK_SGMII_GMAC1_TX_DISABLE_DATA, CLK_SGMII_GMAC1_TX_EN_SHIFT, CLK_SGMII_GMAC1_TX_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_SGMII_GMAC1_TX_ 		itg_get_reg(CLK_SGMII_GMAC1_TX_CTRL_REG_ADDR, CLK_SGMII_GMAC1_TX_EN_SHIFT, CLK_SGMII_GMAC1_TX_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_SGMII_GMAC1_TX_(x) 		itg_set_reg(CLK_SGMII_GMAC1_TX_CTRL_REG_ADDR, x, CLK_SGMII_GMAC1_TX_EN_SHIFT, CLK_SGMII_GMAC1_TX_EN_MASK)
#define _DIVIDE_CLOCK_CLK_APB_SYSCON_(div) 			itg_set_reg(CLK_APB_SYSCON_CTRL_REG_ADDR, div, CLK_APB_SYSCON_DIV_SHIFT, CLK_APB_SYSCON_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_SYSCON_ 		itg_get_reg(CLK_APB_SYSCON_CTRL_REG_ADDR, CLK_APB_SYSCON_DIV_SHIFT, CLK_APB_SYSCON_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_APB_SECURE_SYSCON_(div) 			itg_set_reg(CLK_APB_SECURE_SYSCON_CTRL_REG_ADDR, div, CLK_APB_SECURE_SYSCON_DIV_SHIFT, CLK_APB_SECURE_SYSCON_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_SECURE_SYSCON_ 		itg_get_reg(CLK_APB_SECURE_SYSCON_CTRL_REG_ADDR, CLK_APB_SECURE_SYSCON_DIV_SHIFT, CLK_APB_SECURE_SYSCON_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH3_IOMUX_(div) 			itg_set_reg(CLK_BMCPERIPH3_IOMUX_CTRL_REG_ADDR, div, CLK_BMCPERIPH3_IOMUX_DIV_SHIFT, CLK_BMCPERIPH3_IOMUX_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH3_IOMUX_ 		itg_get_reg(CLK_BMCPERIPH3_IOMUX_CTRL_REG_ADDR, CLK_BMCPERIPH3_IOMUX_DIV_SHIFT, CLK_BMCPERIPH3_IOMUX_DIV_MASK)
#define _SWITCH_CLOCK_CLK_RMII_MUXED_50M_SOURCE_CLK_RMII_GMAC0_ 	itg_set_reg(CLK_RMII_MUXED_50M_CTRL_REG_ADDR, CLK_RMII_MUXED_50M_SW_CLK_RMII_GMAC0_DATA, CLK_RMII_MUXED_50M_SW_SHIFT, CLK_RMII_MUXED_50M_SW_MASK)
#define _SWITCH_CLOCK_CLK_RMII_MUXED_50M_SOURCE_CLK_PERIPH3_GMAC_RMII_RCLKI_ 	itg_set_reg(CLK_RMII_MUXED_50M_CTRL_REG_ADDR, CLK_RMII_MUXED_50M_SW_CLK_PERIPH3_GMAC_RMII_RCLKI_DATA, CLK_RMII_MUXED_50M_SW_SHIFT, CLK_RMII_MUXED_50M_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_RMII_MUXED_50M_ 		itg_get_reg(CLK_RMII_MUXED_50M_CTRL_REG_ADDR, CLK_RMII_MUXED_50M_SW_SHIFT, CLK_RMII_MUXED_50M_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_RMII_MUXED_50M_(x) 		itg_set_reg(CLK_RMII_MUXED_50M_CTRL_REG_ADDR, x, CLK_RMII_MUXED_50M_SW_SHIFT, CLK_RMII_MUXED_50M_SW_MASK)
#define _DIVIDE_CLOCK_CLK_RMII_DIV2_(div) 			itg_set_reg(CLK_RMII_DIV2_CTRL_REG_ADDR, div, CLK_RMII_DIV2_DIV_SHIFT, CLK_RMII_DIV2_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_RMII_DIV2_ 		itg_get_reg(CLK_RMII_DIV2_CTRL_REG_ADDR, CLK_RMII_DIV2_DIV_SHIFT, CLK_RMII_DIV2_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_U0_PERIPH3_CRG_PCLK_(div) 			itg_set_reg(CLK_U0_PERIPH3_CRG_PCLK_CTRL_REG_ADDR, div, CLK_U0_PERIPH3_CRG_PCLK_DIV_SHIFT, CLK_U0_PERIPH3_CRG_PCLK_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_U0_PERIPH3_CRG_PCLK_ 		itg_get_reg(CLK_U0_PERIPH3_CRG_PCLK_CTRL_REG_ADDR, CLK_U0_PERIPH3_CRG_PCLK_DIV_SHIFT, CLK_U0_PERIPH3_CRG_PCLK_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_(div) 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR, div, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_DIV_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_DIV_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_TX_125_I_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_(div) 			itg_set_reg(CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR, div, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_DIV_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_DIV_SHIFT, CLK_U0_DWC_ETHER_SGMII_CLK_CSR_I_DIV_MASK)

#define _ENABLE_CLOCK_MAIN_ICG_EN_PERIPH3_BUS_ 			itg_set_reg(MAIN_ICG_EN_PERIPH3_BUS_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH3_BUS_ENABLE_DATA, MAIN_ICG_EN_PERIPH3_BUS_EN_SHIFT, MAIN_ICG_EN_PERIPH3_BUS_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_PERIPH3_BUS_ 			itg_set_reg(MAIN_ICG_EN_PERIPH3_BUS_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH3_BUS_DISABLE_DATA, MAIN_ICG_EN_PERIPH3_BUS_EN_SHIFT, MAIN_ICG_EN_PERIPH3_BUS_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PERIPH3_BUS_ 		itg_get_reg(MAIN_ICG_EN_PERIPH3_BUS_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH3_BUS_EN_SHIFT, MAIN_ICG_EN_PERIPH3_BUS_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PERIPH3_BUS_(x) 		itg_set_reg(MAIN_ICG_EN_PERIPH3_BUS_CTRL_REG_ADDR, x, MAIN_ICG_EN_PERIPH3_BUS_EN_SHIFT, MAIN_ICG_EN_PERIPH3_BUS_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_PERIPH3_125M_ 			itg_set_reg(MAIN_ICG_EN_PERIPH3_125M_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH3_125M_ENABLE_DATA, MAIN_ICG_EN_PERIPH3_125M_EN_SHIFT, MAIN_ICG_EN_PERIPH3_125M_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_PERIPH3_125M_ 			itg_set_reg(MAIN_ICG_EN_PERIPH3_125M_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH3_125M_DISABLE_DATA, MAIN_ICG_EN_PERIPH3_125M_EN_SHIFT, MAIN_ICG_EN_PERIPH3_125M_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PERIPH3_125M_ 		itg_get_reg(MAIN_ICG_EN_PERIPH3_125M_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH3_125M_EN_SHIFT, MAIN_ICG_EN_PERIPH3_125M_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PERIPH3_125M_(x) 		itg_set_reg(MAIN_ICG_EN_PERIPH3_125M_CTRL_REG_ADDR, x, MAIN_ICG_EN_PERIPH3_125M_EN_SHIFT, MAIN_ICG_EN_PERIPH3_125M_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_PERIPH3_BUS_100M_ 			itg_set_reg(MAIN_ICG_EN_PERIPH3_BUS_100M_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH3_BUS_100M_ENABLE_DATA, MAIN_ICG_EN_PERIPH3_BUS_100M_EN_SHIFT, MAIN_ICG_EN_PERIPH3_BUS_100M_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_PERIPH3_BUS_100M_ 			itg_set_reg(MAIN_ICG_EN_PERIPH3_BUS_100M_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH3_BUS_100M_DISABLE_DATA, MAIN_ICG_EN_PERIPH3_BUS_100M_EN_SHIFT, MAIN_ICG_EN_PERIPH3_BUS_100M_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PERIPH3_BUS_100M_ 		itg_get_reg(MAIN_ICG_EN_PERIPH3_BUS_100M_CTRL_REG_ADDR, MAIN_ICG_EN_PERIPH3_BUS_100M_EN_SHIFT, MAIN_ICG_EN_PERIPH3_BUS_100M_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_PERIPH3_BUS_100M_(x) 		itg_set_reg(MAIN_ICG_EN_PERIPH3_BUS_100M_CTRL_REG_ADDR, x, MAIN_ICG_EN_PERIPH3_BUS_100M_EN_SHIFT, MAIN_ICG_EN_PERIPH3_BUS_100M_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_CLK_CRG_SECURE_I_ 			itg_set_reg(MAIN_ICG_EN_CLK_CRG_SECURE_I_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_CRG_SECURE_I_ENABLE_DATA, MAIN_ICG_EN_CLK_CRG_SECURE_I_EN_SHIFT, MAIN_ICG_EN_CLK_CRG_SECURE_I_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_CLK_CRG_SECURE_I_ 			itg_set_reg(MAIN_ICG_EN_CLK_CRG_SECURE_I_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_CRG_SECURE_I_DISABLE_DATA, MAIN_ICG_EN_CLK_CRG_SECURE_I_EN_SHIFT, MAIN_ICG_EN_CLK_CRG_SECURE_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_CRG_SECURE_I_ 		itg_get_reg(MAIN_ICG_EN_CLK_CRG_SECURE_I_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_CRG_SECURE_I_EN_SHIFT, MAIN_ICG_EN_CLK_CRG_SECURE_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_CRG_SECURE_I_(x) 		itg_set_reg(MAIN_ICG_EN_CLK_CRG_SECURE_I_CTRL_REG_ADDR, x, MAIN_ICG_EN_CLK_CRG_SECURE_I_EN_SHIFT, MAIN_ICG_EN_CLK_CRG_SECURE_I_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_GMAC0_CLK_RMII_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC0_CLK_RMII_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC0_CLK_RMII_I_ENABLE_DATA, MAIN_ICG_EN_GMAC0_CLK_RMII_I_EN_SHIFT, MAIN_ICG_EN_GMAC0_CLK_RMII_I_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_GMAC0_CLK_RMII_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC0_CLK_RMII_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC0_CLK_RMII_I_DISABLE_DATA, MAIN_ICG_EN_GMAC0_CLK_RMII_I_EN_SHIFT, MAIN_ICG_EN_GMAC0_CLK_RMII_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC0_CLK_RMII_I_ 		itg_get_reg(MAIN_ICG_EN_GMAC0_CLK_RMII_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC0_CLK_RMII_I_EN_SHIFT, MAIN_ICG_EN_GMAC0_CLK_RMII_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC0_CLK_RMII_I_(x) 		itg_set_reg(MAIN_ICG_EN_GMAC0_CLK_RMII_I_CTRL_REG_ADDR, x, MAIN_ICG_EN_GMAC0_CLK_RMII_I_EN_SHIFT, MAIN_ICG_EN_GMAC0_CLK_RMII_I_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_GMAC1_CLK_RMII_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_RMII_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_RMII_I_ENABLE_DATA, MAIN_ICG_EN_GMAC1_CLK_RMII_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_RMII_I_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_GMAC1_CLK_RMII_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_RMII_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_RMII_I_DISABLE_DATA, MAIN_ICG_EN_GMAC1_CLK_RMII_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_RMII_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC1_CLK_RMII_I_ 		itg_get_reg(MAIN_ICG_EN_GMAC1_CLK_RMII_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_RMII_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_RMII_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC1_CLK_RMII_I_(x) 		itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_RMII_I_CTRL_REG_ADDR, x, MAIN_ICG_EN_GMAC1_CLK_RMII_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_RMII_I_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_GMAC0_CLK_AXI_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC0_CLK_AXI_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC0_CLK_AXI_I_ENABLE_DATA, MAIN_ICG_EN_GMAC0_CLK_AXI_I_EN_SHIFT, MAIN_ICG_EN_GMAC0_CLK_AXI_I_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_GMAC0_CLK_AXI_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC0_CLK_AXI_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC0_CLK_AXI_I_DISABLE_DATA, MAIN_ICG_EN_GMAC0_CLK_AXI_I_EN_SHIFT, MAIN_ICG_EN_GMAC0_CLK_AXI_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC0_CLK_AXI_I_ 		itg_get_reg(MAIN_ICG_EN_GMAC0_CLK_AXI_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC0_CLK_AXI_I_EN_SHIFT, MAIN_ICG_EN_GMAC0_CLK_AXI_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC0_CLK_AXI_I_(x) 		itg_set_reg(MAIN_ICG_EN_GMAC0_CLK_AXI_I_CTRL_REG_ADDR, x, MAIN_ICG_EN_GMAC0_CLK_AXI_I_EN_SHIFT, MAIN_ICG_EN_GMAC0_CLK_AXI_I_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_GMAC1_CLK_AXI_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_AXI_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_AXI_I_ENABLE_DATA, MAIN_ICG_EN_GMAC1_CLK_AXI_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_AXI_I_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_GMAC1_CLK_AXI_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_AXI_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_AXI_I_DISABLE_DATA, MAIN_ICG_EN_GMAC1_CLK_AXI_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_AXI_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC1_CLK_AXI_I_ 		itg_get_reg(MAIN_ICG_EN_GMAC1_CLK_AXI_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_AXI_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_AXI_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC1_CLK_AXI_I_(x) 		itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_AXI_I_CTRL_REG_ADDR, x, MAIN_ICG_EN_GMAC1_CLK_AXI_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_AXI_I_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_CLK_PECI0_I_ 			itg_set_reg(MAIN_ICG_EN_CLK_PECI0_I_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_PECI0_I_ENABLE_DATA, MAIN_ICG_EN_CLK_PECI0_I_EN_SHIFT, MAIN_ICG_EN_CLK_PECI0_I_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_CLK_PECI0_I_ 			itg_set_reg(MAIN_ICG_EN_CLK_PECI0_I_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_PECI0_I_DISABLE_DATA, MAIN_ICG_EN_CLK_PECI0_I_EN_SHIFT, MAIN_ICG_EN_CLK_PECI0_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_PECI0_I_ 		itg_get_reg(MAIN_ICG_EN_CLK_PECI0_I_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_PECI0_I_EN_SHIFT, MAIN_ICG_EN_CLK_PECI0_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_PECI0_I_(x) 		itg_set_reg(MAIN_ICG_EN_CLK_PECI0_I_CTRL_REG_ADDR, x, MAIN_ICG_EN_CLK_PECI0_I_EN_SHIFT, MAIN_ICG_EN_CLK_PECI0_I_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_CLK_APB_GMAC0_ 			itg_set_reg(MAIN_ICG_EN_CLK_APB_GMAC0_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_GMAC0_ENABLE_DATA, MAIN_ICG_EN_CLK_APB_GMAC0_EN_SHIFT, MAIN_ICG_EN_CLK_APB_GMAC0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_CLK_APB_GMAC0_ 			itg_set_reg(MAIN_ICG_EN_CLK_APB_GMAC0_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_GMAC0_DISABLE_DATA, MAIN_ICG_EN_CLK_APB_GMAC0_EN_SHIFT, MAIN_ICG_EN_CLK_APB_GMAC0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_APB_GMAC0_ 		itg_get_reg(MAIN_ICG_EN_CLK_APB_GMAC0_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_GMAC0_EN_SHIFT, MAIN_ICG_EN_CLK_APB_GMAC0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_APB_GMAC0_(x) 		itg_set_reg(MAIN_ICG_EN_CLK_APB_GMAC0_CTRL_REG_ADDR, x, MAIN_ICG_EN_CLK_APB_GMAC0_EN_SHIFT, MAIN_ICG_EN_CLK_APB_GMAC0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_CLK_APB_GMAC1_ 			itg_set_reg(MAIN_ICG_EN_CLK_APB_GMAC1_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_GMAC1_ENABLE_DATA, MAIN_ICG_EN_CLK_APB_GMAC1_EN_SHIFT, MAIN_ICG_EN_CLK_APB_GMAC1_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_CLK_APB_GMAC1_ 			itg_set_reg(MAIN_ICG_EN_CLK_APB_GMAC1_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_GMAC1_DISABLE_DATA, MAIN_ICG_EN_CLK_APB_GMAC1_EN_SHIFT, MAIN_ICG_EN_CLK_APB_GMAC1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_APB_GMAC1_ 		itg_get_reg(MAIN_ICG_EN_CLK_APB_GMAC1_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_GMAC1_EN_SHIFT, MAIN_ICG_EN_CLK_APB_GMAC1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_APB_GMAC1_(x) 		itg_set_reg(MAIN_ICG_EN_CLK_APB_GMAC1_CTRL_REG_ADDR, x, MAIN_ICG_EN_CLK_APB_GMAC1_EN_SHIFT, MAIN_ICG_EN_CLK_APB_GMAC1_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_CLK_APB_PECI0_ 			itg_set_reg(MAIN_ICG_EN_CLK_APB_PECI0_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_PECI0_ENABLE_DATA, MAIN_ICG_EN_CLK_APB_PECI0_EN_SHIFT, MAIN_ICG_EN_CLK_APB_PECI0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_CLK_APB_PECI0_ 			itg_set_reg(MAIN_ICG_EN_CLK_APB_PECI0_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_PECI0_DISABLE_DATA, MAIN_ICG_EN_CLK_APB_PECI0_EN_SHIFT, MAIN_ICG_EN_CLK_APB_PECI0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_APB_PECI0_ 		itg_get_reg(MAIN_ICG_EN_CLK_APB_PECI0_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_PECI0_EN_SHIFT, MAIN_ICG_EN_CLK_APB_PECI0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_APB_PECI0_(x) 		itg_set_reg(MAIN_ICG_EN_CLK_APB_PECI0_CTRL_REG_ADDR, x, MAIN_ICG_EN_CLK_APB_PECI0_EN_SHIFT, MAIN_ICG_EN_CLK_APB_PECI0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_CLK_APB_SENSORS_PD_ 			itg_set_reg(MAIN_ICG_EN_CLK_APB_SENSORS_PD_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_SENSORS_PD_ENABLE_DATA, MAIN_ICG_EN_CLK_APB_SENSORS_PD_EN_SHIFT, MAIN_ICG_EN_CLK_APB_SENSORS_PD_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_CLK_APB_SENSORS_PD_ 			itg_set_reg(MAIN_ICG_EN_CLK_APB_SENSORS_PD_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_SENSORS_PD_DISABLE_DATA, MAIN_ICG_EN_CLK_APB_SENSORS_PD_EN_SHIFT, MAIN_ICG_EN_CLK_APB_SENSORS_PD_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_APB_SENSORS_PD_ 		itg_get_reg(MAIN_ICG_EN_CLK_APB_SENSORS_PD_CTRL_REG_ADDR, MAIN_ICG_EN_CLK_APB_SENSORS_PD_EN_SHIFT, MAIN_ICG_EN_CLK_APB_SENSORS_PD_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CLK_APB_SENSORS_PD_(x) 		itg_set_reg(MAIN_ICG_EN_CLK_APB_SENSORS_PD_CTRL_REG_ADDR, x, MAIN_ICG_EN_CLK_APB_SENSORS_PD_EN_SHIFT, MAIN_ICG_EN_CLK_APB_SENSORS_PD_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_GMAC1_CLK_RX_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_RX_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_RX_I_ENABLE_DATA, MAIN_ICG_EN_GMAC1_CLK_RX_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_RX_I_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_GMAC1_CLK_RX_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_RX_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_RX_I_DISABLE_DATA, MAIN_ICG_EN_GMAC1_CLK_RX_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_RX_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC1_CLK_RX_I_ 		itg_get_reg(MAIN_ICG_EN_GMAC1_CLK_RX_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_RX_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_RX_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC1_CLK_RX_I_(x) 		itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_RX_I_CTRL_REG_ADDR, x, MAIN_ICG_EN_GMAC1_CLK_RX_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_RX_I_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_GMAC1_CLK_TX_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_TX_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_TX_I_ENABLE_DATA, MAIN_ICG_EN_GMAC1_CLK_TX_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_TX_I_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_GMAC1_CLK_TX_I_ 			itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_TX_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_TX_I_DISABLE_DATA, MAIN_ICG_EN_GMAC1_CLK_TX_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_TX_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC1_CLK_TX_I_ 		itg_get_reg(MAIN_ICG_EN_GMAC1_CLK_TX_I_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC1_CLK_TX_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_TX_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC1_CLK_TX_I_(x) 		itg_set_reg(MAIN_ICG_EN_GMAC1_CLK_TX_I_CTRL_REG_ADDR, x, MAIN_ICG_EN_GMAC1_CLK_TX_I_EN_SHIFT, MAIN_ICG_EN_GMAC1_CLK_TX_I_EN_MASK)


#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_GMAC0_ 	itg_get_reg(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC0_SHIFT, MAIN_RSTN_GMAC0_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_GMAC0_ 	itg_assert_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC0_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_GMAC0_ 	itg_clear_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC0_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_GMAC1_ 	itg_get_reg(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC1_SHIFT, MAIN_RSTN_GMAC1_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_GMAC1_ 	itg_assert_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC1_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_GMAC1_ 	itg_clear_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC1_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_PECI_ 	itg_get_reg(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PECI_SHIFT, MAIN_RSTN_PECI_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_PECI_ 	itg_assert_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PECI_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_PECI_ 	itg_clear_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PECI_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_DWC_SENSORS_PD_ 	itg_get_reg(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DWC_SENSORS_PD_SHIFT, MAIN_RSTN_DWC_SENSORS_PD_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_DWC_SENSORS_PD_ 	itg_assert_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DWC_SENSORS_PD_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_DWC_SENSORS_PD_ 	itg_clear_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DWC_SENSORS_PD_MASK)
// #define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_NCNOC_ 	itg_get_reg(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_NCNOC_SHIFT, MAIN_RSTN_NCNOC_MASK)
// #define _ASSERT_RESET_RSTGEN_MAIN_RSTN_NCNOC_ 	itg_assert_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_NCNOC_MASK)
// #define _CLEAR_RESET_RSTGEN_MAIN_RSTN_NCNOC_ 	itg_clear_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_NCNOC_MASK)
#define _READ_RESET_STATUS_RSTGEN_RST_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_ 	itg_get_reg(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_SHIFT, RST_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_MASK)
#define _ASSERT_RESET_RSTGEN_RST_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_ 	itg_assert_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_MASK)
#define _CLEAR_RESET_RSTGEN_RST_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_ 	itg_clear_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_NCNOC_BMCPERIPH3_RSTN_CRG_SECURE_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_IOMUX_ 	itg_get_reg(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_IOMUX_SHIFT, MAIN_RSTN_IOMUX_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_IOMUX_ 	itg_assert_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_IOMUX_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_IOMUX_ 	itg_clear_rst(PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, PERIPH3_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_IOMUX_MASK)


#endif //_PERIPH3_CRG_MACRO_H_
