#define PERIPH3_SECURE_SYSCONITG__SYSCFG_0_ADDR            (U0_PERIPH3_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define U11_DWC_SENSORS_PD_WR_LOCK_WIDTH                   0x1U
#define U11_DWC_SENSORS_PD_WR_LOCK_SHIFT                   0x0U
#define U11_DWC_SENSORS_PD_WR_LOCK_MASK                    0x1U
#define GET_U11_DWC_SENSORS_PD_WR_LOCK                     itg_get_reg(PERIPH3_SECURE_SYSCONITG__SYSCFG_0_ADDR,U11_DWC_SENSORS_PD_WR_LOCK_SHIFT,U11_DWC_SENSORS_PD_WR_LOCK_MASK)
#define SET_U11_DWC_SENSORS_PD_WR_LOCK(data)               itg_set_reg(PERIPH3_SECURE_SYSCONITG__SYSCFG_0_ADDR,data,U11_DWC_SENSORS_PD_WR_LOCK_SHIFT,U11_DWC_SENSORS_PD_WR_LOCK_MASK)
