#define PERIPH3_SYSCONITG__SYSCFG_0_ADDR                   (U0_PERIPH3_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0__WIDTH     0x20U
#define U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0__SHIFT     0x0U
#define U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0__MASK      0xFFFFFFFFU
#define PERIPH3_SYSCONITG__SYSCFG_4_ADDR                   (U0_PERIPH3_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32__WIDTH    0x20U
#define U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32__SHIFT    0x0U
#define U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32__MASK     0xFFFFFFFFU
#define PERIPH3_SYSCONITG__SYSCFG_8_ADDR                   (U0_PERIPH3_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_31_0__WIDTH      0x20U
#define U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_31_0__SHIFT      0x0U
#define U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_31_0__MASK       0xFFFFFFFFU
#define PERIPH3_SYSCONITG__SYSCFG_12_ADDR                  (U0_PERIPH3_SYSCON__ITG_BD_APBS__BASE_ADDR + 0xcU)
#define U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_63_32__WIDTH     0x20U
#define U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_63_32__SHIFT     0x0U
#define U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_63_32__MASK      0xFFFFFFFFU
#define PERIPH3_SYSCONITG__SYSCFG_16_ADDR                  (U0_PERIPH3_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define U0_DWC_ETHER_SGMII_PHY_INTF_SEL_I_WIDTH            0x4U
#define U0_DWC_ETHER_SGMII_PHY_INTF_SEL_I_SHIFT            0x0U
#define U0_DWC_ETHER_SGMII_PHY_INTF_SEL_I_MASK             0xFU
#define U0_DWC_ETHER_RMII_PHY_INTF_SEL_I_WIDTH             0x4U
#define U0_DWC_ETHER_RMII_PHY_INTF_SEL_I_SHIFT             0x4U
#define U0_DWC_ETHER_RMII_PHY_INTF_SEL_I_MASK              0xF0U
#define U0_DWC_ETHER_SGMII_MAC_SPEED_O_WIDTH               0x2U
#define U0_DWC_ETHER_SGMII_MAC_SPEED_O_SHIFT               0x8U
#define U0_DWC_ETHER_SGMII_MAC_SPEED_O_MASK                0x300U
#define U0_DWC_ETHER_RMII_MAC_SPEED_O_WIDTH                0x2U
#define U0_DWC_ETHER_RMII_MAC_SPEED_O_SHIFT                0xCU
#define U0_DWC_ETHER_RMII_MAC_SPEED_O_MASK                 0x3000U
#define GET_U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0_       itg_get_reg(PERIPH3_SYSCONITG__SYSCFG_0_ADDR,U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0__SHIFT,U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0__MASK)
#define GET_U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32_      itg_get_reg(PERIPH3_SYSCONITG__SYSCFG_4_ADDR,U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32__SHIFT,U0_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32__MASK)
#define GET_U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_31_0_        itg_get_reg(PERIPH3_SYSCONITG__SYSCFG_8_ADDR,U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_31_0__SHIFT,U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_31_0__MASK)
#define GET_U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_63_32_       itg_get_reg(PERIPH3_SYSCONITG__SYSCFG_12_ADDR,U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_63_32__SHIFT,U0_DWC_ETHER_RMII_PTP_TIMESTAMP_O_63_32__MASK)
#define GET_U0_DWC_ETHER_SGMII_PHY_INTF_SEL_I              itg_get_reg(PERIPH3_SYSCONITG__SYSCFG_16_ADDR,U0_DWC_ETHER_SGMII_PHY_INTF_SEL_I_SHIFT,U0_DWC_ETHER_SGMII_PHY_INTF_SEL_I_MASK)
#define SET_U0_DWC_ETHER_SGMII_PHY_INTF_SEL_I(data)        itg_set_reg(PERIPH3_SYSCONITG__SYSCFG_16_ADDR,data,U0_DWC_ETHER_SGMII_PHY_INTF_SEL_I_SHIFT,U0_DWC_ETHER_SGMII_PHY_INTF_SEL_I_MASK)
#define GET_U0_DWC_ETHER_RMII_PHY_INTF_SEL_I               itg_get_reg(PERIPH3_SYSCONITG__SYSCFG_16_ADDR,U0_DWC_ETHER_RMII_PHY_INTF_SEL_I_SHIFT,U0_DWC_ETHER_RMII_PHY_INTF_SEL_I_MASK)
#define SET_U0_DWC_ETHER_RMII_PHY_INTF_SEL_I(data)         itg_set_reg(PERIPH3_SYSCONITG__SYSCFG_16_ADDR,data,U0_DWC_ETHER_RMII_PHY_INTF_SEL_I_SHIFT,U0_DWC_ETHER_RMII_PHY_INTF_SEL_I_MASK)
#define GET_U0_DWC_ETHER_SGMII_MAC_SPEED_O                 itg_get_reg(PERIPH3_SYSCONITG__SYSCFG_16_ADDR,U0_DWC_ETHER_SGMII_MAC_SPEED_O_SHIFT,U0_DWC_ETHER_SGMII_MAC_SPEED_O_MASK)
#define GET_U0_DWC_ETHER_RMII_MAC_SPEED_O                  itg_get_reg(PERIPH3_SYSCONITG__SYSCFG_16_ADDR,U0_DWC_ETHER_RMII_MAC_SPEED_O_SHIFT,U0_DWC_ETHER_RMII_MAC_SPEED_O_MASK)
