# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2022 StarFive Technology Co., Ltd.

obj-y += board.o
obj-y += starfive-jhb100.o
obj-$(CONFIG_STARFIVE_JHB100_SAFE_MTEST) += safe_mtest.o
obj-$(CONFIG_SPL_BUILD) += spl.o
