#include <asm/arch/saif_init.h>

void u0_dwc_ssi_sfc_enable(void){
	SET_U0_BMCPERIPH1_IOMUX_FUNC5_SEL(1);
	SET_U0_BMCPERIPH1_IOMUX_FUNC6_SEL(1);
	SET_U0_BMCPERIPH1_IOMUX_FUNC7_SEL(1);
	SET_U0_BMCPERIPH1_IOMUX_FUNC8_SEL(1);
	SET_U0_BMCPERIPH1_IOMUX_FUNC9_SEL(1);
	SET_U0_BMCPERIPH1_IOMUX_FUNC10_SEL(1);
	SET_U0_BMCPERIPH1_IOMUX_FUNC11_SEL(1);

	_ENABLE_CLOCK_MAIN_ICG_EN_SFC0_;
	_ENABLE_CLOCK_CLK_U0_DWC_SSI_SFC_SSI_CLK_;
	_ENABLE_CLOCK_CLK_U0_DWC_SSI_SFC_HCLK_;
	_CLEAR_RESET_RSTGEN_MAIN_RSTN_SFC0_;
}

void u6_dwc_i2c_smbus_enable(void){
	SET_U0_BMCPERIPH0_GPIO_IOMUX_FUNC12_SEL(1);
	SET_U0_BMCPERIPH0_GPIO_IOMUX_FUNC13_SEL(1);

	_ENABLE_CLOCK_MAIN_ICG_EN_I2C6_;
	_ENABLE_CLOCK_CLK_GRP_100_APB_I2C_I2C6_;
	_ENABLE_CLOCK_CLK_GRP_100_APB_I2CF_I2CF6_;
	_ENABLE_CLOCK_CLK_CORE_I2C6_;
	_CLEAR_RESET_RSTGEN_MAIN_RSTN_I2C6_;
}

void u0_dwc_ether_rmiiandrgmii_enable_patch(void){ /* Get from baremetal - different from bitfile 014 */
		_ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_;
		_ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_;
		_ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_;
		_ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_;
		_ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_;
		_ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_;
		_ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_;
		_ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_;
		_CLEAR_RESET_RSTGEN_MAIN_RSTN_GMAC2_;
		// _CLEAR_RESET_RSTGEN_RSTN_U0_DWC_ETHER_RMIIANDRGMII_ARESETN_I_;
}

void u0_dwc_ether_rmiiandrgmii_disable_patch(void){ /* Get from baremetal - different from bitfile 014 */
	_ASSERT_RESET_RSTGEN_MAIN_RSTN_GMAC2_;
  // _ASSERT_RESET_RSTGEN_RSTN_U0_DWC_ETHER_RMIIANDRGMII_ARESETN_I_;
	_DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_;
	_DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_;
	_DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_;
	_DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_;
	_DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_;
	_DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_;
	_DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_;
	_DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_;
}
