#define  U0_SYS0_CRG__ITG_BD_APBS__BASE_ADDR                                                                  0x0013000000
#define  U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR                                                                  0x0013004000
#define  U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR                                                                  0x0013008000
#define  U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR                                                               0x0013010000
#define  U0_RESOURCE_ARB__ITG_BD_APB__BASE_ADDR                                                               0x0013012000
#define  U0_SYS1_SYSCON__ITG_BD_APBS__BASE_ADDR                                                               0x0013014000
#define  U0_SYS2_SYSCON__ITG_BD_APBS__BASE_ADDR                                                               0x0013018000
#define  U1_STRAP__ITG_BD_APBS__BASE_ADDR                                                                     0x001301A000
#define  U3_DWC_SENSORS_TSPD__ITG_BD_APBS__BASE_ADDR                                                          0x0013020000
#define  U0_SYS0_IOMUX__ITG_BD_APBS__BASE_ADDR                                                                0x0013080000
#define  U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR                                                               0x0013080800
#define  U0_SYS1_IOMUX__ITG_BD_APBS__BASE_ADDR                                                                0x0013081000
#define  U0_SYS2_IOMUX__ITG_BD_APBS__BASE_ADDR                                                                0x0013082000
#define  U0_SYS2SEC_IOMUX__ITG_BD_APBS__BASE_ADDR                                                             0x0013083000
#define  U0_JTAG_MST_WRAP__ITG_BD_AHB__BASE_ADDR                                                              0x00130C0000
#define  U0_JTAG_MST_WRAP__ITG_BD_APB__BASE_ADDR                                                              0x00130C0400
#define  U1_JTAG_MST_WRAP__ITG_BD_AHB__BASE_ADDR                                                              0x00130C0800
#define  U1_JTAG_MST_WRAP__ITG_BD_APB__BASE_ADDR                                                              0x00130C0C00
#define  U0_SIM_APB__ITG_BD_APB__BASE_ADDR                                                                    0x00130C1000
#define  U0_DEBUG_SUBSYS_RELEASE__ITG_BD_AXI_EC_DATA__BASE_ADDR                                               0x00130C1400
#define  U0_DEBUG_SUBSYS_RELEASE__ITG_BD_APB_JTAG_CERTIFICATION__BASE_ADDR                                    0x00130C1800
#define  U0_DEBUG_SUBSYS_RELEASE__ITG_BD_APB_EC_CFG__BASE_ADDR                                                0x00130E0000
#define  U6_PCU__ITG_BD_APB__BASE_ADDR                                                                        0x00140A0000
#define  U8_PCU__ITG_BD_APB__BASE_ADDR                                                                        0x00140A2000
#define  U4_PCU__ITG_BD_APB__BASE_ADDR                                                                        0x00140A2400
#define  U0_PCU__ITG_BD_APB__BASE_ADDR                                                                        0x00140A2800
#define  U2_PCU__ITG_BD_APB__BASE_ADDR                                                                        0x00140A2C00
#define  U9_PCU__ITG_BD_APB__BASE_ADDR                                                                        0x00140A3000
#define  U5_PCU__ITG_BD_APB__BASE_ADDR                                                                        0x00140A3400
#define  U1_PCU__ITG_BD_APB__BASE_ADDR                                                                        0x00140A3800
#define  U3_PCU__ITG_BD_APB__BASE_ADDR                                                                        0x00140A3C00
#define  U7_PCU__ITG_BD_APB__BASE_ADDR                                                                        0x00140A4000
#define  U10_PCU__ITG_BD_APB__BASE_ADDR                                                                       0x00140A4400
#define  U11_PCU__ITG_BD_APB__BASE_ADDR                                                                       0x00140A4800
#define  U0_BCU__ITG_BD_APB__BASE_ADDR                                                                        0x00140A8000
#define  U0_SYS0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR                                                           0x0014100000
#define  U0_SYS1_SECURE_CRG__ITG_BD_APBS__BASE_ADDR                                                           0x0014104000
#define  U0_SYS2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR                                                           0x0014108000
#define  U0_SYS0_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR                                                        0x0014110000
#define  U0_SYS0_SECURE_IPREG_TOP__ITG_BD_APBS__BASE_ADDR                                                     0x0014112000
#define  U0_SYS1_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR                                                        0x0014114000
#define  U0_SYS2_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR                                                        0x0014118000
#define  U1_STRAP__ITG_BD_APBS_SECURE__BASE_ADDR                                                              0x001411A000
#define  U0_DOM_DDRSS__ITG_BD_AXI0_CACHEABLE__BASE_ADDR                                                       0x0040000000
#define  U0_DOM_DDRSS__ITG_BD_AXI1_CACHEABLE__BASE_ADDR                                                       0x0040000000
#define  U0_DOM_DDRSS__ITG_BD_AXI2_CACHEABLE__BASE_ADDR                                                       0x0040000000
#define  U0_DOM_DDRSS__ITG_BD_AXI3_CACHEABLE__BASE_ADDR                                                       0x0040000000
#define  U0_DOM_DDRSS__ITG_BD_AXI0_UNCACHEABLE__BASE_ADDR                                                     0x0400000000
#define  U0_DOM_DDRSS__ITG_BD_AXI1_UNCACHEABLE__BASE_ADDR                                                     0x0400000000
#define  U0_DOM_DDRSS__ITG_BD_AXI2_UNCACHEABLE__BASE_ADDR                                                     0x0400000000
#define  U0_DOM_DDRSS__ITG_BD_AXI3_UNCACHEABLE__BASE_ADDR                                                     0x0400000000


#define  U0_SYS0_CRG__ITG_BD_APBS__END_ADDR                                                                   0x0013003FFF
#define  U0_SYS1_CRG__ITG_BD_APBS__END_ADDR                                                                   0x0013007FFF
#define  U0_SYS2_CRG__ITG_BD_APBS__END_ADDR                                                                   0x001300BFFF
#define  U0_SYS0_SYSCON__ITG_BD_APBS__END_ADDR                                                                0x0013011FFF
#define  U0_RESOURCE_ARB__ITG_BD_APB__END_ADDR                                                                0x0013013FFF
#define  U0_SYS1_SYSCON__ITG_BD_APBS__END_ADDR                                                                0x0013017FFF
#define  U0_SYS2_SYSCON__ITG_BD_APBS__END_ADDR                                                                0x0013019FFF
#define  U1_STRAP__ITG_BD_APBS__END_ADDR                                                                      0x001301BFFF
#define  U3_DWC_SENSORS_TSPD__ITG_BD_APBS__END_ADDR                                                           0x0013023FFF
#define  U0_SYS0_IOMUX__ITG_BD_APBS__END_ADDR                                                                 0x00130807FF
#define  U0_SYS0H_IOMUX__ITG_BD_APBS__END_ADDR                                                                0x0013080FFF
#define  U0_SYS1_IOMUX__ITG_BD_APBS__END_ADDR                                                                 0x0013081FFF
#define  U0_SYS2_IOMUX__ITG_BD_APBS__END_ADDR                                                                 0x0013082FFF
#define  U0_SYS2SEC_IOMUX__ITG_BD_APBS__END_ADDR                                                              0x0013083FFF
#define  U0_JTAG_MST_WRAP__ITG_BD_AHB__END_ADDR                                                               0x00130C03FF
#define  U0_JTAG_MST_WRAP__ITG_BD_APB__END_ADDR                                                               0x00130C07FF
#define  U1_JTAG_MST_WRAP__ITG_BD_AHB__END_ADDR                                                               0x00130C0BFF
#define  U1_JTAG_MST_WRAP__ITG_BD_APB__END_ADDR                                                               0x00130C0FFF
#define  U0_SIM_APB__ITG_BD_APB__END_ADDR                                                                     0x00130C13FF
#define  U0_DEBUG_SUBSYS_RELEASE__ITG_BD_AXI_EC_DATA__END_ADDR                                                0x00130C17FF
#define  U0_DEBUG_SUBSYS_RELEASE__ITG_BD_APB_JTAG_CERTIFICATION__END_ADDR                                     0x00130C1BFF
#define  U0_DEBUG_SUBSYS_RELEASE__ITG_BD_APB_EC_CFG__END_ADDR                                                 0x00130E4FFF
#define  U6_PCU__ITG_BD_APB__END_ADDR                                                                         0x00140A1FFF
#define  U8_PCU__ITG_BD_APB__END_ADDR                                                                         0x00140A23FF
#define  U4_PCU__ITG_BD_APB__END_ADDR                                                                         0x00140A27FF
#define  U0_PCU__ITG_BD_APB__END_ADDR                                                                         0x00140A2BFF
#define  U2_PCU__ITG_BD_APB__END_ADDR                                                                         0x00140A2FFF
#define  U9_PCU__ITG_BD_APB__END_ADDR                                                                         0x00140A33FF
#define  U5_PCU__ITG_BD_APB__END_ADDR                                                                         0x00140A37FF
#define  U1_PCU__ITG_BD_APB__END_ADDR                                                                         0x00140A3BFF
#define  U3_PCU__ITG_BD_APB__END_ADDR                                                                         0x00140A3FFF
#define  U7_PCU__ITG_BD_APB__END_ADDR                                                                         0x00140A43FF
#define  U10_PCU__ITG_BD_APB__END_ADDR                                                                        0x00140A47FF
#define  U11_PCU__ITG_BD_APB__END_ADDR                                                                        0x00140A4BFF
#define  U0_BCU__ITG_BD_APB__END_ADDR                                                                         0x00140A83FF
#define  U0_SYS0_SECURE_CRG__ITG_BD_APBS__END_ADDR                                                            0x0014103FFF
#define  U0_SYS1_SECURE_CRG__ITG_BD_APBS__END_ADDR                                                            0x0014107FFF
#define  U0_SYS2_SECURE_CRG__ITG_BD_APBS__END_ADDR                                                            0x001410BFFF
#define  U0_SYS0_SECURE_SYSCON__ITG_BD_APBS__END_ADDR                                                         0x0014111FFF
#define  U0_SYS0_SECURE_IPREG_TOP__ITG_BD_APBS__END_ADDR                                                      0x0014113FFF
#define  U0_SYS1_SECURE_SYSCON__ITG_BD_APBS__END_ADDR                                                         0x0014117FFF
#define  U0_SYS2_SECURE_SYSCON__ITG_BD_APBS__END_ADDR                                                         0x0014119FFF
#define  U1_STRAP__ITG_BD_APBS_SECURE__END_ADDR                                                               0x001411BFFF
#define  U0_DOM_DDRSS__ITG_BD_AXI0_CACHEABLE__END_ADDR                                                        0x023FFFFFFF
#define  U0_DOM_DDRSS__ITG_BD_AXI1_CACHEABLE__END_ADDR                                                        0x023FFFFFFF
#define  U0_DOM_DDRSS__ITG_BD_AXI2_CACHEABLE__END_ADDR                                                        0x023FFFFFFF
#define  U0_DOM_DDRSS__ITG_BD_AXI3_CACHEABLE__END_ADDR                                                        0x023FFFFFFF
#define  U0_DOM_DDRSS__ITG_BD_AXI0_UNCACHEABLE__END_ADDR                                                      0x05FFFFFFFF
#define  U0_DOM_DDRSS__ITG_BD_AXI1_UNCACHEABLE__END_ADDR                                                      0x05FFFFFFFF
#define  U0_DOM_DDRSS__ITG_BD_AXI2_UNCACHEABLE__END_ADDR                                                      0x05FFFFFFFF
#define  U0_DOM_DDRSS__ITG_BD_AXI3_UNCACHEABLE__END_ADDR                                                      0x05FFFFFFFF
