//commit:06b6362e (HEAD -> b0.8.1_dv, origin/b0.8.1_dv)
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR                (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define PADCFG_PAD_GPIO_A4_DS_WIDTH                        0x2U
#define PADCFG_PAD_GPIO_A4_DS_SHIFT                        0x0U
#define PADCFG_PAD_GPIO_A4_DS_MASK                         0x3U
#define PADCFG_PAD_GPIO_A4_IE_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A4_IE_SHIFT                        0x2U
#define PADCFG_PAD_GPIO_A4_IE_MASK                         0x4U
#define PADCFG_PAD_GPIO_A4_PD_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A4_PD_SHIFT                        0x3U
#define PADCFG_PAD_GPIO_A4_PD_MASK                         0x8U
#define PADCFG_PAD_GPIO_A4_PU_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A4_PU_SHIFT                        0x4U
#define PADCFG_PAD_GPIO_A4_PU_MASK                         0x10U
#define PADCFG_PAD_GPIO_A4_SLEW_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A4_SLEW_SHIFT                      0x5U
#define PADCFG_PAD_GPIO_A4_SLEW_MASK                       0x20U
#define PADCFG_PAD_GPIO_A4_SMT_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A4_SMT_SHIFT                       0x6U
#define PADCFG_PAD_GPIO_A4_SMT_MASK                        0x40U
#define PADCFG_PAD_GPIO_A4_DEBOUNCE_WIDTH                  0x11U
#define PADCFG_PAD_GPIO_A4_DEBOUNCE_SHIFT                  0xFU
#define PADCFG_PAD_GPIO_A4_DEBOUNCE_MASK                   0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR                (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define PADCFG_PAD_GPIO_A5_DS_WIDTH                        0x2U
#define PADCFG_PAD_GPIO_A5_DS_SHIFT                        0x0U
#define PADCFG_PAD_GPIO_A5_DS_MASK                         0x3U
#define PADCFG_PAD_GPIO_A5_IE_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A5_IE_SHIFT                        0x2U
#define PADCFG_PAD_GPIO_A5_IE_MASK                         0x4U
#define PADCFG_PAD_GPIO_A5_PD_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A5_PD_SHIFT                        0x3U
#define PADCFG_PAD_GPIO_A5_PD_MASK                         0x8U
#define PADCFG_PAD_GPIO_A5_PU_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A5_PU_SHIFT                        0x4U
#define PADCFG_PAD_GPIO_A5_PU_MASK                         0x10U
#define PADCFG_PAD_GPIO_A5_SLEW_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A5_SLEW_SHIFT                      0x5U
#define PADCFG_PAD_GPIO_A5_SLEW_MASK                       0x20U
#define PADCFG_PAD_GPIO_A5_SMT_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A5_SMT_SHIFT                       0x6U
#define PADCFG_PAD_GPIO_A5_SMT_MASK                        0x40U
#define PADCFG_PAD_GPIO_A5_DEBOUNCE_WIDTH                  0x11U
#define PADCFG_PAD_GPIO_A5_DEBOUNCE_SHIFT                  0xFU
#define PADCFG_PAD_GPIO_A5_DEBOUNCE_MASK                   0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR                (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define PADCFG_PAD_GPIO_A6_DS_WIDTH                        0x2U
#define PADCFG_PAD_GPIO_A6_DS_SHIFT                        0x0U
#define PADCFG_PAD_GPIO_A6_DS_MASK                         0x3U
#define PADCFG_PAD_GPIO_A6_IE_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A6_IE_SHIFT                        0x2U
#define PADCFG_PAD_GPIO_A6_IE_MASK                         0x4U
#define PADCFG_PAD_GPIO_A6_PD_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A6_PD_SHIFT                        0x3U
#define PADCFG_PAD_GPIO_A6_PD_MASK                         0x8U
#define PADCFG_PAD_GPIO_A6_PU_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A6_PU_SHIFT                        0x4U
#define PADCFG_PAD_GPIO_A6_PU_MASK                         0x10U
#define PADCFG_PAD_GPIO_A6_SLEW_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A6_SLEW_SHIFT                      0x5U
#define PADCFG_PAD_GPIO_A6_SLEW_MASK                       0x20U
#define PADCFG_PAD_GPIO_A6_SMT_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A6_SMT_SHIFT                       0x6U
#define PADCFG_PAD_GPIO_A6_SMT_MASK                        0x40U
#define PADCFG_PAD_GPIO_A6_DEBOUNCE_WIDTH                  0x11U
#define PADCFG_PAD_GPIO_A6_DEBOUNCE_SHIFT                  0xFU
#define PADCFG_PAD_GPIO_A6_DEBOUNCE_MASK                   0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0xcU)
#define PADCFG_PAD_GPIO_A7_DS_WIDTH                        0x2U
#define PADCFG_PAD_GPIO_A7_DS_SHIFT                        0x0U
#define PADCFG_PAD_GPIO_A7_DS_MASK                         0x3U
#define PADCFG_PAD_GPIO_A7_IE_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A7_IE_SHIFT                        0x2U
#define PADCFG_PAD_GPIO_A7_IE_MASK                         0x4U
#define PADCFG_PAD_GPIO_A7_PD_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A7_PD_SHIFT                        0x3U
#define PADCFG_PAD_GPIO_A7_PD_MASK                         0x8U
#define PADCFG_PAD_GPIO_A7_PU_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A7_PU_SHIFT                        0x4U
#define PADCFG_PAD_GPIO_A7_PU_MASK                         0x10U
#define PADCFG_PAD_GPIO_A7_SLEW_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A7_SLEW_SHIFT                      0x5U
#define PADCFG_PAD_GPIO_A7_SLEW_MASK                       0x20U
#define PADCFG_PAD_GPIO_A7_SMT_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A7_SMT_SHIFT                       0x6U
#define PADCFG_PAD_GPIO_A7_SMT_MASK                        0x40U
#define PADCFG_PAD_GPIO_A7_DEBOUNCE_WIDTH                  0x11U
#define PADCFG_PAD_GPIO_A7_DEBOUNCE_SHIFT                  0xFU
#define PADCFG_PAD_GPIO_A7_DEBOUNCE_MASK                   0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define PADCFG_PAD_GPIO_A8_DS_WIDTH                        0x2U
#define PADCFG_PAD_GPIO_A8_DS_SHIFT                        0x0U
#define PADCFG_PAD_GPIO_A8_DS_MASK                         0x3U
#define PADCFG_PAD_GPIO_A8_IE_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A8_IE_SHIFT                        0x2U
#define PADCFG_PAD_GPIO_A8_IE_MASK                         0x4U
#define PADCFG_PAD_GPIO_A8_PD_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A8_PD_SHIFT                        0x3U
#define PADCFG_PAD_GPIO_A8_PD_MASK                         0x8U
#define PADCFG_PAD_GPIO_A8_PU_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A8_PU_SHIFT                        0x4U
#define PADCFG_PAD_GPIO_A8_PU_MASK                         0x10U
#define PADCFG_PAD_GPIO_A8_SLEW_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A8_SLEW_SHIFT                      0x5U
#define PADCFG_PAD_GPIO_A8_SLEW_MASK                       0x20U
#define PADCFG_PAD_GPIO_A8_SMT_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A8_SMT_SHIFT                       0x6U
#define PADCFG_PAD_GPIO_A8_SMT_MASK                        0x40U
#define PADCFG_PAD_GPIO_A8_DEBOUNCE_WIDTH                  0x11U
#define PADCFG_PAD_GPIO_A8_DEBOUNCE_SHIFT                  0xFU
#define PADCFG_PAD_GPIO_A8_DEBOUNCE_MASK                   0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define PADCFG_PAD_GPIO_A9_DS_WIDTH                        0x2U
#define PADCFG_PAD_GPIO_A9_DS_SHIFT                        0x0U
#define PADCFG_PAD_GPIO_A9_DS_MASK                         0x3U
#define PADCFG_PAD_GPIO_A9_IE_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A9_IE_SHIFT                        0x2U
#define PADCFG_PAD_GPIO_A9_IE_MASK                         0x4U
#define PADCFG_PAD_GPIO_A9_PD_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A9_PD_SHIFT                        0x3U
#define PADCFG_PAD_GPIO_A9_PD_MASK                         0x8U
#define PADCFG_PAD_GPIO_A9_PU_WIDTH                        0x1U
#define PADCFG_PAD_GPIO_A9_PU_SHIFT                        0x4U
#define PADCFG_PAD_GPIO_A9_PU_MASK                         0x10U
#define PADCFG_PAD_GPIO_A9_SLEW_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A9_SLEW_SHIFT                      0x5U
#define PADCFG_PAD_GPIO_A9_SLEW_MASK                       0x20U
#define PADCFG_PAD_GPIO_A9_SMT_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A9_SMT_SHIFT                       0x6U
#define PADCFG_PAD_GPIO_A9_SMT_MASK                        0x40U
#define PADCFG_PAD_GPIO_A9_DEBOUNCE_WIDTH                  0x11U
#define PADCFG_PAD_GPIO_A9_DEBOUNCE_SHIFT                  0xFU
#define PADCFG_PAD_GPIO_A9_DEBOUNCE_MASK                   0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define PADCFG_PAD_GPIO_A10_DS_WIDTH                       0x2U
#define PADCFG_PAD_GPIO_A10_DS_SHIFT                       0x0U
#define PADCFG_PAD_GPIO_A10_DS_MASK                        0x3U
#define PADCFG_PAD_GPIO_A10_IE_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A10_IE_SHIFT                       0x2U
#define PADCFG_PAD_GPIO_A10_IE_MASK                        0x4U
#define PADCFG_PAD_GPIO_A10_PD_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A10_PD_SHIFT                       0x3U
#define PADCFG_PAD_GPIO_A10_PD_MASK                        0x8U
#define PADCFG_PAD_GPIO_A10_PU_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A10_PU_SHIFT                       0x4U
#define PADCFG_PAD_GPIO_A10_PU_MASK                        0x10U
#define PADCFG_PAD_GPIO_A10_SLEW_WIDTH                     0x1U
#define PADCFG_PAD_GPIO_A10_SLEW_SHIFT                     0x5U
#define PADCFG_PAD_GPIO_A10_SLEW_MASK                      0x20U
#define PADCFG_PAD_GPIO_A10_SMT_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A10_SMT_SHIFT                      0x6U
#define PADCFG_PAD_GPIO_A10_SMT_MASK                       0x40U
#define PADCFG_PAD_GPIO_A10_DEBOUNCE_WIDTH                 0x11U
#define PADCFG_PAD_GPIO_A10_DEBOUNCE_SHIFT                 0xFU
#define PADCFG_PAD_GPIO_A10_DEBOUNCE_MASK                  0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x1cU)
#define PADCFG_PAD_GPIO_A11_DS_WIDTH                       0x2U
#define PADCFG_PAD_GPIO_A11_DS_SHIFT                       0x0U
#define PADCFG_PAD_GPIO_A11_DS_MASK                        0x3U
#define PADCFG_PAD_GPIO_A11_IE_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A11_IE_SHIFT                       0x2U
#define PADCFG_PAD_GPIO_A11_IE_MASK                        0x4U
#define PADCFG_PAD_GPIO_A11_PD_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A11_PD_SHIFT                       0x3U
#define PADCFG_PAD_GPIO_A11_PD_MASK                        0x8U
#define PADCFG_PAD_GPIO_A11_PU_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A11_PU_SHIFT                       0x4U
#define PADCFG_PAD_GPIO_A11_PU_MASK                        0x10U
#define PADCFG_PAD_GPIO_A11_SLEW_WIDTH                     0x1U
#define PADCFG_PAD_GPIO_A11_SLEW_SHIFT                     0x5U
#define PADCFG_PAD_GPIO_A11_SLEW_MASK                      0x20U
#define PADCFG_PAD_GPIO_A11_SMT_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A11_SMT_SHIFT                      0x6U
#define PADCFG_PAD_GPIO_A11_SMT_MASK                       0x40U
#define PADCFG_PAD_GPIO_A11_DEBOUNCE_WIDTH                 0x11U
#define PADCFG_PAD_GPIO_A11_DEBOUNCE_SHIFT                 0xFU
#define PADCFG_PAD_GPIO_A11_DEBOUNCE_MASK                  0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x20U)
#define PADCFG_PAD_GPIO_A12_DS_WIDTH                       0x2U
#define PADCFG_PAD_GPIO_A12_DS_SHIFT                       0x0U
#define PADCFG_PAD_GPIO_A12_DS_MASK                        0x3U
#define PADCFG_PAD_GPIO_A12_IE_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A12_IE_SHIFT                       0x2U
#define PADCFG_PAD_GPIO_A12_IE_MASK                        0x4U
#define PADCFG_PAD_GPIO_A12_PD_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A12_PD_SHIFT                       0x3U
#define PADCFG_PAD_GPIO_A12_PD_MASK                        0x8U
#define PADCFG_PAD_GPIO_A12_PU_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A12_PU_SHIFT                       0x4U
#define PADCFG_PAD_GPIO_A12_PU_MASK                        0x10U
#define PADCFG_PAD_GPIO_A12_SLEW_WIDTH                     0x1U
#define PADCFG_PAD_GPIO_A12_SLEW_SHIFT                     0x5U
#define PADCFG_PAD_GPIO_A12_SLEW_MASK                      0x20U
#define PADCFG_PAD_GPIO_A12_SMT_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A12_SMT_SHIFT                      0x6U
#define PADCFG_PAD_GPIO_A12_SMT_MASK                       0x40U
#define PADCFG_PAD_GPIO_A12_DEBOUNCE_WIDTH                 0x11U
#define PADCFG_PAD_GPIO_A12_DEBOUNCE_SHIFT                 0xFU
#define PADCFG_PAD_GPIO_A12_DEBOUNCE_MASK                  0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x24U)
#define PADCFG_PAD_GPIO_A13_DS_WIDTH                       0x2U
#define PADCFG_PAD_GPIO_A13_DS_SHIFT                       0x0U
#define PADCFG_PAD_GPIO_A13_DS_MASK                        0x3U
#define PADCFG_PAD_GPIO_A13_IE_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A13_IE_SHIFT                       0x2U
#define PADCFG_PAD_GPIO_A13_IE_MASK                        0x4U
#define PADCFG_PAD_GPIO_A13_PD_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A13_PD_SHIFT                       0x3U
#define PADCFG_PAD_GPIO_A13_PD_MASK                        0x8U
#define PADCFG_PAD_GPIO_A13_PU_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A13_PU_SHIFT                       0x4U
#define PADCFG_PAD_GPIO_A13_PU_MASK                        0x10U
#define PADCFG_PAD_GPIO_A13_SLEW_WIDTH                     0x1U
#define PADCFG_PAD_GPIO_A13_SLEW_SHIFT                     0x5U
#define PADCFG_PAD_GPIO_A13_SLEW_MASK                      0x20U
#define PADCFG_PAD_GPIO_A13_SMT_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A13_SMT_SHIFT                      0x6U
#define PADCFG_PAD_GPIO_A13_SMT_MASK                       0x40U
#define PADCFG_PAD_GPIO_A13_DEBOUNCE_WIDTH                 0x11U
#define PADCFG_PAD_GPIO_A13_DEBOUNCE_SHIFT                 0xFU
#define PADCFG_PAD_GPIO_A13_DEBOUNCE_MASK                  0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x28U)
#define PADCFG_PAD_GPIO_A14_DS_WIDTH                       0x2U
#define PADCFG_PAD_GPIO_A14_DS_SHIFT                       0x0U
#define PADCFG_PAD_GPIO_A14_DS_MASK                        0x3U
#define PADCFG_PAD_GPIO_A14_IE_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A14_IE_SHIFT                       0x2U
#define PADCFG_PAD_GPIO_A14_IE_MASK                        0x4U
#define PADCFG_PAD_GPIO_A14_PD_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A14_PD_SHIFT                       0x3U
#define PADCFG_PAD_GPIO_A14_PD_MASK                        0x8U
#define PADCFG_PAD_GPIO_A14_PU_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A14_PU_SHIFT                       0x4U
#define PADCFG_PAD_GPIO_A14_PU_MASK                        0x10U
#define PADCFG_PAD_GPIO_A14_SLEW_WIDTH                     0x1U
#define PADCFG_PAD_GPIO_A14_SLEW_SHIFT                     0x5U
#define PADCFG_PAD_GPIO_A14_SLEW_MASK                      0x20U
#define PADCFG_PAD_GPIO_A14_SMT_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A14_SMT_SHIFT                      0x6U
#define PADCFG_PAD_GPIO_A14_SMT_MASK                       0x40U
#define PADCFG_PAD_GPIO_A14_DEBOUNCE_WIDTH                 0x11U
#define PADCFG_PAD_GPIO_A14_DEBOUNCE_SHIFT                 0xFU
#define PADCFG_PAD_GPIO_A14_DEBOUNCE_MASK                  0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x2cU)
#define PADCFG_PAD_GPIO_A15_DS_WIDTH                       0x2U
#define PADCFG_PAD_GPIO_A15_DS_SHIFT                       0x0U
#define PADCFG_PAD_GPIO_A15_DS_MASK                        0x3U
#define PADCFG_PAD_GPIO_A15_IE_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A15_IE_SHIFT                       0x2U
#define PADCFG_PAD_GPIO_A15_IE_MASK                        0x4U
#define PADCFG_PAD_GPIO_A15_PD_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A15_PD_SHIFT                       0x3U
#define PADCFG_PAD_GPIO_A15_PD_MASK                        0x8U
#define PADCFG_PAD_GPIO_A15_PU_WIDTH                       0x1U
#define PADCFG_PAD_GPIO_A15_PU_SHIFT                       0x4U
#define PADCFG_PAD_GPIO_A15_PU_MASK                        0x10U
#define PADCFG_PAD_GPIO_A15_SLEW_WIDTH                     0x1U
#define PADCFG_PAD_GPIO_A15_SLEW_SHIFT                     0x5U
#define PADCFG_PAD_GPIO_A15_SLEW_MASK                      0x20U
#define PADCFG_PAD_GPIO_A15_SMT_WIDTH                      0x1U
#define PADCFG_PAD_GPIO_A15_SMT_SHIFT                      0x6U
#define PADCFG_PAD_GPIO_A15_SMT_MASK                       0x40U
#define PADCFG_PAD_GPIO_A15_DEBOUNCE_WIDTH                 0x11U
#define PADCFG_PAD_GPIO_A15_DEBOUNCE_SHIFT                 0xFU
#define PADCFG_PAD_GPIO_A15_DEBOUNCE_MASK                  0xFFFF8000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x30U)
#define U0_SYS0H_IOMUX_FMUX_O0_SEL_WIDTH                   0x1U
#define U0_SYS0H_IOMUX_FMUX_O0_SEL_SHIFT                   0x0U
#define U0_SYS0H_IOMUX_FMUX_O0_SEL_MASK                    0x1U
#define U0_SYS0H_IOMUX_FMUX_O1_SEL_WIDTH                   0x1U
#define U0_SYS0H_IOMUX_FMUX_O1_SEL_SHIFT                   0x1U
#define U0_SYS0H_IOMUX_FMUX_O1_SEL_MASK                    0x2U
#define U0_SYS0H_IOMUX_FMUX_O2_SEL_WIDTH                   0x1U
#define U0_SYS0H_IOMUX_FMUX_O2_SEL_SHIFT                   0x2U
#define U0_SYS0H_IOMUX_FMUX_O2_SEL_MASK                    0x4U
#define U0_SYS0H_IOMUX_FMUX_O3_SEL_WIDTH                   0x1U
#define U0_SYS0H_IOMUX_FMUX_O3_SEL_SHIFT                   0x3U
#define U0_SYS0H_IOMUX_FMUX_O3_SEL_MASK                    0x8U
#define U0_SYS0H_IOMUX_FMUX_O4_SEL_WIDTH                   0x1U
#define U0_SYS0H_IOMUX_FMUX_O4_SEL_SHIFT                   0x4U
#define U0_SYS0H_IOMUX_FMUX_O4_SEL_MASK                    0x10U
#define U0_SYS0H_IOMUX_FMUX_O5_SEL_WIDTH                   0x1U
#define U0_SYS0H_IOMUX_FMUX_O5_SEL_SHIFT                   0x5U
#define U0_SYS0H_IOMUX_FMUX_O5_SEL_MASK                    0x20U
#define U0_SYS0H_IOMUX_FMUX_O6_SEL_WIDTH                   0x1U
#define U0_SYS0H_IOMUX_FMUX_O6_SEL_SHIFT                   0x6U
#define U0_SYS0H_IOMUX_FMUX_O6_SEL_MASK                    0x40U
#define U0_SYS0H_IOMUX_FMUX_O7_SEL_WIDTH                   0x1U
#define U0_SYS0H_IOMUX_FMUX_O7_SEL_SHIFT                   0x7U
#define U0_SYS0H_IOMUX_FMUX_O7_SEL_MASK                    0x80U
#define U0_SYS0H_IOMUX_FMUX_O8_SEL_WIDTH                   0x1U
#define U0_SYS0H_IOMUX_FMUX_O8_SEL_SHIFT                   0x8U
#define U0_SYS0H_IOMUX_FMUX_O8_SEL_MASK                    0x100U
#define U0_SYS0H_IOMUX_FMUX_O9_SEL_WIDTH                   0x1U
#define U0_SYS0H_IOMUX_FMUX_O9_SEL_SHIFT                   0x9U
#define U0_SYS0H_IOMUX_FMUX_O9_SEL_MASK                    0x200U
#define U0_SYS0H_IOMUX_FMUX_O10_SEL_WIDTH                  0x1U
#define U0_SYS0H_IOMUX_FMUX_O10_SEL_SHIFT                  0xAU
#define U0_SYS0H_IOMUX_FMUX_O10_SEL_MASK                   0x400U
#define U0_SYS0H_IOMUX_FMUX_O11_SEL_WIDTH                  0x1U
#define U0_SYS0H_IOMUX_FMUX_O11_SEL_SHIFT                  0xBU
#define U0_SYS0H_IOMUX_FMUX_O11_SEL_MASK                   0x800U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x34U)
#define U0_SYS0H_IOMUX_FMUX_OEN0_SEL_WIDTH                 0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN0_SEL_SHIFT                 0x0U
#define U0_SYS0H_IOMUX_FMUX_OEN0_SEL_MASK                  0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN1_SEL_WIDTH                 0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN1_SEL_SHIFT                 0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN1_SEL_MASK                  0x2U
#define U0_SYS0H_IOMUX_FMUX_OEN2_SEL_WIDTH                 0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN2_SEL_SHIFT                 0x2U
#define U0_SYS0H_IOMUX_FMUX_OEN2_SEL_MASK                  0x4U
#define U0_SYS0H_IOMUX_FMUX_OEN3_SEL_WIDTH                 0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN3_SEL_SHIFT                 0x3U
#define U0_SYS0H_IOMUX_FMUX_OEN3_SEL_MASK                  0x8U
#define U0_SYS0H_IOMUX_FMUX_OEN4_SEL_WIDTH                 0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN4_SEL_SHIFT                 0x4U
#define U0_SYS0H_IOMUX_FMUX_OEN4_SEL_MASK                  0x10U
#define U0_SYS0H_IOMUX_FMUX_OEN5_SEL_WIDTH                 0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN5_SEL_SHIFT                 0x5U
#define U0_SYS0H_IOMUX_FMUX_OEN5_SEL_MASK                  0x20U
#define U0_SYS0H_IOMUX_FMUX_OEN6_SEL_WIDTH                 0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN6_SEL_SHIFT                 0x6U
#define U0_SYS0H_IOMUX_FMUX_OEN6_SEL_MASK                  0x40U
#define U0_SYS0H_IOMUX_FMUX_OEN7_SEL_WIDTH                 0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN7_SEL_SHIFT                 0x7U
#define U0_SYS0H_IOMUX_FMUX_OEN7_SEL_MASK                  0x80U
#define U0_SYS0H_IOMUX_FMUX_OEN8_SEL_WIDTH                 0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN8_SEL_SHIFT                 0x8U
#define U0_SYS0H_IOMUX_FMUX_OEN8_SEL_MASK                  0x100U
#define U0_SYS0H_IOMUX_FMUX_OEN9_SEL_WIDTH                 0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN9_SEL_SHIFT                 0x9U
#define U0_SYS0H_IOMUX_FMUX_OEN9_SEL_MASK                  0x200U
#define U0_SYS0H_IOMUX_FMUX_OEN10_SEL_WIDTH                0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN10_SEL_SHIFT                0xAU
#define U0_SYS0H_IOMUX_FMUX_OEN10_SEL_MASK                 0x400U
#define U0_SYS0H_IOMUX_FMUX_OEN11_SEL_WIDTH                0x1U
#define U0_SYS0H_IOMUX_FMUX_OEN11_SEL_SHIFT                0xBU
#define U0_SYS0H_IOMUX_FMUX_OEN11_SEL_MASK                 0x800U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_56_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x38U)
#define U0_SYS0H_IOMUX_O_I_11_0__WIDTH                     0xCU
#define U0_SYS0H_IOMUX_O_I_11_0__SHIFT                     0x0U
#define U0_SYS0H_IOMUX_O_I_11_0__MASK                      0xFFFU
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x3cU)
#define U0_SYS0H_IOMUX_FUNC0_SEL_WIDTH                     0x1U
#define U0_SYS0H_IOMUX_FUNC0_SEL_SHIFT                     0x0U
#define U0_SYS0H_IOMUX_FUNC0_SEL_MASK                      0x1U
#define U0_SYS0H_IOMUX_FUNC1_SEL_WIDTH                     0x1U
#define U0_SYS0H_IOMUX_FUNC1_SEL_SHIFT                     0x2U
#define U0_SYS0H_IOMUX_FUNC1_SEL_MASK                      0x4U
#define U0_SYS0H_IOMUX_FUNC2_SEL_WIDTH                     0x1U
#define U0_SYS0H_IOMUX_FUNC2_SEL_SHIFT                     0x4U
#define U0_SYS0H_IOMUX_FUNC2_SEL_MASK                      0x10U
#define U0_SYS0H_IOMUX_FUNC3_SEL_WIDTH                     0x1U
#define U0_SYS0H_IOMUX_FUNC3_SEL_SHIFT                     0x6U
#define U0_SYS0H_IOMUX_FUNC3_SEL_MASK                      0x40U
#define U0_SYS0H_IOMUX_FUNC4_SEL_WIDTH                     0x1U
#define U0_SYS0H_IOMUX_FUNC4_SEL_SHIFT                     0x8U
#define U0_SYS0H_IOMUX_FUNC4_SEL_MASK                      0x100U
#define U0_SYS0H_IOMUX_FUNC5_SEL_WIDTH                     0x1U
#define U0_SYS0H_IOMUX_FUNC5_SEL_SHIFT                     0xAU
#define U0_SYS0H_IOMUX_FUNC5_SEL_MASK                      0x400U
#define U0_SYS0H_IOMUX_FUNC6_SEL_WIDTH                     0x1U
#define U0_SYS0H_IOMUX_FUNC6_SEL_SHIFT                     0xCU
#define U0_SYS0H_IOMUX_FUNC6_SEL_MASK                      0x1000U
#define U0_SYS0H_IOMUX_FUNC7_SEL_WIDTH                     0x1U
#define U0_SYS0H_IOMUX_FUNC7_SEL_SHIFT                     0xEU
#define U0_SYS0H_IOMUX_FUNC7_SEL_MASK                      0x4000U
#define U0_SYS0H_IOMUX_FUNC8_SEL_WIDTH                     0x2U
#define U0_SYS0H_IOMUX_FUNC8_SEL_SHIFT                     0x10U
#define U0_SYS0H_IOMUX_FUNC8_SEL_MASK                      0x30000U
#define U0_SYS0H_IOMUX_FUNC9_SEL_WIDTH                     0x2U
#define U0_SYS0H_IOMUX_FUNC9_SEL_SHIFT                     0x12U
#define U0_SYS0H_IOMUX_FUNC9_SEL_MASK                      0xC0000U
#define U0_SYS0H_IOMUX_FUNC10_SEL_WIDTH                    0x2U
#define U0_SYS0H_IOMUX_FUNC10_SEL_SHIFT                    0x14U
#define U0_SYS0H_IOMUX_FUNC10_SEL_MASK                     0x300000U
#define U0_SYS0H_IOMUX_FUNC11_SEL_WIDTH                    0x2U
#define U0_SYS0H_IOMUX_FUNC11_SEL_SHIFT                    0x16U
#define U0_SYS0H_IOMUX_FUNC11_SEL_MASK                     0xC00000U
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_64_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x40U)
#define U0_SYS0H_IOMUX_INT_EN_11_0__WIDTH                  0xCU
#define U0_SYS0H_IOMUX_INT_EN_11_0__SHIFT                  0x0U
#define U0_SYS0H_IOMUX_INT_EN_11_0__MASK                   0xFFFU
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_68_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x44U)
#define U0_SYS0H_IOMUX_INT_STATUS_11_0__WIDTH              0xCU
#define U0_SYS0H_IOMUX_INT_STATUS_11_0__SHIFT              0x0U
#define U0_SYS0H_IOMUX_INT_STATUS_11_0__MASK               0xFFFU
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_72_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x48U)
#define U0_SYS0H_IOMUX_INT_CLR_11_0__WIDTH                 0xCU
#define U0_SYS0H_IOMUX_INT_CLR_11_0__SHIFT                 0x0U
#define U0_SYS0H_IOMUX_INT_CLR_11_0__MASK                  0xFFFU
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_76_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x4cU)
#define U0_SYS0H_IOMUX_INT_EDGE_11_0__WIDTH                0xCU
#define U0_SYS0H_IOMUX_INT_EDGE_11_0__SHIFT                0x0U
#define U0_SYS0H_IOMUX_INT_EDGE_11_0__MASK                 0xFFFU
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_80_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x50U)
#define U0_SYS0H_IOMUX_INT_HIGH_LEVEL_11_0__WIDTH          0xCU
#define U0_SYS0H_IOMUX_INT_HIGH_LEVEL_11_0__SHIFT          0x0U
#define U0_SYS0H_IOMUX_INT_HIGH_LEVEL_11_0__MASK           0xFFFU
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_84_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x54U)
#define U0_SYS0H_IOMUX_INT_BOTH_EDGE_11_0__WIDTH           0xCU
#define U0_SYS0H_IOMUX_INT_BOTH_EDGE_11_0__SHIFT           0x0U
#define U0_SYS0H_IOMUX_INT_BOTH_EDGE_11_0__MASK            0xFFFU
#define SYS0H_IOMUX_CFG__ITG__SYSCFG_88_ADDR               (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x58U)
#define U0_SYS0H_IOMUX_INT_RISING_EDGE_11_0__WIDTH         0xCU
#define U0_SYS0H_IOMUX_INT_RISING_EDGE_11_0__SHIFT         0x0U
#define U0_SYS0H_IOMUX_INT_RISING_EDGE_11_0__MASK          0xFFFU
#define SYS0H_IOMUX_CFGITG__SYSCFG_92_ADDR                 (U0_SYS0H_IOMUX__ITG_BD_APBS__BASE_ADDR + 0x5cU)
#define GET_PADCFG_PAD_GPIO_A4_DS                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,PADCFG_PAD_GPIO_A4_DS_SHIFT,PADCFG_PAD_GPIO_A4_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A4_DS(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,data,PADCFG_PAD_GPIO_A4_DS_SHIFT,PADCFG_PAD_GPIO_A4_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A4_IE                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,PADCFG_PAD_GPIO_A4_IE_SHIFT,PADCFG_PAD_GPIO_A4_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A4_IE(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,data,PADCFG_PAD_GPIO_A4_IE_SHIFT,PADCFG_PAD_GPIO_A4_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A4_PD                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,PADCFG_PAD_GPIO_A4_PD_SHIFT,PADCFG_PAD_GPIO_A4_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A4_PD(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,data,PADCFG_PAD_GPIO_A4_PD_SHIFT,PADCFG_PAD_GPIO_A4_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A4_PU                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,PADCFG_PAD_GPIO_A4_PU_SHIFT,PADCFG_PAD_GPIO_A4_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A4_PU(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,data,PADCFG_PAD_GPIO_A4_PU_SHIFT,PADCFG_PAD_GPIO_A4_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A4_SLEW                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,PADCFG_PAD_GPIO_A4_SLEW_SHIFT,PADCFG_PAD_GPIO_A4_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A4_SLEW(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,data,PADCFG_PAD_GPIO_A4_SLEW_SHIFT,PADCFG_PAD_GPIO_A4_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A4_SMT                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,PADCFG_PAD_GPIO_A4_SMT_SHIFT,PADCFG_PAD_GPIO_A4_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A4_SMT(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,data,PADCFG_PAD_GPIO_A4_SMT_SHIFT,PADCFG_PAD_GPIO_A4_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A4_DEBOUNCE                    itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,PADCFG_PAD_GPIO_A4_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A4_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A4_DEBOUNCE(data)              itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_0_ADDR,data,PADCFG_PAD_GPIO_A4_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A4_DEBOUNCE_MASK)
#define GET_PADCFG_PAD_GPIO_A5_DS                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,PADCFG_PAD_GPIO_A5_DS_SHIFT,PADCFG_PAD_GPIO_A5_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A5_DS(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,data,PADCFG_PAD_GPIO_A5_DS_SHIFT,PADCFG_PAD_GPIO_A5_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A5_IE                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,PADCFG_PAD_GPIO_A5_IE_SHIFT,PADCFG_PAD_GPIO_A5_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A5_IE(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,data,PADCFG_PAD_GPIO_A5_IE_SHIFT,PADCFG_PAD_GPIO_A5_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A5_PD                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,PADCFG_PAD_GPIO_A5_PD_SHIFT,PADCFG_PAD_GPIO_A5_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A5_PD(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,data,PADCFG_PAD_GPIO_A5_PD_SHIFT,PADCFG_PAD_GPIO_A5_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A5_PU                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,PADCFG_PAD_GPIO_A5_PU_SHIFT,PADCFG_PAD_GPIO_A5_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A5_PU(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,data,PADCFG_PAD_GPIO_A5_PU_SHIFT,PADCFG_PAD_GPIO_A5_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A5_SLEW                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,PADCFG_PAD_GPIO_A5_SLEW_SHIFT,PADCFG_PAD_GPIO_A5_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A5_SLEW(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,data,PADCFG_PAD_GPIO_A5_SLEW_SHIFT,PADCFG_PAD_GPIO_A5_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A5_SMT                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,PADCFG_PAD_GPIO_A5_SMT_SHIFT,PADCFG_PAD_GPIO_A5_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A5_SMT(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,data,PADCFG_PAD_GPIO_A5_SMT_SHIFT,PADCFG_PAD_GPIO_A5_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A5_DEBOUNCE                    itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,PADCFG_PAD_GPIO_A5_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A5_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A5_DEBOUNCE(data)              itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_4_ADDR,data,PADCFG_PAD_GPIO_A5_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A5_DEBOUNCE_MASK)
#define GET_PADCFG_PAD_GPIO_A6_DS                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,PADCFG_PAD_GPIO_A6_DS_SHIFT,PADCFG_PAD_GPIO_A6_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A6_DS(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,data,PADCFG_PAD_GPIO_A6_DS_SHIFT,PADCFG_PAD_GPIO_A6_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A6_IE                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,PADCFG_PAD_GPIO_A6_IE_SHIFT,PADCFG_PAD_GPIO_A6_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A6_IE(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,data,PADCFG_PAD_GPIO_A6_IE_SHIFT,PADCFG_PAD_GPIO_A6_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A6_PD                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,PADCFG_PAD_GPIO_A6_PD_SHIFT,PADCFG_PAD_GPIO_A6_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A6_PD(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,data,PADCFG_PAD_GPIO_A6_PD_SHIFT,PADCFG_PAD_GPIO_A6_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A6_PU                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,PADCFG_PAD_GPIO_A6_PU_SHIFT,PADCFG_PAD_GPIO_A6_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A6_PU(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,data,PADCFG_PAD_GPIO_A6_PU_SHIFT,PADCFG_PAD_GPIO_A6_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A6_SLEW                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,PADCFG_PAD_GPIO_A6_SLEW_SHIFT,PADCFG_PAD_GPIO_A6_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A6_SLEW(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,data,PADCFG_PAD_GPIO_A6_SLEW_SHIFT,PADCFG_PAD_GPIO_A6_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A6_SMT                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,PADCFG_PAD_GPIO_A6_SMT_SHIFT,PADCFG_PAD_GPIO_A6_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A6_SMT(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,data,PADCFG_PAD_GPIO_A6_SMT_SHIFT,PADCFG_PAD_GPIO_A6_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A6_DEBOUNCE                    itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,PADCFG_PAD_GPIO_A6_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A6_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A6_DEBOUNCE(data)              itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_8_ADDR,data,PADCFG_PAD_GPIO_A6_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A6_DEBOUNCE_MASK)
#define GET_PADCFG_PAD_GPIO_A7_DS                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,PADCFG_PAD_GPIO_A7_DS_SHIFT,PADCFG_PAD_GPIO_A7_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A7_DS(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,data,PADCFG_PAD_GPIO_A7_DS_SHIFT,PADCFG_PAD_GPIO_A7_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A7_IE                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,PADCFG_PAD_GPIO_A7_IE_SHIFT,PADCFG_PAD_GPIO_A7_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A7_IE(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,data,PADCFG_PAD_GPIO_A7_IE_SHIFT,PADCFG_PAD_GPIO_A7_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A7_PD                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,PADCFG_PAD_GPIO_A7_PD_SHIFT,PADCFG_PAD_GPIO_A7_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A7_PD(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,data,PADCFG_PAD_GPIO_A7_PD_SHIFT,PADCFG_PAD_GPIO_A7_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A7_PU                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,PADCFG_PAD_GPIO_A7_PU_SHIFT,PADCFG_PAD_GPIO_A7_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A7_PU(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,data,PADCFG_PAD_GPIO_A7_PU_SHIFT,PADCFG_PAD_GPIO_A7_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A7_SLEW                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,PADCFG_PAD_GPIO_A7_SLEW_SHIFT,PADCFG_PAD_GPIO_A7_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A7_SLEW(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,data,PADCFG_PAD_GPIO_A7_SLEW_SHIFT,PADCFG_PAD_GPIO_A7_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A7_SMT                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,PADCFG_PAD_GPIO_A7_SMT_SHIFT,PADCFG_PAD_GPIO_A7_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A7_SMT(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,data,PADCFG_PAD_GPIO_A7_SMT_SHIFT,PADCFG_PAD_GPIO_A7_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A7_DEBOUNCE                    itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,PADCFG_PAD_GPIO_A7_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A7_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A7_DEBOUNCE(data)              itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_12_ADDR,data,PADCFG_PAD_GPIO_A7_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A7_DEBOUNCE_MASK)
#define GET_PADCFG_PAD_GPIO_A8_DS                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,PADCFG_PAD_GPIO_A8_DS_SHIFT,PADCFG_PAD_GPIO_A8_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A8_DS(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,data,PADCFG_PAD_GPIO_A8_DS_SHIFT,PADCFG_PAD_GPIO_A8_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A8_IE                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,PADCFG_PAD_GPIO_A8_IE_SHIFT,PADCFG_PAD_GPIO_A8_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A8_IE(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,data,PADCFG_PAD_GPIO_A8_IE_SHIFT,PADCFG_PAD_GPIO_A8_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A8_PD                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,PADCFG_PAD_GPIO_A8_PD_SHIFT,PADCFG_PAD_GPIO_A8_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A8_PD(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,data,PADCFG_PAD_GPIO_A8_PD_SHIFT,PADCFG_PAD_GPIO_A8_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A8_PU                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,PADCFG_PAD_GPIO_A8_PU_SHIFT,PADCFG_PAD_GPIO_A8_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A8_PU(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,data,PADCFG_PAD_GPIO_A8_PU_SHIFT,PADCFG_PAD_GPIO_A8_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A8_SLEW                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,PADCFG_PAD_GPIO_A8_SLEW_SHIFT,PADCFG_PAD_GPIO_A8_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A8_SLEW(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,data,PADCFG_PAD_GPIO_A8_SLEW_SHIFT,PADCFG_PAD_GPIO_A8_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A8_SMT                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,PADCFG_PAD_GPIO_A8_SMT_SHIFT,PADCFG_PAD_GPIO_A8_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A8_SMT(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,data,PADCFG_PAD_GPIO_A8_SMT_SHIFT,PADCFG_PAD_GPIO_A8_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A8_DEBOUNCE                    itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,PADCFG_PAD_GPIO_A8_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A8_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A8_DEBOUNCE(data)              itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_16_ADDR,data,PADCFG_PAD_GPIO_A8_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A8_DEBOUNCE_MASK)
#define GET_PADCFG_PAD_GPIO_A9_DS                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,PADCFG_PAD_GPIO_A9_DS_SHIFT,PADCFG_PAD_GPIO_A9_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A9_DS(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,data,PADCFG_PAD_GPIO_A9_DS_SHIFT,PADCFG_PAD_GPIO_A9_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A9_IE                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,PADCFG_PAD_GPIO_A9_IE_SHIFT,PADCFG_PAD_GPIO_A9_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A9_IE(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,data,PADCFG_PAD_GPIO_A9_IE_SHIFT,PADCFG_PAD_GPIO_A9_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A9_PD                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,PADCFG_PAD_GPIO_A9_PD_SHIFT,PADCFG_PAD_GPIO_A9_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A9_PD(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,data,PADCFG_PAD_GPIO_A9_PD_SHIFT,PADCFG_PAD_GPIO_A9_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A9_PU                          itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,PADCFG_PAD_GPIO_A9_PU_SHIFT,PADCFG_PAD_GPIO_A9_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A9_PU(data)                    itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,data,PADCFG_PAD_GPIO_A9_PU_SHIFT,PADCFG_PAD_GPIO_A9_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A9_SLEW                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,PADCFG_PAD_GPIO_A9_SLEW_SHIFT,PADCFG_PAD_GPIO_A9_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A9_SLEW(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,data,PADCFG_PAD_GPIO_A9_SLEW_SHIFT,PADCFG_PAD_GPIO_A9_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A9_SMT                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,PADCFG_PAD_GPIO_A9_SMT_SHIFT,PADCFG_PAD_GPIO_A9_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A9_SMT(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,data,PADCFG_PAD_GPIO_A9_SMT_SHIFT,PADCFG_PAD_GPIO_A9_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A9_DEBOUNCE                    itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,PADCFG_PAD_GPIO_A9_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A9_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A9_DEBOUNCE(data)              itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_20_ADDR,data,PADCFG_PAD_GPIO_A9_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A9_DEBOUNCE_MASK)
#define GET_PADCFG_PAD_GPIO_A10_DS                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,PADCFG_PAD_GPIO_A10_DS_SHIFT,PADCFG_PAD_GPIO_A10_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A10_DS(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,data,PADCFG_PAD_GPIO_A10_DS_SHIFT,PADCFG_PAD_GPIO_A10_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A10_IE                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,PADCFG_PAD_GPIO_A10_IE_SHIFT,PADCFG_PAD_GPIO_A10_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A10_IE(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,data,PADCFG_PAD_GPIO_A10_IE_SHIFT,PADCFG_PAD_GPIO_A10_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A10_PD                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,PADCFG_PAD_GPIO_A10_PD_SHIFT,PADCFG_PAD_GPIO_A10_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A10_PD(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,data,PADCFG_PAD_GPIO_A10_PD_SHIFT,PADCFG_PAD_GPIO_A10_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A10_PU                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,PADCFG_PAD_GPIO_A10_PU_SHIFT,PADCFG_PAD_GPIO_A10_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A10_PU(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,data,PADCFG_PAD_GPIO_A10_PU_SHIFT,PADCFG_PAD_GPIO_A10_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A10_SLEW                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,PADCFG_PAD_GPIO_A10_SLEW_SHIFT,PADCFG_PAD_GPIO_A10_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A10_SLEW(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,data,PADCFG_PAD_GPIO_A10_SLEW_SHIFT,PADCFG_PAD_GPIO_A10_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A10_SMT                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,PADCFG_PAD_GPIO_A10_SMT_SHIFT,PADCFG_PAD_GPIO_A10_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A10_SMT(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,data,PADCFG_PAD_GPIO_A10_SMT_SHIFT,PADCFG_PAD_GPIO_A10_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A10_DEBOUNCE                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,PADCFG_PAD_GPIO_A10_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A10_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A10_DEBOUNCE(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_24_ADDR,data,PADCFG_PAD_GPIO_A10_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A10_DEBOUNCE_MASK)
#define GET_PADCFG_PAD_GPIO_A11_DS                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,PADCFG_PAD_GPIO_A11_DS_SHIFT,PADCFG_PAD_GPIO_A11_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A11_DS(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,data,PADCFG_PAD_GPIO_A11_DS_SHIFT,PADCFG_PAD_GPIO_A11_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A11_IE                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,PADCFG_PAD_GPIO_A11_IE_SHIFT,PADCFG_PAD_GPIO_A11_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A11_IE(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,data,PADCFG_PAD_GPIO_A11_IE_SHIFT,PADCFG_PAD_GPIO_A11_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A11_PD                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,PADCFG_PAD_GPIO_A11_PD_SHIFT,PADCFG_PAD_GPIO_A11_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A11_PD(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,data,PADCFG_PAD_GPIO_A11_PD_SHIFT,PADCFG_PAD_GPIO_A11_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A11_PU                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,PADCFG_PAD_GPIO_A11_PU_SHIFT,PADCFG_PAD_GPIO_A11_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A11_PU(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,data,PADCFG_PAD_GPIO_A11_PU_SHIFT,PADCFG_PAD_GPIO_A11_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A11_SLEW                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,PADCFG_PAD_GPIO_A11_SLEW_SHIFT,PADCFG_PAD_GPIO_A11_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A11_SLEW(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,data,PADCFG_PAD_GPIO_A11_SLEW_SHIFT,PADCFG_PAD_GPIO_A11_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A11_SMT                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,PADCFG_PAD_GPIO_A11_SMT_SHIFT,PADCFG_PAD_GPIO_A11_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A11_SMT(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,data,PADCFG_PAD_GPIO_A11_SMT_SHIFT,PADCFG_PAD_GPIO_A11_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A11_DEBOUNCE                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,PADCFG_PAD_GPIO_A11_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A11_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A11_DEBOUNCE(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_28_ADDR,data,PADCFG_PAD_GPIO_A11_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A11_DEBOUNCE_MASK)
#define GET_PADCFG_PAD_GPIO_A12_DS                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,PADCFG_PAD_GPIO_A12_DS_SHIFT,PADCFG_PAD_GPIO_A12_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A12_DS(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,data,PADCFG_PAD_GPIO_A12_DS_SHIFT,PADCFG_PAD_GPIO_A12_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A12_IE                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,PADCFG_PAD_GPIO_A12_IE_SHIFT,PADCFG_PAD_GPIO_A12_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A12_IE(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,data,PADCFG_PAD_GPIO_A12_IE_SHIFT,PADCFG_PAD_GPIO_A12_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A12_PD                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,PADCFG_PAD_GPIO_A12_PD_SHIFT,PADCFG_PAD_GPIO_A12_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A12_PD(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,data,PADCFG_PAD_GPIO_A12_PD_SHIFT,PADCFG_PAD_GPIO_A12_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A12_PU                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,PADCFG_PAD_GPIO_A12_PU_SHIFT,PADCFG_PAD_GPIO_A12_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A12_PU(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,data,PADCFG_PAD_GPIO_A12_PU_SHIFT,PADCFG_PAD_GPIO_A12_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A12_SLEW                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,PADCFG_PAD_GPIO_A12_SLEW_SHIFT,PADCFG_PAD_GPIO_A12_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A12_SLEW(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,data,PADCFG_PAD_GPIO_A12_SLEW_SHIFT,PADCFG_PAD_GPIO_A12_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A12_SMT                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,PADCFG_PAD_GPIO_A12_SMT_SHIFT,PADCFG_PAD_GPIO_A12_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A12_SMT(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,data,PADCFG_PAD_GPIO_A12_SMT_SHIFT,PADCFG_PAD_GPIO_A12_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A12_DEBOUNCE                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,PADCFG_PAD_GPIO_A12_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A12_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A12_DEBOUNCE(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_32_ADDR,data,PADCFG_PAD_GPIO_A12_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A12_DEBOUNCE_MASK)
#define GET_PADCFG_PAD_GPIO_A13_DS                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,PADCFG_PAD_GPIO_A13_DS_SHIFT,PADCFG_PAD_GPIO_A13_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A13_DS(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,data,PADCFG_PAD_GPIO_A13_DS_SHIFT,PADCFG_PAD_GPIO_A13_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A13_IE                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,PADCFG_PAD_GPIO_A13_IE_SHIFT,PADCFG_PAD_GPIO_A13_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A13_IE(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,data,PADCFG_PAD_GPIO_A13_IE_SHIFT,PADCFG_PAD_GPIO_A13_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A13_PD                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,PADCFG_PAD_GPIO_A13_PD_SHIFT,PADCFG_PAD_GPIO_A13_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A13_PD(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,data,PADCFG_PAD_GPIO_A13_PD_SHIFT,PADCFG_PAD_GPIO_A13_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A13_PU                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,PADCFG_PAD_GPIO_A13_PU_SHIFT,PADCFG_PAD_GPIO_A13_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A13_PU(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,data,PADCFG_PAD_GPIO_A13_PU_SHIFT,PADCFG_PAD_GPIO_A13_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A13_SLEW                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,PADCFG_PAD_GPIO_A13_SLEW_SHIFT,PADCFG_PAD_GPIO_A13_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A13_SLEW(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,data,PADCFG_PAD_GPIO_A13_SLEW_SHIFT,PADCFG_PAD_GPIO_A13_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A13_SMT                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,PADCFG_PAD_GPIO_A13_SMT_SHIFT,PADCFG_PAD_GPIO_A13_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A13_SMT(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,data,PADCFG_PAD_GPIO_A13_SMT_SHIFT,PADCFG_PAD_GPIO_A13_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A13_DEBOUNCE                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,PADCFG_PAD_GPIO_A13_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A13_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A13_DEBOUNCE(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_36_ADDR,data,PADCFG_PAD_GPIO_A13_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A13_DEBOUNCE_MASK)
#define GET_PADCFG_PAD_GPIO_A14_DS                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,PADCFG_PAD_GPIO_A14_DS_SHIFT,PADCFG_PAD_GPIO_A14_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A14_DS(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,data,PADCFG_PAD_GPIO_A14_DS_SHIFT,PADCFG_PAD_GPIO_A14_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A14_IE                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,PADCFG_PAD_GPIO_A14_IE_SHIFT,PADCFG_PAD_GPIO_A14_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A14_IE(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,data,PADCFG_PAD_GPIO_A14_IE_SHIFT,PADCFG_PAD_GPIO_A14_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A14_PD                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,PADCFG_PAD_GPIO_A14_PD_SHIFT,PADCFG_PAD_GPIO_A14_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A14_PD(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,data,PADCFG_PAD_GPIO_A14_PD_SHIFT,PADCFG_PAD_GPIO_A14_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A14_PU                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,PADCFG_PAD_GPIO_A14_PU_SHIFT,PADCFG_PAD_GPIO_A14_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A14_PU(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,data,PADCFG_PAD_GPIO_A14_PU_SHIFT,PADCFG_PAD_GPIO_A14_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A14_SLEW                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,PADCFG_PAD_GPIO_A14_SLEW_SHIFT,PADCFG_PAD_GPIO_A14_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A14_SLEW(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,data,PADCFG_PAD_GPIO_A14_SLEW_SHIFT,PADCFG_PAD_GPIO_A14_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A14_SMT                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,PADCFG_PAD_GPIO_A14_SMT_SHIFT,PADCFG_PAD_GPIO_A14_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A14_SMT(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,data,PADCFG_PAD_GPIO_A14_SMT_SHIFT,PADCFG_PAD_GPIO_A14_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A14_DEBOUNCE                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,PADCFG_PAD_GPIO_A14_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A14_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A14_DEBOUNCE(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_40_ADDR,data,PADCFG_PAD_GPIO_A14_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A14_DEBOUNCE_MASK)
#define GET_PADCFG_PAD_GPIO_A15_DS                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,PADCFG_PAD_GPIO_A15_DS_SHIFT,PADCFG_PAD_GPIO_A15_DS_MASK)
#define SET_PADCFG_PAD_GPIO_A15_DS(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,data,PADCFG_PAD_GPIO_A15_DS_SHIFT,PADCFG_PAD_GPIO_A15_DS_MASK)
#define GET_PADCFG_PAD_GPIO_A15_IE                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,PADCFG_PAD_GPIO_A15_IE_SHIFT,PADCFG_PAD_GPIO_A15_IE_MASK)
#define SET_PADCFG_PAD_GPIO_A15_IE(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,data,PADCFG_PAD_GPIO_A15_IE_SHIFT,PADCFG_PAD_GPIO_A15_IE_MASK)
#define GET_PADCFG_PAD_GPIO_A15_PD                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,PADCFG_PAD_GPIO_A15_PD_SHIFT,PADCFG_PAD_GPIO_A15_PD_MASK)
#define SET_PADCFG_PAD_GPIO_A15_PD(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,data,PADCFG_PAD_GPIO_A15_PD_SHIFT,PADCFG_PAD_GPIO_A15_PD_MASK)
#define GET_PADCFG_PAD_GPIO_A15_PU                         itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,PADCFG_PAD_GPIO_A15_PU_SHIFT,PADCFG_PAD_GPIO_A15_PU_MASK)
#define SET_PADCFG_PAD_GPIO_A15_PU(data)                   itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,data,PADCFG_PAD_GPIO_A15_PU_SHIFT,PADCFG_PAD_GPIO_A15_PU_MASK)
#define GET_PADCFG_PAD_GPIO_A15_SLEW                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,PADCFG_PAD_GPIO_A15_SLEW_SHIFT,PADCFG_PAD_GPIO_A15_SLEW_MASK)
#define SET_PADCFG_PAD_GPIO_A15_SLEW(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,data,PADCFG_PAD_GPIO_A15_SLEW_SHIFT,PADCFG_PAD_GPIO_A15_SLEW_MASK)
#define GET_PADCFG_PAD_GPIO_A15_SMT                        itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,PADCFG_PAD_GPIO_A15_SMT_SHIFT,PADCFG_PAD_GPIO_A15_SMT_MASK)
#define SET_PADCFG_PAD_GPIO_A15_SMT(data)                  itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,data,PADCFG_PAD_GPIO_A15_SMT_SHIFT,PADCFG_PAD_GPIO_A15_SMT_MASK)
#define GET_PADCFG_PAD_GPIO_A15_DEBOUNCE                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,PADCFG_PAD_GPIO_A15_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A15_DEBOUNCE_MASK)
#define SET_PADCFG_PAD_GPIO_A15_DEBOUNCE(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_44_ADDR,data,PADCFG_PAD_GPIO_A15_DEBOUNCE_SHIFT,PADCFG_PAD_GPIO_A15_DEBOUNCE_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O0_SEL                     itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O0_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O0_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O0_SEL(data)               itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O0_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O0_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O1_SEL                     itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O1_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O1_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O1_SEL(data)               itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O1_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O1_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O2_SEL                     itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O2_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O2_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O2_SEL(data)               itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O2_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O2_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O3_SEL                     itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O3_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O3_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O3_SEL(data)               itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O3_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O3_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O4_SEL                     itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O4_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O4_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O4_SEL(data)               itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O4_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O4_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O5_SEL                     itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O5_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O5_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O5_SEL(data)               itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O5_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O5_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O6_SEL                     itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O6_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O6_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O6_SEL(data)               itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O6_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O6_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O7_SEL                     itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O7_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O7_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O7_SEL(data)               itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O7_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O7_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O8_SEL                     itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O8_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O8_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O8_SEL(data)               itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O8_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O8_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O9_SEL                     itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O9_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O9_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O9_SEL(data)               itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O9_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O9_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O10_SEL                    itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O10_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O10_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O10_SEL(data)              itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O10_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O10_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_O11_SEL                    itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,U0_SYS0H_IOMUX_FMUX_O11_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O11_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_O11_SEL(data)              itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_48_ADDR,data,U0_SYS0H_IOMUX_FMUX_O11_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_O11_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN0_SEL                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN0_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN0_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN0_SEL(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN0_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN0_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN1_SEL                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN1_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN1_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN1_SEL(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN1_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN1_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN2_SEL                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN2_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN2_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN2_SEL(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN2_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN2_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN3_SEL                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN3_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN3_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN3_SEL(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN3_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN3_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN4_SEL                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN4_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN4_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN4_SEL(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN4_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN4_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN5_SEL                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN5_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN5_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN5_SEL(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN5_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN5_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN6_SEL                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN6_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN6_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN6_SEL(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN6_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN6_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN7_SEL                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN7_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN7_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN7_SEL(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN7_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN7_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN8_SEL                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN8_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN8_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN8_SEL(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN8_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN8_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN9_SEL                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN9_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN9_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN9_SEL(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN9_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN9_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN10_SEL                  itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN10_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN10_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN10_SEL(data)            itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN10_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN10_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FMUX_OEN11_SEL                  itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,U0_SYS0H_IOMUX_FMUX_OEN11_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN11_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FMUX_OEN11_SEL(data)            itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_52_ADDR,data,U0_SYS0H_IOMUX_FMUX_OEN11_SEL_SHIFT,U0_SYS0H_IOMUX_FMUX_OEN11_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_O_I_11_0_                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_56_ADDR,U0_SYS0H_IOMUX_O_I_11_0__SHIFT,U0_SYS0H_IOMUX_O_I_11_0__MASK)
#define GET_U0_SYS0H_IOMUX_FUNC0_SEL                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC0_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC0_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC0_SEL(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC0_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC0_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FUNC1_SEL                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC1_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC1_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC1_SEL(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC1_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC1_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FUNC2_SEL                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC2_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC2_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC2_SEL(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC2_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC2_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FUNC3_SEL                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC3_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC3_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC3_SEL(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC3_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC3_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FUNC4_SEL                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC4_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC4_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC4_SEL(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC4_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC4_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FUNC5_SEL                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC5_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC5_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC5_SEL(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC5_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC5_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FUNC6_SEL                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC6_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC6_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC6_SEL(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC6_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC6_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FUNC7_SEL                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC7_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC7_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC7_SEL(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC7_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC7_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FUNC8_SEL                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC8_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC8_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC8_SEL(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC8_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC8_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FUNC9_SEL                       itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC9_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC9_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC9_SEL(data)                 itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC9_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC9_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FUNC10_SEL                      itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC10_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC10_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC10_SEL(data)                itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC10_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC10_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_FUNC11_SEL                      itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,U0_SYS0H_IOMUX_FUNC11_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC11_SEL_MASK)
#define SET_U0_SYS0H_IOMUX_FUNC11_SEL(data)                itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_60_ADDR,data,U0_SYS0H_IOMUX_FUNC11_SEL_SHIFT,U0_SYS0H_IOMUX_FUNC11_SEL_MASK)
#define GET_U0_SYS0H_IOMUX_INT_EN_11_0_                    itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_64_ADDR,U0_SYS0H_IOMUX_INT_EN_11_0__SHIFT,U0_SYS0H_IOMUX_INT_EN_11_0__MASK)
#define SET_U0_SYS0H_IOMUX_INT_EN_11_0_(data)              itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_64_ADDR,data,U0_SYS0H_IOMUX_INT_EN_11_0__SHIFT,U0_SYS0H_IOMUX_INT_EN_11_0__MASK)
#define GET_U0_SYS0H_IOMUX_INT_STATUS_11_0_                itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_68_ADDR,U0_SYS0H_IOMUX_INT_STATUS_11_0__SHIFT,U0_SYS0H_IOMUX_INT_STATUS_11_0__MASK)
#define GET_U0_SYS0H_IOMUX_INT_CLR_11_0_                   itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_72_ADDR,U0_SYS0H_IOMUX_INT_CLR_11_0__SHIFT,U0_SYS0H_IOMUX_INT_CLR_11_0__MASK)
#define SET_U0_SYS0H_IOMUX_INT_CLR_11_0_(data)             itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_72_ADDR,data,U0_SYS0H_IOMUX_INT_CLR_11_0__SHIFT,U0_SYS0H_IOMUX_INT_CLR_11_0__MASK)
#define GET_U0_SYS0H_IOMUX_INT_EDGE_11_0_                  itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_76_ADDR,U0_SYS0H_IOMUX_INT_EDGE_11_0__SHIFT,U0_SYS0H_IOMUX_INT_EDGE_11_0__MASK)
#define SET_U0_SYS0H_IOMUX_INT_EDGE_11_0_(data)            itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_76_ADDR,data,U0_SYS0H_IOMUX_INT_EDGE_11_0__SHIFT,U0_SYS0H_IOMUX_INT_EDGE_11_0__MASK)
#define GET_U0_SYS0H_IOMUX_INT_HIGH_LEVEL_11_0_            itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_80_ADDR,U0_SYS0H_IOMUX_INT_HIGH_LEVEL_11_0__SHIFT,U0_SYS0H_IOMUX_INT_HIGH_LEVEL_11_0__MASK)
#define SET_U0_SYS0H_IOMUX_INT_HIGH_LEVEL_11_0_(data)      itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_80_ADDR,data,U0_SYS0H_IOMUX_INT_HIGH_LEVEL_11_0__SHIFT,U0_SYS0H_IOMUX_INT_HIGH_LEVEL_11_0__MASK)
#define GET_U0_SYS0H_IOMUX_INT_BOTH_EDGE_11_0_             itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_84_ADDR,U0_SYS0H_IOMUX_INT_BOTH_EDGE_11_0__SHIFT,U0_SYS0H_IOMUX_INT_BOTH_EDGE_11_0__MASK)
#define SET_U0_SYS0H_IOMUX_INT_BOTH_EDGE_11_0_(data)       itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_84_ADDR,data,U0_SYS0H_IOMUX_INT_BOTH_EDGE_11_0__SHIFT,U0_SYS0H_IOMUX_INT_BOTH_EDGE_11_0__MASK)
#define GET_U0_SYS0H_IOMUX_INT_RISING_EDGE_11_0_           itg_get_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_88_ADDR,U0_SYS0H_IOMUX_INT_RISING_EDGE_11_0__SHIFT,U0_SYS0H_IOMUX_INT_RISING_EDGE_11_0__MASK)
#define SET_U0_SYS0H_IOMUX_INT_RISING_EDGE_11_0_(data)     itg_set_reg(SYS0H_IOMUX_CFG__ITG__SYSCFG_88_ADDR,data,U0_SYS0H_IOMUX_INT_RISING_EDGE_11_0__SHIFT,U0_SYS0H_IOMUX_INT_RISING_EDGE_11_0__MASK)
