
#ifndef _SYS0_SECURE_CRG_MACRO_H_
#define _SYS0_SECURE_CRG_MACRO_H_

//#define SYS0_SECURE_CRG_BASE_ADDR 0x0
#define CLK_APB_MAIN_SYS0_SEC_CTRL_REG_ADDR                          (U0_SYS0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_SEC_600_CTRL_REG_ADDR                                    (U0_SYS0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define CLK_SEC_CORE_CTRL_REG_ADDR                                   (U0_SYS0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)


#define SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR       (U0_SYS0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)

#define SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR       (U0_SYS0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x10U)


#define CLK_APB_MAIN_SYS0_SEC_DIV_SHIFT                              0
#define CLK_APB_MAIN_SYS0_SEC_DIV_MASK                               0xFU
#define CLK_SEC_600_DIV_SHIFT                                        0
#define CLK_SEC_600_DIV_MASK                                         0x7U
#define CLK_SEC_CORE_DIV_SHIFT                                       0
#define CLK_SEC_CORE_DIV_MASK                                        0x7U




#define RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_SHIFT                     0
#define RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_MASK                      (0x1 << 0)
#define RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_ASSERT                    1
#define RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_CLEAR                     0
#define RSTN_U0_SYS0_SECURE_IPREG_TOP_PRSTN_SHIFT                    1
#define RSTN_U0_SYS0_SECURE_IPREG_TOP_PRSTN_MASK                     (0x1 << 1)
#define RSTN_U0_SYS0_SECURE_IPREG_TOP_PRSTN_ASSERT                   1
#define RSTN_U0_SYS0_SECURE_IPREG_TOP_PRSTN_CLEAR                    0
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_SHIFT                  2
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_MASK                   (0x1 << 2)
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_ASSERT                 1
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_CLEAR                  0

#define _DIVIDE_CLOCK_CLK_APB_MAIN_SYS0_SEC_(div) 			itg_set_reg(CLK_APB_MAIN_SYS0_SEC_CTRL_REG_ADDR, div, CLK_APB_MAIN_SYS0_SEC_DIV_SHIFT, CLK_APB_MAIN_SYS0_SEC_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_MAIN_SYS0_SEC_ 		itg_get_reg(CLK_APB_MAIN_SYS0_SEC_CTRL_REG_ADDR, CLK_APB_MAIN_SYS0_SEC_DIV_SHIFT, CLK_APB_MAIN_SYS0_SEC_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_SEC_600_(div) 			itg_set_reg(CLK_SEC_600_CTRL_REG_ADDR, div, CLK_SEC_600_DIV_SHIFT, CLK_SEC_600_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_SEC_600_ 		itg_get_reg(CLK_SEC_600_CTRL_REG_ADDR, CLK_SEC_600_DIV_SHIFT, CLK_SEC_600_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_SEC_CORE_(div) 			itg_set_reg(CLK_SEC_CORE_CTRL_REG_ADDR, div, CLK_SEC_CORE_DIV_SHIFT, CLK_SEC_CORE_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_SEC_CORE_ 		itg_get_reg(CLK_SEC_CORE_CTRL_REG_ADDR, CLK_SEC_CORE_DIV_SHIFT, CLK_SEC_CORE_DIV_MASK)



#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_ 	itg_get_reg(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_SHIFT, RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_ 	itg_assert_rst(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_ 	itg_clear_rst(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_SYS0_SECURE_IPREG_TOP_PRSTN_ 	itg_get_reg(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS0_SECURE_IPREG_TOP_PRSTN_SHIFT, RSTN_U0_SYS0_SECURE_IPREG_TOP_PRSTN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_SYS0_SECURE_IPREG_TOP_PRSTN_ 	itg_assert_rst(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS0_SECURE_IPREG_TOP_PRSTN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_SYS0_SECURE_IPREG_TOP_PRSTN_ 	itg_clear_rst(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS0_SECURE_IPREG_TOP_PRSTN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_ 	itg_get_reg(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_SHIFT, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_ 	itg_assert_rst(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_ 	itg_clear_rst(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_MASK)


#endif //_SYS0_SECURE_CRG_MACRO_H_
