//RTL tag v0.5.1

#define SYS0_SYSCONITG__SYSCFG_0_ADDR                      (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define U0_PLL7_PLL_FRAC_WIDTH                             0x18U
#define U0_PLL7_PLL_FRAC_SHIFT                             0x0U
#define U0_PLL7_PLL_FRAC_MASK                              0xFFFFFFU
#define SYS0_SYSCONITG__SYSCFG_4_ADDR                      (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define U0_PLL6_PLL_FRAC_WIDTH                             0x18U
#define U0_PLL6_PLL_FRAC_SHIFT                             0x0U
#define U0_PLL6_PLL_FRAC_MASK                              0xFFFFFFU
#define SYS0_SYSCONITG__SYSCFG_8_ADDR                      (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define U0_PLL5_PLL_FRAC_WIDTH                             0x18U
#define U0_PLL5_PLL_FRAC_SHIFT                             0x0U
#define U0_PLL5_PLL_FRAC_MASK                              0xFFFFFFU
#define SYS0_SYSCONITG__SYSCFG_12_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0xcU)
#define U0_PLL4_PLL_FRAC_WIDTH                             0x18U
#define U0_PLL4_PLL_FRAC_SHIFT                             0x0U
#define U0_PLL4_PLL_FRAC_MASK                              0xFFFFFFU
#define SYS0_SYSCONITG__SYSCFG_16_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define U0_PLL3_PLL_FRAC_WIDTH                             0x18U
#define U0_PLL3_PLL_FRAC_SHIFT                             0x0U
#define U0_PLL3_PLL_FRAC_MASK                              0xFFFFFFU
#define SYS0_SYSCONITG__SYSCFG_20_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define U0_PLL2_PLL_FRAC_WIDTH                             0x18U
#define U0_PLL2_PLL_FRAC_SHIFT                             0x0U
#define U0_PLL2_PLL_FRAC_MASK                              0xFFFFFFU
#define SYS0_SYSCONITG__SYSCFG_24_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define U0_PLL1_PLL_FRAC_WIDTH                             0x18U
#define U0_PLL1_PLL_FRAC_SHIFT                             0x0U
#define U0_PLL1_PLL_FRAC_MASK                              0xFFFFFFU
#define SYS0_SYSCONITG__SYSCFG_28_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x1cU)
#define U0_PLL0_PLL_FRAC_WIDTH                             0x18U
#define U0_PLL0_PLL_FRAC_SHIFT                             0x0U
#define U0_PLL0_PLL_FRAC_MASK                              0xFFFFFFU
#define SYS0_SYSCONITG__SYSCFG_32_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x20U)
#define U0_PLL7_PLL_OFFSETCALOUT_WIDTH                     0xCU
#define U0_PLL7_PLL_OFFSETCALOUT_SHIFT                     0x0U
#define U0_PLL7_PLL_OFFSETCALOUT_MASK                      0xFFFU
#define U0_PLL7_PLL_FBDIV_WIDTH                            0xCU
#define U0_PLL7_PLL_FBDIV_SHIFT                            0xCU
#define U0_PLL7_PLL_FBDIV_MASK                             0xFFF000U
#define SYS0_SYSCONITG__SYSCFG_36_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x24U)
#define U0_PLL6_PLL_OFFSETCALOUT_WIDTH                     0xCU
#define U0_PLL6_PLL_OFFSETCALOUT_SHIFT                     0x0U
#define U0_PLL6_PLL_OFFSETCALOUT_MASK                      0xFFFU
#define U0_PLL6_PLL_FBDIV_WIDTH                            0xCU
#define U0_PLL6_PLL_FBDIV_SHIFT                            0xCU
#define U0_PLL6_PLL_FBDIV_MASK                             0xFFF000U
#define SYS0_SYSCONITG__SYSCFG_40_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x28U)
#define U0_PLL5_PLL_OFFSETCALOUT_WIDTH                     0xCU
#define U0_PLL5_PLL_OFFSETCALOUT_SHIFT                     0x0U
#define U0_PLL5_PLL_OFFSETCALOUT_MASK                      0xFFFU
#define U0_PLL5_PLL_FBDIV_WIDTH                            0xCU
#define U0_PLL5_PLL_FBDIV_SHIFT                            0xCU
#define U0_PLL5_PLL_FBDIV_MASK                             0xFFF000U
#define SYS0_SYSCONITG__SYSCFG_44_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x2cU)
#define U0_PLL4_PLL_OFFSETCALOUT_WIDTH                     0xCU
#define U0_PLL4_PLL_OFFSETCALOUT_SHIFT                     0x0U
#define U0_PLL4_PLL_OFFSETCALOUT_MASK                      0xFFFU
#define U0_PLL4_PLL_FBDIV_WIDTH                            0xCU
#define U0_PLL4_PLL_FBDIV_SHIFT                            0xCU
#define U0_PLL4_PLL_FBDIV_MASK                             0xFFF000U
#define SYS0_SYSCONITG__SYSCFG_48_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x30U)
#define U0_PLL3_PLL_OFFSETCALOUT_WIDTH                     0xCU
#define U0_PLL3_PLL_OFFSETCALOUT_SHIFT                     0x0U
#define U0_PLL3_PLL_OFFSETCALOUT_MASK                      0xFFFU
#define U0_PLL3_PLL_FBDIV_WIDTH                            0xCU
#define U0_PLL3_PLL_FBDIV_SHIFT                            0xCU
#define U0_PLL3_PLL_FBDIV_MASK                             0xFFF000U
#define SYS0_SYSCONITG__SYSCFG_52_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x34U)
#define U0_PLL2_PLL_OFFSETCALOUT_WIDTH                     0xCU
#define U0_PLL2_PLL_OFFSETCALOUT_SHIFT                     0x0U
#define U0_PLL2_PLL_OFFSETCALOUT_MASK                      0xFFFU
#define U0_PLL2_PLL_FBDIV_WIDTH                            0xCU
#define U0_PLL2_PLL_FBDIV_SHIFT                            0xCU
#define U0_PLL2_PLL_FBDIV_MASK                             0xFFF000U
#define SYS0_SYSCONITG__SYSCFG_56_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x38U)
#define U0_PLL1_PLL_OFFSETCALOUT_WIDTH                     0xCU
#define U0_PLL1_PLL_OFFSETCALOUT_SHIFT                     0x0U
#define U0_PLL1_PLL_OFFSETCALOUT_MASK                      0xFFFU
#define U0_PLL1_PLL_FBDIV_WIDTH                            0xCU
#define U0_PLL1_PLL_FBDIV_SHIFT                            0xCU
#define U0_PLL1_PLL_FBDIV_MASK                             0xFFF000U
#define SYS0_SYSCONITG__SYSCFG_60_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x3cU)
#define U0_PLL0_PLL_OFFSETCALOUT_WIDTH                     0xCU
#define U0_PLL0_PLL_OFFSETCALOUT_SHIFT                     0x0U
#define U0_PLL0_PLL_OFFSETCALOUT_MASK                      0xFFFU
#define U0_PLL0_PLL_FBDIV_WIDTH                            0xCU
#define U0_PLL0_PLL_FBDIV_SHIFT                            0xCU
#define U0_PLL0_PLL_FBDIV_MASK                             0xFFF000U
#define U0_PLL7_PLL_REFDIV_WIDTH                           0x6U
#define U0_PLL7_PLL_REFDIV_SHIFT                           0x18U
#define U0_PLL7_PLL_REFDIV_MASK                            0x3F000000U
#define SYS0_SYSCONITG__SYSCFG_64_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x40U)
#define U0_PLL6_PLL_REFDIV_WIDTH                           0x6U
#define U0_PLL6_PLL_REFDIV_SHIFT                           0x0U
#define U0_PLL6_PLL_REFDIV_MASK                            0x3FU
#define U0_PLL5_PLL_REFDIV_WIDTH                           0x6U
#define U0_PLL5_PLL_REFDIV_SHIFT                           0x8U
#define U0_PLL5_PLL_REFDIV_MASK                            0x3F00U
#define U0_PLL4_PLL_REFDIV_WIDTH                           0x6U
#define U0_PLL4_PLL_REFDIV_SHIFT                           0x10U
#define U0_PLL4_PLL_REFDIV_MASK                            0x3F0000U
#define U0_PLL3_PLL_REFDIV_WIDTH                           0x6U
#define U0_PLL3_PLL_REFDIV_SHIFT                           0x18U
#define U0_PLL3_PLL_REFDIV_MASK                            0x3F000000U
#define SYS0_SYSCONITG__SYSCFG_68_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x44U)
#define U0_PLL2_PLL_REFDIV_WIDTH                           0x6U
#define U0_PLL2_PLL_REFDIV_SHIFT                           0x0U
#define U0_PLL2_PLL_REFDIV_MASK                            0x3FU
#define U0_PLL1_PLL_REFDIV_WIDTH                           0x6U
#define U0_PLL1_PLL_REFDIV_SHIFT                           0x8U
#define U0_PLL1_PLL_REFDIV_MASK                            0x3F00U
#define U0_PLL0_PLL_REFDIV_WIDTH                           0x6U
#define U0_PLL0_PLL_REFDIV_SHIFT                           0x10U
#define U0_PLL0_PLL_REFDIV_MASK                            0x3F0000U
#define U0_PLL7_PLL_OFFSETCALCNT_WIDTH                     0x3U
#define U0_PLL7_PLL_OFFSETCALCNT_SHIFT                     0x18U
#define U0_PLL7_PLL_OFFSETCALCNT_MASK                      0x7000000U
#define U0_PLL6_PLL_OFFSETCALCNT_WIDTH                     0x3U
#define U0_PLL6_PLL_OFFSETCALCNT_SHIFT                     0x1CU
#define U0_PLL6_PLL_OFFSETCALCNT_MASK                      0x70000000U
#define SYS0_SYSCONITG__SYSCFG_72_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x48U)
#define U0_PLL5_PLL_OFFSETCALCNT_WIDTH                     0x3U
#define U0_PLL5_PLL_OFFSETCALCNT_SHIFT                     0x0U
#define U0_PLL5_PLL_OFFSETCALCNT_MASK                      0x7U
#define U0_PLL4_PLL_OFFSETCALCNT_WIDTH                     0x3U
#define U0_PLL4_PLL_OFFSETCALCNT_SHIFT                     0x4U
#define U0_PLL4_PLL_OFFSETCALCNT_MASK                      0x70U
#define U0_PLL3_PLL_OFFSETCALCNT_WIDTH                     0x3U
#define U0_PLL3_PLL_OFFSETCALCNT_SHIFT                     0x8U
#define U0_PLL3_PLL_OFFSETCALCNT_MASK                      0x700U
#define U0_PLL2_PLL_OFFSETCALCNT_WIDTH                     0x3U
#define U0_PLL2_PLL_OFFSETCALCNT_SHIFT                     0xCU
#define U0_PLL2_PLL_OFFSETCALCNT_MASK                      0x7000U
#define U0_PLL1_PLL_OFFSETCALCNT_WIDTH                     0x3U
#define U0_PLL1_PLL_OFFSETCALCNT_SHIFT                     0x10U
#define U0_PLL1_PLL_OFFSETCALCNT_MASK                      0x70000U
#define U0_PLL0_PLL_OFFSETCALCNT_WIDTH                     0x3U
#define U0_PLL0_PLL_OFFSETCALCNT_SHIFT                     0x14U
#define U0_PLL0_PLL_OFFSETCALCNT_MASK                      0x700000U
#define U0_PLL7_PLL_POSTDIV_WIDTH                          0x2U
#define U0_PLL7_PLL_POSTDIV_SHIFT                          0x18U
#define U0_PLL7_PLL_POSTDIV_MASK                           0x3000000U
#define U0_PLL6_PLL_POSTDIV_WIDTH                          0x2U
#define U0_PLL6_PLL_POSTDIV_SHIFT                          0x1CU
#define U0_PLL6_PLL_POSTDIV_MASK                           0x30000000U
#define SYS0_SYSCONITG__SYSCFG_76_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x4cU)
#define U0_PLL5_PLL_POSTDIV_WIDTH                          0x2U
#define U0_PLL5_PLL_POSTDIV_SHIFT                          0x0U
#define U0_PLL5_PLL_POSTDIV_MASK                           0x3U
#define U0_PLL4_PLL_POSTDIV_WIDTH                          0x2U
#define U0_PLL4_PLL_POSTDIV_SHIFT                          0x4U
#define U0_PLL4_PLL_POSTDIV_MASK                           0x30U
#define U0_PLL3_PLL_POSTDIV_WIDTH                          0x2U
#define U0_PLL3_PLL_POSTDIV_SHIFT                          0x8U
#define U0_PLL3_PLL_POSTDIV_MASK                           0x300U
#define U0_PLL2_PLL_POSTDIV_WIDTH                          0x2U
#define U0_PLL2_PLL_POSTDIV_SHIFT                          0xCU
#define U0_PLL2_PLL_POSTDIV_MASK                           0x3000U
#define U0_PLL1_PLL_POSTDIV_WIDTH                          0x2U
#define U0_PLL1_PLL_POSTDIV_SHIFT                          0x10U
#define U0_PLL1_PLL_POSTDIV_MASK                           0x30000U
#define U0_PLL0_PLL_POSTDIV_WIDTH                          0x2U
#define U0_PLL0_PLL_POSTDIV_SHIFT                          0x14U
#define U0_PLL0_PLL_POSTDIV_MASK                           0x300000U
#define U0_PLL7_PLL_PD_WIDTH                               0x1U
#define U0_PLL7_PLL_PD_SHIFT                               0x18U
#define U0_PLL7_PLL_PD_MASK                                0x1000000U
#define U0_PLL7_PLL_OFFSETFASTCAL_WIDTH                    0x1U
#define U0_PLL7_PLL_OFFSETFASTCAL_SHIFT                    0x19U
#define U0_PLL7_PLL_OFFSETFASTCAL_MASK                     0x2000000U
#define U0_PLL7_PLL_OFFSETCALLOCK_WIDTH                    0x1U
#define U0_PLL7_PLL_OFFSETCALLOCK_SHIFT                    0x1AU
#define U0_PLL7_PLL_OFFSETCALLOCK_MASK                     0x4000000U
#define U0_PLL7_PLL_LOCK_WIDTH                             0x1U
#define U0_PLL7_PLL_LOCK_SHIFT                             0x1BU
#define U0_PLL7_PLL_LOCK_MASK                              0x8000000U
#define U0_PLL7_PLL_FOUTVCOP_EN_WIDTH                      0x1U
#define U0_PLL7_PLL_FOUTVCOP_EN_SHIFT                      0x1CU
#define U0_PLL7_PLL_FOUTVCOP_EN_MASK                       0x10000000U
#define U0_PLL7_PLL_FOUTPOSTDIVPD_WIDTH                    0x1U
#define U0_PLL7_PLL_FOUTPOSTDIVPD_SHIFT                    0x1DU
#define U0_PLL7_PLL_FOUTPOSTDIVPD_MASK                     0x20000000U
#define U0_PLL7_PLL_FOUTPOSTDIV_EN_WIDTH                   0x1U
#define U0_PLL7_PLL_FOUTPOSTDIV_EN_SHIFT                   0x1EU
#define U0_PLL7_PLL_FOUTPOSTDIV_EN_MASK                    0x40000000U
#define U0_PLL7_PLL_DSMPD_WIDTH                            0x1U
#define U0_PLL7_PLL_DSMPD_SHIFT                            0x1FU
#define U0_PLL7_PLL_DSMPD_MASK                             0x80000000U
#define SYS0_SYSCONITG__SYSCFG_80_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x50U)
#define U0_PLL7_PLL_BYPASS_WIDTH                           0x1U
#define U0_PLL7_PLL_BYPASS_SHIFT                           0x0U
#define U0_PLL7_PLL_BYPASS_MASK                            0x1U
#define U0_PLL6_PLL_PD_WIDTH                               0x1U
#define U0_PLL6_PLL_PD_SHIFT                               0x1U
#define U0_PLL6_PLL_PD_MASK                                0x2U
#define U0_PLL6_PLL_OFFSETFASTCAL_WIDTH                    0x1U
#define U0_PLL6_PLL_OFFSETFASTCAL_SHIFT                    0x2U
#define U0_PLL6_PLL_OFFSETFASTCAL_MASK                     0x4U
#define U0_PLL6_PLL_OFFSETCALLOCK_WIDTH                    0x1U
#define U0_PLL6_PLL_OFFSETCALLOCK_SHIFT                    0x3U
#define U0_PLL6_PLL_OFFSETCALLOCK_MASK                     0x8U
#define U0_PLL6_PLL_LOCK_WIDTH                             0x1U
#define U0_PLL6_PLL_LOCK_SHIFT                             0x4U
#define U0_PLL6_PLL_LOCK_MASK                              0x10U
#define U0_PLL6_PLL_FOUTVCOP_EN_WIDTH                      0x1U
#define U0_PLL6_PLL_FOUTVCOP_EN_SHIFT                      0x5U
#define U0_PLL6_PLL_FOUTVCOP_EN_MASK                       0x20U
#define U0_PLL6_PLL_FOUTPOSTDIVPD_WIDTH                    0x1U
#define U0_PLL6_PLL_FOUTPOSTDIVPD_SHIFT                    0x6U
#define U0_PLL6_PLL_FOUTPOSTDIVPD_MASK                     0x40U
#define U0_PLL6_PLL_FOUTPOSTDIV_EN_WIDTH                   0x1U
#define U0_PLL6_PLL_FOUTPOSTDIV_EN_SHIFT                   0x7U
#define U0_PLL6_PLL_FOUTPOSTDIV_EN_MASK                    0x80U
#define U0_PLL6_PLL_DSMPD_WIDTH                            0x1U
#define U0_PLL6_PLL_DSMPD_SHIFT                            0x8U
#define U0_PLL6_PLL_DSMPD_MASK                             0x100U
#define U0_PLL6_PLL_BYPASS_WIDTH                           0x1U
#define U0_PLL6_PLL_BYPASS_SHIFT                           0x9U
#define U0_PLL6_PLL_BYPASS_MASK                            0x200U
#define U0_PLL5_PLL_PD_WIDTH                               0x1U
#define U0_PLL5_PLL_PD_SHIFT                               0xAU
#define U0_PLL5_PLL_PD_MASK                                0x400U
#define U0_PLL5_PLL_OFFSETFASTCAL_WIDTH                    0x1U
#define U0_PLL5_PLL_OFFSETFASTCAL_SHIFT                    0xBU
#define U0_PLL5_PLL_OFFSETFASTCAL_MASK                     0x800U
#define U0_PLL5_PLL_OFFSETCALLOCK_WIDTH                    0x1U
#define U0_PLL5_PLL_OFFSETCALLOCK_SHIFT                    0xCU
#define U0_PLL5_PLL_OFFSETCALLOCK_MASK                     0x1000U
#define U0_PLL5_PLL_LOCK_WIDTH                             0x1U
#define U0_PLL5_PLL_LOCK_SHIFT                             0xDU
#define U0_PLL5_PLL_LOCK_MASK                              0x2000U
#define U0_PLL5_PLL_FOUTVCOP_EN_WIDTH                      0x1U
#define U0_PLL5_PLL_FOUTVCOP_EN_SHIFT                      0xEU
#define U0_PLL5_PLL_FOUTVCOP_EN_MASK                       0x4000U
#define U0_PLL5_PLL_FOUTPOSTDIVPD_WIDTH                    0x1U
#define U0_PLL5_PLL_FOUTPOSTDIVPD_SHIFT                    0xFU
#define U0_PLL5_PLL_FOUTPOSTDIVPD_MASK                     0x8000U
#define U0_PLL5_PLL_FOUTPOSTDIV_EN_WIDTH                   0x1U
#define U0_PLL5_PLL_FOUTPOSTDIV_EN_SHIFT                   0x10U
#define U0_PLL5_PLL_FOUTPOSTDIV_EN_MASK                    0x10000U
#define U0_PLL5_PLL_DSMPD_WIDTH                            0x1U
#define U0_PLL5_PLL_DSMPD_SHIFT                            0x11U
#define U0_PLL5_PLL_DSMPD_MASK                             0x20000U
#define U0_PLL5_PLL_BYPASS_WIDTH                           0x1U
#define U0_PLL5_PLL_BYPASS_SHIFT                           0x12U
#define U0_PLL5_PLL_BYPASS_MASK                            0x40000U
#define U0_PLL4_PLL_PD_WIDTH                               0x1U
#define U0_PLL4_PLL_PD_SHIFT                               0x13U
#define U0_PLL4_PLL_PD_MASK                                0x80000U
#define U0_PLL4_PLL_OFFSETFASTCAL_WIDTH                    0x1U
#define U0_PLL4_PLL_OFFSETFASTCAL_SHIFT                    0x14U
#define U0_PLL4_PLL_OFFSETFASTCAL_MASK                     0x100000U
#define U0_PLL4_PLL_OFFSETCALLOCK_WIDTH                    0x1U
#define U0_PLL4_PLL_OFFSETCALLOCK_SHIFT                    0x15U
#define U0_PLL4_PLL_OFFSETCALLOCK_MASK                     0x200000U
#define U0_PLL4_PLL_LOCK_WIDTH                             0x1U
#define U0_PLL4_PLL_LOCK_SHIFT                             0x16U
#define U0_PLL4_PLL_LOCK_MASK                              0x400000U
#define U0_PLL4_PLL_FOUTVCOP_EN_WIDTH                      0x1U
#define U0_PLL4_PLL_FOUTVCOP_EN_SHIFT                      0x17U
#define U0_PLL4_PLL_FOUTVCOP_EN_MASK                       0x800000U
#define U0_PLL4_PLL_FOUTPOSTDIVPD_WIDTH                    0x1U
#define U0_PLL4_PLL_FOUTPOSTDIVPD_SHIFT                    0x18U
#define U0_PLL4_PLL_FOUTPOSTDIVPD_MASK                     0x1000000U
#define U0_PLL4_PLL_FOUTPOSTDIV_EN_WIDTH                   0x1U
#define U0_PLL4_PLL_FOUTPOSTDIV_EN_SHIFT                   0x19U
#define U0_PLL4_PLL_FOUTPOSTDIV_EN_MASK                    0x2000000U
#define U0_PLL4_PLL_DSMPD_WIDTH                            0x1U
#define U0_PLL4_PLL_DSMPD_SHIFT                            0x1AU
#define U0_PLL4_PLL_DSMPD_MASK                             0x4000000U
#define U0_PLL4_PLL_BYPASS_WIDTH                           0x1U
#define U0_PLL4_PLL_BYPASS_SHIFT                           0x1BU
#define U0_PLL4_PLL_BYPASS_MASK                            0x8000000U
#define U0_PLL3_PLL_PD_WIDTH                               0x1U
#define U0_PLL3_PLL_PD_SHIFT                               0x1CU
#define U0_PLL3_PLL_PD_MASK                                0x10000000U
#define U0_PLL3_PLL_OFFSETFASTCAL_WIDTH                    0x1U
#define U0_PLL3_PLL_OFFSETFASTCAL_SHIFT                    0x1DU
#define U0_PLL3_PLL_OFFSETFASTCAL_MASK                     0x20000000U
#define U0_PLL3_PLL_OFFSETCALLOCK_WIDTH                    0x1U
#define U0_PLL3_PLL_OFFSETCALLOCK_SHIFT                    0x1EU
#define U0_PLL3_PLL_OFFSETCALLOCK_MASK                     0x40000000U
#define U0_PLL3_PLL_LOCK_WIDTH                             0x1U
#define U0_PLL3_PLL_LOCK_SHIFT                             0x1FU
#define U0_PLL3_PLL_LOCK_MASK                              0x80000000U
#define SYS0_SYSCONITG__SYSCFG_84_ADDR                     (U0_SYS0_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x54U)
#define U0_PLL3_PLL_FOUTVCOP_EN_WIDTH                      0x1U
#define U0_PLL3_PLL_FOUTVCOP_EN_SHIFT                      0x0U
#define U0_PLL3_PLL_FOUTVCOP_EN_MASK                       0x1U
#define U0_PLL3_PLL_FOUTPOSTDIVPD_WIDTH                    0x1U
#define U0_PLL3_PLL_FOUTPOSTDIVPD_SHIFT                    0x1U
#define U0_PLL3_PLL_FOUTPOSTDIVPD_MASK                     0x2U
#define U0_PLL3_PLL_FOUTPOSTDIV_EN_WIDTH                   0x1U
#define U0_PLL3_PLL_FOUTPOSTDIV_EN_SHIFT                   0x2U
#define U0_PLL3_PLL_FOUTPOSTDIV_EN_MASK                    0x4U
#define U0_PLL3_PLL_DSMPD_WIDTH                            0x1U
#define U0_PLL3_PLL_DSMPD_SHIFT                            0x3U
#define U0_PLL3_PLL_DSMPD_MASK                             0x8U
#define U0_PLL3_PLL_BYPASS_WIDTH                           0x1U
#define U0_PLL3_PLL_BYPASS_SHIFT                           0x4U
#define U0_PLL3_PLL_BYPASS_MASK                            0x10U
#define U0_PLL2_PLL_PD_WIDTH                               0x1U
#define U0_PLL2_PLL_PD_SHIFT                               0x5U
#define U0_PLL2_PLL_PD_MASK                                0x20U
#define U0_PLL2_PLL_OFFSETFASTCAL_WIDTH                    0x1U
#define U0_PLL2_PLL_OFFSETFASTCAL_SHIFT                    0x6U
#define U0_PLL2_PLL_OFFSETFASTCAL_MASK                     0x40U
#define U0_PLL2_PLL_OFFSETCALLOCK_WIDTH                    0x1U
#define U0_PLL2_PLL_OFFSETCALLOCK_SHIFT                    0x7U
#define U0_PLL2_PLL_OFFSETCALLOCK_MASK                     0x80U
#define U0_PLL2_PLL_LOCK_WIDTH                             0x1U
#define U0_PLL2_PLL_LOCK_SHIFT                             0x8U
#define U0_PLL2_PLL_LOCK_MASK                              0x100U
#define U0_PLL2_PLL_FOUTVCOP_EN_WIDTH                      0x1U
#define U0_PLL2_PLL_FOUTVCOP_EN_SHIFT                      0x9U
#define U0_PLL2_PLL_FOUTVCOP_EN_MASK                       0x200U
#define U0_PLL2_PLL_FOUTPOSTDIVPD_WIDTH                    0x1U
#define U0_PLL2_PLL_FOUTPOSTDIVPD_SHIFT                    0xAU
#define U0_PLL2_PLL_FOUTPOSTDIVPD_MASK                     0x400U
#define U0_PLL2_PLL_FOUTPOSTDIV_EN_WIDTH                   0x1U
#define U0_PLL2_PLL_FOUTPOSTDIV_EN_SHIFT                   0xBU
#define U0_PLL2_PLL_FOUTPOSTDIV_EN_MASK                    0x800U
#define U0_PLL2_PLL_DSMPD_WIDTH                            0x1U
#define U0_PLL2_PLL_DSMPD_SHIFT                            0xCU
#define U0_PLL2_PLL_DSMPD_MASK                             0x1000U
#define U0_PLL2_PLL_BYPASS_WIDTH                           0x1U
#define U0_PLL2_PLL_BYPASS_SHIFT                           0xDU
#define U0_PLL2_PLL_BYPASS_MASK                            0x2000U
#define U0_PLL1_PLL_PD_WIDTH                               0x1U
#define U0_PLL1_PLL_PD_SHIFT                               0xEU
#define U0_PLL1_PLL_PD_MASK                                0x4000U
#define U0_PLL1_PLL_OFFSETFASTCAL_WIDTH                    0x1U
#define U0_PLL1_PLL_OFFSETFASTCAL_SHIFT                    0xFU
#define U0_PLL1_PLL_OFFSETFASTCAL_MASK                     0x8000U
#define U0_PLL1_PLL_OFFSETCALLOCK_WIDTH                    0x1U
#define U0_PLL1_PLL_OFFSETCALLOCK_SHIFT                    0x10U
#define U0_PLL1_PLL_OFFSETCALLOCK_MASK                     0x10000U
#define U0_PLL1_PLL_LOCK_WIDTH                             0x1U
#define U0_PLL1_PLL_LOCK_SHIFT                             0x11U
#define U0_PLL1_PLL_LOCK_MASK                              0x20000U
#define U0_PLL1_PLL_FOUTVCOP_EN_WIDTH                      0x1U
#define U0_PLL1_PLL_FOUTVCOP_EN_SHIFT                      0x12U
#define U0_PLL1_PLL_FOUTVCOP_EN_MASK                       0x40000U
#define U0_PLL1_PLL_FOUTPOSTDIVPD_WIDTH                    0x1U
#define U0_PLL1_PLL_FOUTPOSTDIVPD_SHIFT                    0x13U
#define U0_PLL1_PLL_FOUTPOSTDIVPD_MASK                     0x80000U
#define U0_PLL1_PLL_FOUTPOSTDIV_EN_WIDTH                   0x1U
#define U0_PLL1_PLL_FOUTPOSTDIV_EN_SHIFT                   0x14U
#define U0_PLL1_PLL_FOUTPOSTDIV_EN_MASK                    0x100000U
#define U0_PLL1_PLL_DSMPD_WIDTH                            0x1U
#define U0_PLL1_PLL_DSMPD_SHIFT                            0x15U
#define U0_PLL1_PLL_DSMPD_MASK                             0x200000U
#define U0_PLL1_PLL_BYPASS_WIDTH                           0x1U
#define U0_PLL1_PLL_BYPASS_SHIFT                           0x16U
#define U0_PLL1_PLL_BYPASS_MASK                            0x400000U
#define U0_PLL0_PLL_PD_WIDTH                               0x1U
#define U0_PLL0_PLL_PD_SHIFT                               0x17U
#define U0_PLL0_PLL_PD_MASK                                0x800000U
#define U0_PLL0_PLL_OFFSETFASTCAL_WIDTH                    0x1U
#define U0_PLL0_PLL_OFFSETFASTCAL_SHIFT                    0x18U
#define U0_PLL0_PLL_OFFSETFASTCAL_MASK                     0x1000000U
#define U0_PLL0_PLL_OFFSETCALLOCK_WIDTH                    0x1U
#define U0_PLL0_PLL_OFFSETCALLOCK_SHIFT                    0x19U
#define U0_PLL0_PLL_OFFSETCALLOCK_MASK                     0x2000000U
#define U0_PLL0_PLL_LOCK_WIDTH                             0x1U
#define U0_PLL0_PLL_LOCK_SHIFT                             0x1AU
#define U0_PLL0_PLL_LOCK_MASK                              0x4000000U
#define U0_PLL0_PLL_FOUTVCOP_EN_WIDTH                      0x1U
#define U0_PLL0_PLL_FOUTVCOP_EN_SHIFT                      0x1BU
#define U0_PLL0_PLL_FOUTVCOP_EN_MASK                       0x8000000U
#define U0_PLL0_PLL_FOUTPOSTDIVPD_WIDTH                    0x1U
#define U0_PLL0_PLL_FOUTPOSTDIVPD_SHIFT                    0x1CU
#define U0_PLL0_PLL_FOUTPOSTDIVPD_MASK                     0x10000000U
#define U0_PLL0_PLL_FOUTPOSTDIV_EN_WIDTH                   0x1U
#define U0_PLL0_PLL_FOUTPOSTDIV_EN_SHIFT                   0x1DU
#define U0_PLL0_PLL_FOUTPOSTDIV_EN_MASK                    0x20000000U
#define U0_PLL0_PLL_DSMPD_WIDTH                            0x1U
#define U0_PLL0_PLL_DSMPD_SHIFT                            0x1EU
#define U0_PLL0_PLL_DSMPD_MASK                             0x40000000U
#define U0_PLL0_PLL_BYPASS_WIDTH                           0x1U
#define U0_PLL0_PLL_BYPASS_SHIFT                           0x1FU
#define U0_PLL0_PLL_BYPASS_MASK                            0x80000000U
#define GET_U0_PLL7_PLL_FRAC                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_0_ADDR,U0_PLL7_PLL_FRAC_SHIFT,U0_PLL7_PLL_FRAC_MASK)
#define SET_U0_PLL7_PLL_FRAC(data)                         itg_set_reg(SYS0_SYSCONITG__SYSCFG_0_ADDR,data,U0_PLL7_PLL_FRAC_SHIFT,U0_PLL7_PLL_FRAC_MASK)
#define GET_U0_PLL6_PLL_FRAC                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_4_ADDR,U0_PLL6_PLL_FRAC_SHIFT,U0_PLL6_PLL_FRAC_MASK)
#define SET_U0_PLL6_PLL_FRAC(data)                         itg_set_reg(SYS0_SYSCONITG__SYSCFG_4_ADDR,data,U0_PLL6_PLL_FRAC_SHIFT,U0_PLL6_PLL_FRAC_MASK)
#define GET_U0_PLL5_PLL_FRAC                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_8_ADDR,U0_PLL5_PLL_FRAC_SHIFT,U0_PLL5_PLL_FRAC_MASK)
#define SET_U0_PLL5_PLL_FRAC(data)                         itg_set_reg(SYS0_SYSCONITG__SYSCFG_8_ADDR,data,U0_PLL5_PLL_FRAC_SHIFT,U0_PLL5_PLL_FRAC_MASK)
#define GET_U0_PLL4_PLL_FRAC                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_12_ADDR,U0_PLL4_PLL_FRAC_SHIFT,U0_PLL4_PLL_FRAC_MASK)
#define SET_U0_PLL4_PLL_FRAC(data)                         itg_set_reg(SYS0_SYSCONITG__SYSCFG_12_ADDR,data,U0_PLL4_PLL_FRAC_SHIFT,U0_PLL4_PLL_FRAC_MASK)
#define GET_U0_PLL3_PLL_FRAC                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_16_ADDR,U0_PLL3_PLL_FRAC_SHIFT,U0_PLL3_PLL_FRAC_MASK)
#define SET_U0_PLL3_PLL_FRAC(data)                         itg_set_reg(SYS0_SYSCONITG__SYSCFG_16_ADDR,data,U0_PLL3_PLL_FRAC_SHIFT,U0_PLL3_PLL_FRAC_MASK)
#define GET_U0_PLL2_PLL_FRAC                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_20_ADDR,U0_PLL2_PLL_FRAC_SHIFT,U0_PLL2_PLL_FRAC_MASK)
#define SET_U0_PLL2_PLL_FRAC(data)                         itg_set_reg(SYS0_SYSCONITG__SYSCFG_20_ADDR,data,U0_PLL2_PLL_FRAC_SHIFT,U0_PLL2_PLL_FRAC_MASK)
#define GET_U0_PLL1_PLL_FRAC                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_24_ADDR,U0_PLL1_PLL_FRAC_SHIFT,U0_PLL1_PLL_FRAC_MASK)
#define SET_U0_PLL1_PLL_FRAC(data)                         itg_set_reg(SYS0_SYSCONITG__SYSCFG_24_ADDR,data,U0_PLL1_PLL_FRAC_SHIFT,U0_PLL1_PLL_FRAC_MASK)
#define GET_U0_PLL0_PLL_FRAC                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_28_ADDR,U0_PLL0_PLL_FRAC_SHIFT,U0_PLL0_PLL_FRAC_MASK)
#define SET_U0_PLL0_PLL_FRAC(data)                         itg_set_reg(SYS0_SYSCONITG__SYSCFG_28_ADDR,data,U0_PLL0_PLL_FRAC_SHIFT,U0_PLL0_PLL_FRAC_MASK)
#define GET_U0_PLL7_PLL_OFFSETCALOUT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_32_ADDR,U0_PLL7_PLL_OFFSETCALOUT_SHIFT,U0_PLL7_PLL_OFFSETCALOUT_MASK)
#define GET_U0_PLL7_PLL_FBDIV                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_32_ADDR,U0_PLL7_PLL_FBDIV_SHIFT,U0_PLL7_PLL_FBDIV_MASK)
#define SET_U0_PLL7_PLL_FBDIV(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_32_ADDR,data,U0_PLL7_PLL_FBDIV_SHIFT,U0_PLL7_PLL_FBDIV_MASK)
#define GET_U0_PLL6_PLL_OFFSETCALOUT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_36_ADDR,U0_PLL6_PLL_OFFSETCALOUT_SHIFT,U0_PLL6_PLL_OFFSETCALOUT_MASK)
#define GET_U0_PLL6_PLL_FBDIV                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_36_ADDR,U0_PLL6_PLL_FBDIV_SHIFT,U0_PLL6_PLL_FBDIV_MASK)
#define SET_U0_PLL6_PLL_FBDIV(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_36_ADDR,data,U0_PLL6_PLL_FBDIV_SHIFT,U0_PLL6_PLL_FBDIV_MASK)
#define GET_U0_PLL5_PLL_OFFSETCALOUT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_40_ADDR,U0_PLL5_PLL_OFFSETCALOUT_SHIFT,U0_PLL5_PLL_OFFSETCALOUT_MASK)
#define GET_U0_PLL5_PLL_FBDIV                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_40_ADDR,U0_PLL5_PLL_FBDIV_SHIFT,U0_PLL5_PLL_FBDIV_MASK)
#define SET_U0_PLL5_PLL_FBDIV(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_40_ADDR,data,U0_PLL5_PLL_FBDIV_SHIFT,U0_PLL5_PLL_FBDIV_MASK)
#define GET_U0_PLL4_PLL_OFFSETCALOUT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_44_ADDR,U0_PLL4_PLL_OFFSETCALOUT_SHIFT,U0_PLL4_PLL_OFFSETCALOUT_MASK)
#define GET_U0_PLL4_PLL_FBDIV                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_44_ADDR,U0_PLL4_PLL_FBDIV_SHIFT,U0_PLL4_PLL_FBDIV_MASK)
#define SET_U0_PLL4_PLL_FBDIV(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_44_ADDR,data,U0_PLL4_PLL_FBDIV_SHIFT,U0_PLL4_PLL_FBDIV_MASK)
#define GET_U0_PLL3_PLL_OFFSETCALOUT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_48_ADDR,U0_PLL3_PLL_OFFSETCALOUT_SHIFT,U0_PLL3_PLL_OFFSETCALOUT_MASK)
#define GET_U0_PLL3_PLL_FBDIV                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_48_ADDR,U0_PLL3_PLL_FBDIV_SHIFT,U0_PLL3_PLL_FBDIV_MASK)
#define SET_U0_PLL3_PLL_FBDIV(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_48_ADDR,data,U0_PLL3_PLL_FBDIV_SHIFT,U0_PLL3_PLL_FBDIV_MASK)
#define GET_U0_PLL2_PLL_OFFSETCALOUT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_52_ADDR,U0_PLL2_PLL_OFFSETCALOUT_SHIFT,U0_PLL2_PLL_OFFSETCALOUT_MASK)
#define GET_U0_PLL2_PLL_FBDIV                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_52_ADDR,U0_PLL2_PLL_FBDIV_SHIFT,U0_PLL2_PLL_FBDIV_MASK)
#define SET_U0_PLL2_PLL_FBDIV(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_52_ADDR,data,U0_PLL2_PLL_FBDIV_SHIFT,U0_PLL2_PLL_FBDIV_MASK)
#define GET_U0_PLL1_PLL_OFFSETCALOUT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_56_ADDR,U0_PLL1_PLL_OFFSETCALOUT_SHIFT,U0_PLL1_PLL_OFFSETCALOUT_MASK)
#define GET_U0_PLL1_PLL_FBDIV                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_56_ADDR,U0_PLL1_PLL_FBDIV_SHIFT,U0_PLL1_PLL_FBDIV_MASK)
#define SET_U0_PLL1_PLL_FBDIV(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_56_ADDR,data,U0_PLL1_PLL_FBDIV_SHIFT,U0_PLL1_PLL_FBDIV_MASK)
#define GET_U0_PLL0_PLL_OFFSETCALOUT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_60_ADDR,U0_PLL0_PLL_OFFSETCALOUT_SHIFT,U0_PLL0_PLL_OFFSETCALOUT_MASK)
#define GET_U0_PLL0_PLL_FBDIV                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_60_ADDR,U0_PLL0_PLL_FBDIV_SHIFT,U0_PLL0_PLL_FBDIV_MASK)
#define SET_U0_PLL0_PLL_FBDIV(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_60_ADDR,data,U0_PLL0_PLL_FBDIV_SHIFT,U0_PLL0_PLL_FBDIV_MASK)
#define GET_U0_PLL7_PLL_REFDIV                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_60_ADDR,U0_PLL7_PLL_REFDIV_SHIFT,U0_PLL7_PLL_REFDIV_MASK)
#define SET_U0_PLL7_PLL_REFDIV(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_60_ADDR,data,U0_PLL7_PLL_REFDIV_SHIFT,U0_PLL7_PLL_REFDIV_MASK)
#define GET_U0_PLL6_PLL_REFDIV                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_64_ADDR,U0_PLL6_PLL_REFDIV_SHIFT,U0_PLL6_PLL_REFDIV_MASK)
#define SET_U0_PLL6_PLL_REFDIV(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_64_ADDR,data,U0_PLL6_PLL_REFDIV_SHIFT,U0_PLL6_PLL_REFDIV_MASK)
#define GET_U0_PLL5_PLL_REFDIV                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_64_ADDR,U0_PLL5_PLL_REFDIV_SHIFT,U0_PLL5_PLL_REFDIV_MASK)
#define SET_U0_PLL5_PLL_REFDIV(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_64_ADDR,data,U0_PLL5_PLL_REFDIV_SHIFT,U0_PLL5_PLL_REFDIV_MASK)
#define GET_U0_PLL4_PLL_REFDIV                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_64_ADDR,U0_PLL4_PLL_REFDIV_SHIFT,U0_PLL4_PLL_REFDIV_MASK)
#define SET_U0_PLL4_PLL_REFDIV(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_64_ADDR,data,U0_PLL4_PLL_REFDIV_SHIFT,U0_PLL4_PLL_REFDIV_MASK)
#define GET_U0_PLL3_PLL_REFDIV                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_64_ADDR,U0_PLL3_PLL_REFDIV_SHIFT,U0_PLL3_PLL_REFDIV_MASK)
#define SET_U0_PLL3_PLL_REFDIV(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_64_ADDR,data,U0_PLL3_PLL_REFDIV_SHIFT,U0_PLL3_PLL_REFDIV_MASK)
#define GET_U0_PLL2_PLL_REFDIV                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_68_ADDR,U0_PLL2_PLL_REFDIV_SHIFT,U0_PLL2_PLL_REFDIV_MASK)
#define SET_U0_PLL2_PLL_REFDIV(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_68_ADDR,data,U0_PLL2_PLL_REFDIV_SHIFT,U0_PLL2_PLL_REFDIV_MASK)
#define GET_U0_PLL1_PLL_REFDIV                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_68_ADDR,U0_PLL1_PLL_REFDIV_SHIFT,U0_PLL1_PLL_REFDIV_MASK)
#define SET_U0_PLL1_PLL_REFDIV(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_68_ADDR,data,U0_PLL1_PLL_REFDIV_SHIFT,U0_PLL1_PLL_REFDIV_MASK)
#define GET_U0_PLL0_PLL_REFDIV                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_68_ADDR,U0_PLL0_PLL_REFDIV_SHIFT,U0_PLL0_PLL_REFDIV_MASK)
#define SET_U0_PLL0_PLL_REFDIV(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_68_ADDR,data,U0_PLL0_PLL_REFDIV_SHIFT,U0_PLL0_PLL_REFDIV_MASK)
#define GET_U0_PLL7_PLL_OFFSETCALCNT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_68_ADDR,U0_PLL7_PLL_OFFSETCALCNT_SHIFT,U0_PLL7_PLL_OFFSETCALCNT_MASK)
#define SET_U0_PLL7_PLL_OFFSETCALCNT(data)                 itg_set_reg(SYS0_SYSCONITG__SYSCFG_68_ADDR,data,U0_PLL7_PLL_OFFSETCALCNT_SHIFT,U0_PLL7_PLL_OFFSETCALCNT_MASK)
#define GET_U0_PLL6_PLL_OFFSETCALCNT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_68_ADDR,U0_PLL6_PLL_OFFSETCALCNT_SHIFT,U0_PLL6_PLL_OFFSETCALCNT_MASK)
#define SET_U0_PLL6_PLL_OFFSETCALCNT(data)                 itg_set_reg(SYS0_SYSCONITG__SYSCFG_68_ADDR,data,U0_PLL6_PLL_OFFSETCALCNT_SHIFT,U0_PLL6_PLL_OFFSETCALCNT_MASK)
#define GET_U0_PLL5_PLL_OFFSETCALCNT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,U0_PLL5_PLL_OFFSETCALCNT_SHIFT,U0_PLL5_PLL_OFFSETCALCNT_MASK)
#define SET_U0_PLL5_PLL_OFFSETCALCNT(data)                 itg_set_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL5_PLL_OFFSETCALCNT_SHIFT,U0_PLL5_PLL_OFFSETCALCNT_MASK)
#define GET_U0_PLL4_PLL_OFFSETCALCNT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,U0_PLL4_PLL_OFFSETCALCNT_SHIFT,U0_PLL4_PLL_OFFSETCALCNT_MASK)
#define SET_U0_PLL4_PLL_OFFSETCALCNT(data)                 itg_set_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL4_PLL_OFFSETCALCNT_SHIFT,U0_PLL4_PLL_OFFSETCALCNT_MASK)
#define GET_U0_PLL3_PLL_OFFSETCALCNT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,U0_PLL3_PLL_OFFSETCALCNT_SHIFT,U0_PLL3_PLL_OFFSETCALCNT_MASK)
#define SET_U0_PLL3_PLL_OFFSETCALCNT(data)                 itg_set_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL3_PLL_OFFSETCALCNT_SHIFT,U0_PLL3_PLL_OFFSETCALCNT_MASK)
#define GET_U0_PLL2_PLL_OFFSETCALCNT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,U0_PLL2_PLL_OFFSETCALCNT_SHIFT,U0_PLL2_PLL_OFFSETCALCNT_MASK)
#define SET_U0_PLL2_PLL_OFFSETCALCNT(data)                 itg_set_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL2_PLL_OFFSETCALCNT_SHIFT,U0_PLL2_PLL_OFFSETCALCNT_MASK)
#define GET_U0_PLL1_PLL_OFFSETCALCNT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,U0_PLL1_PLL_OFFSETCALCNT_SHIFT,U0_PLL1_PLL_OFFSETCALCNT_MASK)
#define SET_U0_PLL1_PLL_OFFSETCALCNT(data)                 itg_set_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL1_PLL_OFFSETCALCNT_SHIFT,U0_PLL1_PLL_OFFSETCALCNT_MASK)
#define GET_U0_PLL0_PLL_OFFSETCALCNT                       itg_get_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,U0_PLL0_PLL_OFFSETCALCNT_SHIFT,U0_PLL0_PLL_OFFSETCALCNT_MASK)
#define SET_U0_PLL0_PLL_OFFSETCALCNT(data)                 itg_set_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL0_PLL_OFFSETCALCNT_SHIFT,U0_PLL0_PLL_OFFSETCALCNT_MASK)
#define GET_U0_PLL7_PLL_POSTDIV                            itg_get_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,U0_PLL7_PLL_POSTDIV_SHIFT,U0_PLL7_PLL_POSTDIV_MASK)
#define SET_U0_PLL7_PLL_POSTDIV(data)                      itg_set_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL7_PLL_POSTDIV_SHIFT,U0_PLL7_PLL_POSTDIV_MASK)
#define GET_U0_PLL6_PLL_POSTDIV                            itg_get_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,U0_PLL6_PLL_POSTDIV_SHIFT,U0_PLL6_PLL_POSTDIV_MASK)
#define SET_U0_PLL6_PLL_POSTDIV(data)                      itg_set_reg(SYS0_SYSCONITG__SYSCFG_72_ADDR,data,U0_PLL6_PLL_POSTDIV_SHIFT,U0_PLL6_PLL_POSTDIV_MASK)
#define GET_U0_PLL5_PLL_POSTDIV                            itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL5_PLL_POSTDIV_SHIFT,U0_PLL5_PLL_POSTDIV_MASK)
#define SET_U0_PLL5_PLL_POSTDIV(data)                      itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL5_PLL_POSTDIV_SHIFT,U0_PLL5_PLL_POSTDIV_MASK)
#define GET_U0_PLL4_PLL_POSTDIV                            itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL4_PLL_POSTDIV_SHIFT,U0_PLL4_PLL_POSTDIV_MASK)
#define SET_U0_PLL4_PLL_POSTDIV(data)                      itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL4_PLL_POSTDIV_SHIFT,U0_PLL4_PLL_POSTDIV_MASK)
#define GET_U0_PLL3_PLL_POSTDIV                            itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL3_PLL_POSTDIV_SHIFT,U0_PLL3_PLL_POSTDIV_MASK)
#define SET_U0_PLL3_PLL_POSTDIV(data)                      itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL3_PLL_POSTDIV_SHIFT,U0_PLL3_PLL_POSTDIV_MASK)
#define GET_U0_PLL2_PLL_POSTDIV                            itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL2_PLL_POSTDIV_SHIFT,U0_PLL2_PLL_POSTDIV_MASK)
#define SET_U0_PLL2_PLL_POSTDIV(data)                      itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL2_PLL_POSTDIV_SHIFT,U0_PLL2_PLL_POSTDIV_MASK)
#define GET_U0_PLL1_PLL_POSTDIV                            itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL1_PLL_POSTDIV_SHIFT,U0_PLL1_PLL_POSTDIV_MASK)
#define SET_U0_PLL1_PLL_POSTDIV(data)                      itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL1_PLL_POSTDIV_SHIFT,U0_PLL1_PLL_POSTDIV_MASK)
#define GET_U0_PLL0_PLL_POSTDIV                            itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL0_PLL_POSTDIV_SHIFT,U0_PLL0_PLL_POSTDIV_MASK)
#define SET_U0_PLL0_PLL_POSTDIV(data)                      itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL0_PLL_POSTDIV_SHIFT,U0_PLL0_PLL_POSTDIV_MASK)
#define GET_U0_PLL7_PLL_PD                                 itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL7_PLL_PD_SHIFT,U0_PLL7_PLL_PD_MASK)
#define SET_U0_PLL7_PLL_PD(data)                           itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL7_PLL_PD_SHIFT,U0_PLL7_PLL_PD_MASK)
#define GET_U0_PLL7_PLL_OFFSETFASTCAL                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL7_PLL_OFFSETFASTCAL_SHIFT,U0_PLL7_PLL_OFFSETFASTCAL_MASK)
#define SET_U0_PLL7_PLL_OFFSETFASTCAL(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL7_PLL_OFFSETFASTCAL_SHIFT,U0_PLL7_PLL_OFFSETFASTCAL_MASK)
#define GET_U0_PLL7_PLL_OFFSETCALLOCK                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL7_PLL_OFFSETCALLOCK_SHIFT,U0_PLL7_PLL_OFFSETCALLOCK_MASK)
#define GET_U0_PLL7_PLL_LOCK                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL7_PLL_LOCK_SHIFT,U0_PLL7_PLL_LOCK_MASK)
#define GET_U0_PLL7_PLL_FOUTVCOP_EN                        itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL7_PLL_FOUTVCOP_EN_SHIFT,U0_PLL7_PLL_FOUTVCOP_EN_MASK)
#define SET_U0_PLL7_PLL_FOUTVCOP_EN(data)                  itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL7_PLL_FOUTVCOP_EN_SHIFT,U0_PLL7_PLL_FOUTVCOP_EN_MASK)
#define GET_U0_PLL7_PLL_FOUTPOSTDIVPD                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL7_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL7_PLL_FOUTPOSTDIVPD_MASK)
#define SET_U0_PLL7_PLL_FOUTPOSTDIVPD(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL7_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL7_PLL_FOUTPOSTDIVPD_MASK)
#define GET_U0_PLL7_PLL_FOUTPOSTDIV_EN                     itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL7_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL7_PLL_FOUTPOSTDIV_EN_MASK)
#define SET_U0_PLL7_PLL_FOUTPOSTDIV_EN(data)               itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL7_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL7_PLL_FOUTPOSTDIV_EN_MASK)
#define GET_U0_PLL7_PLL_DSMPD                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,U0_PLL7_PLL_DSMPD_SHIFT,U0_PLL7_PLL_DSMPD_MASK)
#define SET_U0_PLL7_PLL_DSMPD(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_76_ADDR,data,U0_PLL7_PLL_DSMPD_SHIFT,U0_PLL7_PLL_DSMPD_MASK)
#define GET_U0_PLL7_PLL_BYPASS                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL7_PLL_BYPASS_SHIFT,U0_PLL7_PLL_BYPASS_MASK)
#define SET_U0_PLL7_PLL_BYPASS(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL7_PLL_BYPASS_SHIFT,U0_PLL7_PLL_BYPASS_MASK)
#define GET_U0_PLL6_PLL_PD                                 itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL6_PLL_PD_SHIFT,U0_PLL6_PLL_PD_MASK)
#define SET_U0_PLL6_PLL_PD(data)                           itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL6_PLL_PD_SHIFT,U0_PLL6_PLL_PD_MASK)
#define GET_U0_PLL6_PLL_OFFSETFASTCAL                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL6_PLL_OFFSETFASTCAL_SHIFT,U0_PLL6_PLL_OFFSETFASTCAL_MASK)
#define SET_U0_PLL6_PLL_OFFSETFASTCAL(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL6_PLL_OFFSETFASTCAL_SHIFT,U0_PLL6_PLL_OFFSETFASTCAL_MASK)
#define GET_U0_PLL6_PLL_OFFSETCALLOCK                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL6_PLL_OFFSETCALLOCK_SHIFT,U0_PLL6_PLL_OFFSETCALLOCK_MASK)
#define GET_U0_PLL6_PLL_LOCK                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL6_PLL_LOCK_SHIFT,U0_PLL6_PLL_LOCK_MASK)
#define GET_U0_PLL6_PLL_FOUTVCOP_EN                        itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL6_PLL_FOUTVCOP_EN_SHIFT,U0_PLL6_PLL_FOUTVCOP_EN_MASK)
#define SET_U0_PLL6_PLL_FOUTVCOP_EN(data)                  itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL6_PLL_FOUTVCOP_EN_SHIFT,U0_PLL6_PLL_FOUTVCOP_EN_MASK)
#define GET_U0_PLL6_PLL_FOUTPOSTDIVPD                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL6_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL6_PLL_FOUTPOSTDIVPD_MASK)
#define SET_U0_PLL6_PLL_FOUTPOSTDIVPD(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL6_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL6_PLL_FOUTPOSTDIVPD_MASK)
#define GET_U0_PLL6_PLL_FOUTPOSTDIV_EN                     itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL6_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL6_PLL_FOUTPOSTDIV_EN_MASK)
#define SET_U0_PLL6_PLL_FOUTPOSTDIV_EN(data)               itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL6_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL6_PLL_FOUTPOSTDIV_EN_MASK)
#define GET_U0_PLL6_PLL_DSMPD                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL6_PLL_DSMPD_SHIFT,U0_PLL6_PLL_DSMPD_MASK)
#define SET_U0_PLL6_PLL_DSMPD(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL6_PLL_DSMPD_SHIFT,U0_PLL6_PLL_DSMPD_MASK)
#define GET_U0_PLL6_PLL_BYPASS                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL6_PLL_BYPASS_SHIFT,U0_PLL6_PLL_BYPASS_MASK)
#define SET_U0_PLL6_PLL_BYPASS(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL6_PLL_BYPASS_SHIFT,U0_PLL6_PLL_BYPASS_MASK)
#define GET_U0_PLL5_PLL_PD                                 itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL5_PLL_PD_SHIFT,U0_PLL5_PLL_PD_MASK)
#define SET_U0_PLL5_PLL_PD(data)                           itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL5_PLL_PD_SHIFT,U0_PLL5_PLL_PD_MASK)
#define GET_U0_PLL5_PLL_OFFSETFASTCAL                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL5_PLL_OFFSETFASTCAL_SHIFT,U0_PLL5_PLL_OFFSETFASTCAL_MASK)
#define SET_U0_PLL5_PLL_OFFSETFASTCAL(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL5_PLL_OFFSETFASTCAL_SHIFT,U0_PLL5_PLL_OFFSETFASTCAL_MASK)
#define GET_U0_PLL5_PLL_OFFSETCALLOCK                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL5_PLL_OFFSETCALLOCK_SHIFT,U0_PLL5_PLL_OFFSETCALLOCK_MASK)
#define GET_U0_PLL5_PLL_LOCK                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL5_PLL_LOCK_SHIFT,U0_PLL5_PLL_LOCK_MASK)
#define GET_U0_PLL5_PLL_FOUTVCOP_EN                        itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL5_PLL_FOUTVCOP_EN_SHIFT,U0_PLL5_PLL_FOUTVCOP_EN_MASK)
#define SET_U0_PLL5_PLL_FOUTVCOP_EN(data)                  itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL5_PLL_FOUTVCOP_EN_SHIFT,U0_PLL5_PLL_FOUTVCOP_EN_MASK)
#define GET_U0_PLL5_PLL_FOUTPOSTDIVPD                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL5_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL5_PLL_FOUTPOSTDIVPD_MASK)
#define SET_U0_PLL5_PLL_FOUTPOSTDIVPD(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL5_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL5_PLL_FOUTPOSTDIVPD_MASK)
#define GET_U0_PLL5_PLL_FOUTPOSTDIV_EN                     itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL5_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL5_PLL_FOUTPOSTDIV_EN_MASK)
#define SET_U0_PLL5_PLL_FOUTPOSTDIV_EN(data)               itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL5_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL5_PLL_FOUTPOSTDIV_EN_MASK)
#define GET_U0_PLL5_PLL_DSMPD                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL5_PLL_DSMPD_SHIFT,U0_PLL5_PLL_DSMPD_MASK)
#define SET_U0_PLL5_PLL_DSMPD(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL5_PLL_DSMPD_SHIFT,U0_PLL5_PLL_DSMPD_MASK)
#define GET_U0_PLL5_PLL_BYPASS                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL5_PLL_BYPASS_SHIFT,U0_PLL5_PLL_BYPASS_MASK)
#define SET_U0_PLL5_PLL_BYPASS(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL5_PLL_BYPASS_SHIFT,U0_PLL5_PLL_BYPASS_MASK)
#define GET_U0_PLL4_PLL_PD                                 itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL4_PLL_PD_SHIFT,U0_PLL4_PLL_PD_MASK)
#define SET_U0_PLL4_PLL_PD(data)                           itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL4_PLL_PD_SHIFT,U0_PLL4_PLL_PD_MASK)
#define GET_U0_PLL4_PLL_OFFSETFASTCAL                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL4_PLL_OFFSETFASTCAL_SHIFT,U0_PLL4_PLL_OFFSETFASTCAL_MASK)
#define SET_U0_PLL4_PLL_OFFSETFASTCAL(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL4_PLL_OFFSETFASTCAL_SHIFT,U0_PLL4_PLL_OFFSETFASTCAL_MASK)
#define GET_U0_PLL4_PLL_OFFSETCALLOCK                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL4_PLL_OFFSETCALLOCK_SHIFT,U0_PLL4_PLL_OFFSETCALLOCK_MASK)
#define GET_U0_PLL4_PLL_LOCK                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL4_PLL_LOCK_SHIFT,U0_PLL4_PLL_LOCK_MASK)
#define GET_U0_PLL4_PLL_FOUTVCOP_EN                        itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL4_PLL_FOUTVCOP_EN_SHIFT,U0_PLL4_PLL_FOUTVCOP_EN_MASK)
#define SET_U0_PLL4_PLL_FOUTVCOP_EN(data)                  itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL4_PLL_FOUTVCOP_EN_SHIFT,U0_PLL4_PLL_FOUTVCOP_EN_MASK)
#define GET_U0_PLL4_PLL_FOUTPOSTDIVPD                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL4_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL4_PLL_FOUTPOSTDIVPD_MASK)
#define SET_U0_PLL4_PLL_FOUTPOSTDIVPD(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL4_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL4_PLL_FOUTPOSTDIVPD_MASK)
#define GET_U0_PLL4_PLL_FOUTPOSTDIV_EN                     itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL4_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL4_PLL_FOUTPOSTDIV_EN_MASK)
#define SET_U0_PLL4_PLL_FOUTPOSTDIV_EN(data)               itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL4_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL4_PLL_FOUTPOSTDIV_EN_MASK)
#define GET_U0_PLL4_PLL_DSMPD                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL4_PLL_DSMPD_SHIFT,U0_PLL4_PLL_DSMPD_MASK)
#define SET_U0_PLL4_PLL_DSMPD(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL4_PLL_DSMPD_SHIFT,U0_PLL4_PLL_DSMPD_MASK)
#define GET_U0_PLL4_PLL_BYPASS                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL4_PLL_BYPASS_SHIFT,U0_PLL4_PLL_BYPASS_MASK)
#define SET_U0_PLL4_PLL_BYPASS(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL4_PLL_BYPASS_SHIFT,U0_PLL4_PLL_BYPASS_MASK)
#define GET_U0_PLL3_PLL_PD                                 itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL3_PLL_PD_SHIFT,U0_PLL3_PLL_PD_MASK)
#define SET_U0_PLL3_PLL_PD(data)                           itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL3_PLL_PD_SHIFT,U0_PLL3_PLL_PD_MASK)
#define GET_U0_PLL3_PLL_OFFSETFASTCAL                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL3_PLL_OFFSETFASTCAL_SHIFT,U0_PLL3_PLL_OFFSETFASTCAL_MASK)
#define SET_U0_PLL3_PLL_OFFSETFASTCAL(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,data,U0_PLL3_PLL_OFFSETFASTCAL_SHIFT,U0_PLL3_PLL_OFFSETFASTCAL_MASK)
#define GET_U0_PLL3_PLL_OFFSETCALLOCK                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL3_PLL_OFFSETCALLOCK_SHIFT,U0_PLL3_PLL_OFFSETCALLOCK_MASK)
#define GET_U0_PLL3_PLL_LOCK                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_80_ADDR,U0_PLL3_PLL_LOCK_SHIFT,U0_PLL3_PLL_LOCK_MASK)
#define GET_U0_PLL3_PLL_FOUTVCOP_EN                        itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL3_PLL_FOUTVCOP_EN_SHIFT,U0_PLL3_PLL_FOUTVCOP_EN_MASK)
#define SET_U0_PLL3_PLL_FOUTVCOP_EN(data)                  itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL3_PLL_FOUTVCOP_EN_SHIFT,U0_PLL3_PLL_FOUTVCOP_EN_MASK)
#define GET_U0_PLL3_PLL_FOUTPOSTDIVPD                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL3_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL3_PLL_FOUTPOSTDIVPD_MASK)
#define SET_U0_PLL3_PLL_FOUTPOSTDIVPD(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL3_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL3_PLL_FOUTPOSTDIVPD_MASK)
#define GET_U0_PLL3_PLL_FOUTPOSTDIV_EN                     itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL3_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL3_PLL_FOUTPOSTDIV_EN_MASK)
#define SET_U0_PLL3_PLL_FOUTPOSTDIV_EN(data)               itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL3_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL3_PLL_FOUTPOSTDIV_EN_MASK)
#define GET_U0_PLL3_PLL_DSMPD                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL3_PLL_DSMPD_SHIFT,U0_PLL3_PLL_DSMPD_MASK)
#define SET_U0_PLL3_PLL_DSMPD(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL3_PLL_DSMPD_SHIFT,U0_PLL3_PLL_DSMPD_MASK)
#define GET_U0_PLL3_PLL_BYPASS                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL3_PLL_BYPASS_SHIFT,U0_PLL3_PLL_BYPASS_MASK)
#define SET_U0_PLL3_PLL_BYPASS(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL3_PLL_BYPASS_SHIFT,U0_PLL3_PLL_BYPASS_MASK)
#define GET_U0_PLL2_PLL_PD                                 itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL2_PLL_PD_SHIFT,U0_PLL2_PLL_PD_MASK)
#define SET_U0_PLL2_PLL_PD(data)                           itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL2_PLL_PD_SHIFT,U0_PLL2_PLL_PD_MASK)
#define GET_U0_PLL2_PLL_OFFSETFASTCAL                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL2_PLL_OFFSETFASTCAL_SHIFT,U0_PLL2_PLL_OFFSETFASTCAL_MASK)
#define SET_U0_PLL2_PLL_OFFSETFASTCAL(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL2_PLL_OFFSETFASTCAL_SHIFT,U0_PLL2_PLL_OFFSETFASTCAL_MASK)
#define GET_U0_PLL2_PLL_OFFSETCALLOCK                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL2_PLL_OFFSETCALLOCK_SHIFT,U0_PLL2_PLL_OFFSETCALLOCK_MASK)
#define GET_U0_PLL2_PLL_LOCK                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL2_PLL_LOCK_SHIFT,U0_PLL2_PLL_LOCK_MASK)
#define GET_U0_PLL2_PLL_FOUTVCOP_EN                        itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL2_PLL_FOUTVCOP_EN_SHIFT,U0_PLL2_PLL_FOUTVCOP_EN_MASK)
#define SET_U0_PLL2_PLL_FOUTVCOP_EN(data)                  itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL2_PLL_FOUTVCOP_EN_SHIFT,U0_PLL2_PLL_FOUTVCOP_EN_MASK)
#define GET_U0_PLL2_PLL_FOUTPOSTDIVPD                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL2_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL2_PLL_FOUTPOSTDIVPD_MASK)
#define SET_U0_PLL2_PLL_FOUTPOSTDIVPD(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL2_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL2_PLL_FOUTPOSTDIVPD_MASK)
#define GET_U0_PLL2_PLL_FOUTPOSTDIV_EN                     itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL2_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL2_PLL_FOUTPOSTDIV_EN_MASK)
#define SET_U0_PLL2_PLL_FOUTPOSTDIV_EN(data)               itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL2_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL2_PLL_FOUTPOSTDIV_EN_MASK)
#define GET_U0_PLL2_PLL_DSMPD                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL2_PLL_DSMPD_SHIFT,U0_PLL2_PLL_DSMPD_MASK)
#define SET_U0_PLL2_PLL_DSMPD(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL2_PLL_DSMPD_SHIFT,U0_PLL2_PLL_DSMPD_MASK)
#define GET_U0_PLL2_PLL_BYPASS                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL2_PLL_BYPASS_SHIFT,U0_PLL2_PLL_BYPASS_MASK)
#define SET_U0_PLL2_PLL_BYPASS(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL2_PLL_BYPASS_SHIFT,U0_PLL2_PLL_BYPASS_MASK)
#define GET_U0_PLL1_PLL_PD                                 itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL1_PLL_PD_SHIFT,U0_PLL1_PLL_PD_MASK)
#define SET_U0_PLL1_PLL_PD(data)                           itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL1_PLL_PD_SHIFT,U0_PLL1_PLL_PD_MASK)
#define GET_U0_PLL1_PLL_OFFSETFASTCAL                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL1_PLL_OFFSETFASTCAL_SHIFT,U0_PLL1_PLL_OFFSETFASTCAL_MASK)
#define SET_U0_PLL1_PLL_OFFSETFASTCAL(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL1_PLL_OFFSETFASTCAL_SHIFT,U0_PLL1_PLL_OFFSETFASTCAL_MASK)
#define GET_U0_PLL1_PLL_OFFSETCALLOCK                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL1_PLL_OFFSETCALLOCK_SHIFT,U0_PLL1_PLL_OFFSETCALLOCK_MASK)
#define GET_U0_PLL1_PLL_LOCK                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL1_PLL_LOCK_SHIFT,U0_PLL1_PLL_LOCK_MASK)
#define GET_U0_PLL1_PLL_FOUTVCOP_EN                        itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL1_PLL_FOUTVCOP_EN_SHIFT,U0_PLL1_PLL_FOUTVCOP_EN_MASK)
#define SET_U0_PLL1_PLL_FOUTVCOP_EN(data)                  itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL1_PLL_FOUTVCOP_EN_SHIFT,U0_PLL1_PLL_FOUTVCOP_EN_MASK)
#define GET_U0_PLL1_PLL_FOUTPOSTDIVPD                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL1_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL1_PLL_FOUTPOSTDIVPD_MASK)
#define SET_U0_PLL1_PLL_FOUTPOSTDIVPD(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL1_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL1_PLL_FOUTPOSTDIVPD_MASK)
#define GET_U0_PLL1_PLL_FOUTPOSTDIV_EN                     itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL1_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL1_PLL_FOUTPOSTDIV_EN_MASK)
#define SET_U0_PLL1_PLL_FOUTPOSTDIV_EN(data)               itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL1_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL1_PLL_FOUTPOSTDIV_EN_MASK)
#define GET_U0_PLL1_PLL_DSMPD                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL1_PLL_DSMPD_SHIFT,U0_PLL1_PLL_DSMPD_MASK)
#define SET_U0_PLL1_PLL_DSMPD(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL1_PLL_DSMPD_SHIFT,U0_PLL1_PLL_DSMPD_MASK)
#define GET_U0_PLL1_PLL_BYPASS                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL1_PLL_BYPASS_SHIFT,U0_PLL1_PLL_BYPASS_MASK)
#define SET_U0_PLL1_PLL_BYPASS(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL1_PLL_BYPASS_SHIFT,U0_PLL1_PLL_BYPASS_MASK)
#define GET_U0_PLL0_PLL_PD                                 itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL0_PLL_PD_SHIFT,U0_PLL0_PLL_PD_MASK)
#define SET_U0_PLL0_PLL_PD(data)                           itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL0_PLL_PD_SHIFT,U0_PLL0_PLL_PD_MASK)
#define GET_U0_PLL0_PLL_OFFSETFASTCAL                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL0_PLL_OFFSETFASTCAL_SHIFT,U0_PLL0_PLL_OFFSETFASTCAL_MASK)
#define SET_U0_PLL0_PLL_OFFSETFASTCAL(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL0_PLL_OFFSETFASTCAL_SHIFT,U0_PLL0_PLL_OFFSETFASTCAL_MASK)
#define GET_U0_PLL0_PLL_OFFSETCALLOCK                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL0_PLL_OFFSETCALLOCK_SHIFT,U0_PLL0_PLL_OFFSETCALLOCK_MASK)
#define GET_U0_PLL0_PLL_LOCK                               itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL0_PLL_LOCK_SHIFT,U0_PLL0_PLL_LOCK_MASK)
#define GET_U0_PLL0_PLL_FOUTVCOP_EN                        itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL0_PLL_FOUTVCOP_EN_SHIFT,U0_PLL0_PLL_FOUTVCOP_EN_MASK)
#define SET_U0_PLL0_PLL_FOUTVCOP_EN(data)                  itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL0_PLL_FOUTVCOP_EN_SHIFT,U0_PLL0_PLL_FOUTVCOP_EN_MASK)
#define GET_U0_PLL0_PLL_FOUTPOSTDIVPD                      itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL0_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL0_PLL_FOUTPOSTDIVPD_MASK)
#define SET_U0_PLL0_PLL_FOUTPOSTDIVPD(data)                itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL0_PLL_FOUTPOSTDIVPD_SHIFT,U0_PLL0_PLL_FOUTPOSTDIVPD_MASK)
#define GET_U0_PLL0_PLL_FOUTPOSTDIV_EN                     itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL0_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL0_PLL_FOUTPOSTDIV_EN_MASK)
#define SET_U0_PLL0_PLL_FOUTPOSTDIV_EN(data)               itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL0_PLL_FOUTPOSTDIV_EN_SHIFT,U0_PLL0_PLL_FOUTPOSTDIV_EN_MASK)
#define GET_U0_PLL0_PLL_DSMPD                              itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL0_PLL_DSMPD_SHIFT,U0_PLL0_PLL_DSMPD_MASK)
#define SET_U0_PLL0_PLL_DSMPD(data)                        itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL0_PLL_DSMPD_SHIFT,U0_PLL0_PLL_DSMPD_MASK)
#define GET_U0_PLL0_PLL_BYPASS                             itg_get_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,U0_PLL0_PLL_BYPASS_SHIFT,U0_PLL0_PLL_BYPASS_MASK)
#define SET_U0_PLL0_PLL_BYPASS(data)                       itg_set_reg(SYS0_SYSCONITG__SYSCFG_84_ADDR,data,U0_PLL0_PLL_BYPASS_SHIFT,U0_PLL0_PLL_BYPASS_MASK)
