//commit:8ece02821 (HEAD -> b0.8.1_dv, origin/b0.8.1_dv)

#ifndef _SYS0_SECURE_CRG_MACRO_H_
#define _SYS0_SECURE_CRG_MACRO_H_

//#define SYS0_SECURE_CRG_BASE_ADDR 0x0
#define CLK_APB_MAIN_SYS0_SEC_CTRL_REG_ADDR                          (U0_SYS0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_APB_OSC_SYS0_SEC_CTRL_REG_ADDR                           (U0_SYS0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)


#define SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR       (U0_SYS0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)

#define SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR       (U0_SYS0_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)


#define CLK_APB_MAIN_SYS0_SEC_DIV_SHIFT                              0
#define CLK_APB_MAIN_SYS0_SEC_DIV_MASK                               0xFU
#define CLK_APB_OSC_SYS0_SEC_SW_SHIFT                                24
#define CLK_APB_OSC_SYS0_SEC_SW_MASK                                 0x1000000U
#define CLK_APB_OSC_SYS0_SEC_SW_CLK_OSC_DATA                         0
#define CLK_APB_OSC_SYS0_SEC_SW_CLK_APB_MAIN_SYS0_SEC_DATA           1




#define RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_SHIFT                     0
#define RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_MASK                      (0x1 << 0)
#define RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_ASSERT                    1
#define RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_CLEAR                     0
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_SHIFT                  1
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_MASK                   (0x1 << 1)
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_ASSERT                 1
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_CLEAR                  0

#define _DIVIDE_CLOCK_CLK_APB_MAIN_SYS0_SEC_(div) 			itg_set_reg(CLK_APB_MAIN_SYS0_SEC_CTRL_REG_ADDR, div, CLK_APB_MAIN_SYS0_SEC_DIV_SHIFT, CLK_APB_MAIN_SYS0_SEC_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_MAIN_SYS0_SEC_ 		itg_get_reg(CLK_APB_MAIN_SYS0_SEC_CTRL_REG_ADDR, CLK_APB_MAIN_SYS0_SEC_DIV_SHIFT, CLK_APB_MAIN_SYS0_SEC_DIV_MASK)
#define _SWITCH_CLOCK_CLK_APB_OSC_SYS0_SEC_SOURCE_CLK_OSC_ 	itg_set_reg(CLK_APB_OSC_SYS0_SEC_CTRL_REG_ADDR, CLK_APB_OSC_SYS0_SEC_SW_CLK_OSC_DATA, CLK_APB_OSC_SYS0_SEC_SW_SHIFT, CLK_APB_OSC_SYS0_SEC_SW_MASK)
#define _SWITCH_CLOCK_CLK_APB_OSC_SYS0_SEC_SOURCE_CLK_APB_MAIN_SYS0_SEC_ 	itg_set_reg(CLK_APB_OSC_SYS0_SEC_CTRL_REG_ADDR, CLK_APB_OSC_SYS0_SEC_SW_CLK_APB_MAIN_SYS0_SEC_DATA, CLK_APB_OSC_SYS0_SEC_SW_SHIFT, CLK_APB_OSC_SYS0_SEC_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_APB_OSC_SYS0_SEC_ 		itg_get_reg(CLK_APB_OSC_SYS0_SEC_CTRL_REG_ADDR, CLK_APB_OSC_SYS0_SEC_SW_SHIFT, CLK_APB_OSC_SYS0_SEC_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_APB_OSC_SYS0_SEC_(x) 		itg_set_reg(CLK_APB_OSC_SYS0_SEC_CTRL_REG_ADDR, x, CLK_APB_OSC_SYS0_SEC_SW_SHIFT, CLK_APB_OSC_SYS0_SEC_SW_MASK)



#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_ 	itg_get_reg(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_SHIFT, RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_ 	itg_assert_rst(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_ 	itg_clear_rst(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS0_SECURE_SYSCON_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_ 	itg_get_reg(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_SHIFT, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_ 	itg_assert_rst(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_ 	itg_clear_rst(SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS0_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR0_SECURE_MASK)


#endif //_SYS0_SECURE_CRG_MACRO_H_
