//RTL tag v0.5.1

#define SYS1_SECURE_SYSCONITG__SYSCFG_0_ADDR               (U0_SYS1_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define U3_DWC_SENSORS_TSPD_WR_LOCK_WIDTH                  0x1U
#define U3_DWC_SENSORS_TSPD_WR_LOCK_SHIFT                  0x0U
#define U3_DWC_SENSORS_TSPD_WR_LOCK_MASK                   0x1U
#define GET_U3_DWC_SENSORS_TSPD_WR_LOCK                    itg_get_reg(SYS1_SECURE_SYSCONITG__SYSCFG_0_ADDR,U3_DWC_SENSORS_TSPD_WR_LOCK_SHIFT,U3_DWC_SENSORS_TSPD_WR_LOCK_MASK)
#define SET_U3_DWC_SENSORS_TSPD_WR_LOCK(data)              itg_set_reg(SYS1_SECURE_SYSCONITG__SYSCFG_0_ADDR,data,U3_DWC_SENSORS_TSPD_WR_LOCK_SHIFT,U3_DWC_SENSORS_TSPD_WR_LOCK_MASK)
