//commit:8ece02821 (HEAD -> b0.8.1_dv, origin/b0.8.1_dv)

#ifndef _SYS1_CRG_MACRO_H_
#define _SYS1_CRG_MACRO_H_

//#define SYS1_CRG_BASE_ADDR 0x0
#define CLK_APB_MAIN_SYS1_CTRL_REG_ADDR                              (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_APB_OSC_SYS1_CTRL_REG_ADDR                               (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define CLK_NCNOC1_200_CTRL_REG_ADDR                                 (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define CLK_U0_BCU_PCLK_CTRL_REG_ADDR                                (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)
#define CLK_U0_BCU_DFT_BISR_CLK_CTRL_REG_ADDR                        (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define DFT_GPIO_ESPI1_66_CTRL_REG_ADDR                              (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define CLK_ESPI1_EXT_DFT_MUX_CTRL_REG_ADDR                          (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define CLK_HOSTSS1_100_CTRL_REG_ADDR                                (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x1CU)
#define CLK_HOSTSS1_CFG_CTRL_REG_ADDR                                (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x20U)
#define CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_CTRL_REG_ADDR              (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x24U)
#define CLK_VOUT_100_CTRL_REG_ADDR                                   (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x50U)
#define CLK_VOUT_TARG_CTRL_REG_ADDR                                  (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x54U)
#define CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_CTRL_REG_ADDR (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x58U)
#define CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_CTRL_REG_ADDR  (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x5CU)
#define CLK_BMCPER3_100_CTRL_REG_ADDR                                (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x60U)
#define CLK_BMCPER3_TARG_CTRL_REG_ADDR                               (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x64U)
#define CLK_BMCPER3_125_CTRL_REG_ADDR                                (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x68U)
#define CLK_BMCPER3_125_OSC_CTRL_REG_ADDR                            (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x6CU)


#define MAIN_ICG_EN_BCU_CTRL_REG_ADDR                                (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x70U)


#define SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR              (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x74U)

#define SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR              (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x78U)


#define CLK_APB_MAIN_SYS1_DIV_SHIFT                                  0
#define CLK_APB_MAIN_SYS1_DIV_MASK                                   0xFU
#define CLK_APB_OSC_SYS1_SW_SHIFT                                    24
#define CLK_APB_OSC_SYS1_SW_MASK                                     0x1000000U
#define CLK_APB_OSC_SYS1_SW_CLK_OSC_DATA                             0
#define CLK_APB_OSC_SYS1_SW_CLK_APB_MAIN_SYS1_DATA                   1
#define CLK_NCNOC1_200_DIV_SHIFT                                     0
#define CLK_NCNOC1_200_DIV_MASK                                      0x7U
#define CLK_U0_BCU_PCLK_ENABLE_DATA                                  1
#define CLK_U0_BCU_PCLK_DISABLE_DATA                                 0
#define CLK_U0_BCU_PCLK_EN_SHIFT                                     31
#define CLK_U0_BCU_PCLK_EN_MASK                                      0x80000000U
#define CLK_U0_BCU_DFT_BISR_CLK_ENABLE_DATA                          1
#define CLK_U0_BCU_DFT_BISR_CLK_DISABLE_DATA                         0
#define CLK_U0_BCU_DFT_BISR_CLK_EN_SHIFT                             31
#define CLK_U0_BCU_DFT_BISR_CLK_EN_MASK                              0x80000000U
#define DFT_GPIO_ESPI1_66_ENABLE_DATA                                1
#define DFT_GPIO_ESPI1_66_DISABLE_DATA                               0
#define DFT_GPIO_ESPI1_66_EN_SHIFT                                   31
#define DFT_GPIO_ESPI1_66_EN_MASK                                    0x80000000U
#define DFT_GPIO_ESPI1_66_DIV_SHIFT                                  0
#define DFT_GPIO_ESPI1_66_DIV_MASK                                   0xFU
#define CLK_ESPI1_EXT_DFT_MUX_SW_SHIFT                               24
#define CLK_ESPI1_EXT_DFT_MUX_SW_MASK                                0x1000000U
#define CLK_ESPI1_EXT_DFT_MUX_SW_CLK_ESPI1_EXT_DATA                  0
#define CLK_ESPI1_EXT_DFT_MUX_SW_DFT_GPIO_ESPI1_66_DATA              1
#define CLK_HOSTSS1_100_DIV_SHIFT                                    0
#define CLK_HOSTSS1_100_DIV_MASK                                     0xFU
#define CLK_HOSTSS1_CFG_SW_SHIFT                                     24
#define CLK_HOSTSS1_CFG_SW_MASK                                      0x1000000U
#define CLK_HOSTSS1_CFG_SW_CLK_OSC_DATA                              0
#define CLK_HOSTSS1_CFG_SW_CLK_HOSTSS1_100_DATA                      1
#define CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_ENABLE_DATA                1
#define CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_DISABLE_DATA               0
#define CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_SHIFT                   31
#define CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_MASK                    0x80000000U
#define CLK_VOUT_100_DIV_SHIFT                                       0
#define CLK_VOUT_100_DIV_MASK                                        0xFU
#define CLK_VOUT_TARG_SW_SHIFT                                       24
#define CLK_VOUT_TARG_SW_MASK                                        0x1000000U
#define CLK_VOUT_TARG_SW_CLK_OSC_DATA                                0
#define CLK_VOUT_TARG_SW_CLK_VOUT_100_DATA                           1
#define CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_ENABLE_DATA   1
#define CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_DISABLE_DATA  0
#define CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_EN_SHIFT      31
#define CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_EN_MASK       0x80000000U
#define CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_ENABLE_DATA    1
#define CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_DISABLE_DATA   0
#define CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_EN_SHIFT       31
#define CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_EN_MASK        0x80000000U
#define CLK_BMCPER3_100_DIV_SHIFT                                    0
#define CLK_BMCPER3_100_DIV_MASK                                     0xFU
#define CLK_BMCPER3_TARG_SW_SHIFT                                    24
#define CLK_BMCPER3_TARG_SW_MASK                                     0x1000000U
#define CLK_BMCPER3_TARG_SW_CLK_OSC_DATA                             0
#define CLK_BMCPER3_TARG_SW_CLK_BMCPER3_100_DATA                     1
#define CLK_BMCPER3_125_DIV_SHIFT                                    0
#define CLK_BMCPER3_125_DIV_MASK                                     0xFU
#define CLK_BMCPER3_125_OSC_SW_SHIFT                                 24
#define CLK_BMCPER3_125_OSC_SW_MASK                                  0x1000000U
#define CLK_BMCPER3_125_OSC_SW_CLK_OSC_DATA                          0
#define CLK_BMCPER3_125_OSC_SW_CLK_BMCPER3_125_DATA                  1

#define MAIN_ICG_EN_BCU_ENABLE_DATA                                  1
#define MAIN_ICG_EN_BCU_DISABLE_DATA                                 0
#define MAIN_ICG_EN_BCU_EN_SHIFT                                     31
#define MAIN_ICG_EN_BCU_EN_MASK                                      0x80000000U



#define RSTN_U0_SYS1_SYSCON_PRESETN_SHIFT                            0
#define RSTN_U0_SYS1_SYSCON_PRESETN_MASK                             (0x1 << 0)
#define RSTN_U0_SYS1_SYSCON_PRESETN_ASSERT                           1
#define RSTN_U0_SYS1_SYSCON_PRESETN_CLEAR                            0
#define RSTN_U0_SYS1_IOMUX_PRESETN_SHIFT                             1
#define RSTN_U0_SYS1_IOMUX_PRESETN_MASK                              (0x1 << 1)
#define RSTN_U0_SYS1_IOMUX_PRESETN_ASSERT                            1
#define RSTN_U0_SYS1_IOMUX_PRESETN_CLEAR                             0
#define RSTN_U0_BCU_PRST_SHIFT                                       2
#define RSTN_U0_BCU_PRST_MASK                                        (0x1 << 2)
#define RSTN_U0_BCU_PRST_ASSERT                                      1
#define RSTN_U0_BCU_PRST_CLEAR                                       0
#define RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_SHIFT                          3
#define RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_MASK                           (0x1 << 3)
#define RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_ASSERT                         1
#define RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_CLEAR                          0
#define RSTN_U0_BCU_DFT_BISR_RST_SHIFT                               4
#define RSTN_U0_BCU_DFT_BISR_RST_MASK                                (0x1 << 4)
#define RSTN_U0_BCU_DFT_BISR_RST_ASSERT                              1
#define RSTN_U0_BCU_DFT_BISR_RST_CLEAR                               0
#define MAIN_RSTN_PCU_DC0_SHIFT                                      6
#define MAIN_RSTN_PCU_DC0_MASK                                       (0x1 << 6)
#define MAIN_RSTN_PCU_DC0_ASSERT                                     1
#define MAIN_RSTN_PCU_DC0_CLEAR                                      0
#define MAIN_RSTN_PCU_DC1_SHIFT                                      7
#define MAIN_RSTN_PCU_DC1_MASK                                       (0x1 << 7)
#define MAIN_RSTN_PCU_DC1_ASSERT                                     1
#define MAIN_RSTN_PCU_DC1_CLEAR                                      0
#define MAIN_RSTN_PCU_HOSTSS1_SHIFT                                  8
#define MAIN_RSTN_PCU_HOSTSS1_MASK                                   (0x1 << 8)
#define MAIN_RSTN_PCU_HOSTSS1_ASSERT                                 1
#define MAIN_RSTN_PCU_HOSTSS1_CLEAR                                  0

#define _DIVIDE_CLOCK_CLK_APB_MAIN_SYS1_(div) 			itg_set_reg(CLK_APB_MAIN_SYS1_CTRL_REG_ADDR, div, CLK_APB_MAIN_SYS1_DIV_SHIFT, CLK_APB_MAIN_SYS1_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_MAIN_SYS1_ 		itg_get_reg(CLK_APB_MAIN_SYS1_CTRL_REG_ADDR, CLK_APB_MAIN_SYS1_DIV_SHIFT, CLK_APB_MAIN_SYS1_DIV_MASK)
#define _SWITCH_CLOCK_CLK_APB_OSC_SYS1_SOURCE_CLK_OSC_ 	itg_set_reg(CLK_APB_OSC_SYS1_CTRL_REG_ADDR, CLK_APB_OSC_SYS1_SW_CLK_OSC_DATA, CLK_APB_OSC_SYS1_SW_SHIFT, CLK_APB_OSC_SYS1_SW_MASK)
#define _SWITCH_CLOCK_CLK_APB_OSC_SYS1_SOURCE_CLK_APB_MAIN_SYS1_ 	itg_set_reg(CLK_APB_OSC_SYS1_CTRL_REG_ADDR, CLK_APB_OSC_SYS1_SW_CLK_APB_MAIN_SYS1_DATA, CLK_APB_OSC_SYS1_SW_SHIFT, CLK_APB_OSC_SYS1_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_APB_OSC_SYS1_ 		itg_get_reg(CLK_APB_OSC_SYS1_CTRL_REG_ADDR, CLK_APB_OSC_SYS1_SW_SHIFT, CLK_APB_OSC_SYS1_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_APB_OSC_SYS1_(x) 		itg_set_reg(CLK_APB_OSC_SYS1_CTRL_REG_ADDR, x, CLK_APB_OSC_SYS1_SW_SHIFT, CLK_APB_OSC_SYS1_SW_MASK)
#define _DIVIDE_CLOCK_CLK_NCNOC1_200_(div) 			itg_set_reg(CLK_NCNOC1_200_CTRL_REG_ADDR, div, CLK_NCNOC1_200_DIV_SHIFT, CLK_NCNOC1_200_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_NCNOC1_200_ 		itg_get_reg(CLK_NCNOC1_200_CTRL_REG_ADDR, CLK_NCNOC1_200_DIV_SHIFT, CLK_NCNOC1_200_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_BCU_PCLK_ 			itg_set_reg(CLK_U0_BCU_PCLK_CTRL_REG_ADDR, CLK_U0_BCU_PCLK_ENABLE_DATA, CLK_U0_BCU_PCLK_EN_SHIFT, CLK_U0_BCU_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_BCU_PCLK_ 			itg_set_reg(CLK_U0_BCU_PCLK_CTRL_REG_ADDR, CLK_U0_BCU_PCLK_DISABLE_DATA, CLK_U0_BCU_PCLK_EN_SHIFT, CLK_U0_BCU_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_BCU_PCLK_ 		itg_get_reg(CLK_U0_BCU_PCLK_CTRL_REG_ADDR, CLK_U0_BCU_PCLK_EN_SHIFT, CLK_U0_BCU_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_BCU_PCLK_(x) 		itg_set_reg(CLK_U0_BCU_PCLK_CTRL_REG_ADDR, x, CLK_U0_BCU_PCLK_EN_SHIFT, CLK_U0_BCU_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_BCU_DFT_BISR_CLK_ 			itg_set_reg(CLK_U0_BCU_DFT_BISR_CLK_CTRL_REG_ADDR, CLK_U0_BCU_DFT_BISR_CLK_ENABLE_DATA, CLK_U0_BCU_DFT_BISR_CLK_EN_SHIFT, CLK_U0_BCU_DFT_BISR_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_BCU_DFT_BISR_CLK_ 			itg_set_reg(CLK_U0_BCU_DFT_BISR_CLK_CTRL_REG_ADDR, CLK_U0_BCU_DFT_BISR_CLK_DISABLE_DATA, CLK_U0_BCU_DFT_BISR_CLK_EN_SHIFT, CLK_U0_BCU_DFT_BISR_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_BCU_DFT_BISR_CLK_ 		itg_get_reg(CLK_U0_BCU_DFT_BISR_CLK_CTRL_REG_ADDR, CLK_U0_BCU_DFT_BISR_CLK_EN_SHIFT, CLK_U0_BCU_DFT_BISR_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_BCU_DFT_BISR_CLK_(x) 		itg_set_reg(CLK_U0_BCU_DFT_BISR_CLK_CTRL_REG_ADDR, x, CLK_U0_BCU_DFT_BISR_CLK_EN_SHIFT, CLK_U0_BCU_DFT_BISR_CLK_EN_MASK)
#define _ENABLE_CLOCK_DFT_GPIO_ESPI1_66_ 			itg_set_reg(DFT_GPIO_ESPI1_66_CTRL_REG_ADDR, DFT_GPIO_ESPI1_66_ENABLE_DATA, DFT_GPIO_ESPI1_66_EN_SHIFT, DFT_GPIO_ESPI1_66_EN_MASK)
#define _DISABLE_CLOCK_DFT_GPIO_ESPI1_66_ 			itg_set_reg(DFT_GPIO_ESPI1_66_CTRL_REG_ADDR, DFT_GPIO_ESPI1_66_DISABLE_DATA, DFT_GPIO_ESPI1_66_EN_SHIFT, DFT_GPIO_ESPI1_66_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_DFT_GPIO_ESPI1_66_ 		itg_get_reg(DFT_GPIO_ESPI1_66_CTRL_REG_ADDR, DFT_GPIO_ESPI1_66_EN_SHIFT, DFT_GPIO_ESPI1_66_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_DFT_GPIO_ESPI1_66_(x) 		itg_set_reg(DFT_GPIO_ESPI1_66_CTRL_REG_ADDR, x, DFT_GPIO_ESPI1_66_EN_SHIFT, DFT_GPIO_ESPI1_66_EN_MASK)
#define _DIVIDE_CLOCK_DFT_GPIO_ESPI1_66_(div) 			itg_set_reg(DFT_GPIO_ESPI1_66_CTRL_REG_ADDR, div, DFT_GPIO_ESPI1_66_DIV_SHIFT, DFT_GPIO_ESPI1_66_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_DFT_GPIO_ESPI1_66_ 		itg_get_reg(DFT_GPIO_ESPI1_66_CTRL_REG_ADDR, DFT_GPIO_ESPI1_66_DIV_SHIFT, DFT_GPIO_ESPI1_66_DIV_MASK)
#define _SWITCH_CLOCK_CLK_ESPI1_EXT_DFT_MUX_SOURCE_CLK_ESPI1_EXT_ 	itg_set_reg(CLK_ESPI1_EXT_DFT_MUX_CTRL_REG_ADDR, CLK_ESPI1_EXT_DFT_MUX_SW_CLK_ESPI1_EXT_DATA, CLK_ESPI1_EXT_DFT_MUX_SW_SHIFT, CLK_ESPI1_EXT_DFT_MUX_SW_MASK)
#define _SWITCH_CLOCK_CLK_ESPI1_EXT_DFT_MUX_SOURCE_DFT_GPIO_ESPI1_66_ 	itg_set_reg(CLK_ESPI1_EXT_DFT_MUX_CTRL_REG_ADDR, CLK_ESPI1_EXT_DFT_MUX_SW_DFT_GPIO_ESPI1_66_DATA, CLK_ESPI1_EXT_DFT_MUX_SW_SHIFT, CLK_ESPI1_EXT_DFT_MUX_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_ESPI1_EXT_DFT_MUX_ 		itg_get_reg(CLK_ESPI1_EXT_DFT_MUX_CTRL_REG_ADDR, CLK_ESPI1_EXT_DFT_MUX_SW_SHIFT, CLK_ESPI1_EXT_DFT_MUX_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_ESPI1_EXT_DFT_MUX_(x) 		itg_set_reg(CLK_ESPI1_EXT_DFT_MUX_CTRL_REG_ADDR, x, CLK_ESPI1_EXT_DFT_MUX_SW_SHIFT, CLK_ESPI1_EXT_DFT_MUX_SW_MASK)
#define _DIVIDE_CLOCK_CLK_HOSTSS1_100_(div) 			itg_set_reg(CLK_HOSTSS1_100_CTRL_REG_ADDR, div, CLK_HOSTSS1_100_DIV_SHIFT, CLK_HOSTSS1_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_HOSTSS1_100_ 		itg_get_reg(CLK_HOSTSS1_100_CTRL_REG_ADDR, CLK_HOSTSS1_100_DIV_SHIFT, CLK_HOSTSS1_100_DIV_MASK)
#define _SWITCH_CLOCK_CLK_HOSTSS1_CFG_SOURCE_CLK_OSC_ 	itg_set_reg(CLK_HOSTSS1_CFG_CTRL_REG_ADDR, CLK_HOSTSS1_CFG_SW_CLK_OSC_DATA, CLK_HOSTSS1_CFG_SW_SHIFT, CLK_HOSTSS1_CFG_SW_MASK)
#define _SWITCH_CLOCK_CLK_HOSTSS1_CFG_SOURCE_CLK_HOSTSS1_100_ 	itg_set_reg(CLK_HOSTSS1_CFG_CTRL_REG_ADDR, CLK_HOSTSS1_CFG_SW_CLK_HOSTSS1_100_DATA, CLK_HOSTSS1_CFG_SW_SHIFT, CLK_HOSTSS1_CFG_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_HOSTSS1_CFG_ 		itg_get_reg(CLK_HOSTSS1_CFG_CTRL_REG_ADDR, CLK_HOSTSS1_CFG_SW_SHIFT, CLK_HOSTSS1_CFG_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_HOSTSS1_CFG_(x) 		itg_set_reg(CLK_HOSTSS1_CFG_CTRL_REG_ADDR, x, CLK_HOSTSS1_CFG_SW_SHIFT, CLK_HOSTSS1_CFG_SW_MASK)
#define _ENABLE_CLOCK_CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_ 			itg_set_reg(CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_CTRL_REG_ADDR, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_ENABLE_DATA, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_SHIFT, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_MASK)
#define _DISABLE_CLOCK_CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_ 			itg_set_reg(CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_CTRL_REG_ADDR, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_DISABLE_DATA, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_SHIFT, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_ 		itg_get_reg(CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_CTRL_REG_ADDR, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_SHIFT, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_(x) 		itg_set_reg(CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_CTRL_REG_ADDR, x, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_SHIFT, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_MASK)
#define _DIVIDE_CLOCK_CLK_VOUT_100_(div) 			itg_set_reg(CLK_VOUT_100_CTRL_REG_ADDR, div, CLK_VOUT_100_DIV_SHIFT, CLK_VOUT_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_VOUT_100_ 		itg_get_reg(CLK_VOUT_100_CTRL_REG_ADDR, CLK_VOUT_100_DIV_SHIFT, CLK_VOUT_100_DIV_MASK)
#define _SWITCH_CLOCK_CLK_VOUT_TARG_SOURCE_CLK_OSC_ 	itg_set_reg(CLK_VOUT_TARG_CTRL_REG_ADDR, CLK_VOUT_TARG_SW_CLK_OSC_DATA, CLK_VOUT_TARG_SW_SHIFT, CLK_VOUT_TARG_SW_MASK)
#define _SWITCH_CLOCK_CLK_VOUT_TARG_SOURCE_CLK_VOUT_100_ 	itg_set_reg(CLK_VOUT_TARG_CTRL_REG_ADDR, CLK_VOUT_TARG_SW_CLK_VOUT_100_DATA, CLK_VOUT_TARG_SW_SHIFT, CLK_VOUT_TARG_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_VOUT_TARG_ 		itg_get_reg(CLK_VOUT_TARG_CTRL_REG_ADDR, CLK_VOUT_TARG_SW_SHIFT, CLK_VOUT_TARG_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_VOUT_TARG_(x) 		itg_set_reg(CLK_VOUT_TARG_CTRL_REG_ADDR, x, CLK_VOUT_TARG_SW_SHIFT, CLK_VOUT_TARG_SW_MASK)
#define _ENABLE_CLOCK_CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_ 			itg_set_reg(CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_CTRL_REG_ADDR, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_ENABLE_DATA, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_EN_SHIFT, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_ 			itg_set_reg(CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_CTRL_REG_ADDR, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_DISABLE_DATA, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_EN_SHIFT, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_ 		itg_get_reg(CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_CTRL_REG_ADDR, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_EN_SHIFT, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_(x) 		itg_set_reg(CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_CTRL_REG_ADDR, x, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_EN_SHIFT, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_1000_DFT_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_ 			itg_set_reg(CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_CTRL_REG_ADDR, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_ENABLE_DATA, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_EN_SHIFT, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_ 			itg_set_reg(CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_CTRL_REG_ADDR, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_DISABLE_DATA, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_EN_SHIFT, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_ 		itg_get_reg(CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_CTRL_REG_ADDR, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_EN_SHIFT, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_(x) 		itg_set_reg(CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_CTRL_REG_ADDR, x, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_EN_SHIFT, CLK_U0_DOM_VOUT_CLK_DOM_VOUT_CLK_SCAN_800_DFT_EN_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPER3_100_(div) 			itg_set_reg(CLK_BMCPER3_100_CTRL_REG_ADDR, div, CLK_BMCPER3_100_DIV_SHIFT, CLK_BMCPER3_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPER3_100_ 		itg_get_reg(CLK_BMCPER3_100_CTRL_REG_ADDR, CLK_BMCPER3_100_DIV_SHIFT, CLK_BMCPER3_100_DIV_MASK)
#define _SWITCH_CLOCK_CLK_BMCPER3_TARG_SOURCE_CLK_OSC_ 	itg_set_reg(CLK_BMCPER3_TARG_CTRL_REG_ADDR, CLK_BMCPER3_TARG_SW_CLK_OSC_DATA, CLK_BMCPER3_TARG_SW_SHIFT, CLK_BMCPER3_TARG_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPER3_TARG_SOURCE_CLK_BMCPER3_100_ 	itg_set_reg(CLK_BMCPER3_TARG_CTRL_REG_ADDR, CLK_BMCPER3_TARG_SW_CLK_BMCPER3_100_DATA, CLK_BMCPER3_TARG_SW_SHIFT, CLK_BMCPER3_TARG_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPER3_TARG_ 		itg_get_reg(CLK_BMCPER3_TARG_CTRL_REG_ADDR, CLK_BMCPER3_TARG_SW_SHIFT, CLK_BMCPER3_TARG_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPER3_TARG_(x) 		itg_set_reg(CLK_BMCPER3_TARG_CTRL_REG_ADDR, x, CLK_BMCPER3_TARG_SW_SHIFT, CLK_BMCPER3_TARG_SW_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPER3_125_(div) 			itg_set_reg(CLK_BMCPER3_125_CTRL_REG_ADDR, div, CLK_BMCPER3_125_DIV_SHIFT, CLK_BMCPER3_125_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPER3_125_ 		itg_get_reg(CLK_BMCPER3_125_CTRL_REG_ADDR, CLK_BMCPER3_125_DIV_SHIFT, CLK_BMCPER3_125_DIV_MASK)
#define _SWITCH_CLOCK_CLK_BMCPER3_125_OSC_SOURCE_CLK_OSC_ 	itg_set_reg(CLK_BMCPER3_125_OSC_CTRL_REG_ADDR, CLK_BMCPER3_125_OSC_SW_CLK_OSC_DATA, CLK_BMCPER3_125_OSC_SW_SHIFT, CLK_BMCPER3_125_OSC_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPER3_125_OSC_SOURCE_CLK_BMCPER3_125_ 	itg_set_reg(CLK_BMCPER3_125_OSC_CTRL_REG_ADDR, CLK_BMCPER3_125_OSC_SW_CLK_BMCPER3_125_DATA, CLK_BMCPER3_125_OSC_SW_SHIFT, CLK_BMCPER3_125_OSC_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPER3_125_OSC_ 		itg_get_reg(CLK_BMCPER3_125_OSC_CTRL_REG_ADDR, CLK_BMCPER3_125_OSC_SW_SHIFT, CLK_BMCPER3_125_OSC_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPER3_125_OSC_(x) 		itg_set_reg(CLK_BMCPER3_125_OSC_CTRL_REG_ADDR, x, CLK_BMCPER3_125_OSC_SW_SHIFT, CLK_BMCPER3_125_OSC_SW_MASK)

#define _ENABLE_CLOCK_MAIN_ICG_EN_BCU_ 			itg_set_reg(MAIN_ICG_EN_BCU_CTRL_REG_ADDR, MAIN_ICG_EN_BCU_ENABLE_DATA, MAIN_ICG_EN_BCU_EN_SHIFT, MAIN_ICG_EN_BCU_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_BCU_ 			itg_set_reg(MAIN_ICG_EN_BCU_CTRL_REG_ADDR, MAIN_ICG_EN_BCU_DISABLE_DATA, MAIN_ICG_EN_BCU_EN_SHIFT, MAIN_ICG_EN_BCU_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_BCU_ 		itg_get_reg(MAIN_ICG_EN_BCU_CTRL_REG_ADDR, MAIN_ICG_EN_BCU_EN_SHIFT, MAIN_ICG_EN_BCU_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_BCU_(x) 		itg_set_reg(MAIN_ICG_EN_BCU_CTRL_REG_ADDR, x, MAIN_ICG_EN_BCU_EN_SHIFT, MAIN_ICG_EN_BCU_EN_MASK)


#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_SYS1_SYSCON_PRESETN_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_SYSCON_PRESETN_SHIFT, RSTN_U0_SYS1_SYSCON_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_SYS1_SYSCON_PRESETN_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_SYSCON_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_SYS1_SYSCON_PRESETN_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_SYSCON_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_SYS1_IOMUX_PRESETN_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_IOMUX_PRESETN_SHIFT, RSTN_U0_SYS1_IOMUX_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_SYS1_IOMUX_PRESETN_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_IOMUX_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_SYS1_IOMUX_PRESETN_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_IOMUX_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BCU_PRST_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_PRST_SHIFT, RSTN_U0_BCU_PRST_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BCU_PRST_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_PRST_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BCU_PRST_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_PRST_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_SHIFT, RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BCU_DFT_BISR_RST_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_DFT_BISR_RST_SHIFT, RSTN_U0_BCU_DFT_BISR_RST_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BCU_DFT_BISR_RST_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_DFT_BISR_RST_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BCU_DFT_BISR_RST_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_DFT_BISR_RST_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_PCU_DC0_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PCU_DC0_SHIFT, MAIN_RSTN_PCU_DC0_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_PCU_DC0_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PCU_DC0_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_PCU_DC0_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PCU_DC0_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_PCU_DC1_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PCU_DC1_SHIFT, MAIN_RSTN_PCU_DC1_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_PCU_DC1_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PCU_DC1_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_PCU_DC1_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PCU_DC1_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_PCU_HOSTSS1_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PCU_HOSTSS1_SHIFT, MAIN_RSTN_PCU_HOSTSS1_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_PCU_HOSTSS1_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PCU_HOSTSS1_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_PCU_HOSTSS1_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_PCU_HOSTSS1_MASK)


#endif //_SYS1_CRG_MACRO_H_
