
#ifndef _SYS1_CRG_MACRO_H_
#define _SYS1_CRG_MACRO_H_

//#define SYS1_CRG_BASE_ADDR 0x0
#define CLK_APB_MAIN_SYS1_CTRL_REG_ADDR                              (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_APB_SENSOR_ICG_BUF_CTRL_REG_ADDR                         (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define CLK_NCNOC1_200_CTRL_REG_ADDR                                 (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define CLK_U0_BCU_PCLK_CTRL_REG_ADDR                                (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)
#define CLK_U0_BCU_DFT_BISR_CLK_CTRL_REG_ADDR                        (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define DFT_GPIO_ESPI1_66_CTRL_REG_ADDR                              (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define CLK_ESPI1_EXT_DFT_MUX_CTRL_REG_ADDR                          (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define CLK_HOSTSS1_100_CTRL_REG_ADDR                                (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x1CU)
#define CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_CTRL_REG_ADDR              (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x20U)
#define CLK_VOUT_100_CTRL_REG_ADDR                                   (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x3CU)
#define CLK_VOUT_PIX0_CTRL_REG_ADDR                                  (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x40U)
#define CLK_VOUT_PIX1_CTRL_REG_ADDR                                  (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x44U)
#define CLK_BMCPER3_100_CTRL_REG_ADDR                                (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x48U)
#define CLK_BMCPER3_125_CTRL_REG_ADDR                                (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x4CU)


#define MAIN_ICG_EN_BCU_CTRL_REG_ADDR                                (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x50U)


#define SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR              (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x54U)

#define SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR              (U0_SYS1_CRG__ITG_BD_APBS__BASE_ADDR + 0x58U)


#define CLK_APB_MAIN_SYS1_DIV_SHIFT                                  0
#define CLK_APB_MAIN_SYS1_DIV_MASK                                   0xFU
#define CLK_APB_SENSOR_ICG_BUF_ENABLE_DATA                           1
#define CLK_APB_SENSOR_ICG_BUF_DISABLE_DATA                          0
#define CLK_APB_SENSOR_ICG_BUF_EN_SHIFT                              31
#define CLK_APB_SENSOR_ICG_BUF_EN_MASK                               0x80000000U
#define CLK_NCNOC1_200_DIV_SHIFT                                     0
#define CLK_NCNOC1_200_DIV_MASK                                      0x7U
#define CLK_U0_BCU_PCLK_ENABLE_DATA                                  1
#define CLK_U0_BCU_PCLK_DISABLE_DATA                                 0
#define CLK_U0_BCU_PCLK_EN_SHIFT                                     31
#define CLK_U0_BCU_PCLK_EN_MASK                                      0x80000000U
#define CLK_U0_BCU_DFT_BISR_CLK_ENABLE_DATA                          1
#define CLK_U0_BCU_DFT_BISR_CLK_DISABLE_DATA                         0
#define CLK_U0_BCU_DFT_BISR_CLK_EN_SHIFT                             31
#define CLK_U0_BCU_DFT_BISR_CLK_EN_MASK                              0x80000000U
#define DFT_GPIO_ESPI1_66_DIV_SHIFT                                  0
#define DFT_GPIO_ESPI1_66_DIV_MASK                                   0xFU
#define CLK_ESPI1_EXT_DFT_MUX_SW_SHIFT                               24
#define CLK_ESPI1_EXT_DFT_MUX_SW_MASK                                0x1000000U
#define CLK_ESPI1_EXT_DFT_MUX_SW_CLK_ESPI1_EXT_DATA                  0
#define CLK_ESPI1_EXT_DFT_MUX_SW_DFT_GPIO_ESPI1_66_DATA              1
#define CLK_HOSTSS1_100_DIV_SHIFT                                    0
#define CLK_HOSTSS1_100_DIV_MASK                                     0xFU
#define CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_ENABLE_DATA                1
#define CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_DISABLE_DATA               0
#define CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_SHIFT                   31
#define CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_MASK                    0x80000000U
#define CLK_VOUT_100_DIV_SHIFT                                       0
#define CLK_VOUT_100_DIV_MASK                                        0xFU
#define CLK_VOUT_PIX0_DIV_SHIFT                                      0
#define CLK_VOUT_PIX0_DIV_MASK                                       0x7U
#define CLK_VOUT_PIX1_DIV_SHIFT                                      0
#define CLK_VOUT_PIX1_DIV_MASK                                       0x7U
#define CLK_BMCPER3_100_DIV_SHIFT                                    0
#define CLK_BMCPER3_100_DIV_MASK                                     0xFU
#define CLK_BMCPER3_125_DIV_SHIFT                                    0
#define CLK_BMCPER3_125_DIV_MASK                                     0xFU

#define MAIN_ICG_EN_BCU_ENABLE_DATA                                  1
#define MAIN_ICG_EN_BCU_DISABLE_DATA                                 0
#define MAIN_ICG_EN_BCU_EN_SHIFT                                     31
#define MAIN_ICG_EN_BCU_EN_MASK                                      0x80000000U



#define RSTN_U0_SYS1_SYSCON_PRESETN_SHIFT                            0
#define RSTN_U0_SYS1_SYSCON_PRESETN_MASK                             (0x1 << 0)
#define RSTN_U0_SYS1_SYSCON_PRESETN_ASSERT                           1
#define RSTN_U0_SYS1_SYSCON_PRESETN_CLEAR                            0
#define RSTN_U0_SYS1_IOMUX_PRESETN_SHIFT                             1
#define RSTN_U0_SYS1_IOMUX_PRESETN_MASK                              (0x1 << 1)
#define RSTN_U0_SYS1_IOMUX_PRESETN_ASSERT                            1
#define RSTN_U0_SYS1_IOMUX_PRESETN_CLEAR                             0
#define RSTN_U0_BCU_PRST_SHIFT                                       2
#define RSTN_U0_BCU_PRST_MASK                                        (0x1 << 2)
#define RSTN_U0_BCU_PRST_ASSERT                                      1
#define RSTN_U0_BCU_PRST_CLEAR                                       0
#define RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_SHIFT                          3
#define RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_MASK                           (0x1 << 3)
#define RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_ASSERT                         1
#define RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_CLEAR                          0
#define RSTN_U0_BCU_DFT_BISR_RST_SHIFT                               4
#define RSTN_U0_BCU_DFT_BISR_RST_MASK                                (0x1 << 4)
#define RSTN_U0_BCU_DFT_BISR_RST_ASSERT                              1
#define RSTN_U0_BCU_DFT_BISR_RST_CLEAR                               0
#define MAIN_RSTN_CHIPTOP_SENSOR_SHIFT                               5
#define MAIN_RSTN_CHIPTOP_SENSOR_MASK                                (0x1 << 5)
#define MAIN_RSTN_CHIPTOP_SENSOR_ASSERT                              1
#define MAIN_RSTN_CHIPTOP_SENSOR_CLEAR                               0
#define RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST0_SHIFT              8
#define RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST0_MASK               (0x1 << 8)
#define RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST0_ASSERT             1
#define RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST0_CLEAR              0
#define RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST1_SHIFT              9
#define RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST1_MASK               (0x1 << 9)
#define RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST1_ASSERT             1
#define RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST1_CLEAR              0
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_ESPI_SHIFT       10
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_ESPI_MASK        (0x1 << 10)
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_ESPI_ASSERT      1
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_ESPI_CLEAR       0
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_PCIE_SHIFT       11
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_PCIE_MASK        (0x1 << 11)
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_PCIE_ASSERT      1
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_PCIE_CLEAR       0
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_CRG_SHIFT            12
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_CRG_MASK             (0x1 << 12)
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_CRG_ASSERT           1
#define RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_CRG_CLEAR            0
#define RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_CRG_SHIFT    13
#define RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_CRG_MASK     (0x1 << 13)
#define RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_CRG_ASSERT   1
#define RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_CRG_CLEAR    0
#define RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_BUS_SHIFT    14
#define RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_BUS_MASK     (0x1 << 14)
#define RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_BUS_ASSERT   1
#define RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_BUS_CLEAR    0

#define _DIVIDE_CLOCK_CLK_APB_MAIN_SYS1_(div) 			itg_set_reg(CLK_APB_MAIN_SYS1_CTRL_REG_ADDR, div, CLK_APB_MAIN_SYS1_DIV_SHIFT, CLK_APB_MAIN_SYS1_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_MAIN_SYS1_ 		itg_get_reg(CLK_APB_MAIN_SYS1_CTRL_REG_ADDR, CLK_APB_MAIN_SYS1_DIV_SHIFT, CLK_APB_MAIN_SYS1_DIV_MASK)
#define _ENABLE_CLOCK_CLK_APB_SENSOR_ICG_BUF_ 			itg_set_reg(CLK_APB_SENSOR_ICG_BUF_CTRL_REG_ADDR, CLK_APB_SENSOR_ICG_BUF_ENABLE_DATA, CLK_APB_SENSOR_ICG_BUF_EN_SHIFT, CLK_APB_SENSOR_ICG_BUF_EN_MASK)
#define _DISABLE_CLOCK_CLK_APB_SENSOR_ICG_BUF_ 			itg_set_reg(CLK_APB_SENSOR_ICG_BUF_CTRL_REG_ADDR, CLK_APB_SENSOR_ICG_BUF_DISABLE_DATA, CLK_APB_SENSOR_ICG_BUF_EN_SHIFT, CLK_APB_SENSOR_ICG_BUF_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_APB_SENSOR_ICG_BUF_ 		itg_get_reg(CLK_APB_SENSOR_ICG_BUF_CTRL_REG_ADDR, CLK_APB_SENSOR_ICG_BUF_EN_SHIFT, CLK_APB_SENSOR_ICG_BUF_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_APB_SENSOR_ICG_BUF_(x) 		itg_set_reg(CLK_APB_SENSOR_ICG_BUF_CTRL_REG_ADDR, x, CLK_APB_SENSOR_ICG_BUF_EN_SHIFT, CLK_APB_SENSOR_ICG_BUF_EN_MASK)
#define _DIVIDE_CLOCK_CLK_NCNOC1_200_(div) 			itg_set_reg(CLK_NCNOC1_200_CTRL_REG_ADDR, div, CLK_NCNOC1_200_DIV_SHIFT, CLK_NCNOC1_200_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_NCNOC1_200_ 		itg_get_reg(CLK_NCNOC1_200_CTRL_REG_ADDR, CLK_NCNOC1_200_DIV_SHIFT, CLK_NCNOC1_200_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_BCU_PCLK_ 			itg_set_reg(CLK_U0_BCU_PCLK_CTRL_REG_ADDR, CLK_U0_BCU_PCLK_ENABLE_DATA, CLK_U0_BCU_PCLK_EN_SHIFT, CLK_U0_BCU_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_BCU_PCLK_ 			itg_set_reg(CLK_U0_BCU_PCLK_CTRL_REG_ADDR, CLK_U0_BCU_PCLK_DISABLE_DATA, CLK_U0_BCU_PCLK_EN_SHIFT, CLK_U0_BCU_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_BCU_PCLK_ 		itg_get_reg(CLK_U0_BCU_PCLK_CTRL_REG_ADDR, CLK_U0_BCU_PCLK_EN_SHIFT, CLK_U0_BCU_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_BCU_PCLK_(x) 		itg_set_reg(CLK_U0_BCU_PCLK_CTRL_REG_ADDR, x, CLK_U0_BCU_PCLK_EN_SHIFT, CLK_U0_BCU_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_BCU_DFT_BISR_CLK_ 			itg_set_reg(CLK_U0_BCU_DFT_BISR_CLK_CTRL_REG_ADDR, CLK_U0_BCU_DFT_BISR_CLK_ENABLE_DATA, CLK_U0_BCU_DFT_BISR_CLK_EN_SHIFT, CLK_U0_BCU_DFT_BISR_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_BCU_DFT_BISR_CLK_ 			itg_set_reg(CLK_U0_BCU_DFT_BISR_CLK_CTRL_REG_ADDR, CLK_U0_BCU_DFT_BISR_CLK_DISABLE_DATA, CLK_U0_BCU_DFT_BISR_CLK_EN_SHIFT, CLK_U0_BCU_DFT_BISR_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_BCU_DFT_BISR_CLK_ 		itg_get_reg(CLK_U0_BCU_DFT_BISR_CLK_CTRL_REG_ADDR, CLK_U0_BCU_DFT_BISR_CLK_EN_SHIFT, CLK_U0_BCU_DFT_BISR_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_BCU_DFT_BISR_CLK_(x) 		itg_set_reg(CLK_U0_BCU_DFT_BISR_CLK_CTRL_REG_ADDR, x, CLK_U0_BCU_DFT_BISR_CLK_EN_SHIFT, CLK_U0_BCU_DFT_BISR_CLK_EN_MASK)
#define _DIVIDE_CLOCK_DFT_GPIO_ESPI1_66_(div) 			itg_set_reg(DFT_GPIO_ESPI1_66_CTRL_REG_ADDR, div, DFT_GPIO_ESPI1_66_DIV_SHIFT, DFT_GPIO_ESPI1_66_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_DFT_GPIO_ESPI1_66_ 		itg_get_reg(DFT_GPIO_ESPI1_66_CTRL_REG_ADDR, DFT_GPIO_ESPI1_66_DIV_SHIFT, DFT_GPIO_ESPI1_66_DIV_MASK)
#define _SWITCH_CLOCK_CLK_ESPI1_EXT_DFT_MUX_SOURCE_CLK_ESPI1_EXT_ 	itg_set_reg(CLK_ESPI1_EXT_DFT_MUX_CTRL_REG_ADDR, CLK_ESPI1_EXT_DFT_MUX_SW_CLK_ESPI1_EXT_DATA, CLK_ESPI1_EXT_DFT_MUX_SW_SHIFT, CLK_ESPI1_EXT_DFT_MUX_SW_MASK)
#define _SWITCH_CLOCK_CLK_ESPI1_EXT_DFT_MUX_SOURCE_DFT_GPIO_ESPI1_66_ 	itg_set_reg(CLK_ESPI1_EXT_DFT_MUX_CTRL_REG_ADDR, CLK_ESPI1_EXT_DFT_MUX_SW_DFT_GPIO_ESPI1_66_DATA, CLK_ESPI1_EXT_DFT_MUX_SW_SHIFT, CLK_ESPI1_EXT_DFT_MUX_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_ESPI1_EXT_DFT_MUX_ 		itg_get_reg(CLK_ESPI1_EXT_DFT_MUX_CTRL_REG_ADDR, CLK_ESPI1_EXT_DFT_MUX_SW_SHIFT, CLK_ESPI1_EXT_DFT_MUX_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_ESPI1_EXT_DFT_MUX_(x) 		itg_set_reg(CLK_ESPI1_EXT_DFT_MUX_CTRL_REG_ADDR, x, CLK_ESPI1_EXT_DFT_MUX_SW_SHIFT, CLK_ESPI1_EXT_DFT_MUX_SW_MASK)
#define _DIVIDE_CLOCK_CLK_HOSTSS1_100_(div) 			itg_set_reg(CLK_HOSTSS1_100_CTRL_REG_ADDR, div, CLK_HOSTSS1_100_DIV_SHIFT, CLK_HOSTSS1_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_HOSTSS1_100_ 		itg_get_reg(CLK_HOSTSS1_100_CTRL_REG_ADDR, CLK_HOSTSS1_100_DIV_SHIFT, CLK_HOSTSS1_100_DIV_MASK)
#define _ENABLE_CLOCK_CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_ 			itg_set_reg(CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_CTRL_REG_ADDR, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_ENABLE_DATA, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_SHIFT, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_MASK)
#define _DISABLE_CLOCK_CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_ 			itg_set_reg(CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_CTRL_REG_ADDR, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_DISABLE_DATA, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_SHIFT, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_ 		itg_get_reg(CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_CTRL_REG_ADDR, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_SHIFT, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_(x) 		itg_set_reg(CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_CTRL_REG_ADDR, x, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_SHIFT, CLK_HOSTSS1_PHY_SCAN_1000_ICG_BUF_EN_MASK)
#define _DIVIDE_CLOCK_CLK_VOUT_100_(div) 			itg_set_reg(CLK_VOUT_100_CTRL_REG_ADDR, div, CLK_VOUT_100_DIV_SHIFT, CLK_VOUT_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_VOUT_100_ 		itg_get_reg(CLK_VOUT_100_CTRL_REG_ADDR, CLK_VOUT_100_DIV_SHIFT, CLK_VOUT_100_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_VOUT_PIX0_(div) 			itg_set_reg(CLK_VOUT_PIX0_CTRL_REG_ADDR, div, CLK_VOUT_PIX0_DIV_SHIFT, CLK_VOUT_PIX0_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_VOUT_PIX0_ 		itg_get_reg(CLK_VOUT_PIX0_CTRL_REG_ADDR, CLK_VOUT_PIX0_DIV_SHIFT, CLK_VOUT_PIX0_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_VOUT_PIX1_(div) 			itg_set_reg(CLK_VOUT_PIX1_CTRL_REG_ADDR, div, CLK_VOUT_PIX1_DIV_SHIFT, CLK_VOUT_PIX1_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_VOUT_PIX1_ 		itg_get_reg(CLK_VOUT_PIX1_CTRL_REG_ADDR, CLK_VOUT_PIX1_DIV_SHIFT, CLK_VOUT_PIX1_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPER3_100_(div) 			itg_set_reg(CLK_BMCPER3_100_CTRL_REG_ADDR, div, CLK_BMCPER3_100_DIV_SHIFT, CLK_BMCPER3_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPER3_100_ 		itg_get_reg(CLK_BMCPER3_100_CTRL_REG_ADDR, CLK_BMCPER3_100_DIV_SHIFT, CLK_BMCPER3_100_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPER3_125_(div) 			itg_set_reg(CLK_BMCPER3_125_CTRL_REG_ADDR, div, CLK_BMCPER3_125_DIV_SHIFT, CLK_BMCPER3_125_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPER3_125_ 		itg_get_reg(CLK_BMCPER3_125_CTRL_REG_ADDR, CLK_BMCPER3_125_DIV_SHIFT, CLK_BMCPER3_125_DIV_MASK)

#define _ENABLE_CLOCK_MAIN_ICG_EN_BCU_ 			itg_set_reg(MAIN_ICG_EN_BCU_CTRL_REG_ADDR, MAIN_ICG_EN_BCU_ENABLE_DATA, MAIN_ICG_EN_BCU_EN_SHIFT, MAIN_ICG_EN_BCU_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_BCU_ 			itg_set_reg(MAIN_ICG_EN_BCU_CTRL_REG_ADDR, MAIN_ICG_EN_BCU_DISABLE_DATA, MAIN_ICG_EN_BCU_EN_SHIFT, MAIN_ICG_EN_BCU_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_BCU_ 		itg_get_reg(MAIN_ICG_EN_BCU_CTRL_REG_ADDR, MAIN_ICG_EN_BCU_EN_SHIFT, MAIN_ICG_EN_BCU_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_BCU_(x) 		itg_set_reg(MAIN_ICG_EN_BCU_CTRL_REG_ADDR, x, MAIN_ICG_EN_BCU_EN_SHIFT, MAIN_ICG_EN_BCU_EN_MASK)


#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_SYS1_SYSCON_PRESETN_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_SYSCON_PRESETN_SHIFT, RSTN_U0_SYS1_SYSCON_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_SYS1_SYSCON_PRESETN_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_SYSCON_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_SYS1_SYSCON_PRESETN_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_SYSCON_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_SYS1_IOMUX_PRESETN_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_IOMUX_PRESETN_SHIFT, RSTN_U0_SYS1_IOMUX_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_SYS1_IOMUX_PRESETN_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_IOMUX_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_SYS1_IOMUX_PRESETN_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS1_IOMUX_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BCU_PRST_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_PRST_SHIFT, RSTN_U0_BCU_PRST_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BCU_PRST_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_PRST_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BCU_PRST_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_PRST_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_SHIFT, RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_BCU_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BCU_DFT_BISR_RST_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_DFT_BISR_RST_SHIFT, RSTN_U0_BCU_DFT_BISR_RST_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BCU_DFT_BISR_RST_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_DFT_BISR_RST_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BCU_DFT_BISR_RST_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BCU_DFT_BISR_RST_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_CHIPTOP_SENSOR_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_CHIPTOP_SENSOR_SHIFT, MAIN_RSTN_CHIPTOP_SENSOR_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_CHIPTOP_SENSOR_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_CHIPTOP_SENSOR_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_CHIPTOP_SENSOR_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_CHIPTOP_SENSOR_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST0_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST0_SHIFT, RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST0_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST0_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST0_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST0_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST0_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST1_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST1_SHIFT, RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST1_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST1_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST1_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST1_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_VOUT_RSTN_DOM_VOUT_RSTN_HOST1_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_ESPI_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_ESPI_SHIFT, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_ESPI_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_ESPI_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_ESPI_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_ESPI_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_ESPI_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_PCIE_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_PCIE_SHIFT, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_PCIE_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_PCIE_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_PCIE_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_PCIE_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_BUS_PCIE_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_CRG_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_CRG_SHIFT, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_CRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_CRG_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_CRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_CRG_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_HOSTSS_RSTN_DOM_HOSTSS_RSTN_CRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_CRG_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_CRG_SHIFT, RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_CRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_CRG_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_CRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_CRG_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_CRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_BUS_ 	itg_get_reg(SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_BUS_SHIFT, RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_BUS_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_BUS_ 	itg_assert_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_BUS_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_BUS_ 	itg_clear_rst(SYS1_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS1_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH3_RSTN_DOM_BMCPERIPH3_RSTN_BUS_MASK)


#endif //_SYS1_CRG_MACRO_H_
