//RTL tag v0.5.1


#ifndef _SYS2_SECURE_CRG_MACRO_H_
#define _SYS2_SECURE_CRG_MACRO_H_

//#define SYS2_SECURE_CRG_BASE_ADDR 0x0
#define CLK_APB_MAIN_SYS2_SEC_CTRL_REG_ADDR                          (U0_SYS2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_APB_OSC_SYS2_SEC_CTRL_REG_ADDR                           (U0_SYS2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)


#define SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR       (U0_SYS2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)

#define SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR       (U0_SYS2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)


#define CLK_APB_MAIN_SYS2_SEC_DIV_SHIFT                              0
#define CLK_APB_MAIN_SYS2_SEC_DIV_MASK                               0xFU
#define CLK_APB_OSC_SYS2_SEC_SW_SHIFT                                24
#define CLK_APB_OSC_SYS2_SEC_SW_MASK                                 0x1000000U
#define CLK_APB_OSC_SYS2_SEC_SW_CLK_OSC_DATA                         0
#define CLK_APB_OSC_SYS2_SEC_SW_CLK_APB_MAIN_SYS2_SEC_DATA           1




#define RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_SHIFT                     0
#define RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_MASK                      (0x1 << 0)
#define RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_ASSERT                    1
#define RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_CLEAR                     0
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_SHIFT                  1
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_MASK                   (0x1 << 1)
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_ASSERT                 1
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_CLEAR                  0
#define MAIN_RSTN_SYS2SEC_IOMUX_SHIFT                                2
#define MAIN_RSTN_SYS2SEC_IOMUX_MASK                                 (0x1 << 2)
#define MAIN_RSTN_SYS2SEC_IOMUX_ASSERT                               1
#define MAIN_RSTN_SYS2SEC_IOMUX_CLEAR                                0

#define _DIVIDE_CLOCK_CLK_APB_MAIN_SYS2_SEC_(div) 			itg_set_reg(CLK_APB_MAIN_SYS2_SEC_CTRL_REG_ADDR, div, CLK_APB_MAIN_SYS2_SEC_DIV_SHIFT, CLK_APB_MAIN_SYS2_SEC_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_MAIN_SYS2_SEC_ 		itg_get_reg(CLK_APB_MAIN_SYS2_SEC_CTRL_REG_ADDR, CLK_APB_MAIN_SYS2_SEC_DIV_SHIFT, CLK_APB_MAIN_SYS2_SEC_DIV_MASK)
#define _SWITCH_CLOCK_CLK_APB_OSC_SYS2_SEC_SOURCE_CLK_OSC_ 	itg_set_reg(CLK_APB_OSC_SYS2_SEC_CTRL_REG_ADDR, CLK_APB_OSC_SYS2_SEC_SW_CLK_OSC_DATA, CLK_APB_OSC_SYS2_SEC_SW_SHIFT, CLK_APB_OSC_SYS2_SEC_SW_MASK)
#define _SWITCH_CLOCK_CLK_APB_OSC_SYS2_SEC_SOURCE_CLK_APB_MAIN_SYS2_SEC_ 	itg_set_reg(CLK_APB_OSC_SYS2_SEC_CTRL_REG_ADDR, CLK_APB_OSC_SYS2_SEC_SW_CLK_APB_MAIN_SYS2_SEC_DATA, CLK_APB_OSC_SYS2_SEC_SW_SHIFT, CLK_APB_OSC_SYS2_SEC_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_APB_OSC_SYS2_SEC_ 		itg_get_reg(CLK_APB_OSC_SYS2_SEC_CTRL_REG_ADDR, CLK_APB_OSC_SYS2_SEC_SW_SHIFT, CLK_APB_OSC_SYS2_SEC_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_APB_OSC_SYS2_SEC_(x) 		itg_set_reg(CLK_APB_OSC_SYS2_SEC_CTRL_REG_ADDR, x, CLK_APB_OSC_SYS2_SEC_SW_SHIFT, CLK_APB_OSC_SYS2_SEC_SW_MASK)



#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_ 	itg_get_reg(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_SHIFT, RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_ 	itg_assert_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_ 	itg_clear_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_ 	itg_get_reg(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_SHIFT, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_ 	itg_assert_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_ 	itg_clear_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_SYS2SEC_IOMUX_ 	itg_get_reg(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SYS2SEC_IOMUX_SHIFT, MAIN_RSTN_SYS2SEC_IOMUX_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_SYS2SEC_IOMUX_ 	itg_assert_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SYS2SEC_IOMUX_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_SYS2SEC_IOMUX_ 	itg_clear_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SYS2SEC_IOMUX_MASK)


#endif //_SYS2_SECURE_CRG_MACRO_H_
