
#ifndef _SYS2_CRG_MACRO_H_
#define _SYS2_CRG_MACRO_H_

//#define SYS2_CRG_BASE_ADDR 0x0
#define CLK_APB_MAIN_SYS2_CTRL_REG_ADDR                              (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define DFT_GPIO_50_CTRL_REG_ADDR                                    (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define CLK_DEBUG_JTAG_CTRL_REG_ADDR                                 (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define CLK_JTAGM0_200_CTRL_REG_ADDR                                 (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)
#define CLK_JTAGM1_200_CTRL_REG_ADDR                                 (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define CLK_JTAGM0_100_CTRL_REG_ADDR                                 (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define CLK_JTAGM1_100_CTRL_REG_ADDR                                 (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define CLK_JTAGM0_ATPG_TCLOCK_CTRL_REG_ADDR                         (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x1CU)
#define CLK_JTAGM1_ATPG_TCLOCK_CTRL_REG_ADDR                         (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x20U)
#define CLK_U0_JTAG_MST_WRAP_HCLK_CTRL_REG_ADDR                      (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x24U)
#define CLK_U0_JTAG_MST_WRAP_CLK_JTAG_CTRL_REG_ADDR                  (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x28U)
#define CLK_U0_JTAG_MST_WRAP_APB_PCLK_CTRL_REG_ADDR                  (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x2CU)
#define CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_CTRL_REG_ADDR               (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x30U)
#define CLK_U1_JTAG_MST_WRAP_HCLK_CTRL_REG_ADDR                      (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x34U)
#define CLK_U1_JTAG_MST_WRAP_CLK_JTAG_CTRL_REG_ADDR                  (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x38U)
#define CLK_U1_JTAG_MST_WRAP_APB_PCLK_CTRL_REG_ADDR                  (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x3CU)
#define CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_CTRL_REG_ADDR               (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x40U)
#define CLK_HOSTUSB_100_CTRL_REG_ADDR                                (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x44U)
#define CLK_HOSTUSBCMN_500_CTRL_REG_ADDR                             (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x48U)
#define CLK_BMCPER1_200_CTRL_REG_ADDR                                (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x4CU)
#define CLK_BMCPER1_250_CTRL_REG_ADDR                                (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x50U)
#define CLK_BMCPER1_143_DFT_CTRL_REG_ADDR                            (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x54U)
#define CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_CTRL_REG_ADDR (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x58U)
#define CLK_BMCPER0_200_CTRL_REG_ADDR                                (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x5CU)
#define CLK_GPU0_100_CTRL_REG_ADDR                                   (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x60U)
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_CTRL_REG_ADDR         (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x64U)
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_CTRL_REG_ADDR         (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x68U)
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_CTRL_REG_ADDR         (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x6CU)
#define CLK_GPU1_100_CTRL_REG_ADDR                                   (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x70U)
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_CTRL_REG_ADDR         (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x74U)
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_CTRL_REG_ADDR         (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x78U)
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_CTRL_REG_ADDR         (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x7CU)


#define MAIN_ICG_EN_JTAG0_CTRL_REG_ADDR                              (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x80U)
#define MAIN_ICG_EN_JTAG1_CTRL_REG_ADDR                              (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x84U)


#define SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR              (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x88U)

#define SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR              (U0_SYS2_CRG__ITG_BD_APBS__BASE_ADDR + 0x8CU)


#define CLK_APB_MAIN_SYS2_DIV_SHIFT                                  0
#define CLK_APB_MAIN_SYS2_DIV_MASK                                   0xFU
#define DFT_GPIO_50_DIV_SHIFT                                        0
#define DFT_GPIO_50_DIV_MASK                                         0x1FU
#define CLK_DEBUG_JTAG_SW_SHIFT                                      24
#define CLK_DEBUG_JTAG_SW_MASK                                       0x1000000U
#define CLK_DEBUG_JTAG_SW_SECJTAG_TCK_EXT_DATA                       0
#define CLK_DEBUG_JTAG_SW_DFT_GPIO_50_DATA                           1
#define CLK_JTAGM0_200_DIV_SHIFT                                     0
#define CLK_JTAGM0_200_DIV_MASK                                      0x7U
#define CLK_JTAGM1_200_DIV_SHIFT                                     0
#define CLK_JTAGM1_200_DIV_MASK                                      0x7U
#define CLK_JTAGM0_100_DIV_SHIFT                                     0
#define CLK_JTAGM0_100_DIV_MASK                                      0xFU
#define CLK_JTAGM1_100_DIV_SHIFT                                     0
#define CLK_JTAGM1_100_DIV_MASK                                      0xFU
#define CLK_JTAGM0_ATPG_TCLOCK_DIV_SHIFT                             0
#define CLK_JTAGM0_ATPG_TCLOCK_DIV_MASK                              0x3U
#define CLK_JTAGM1_ATPG_TCLOCK_DIV_SHIFT                             0
#define CLK_JTAGM1_ATPG_TCLOCK_DIV_MASK                              0x3U
#define CLK_U0_JTAG_MST_WRAP_HCLK_ENABLE_DATA                        1
#define CLK_U0_JTAG_MST_WRAP_HCLK_DISABLE_DATA                       0
#define CLK_U0_JTAG_MST_WRAP_HCLK_EN_SHIFT                           31
#define CLK_U0_JTAG_MST_WRAP_HCLK_EN_MASK                            0x80000000U
#define CLK_U0_JTAG_MST_WRAP_CLK_JTAG_ENABLE_DATA                    1
#define CLK_U0_JTAG_MST_WRAP_CLK_JTAG_DISABLE_DATA                   0
#define CLK_U0_JTAG_MST_WRAP_CLK_JTAG_EN_SHIFT                       31
#define CLK_U0_JTAG_MST_WRAP_CLK_JTAG_EN_MASK                        0x80000000U
#define CLK_U0_JTAG_MST_WRAP_APB_PCLK_ENABLE_DATA                    1
#define CLK_U0_JTAG_MST_WRAP_APB_PCLK_DISABLE_DATA                   0
#define CLK_U0_JTAG_MST_WRAP_APB_PCLK_EN_SHIFT                       31
#define CLK_U0_JTAG_MST_WRAP_APB_PCLK_EN_MASK                        0x80000000U
#define CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_ENABLE_DATA                 1
#define CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_DISABLE_DATA                0
#define CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_EN_SHIFT                    31
#define CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_EN_MASK                     0x80000000U
#define CLK_U1_JTAG_MST_WRAP_HCLK_ENABLE_DATA                        1
#define CLK_U1_JTAG_MST_WRAP_HCLK_DISABLE_DATA                       0
#define CLK_U1_JTAG_MST_WRAP_HCLK_EN_SHIFT                           31
#define CLK_U1_JTAG_MST_WRAP_HCLK_EN_MASK                            0x80000000U
#define CLK_U1_JTAG_MST_WRAP_CLK_JTAG_ENABLE_DATA                    1
#define CLK_U1_JTAG_MST_WRAP_CLK_JTAG_DISABLE_DATA                   0
#define CLK_U1_JTAG_MST_WRAP_CLK_JTAG_EN_SHIFT                       31
#define CLK_U1_JTAG_MST_WRAP_CLK_JTAG_EN_MASK                        0x80000000U
#define CLK_U1_JTAG_MST_WRAP_APB_PCLK_ENABLE_DATA                    1
#define CLK_U1_JTAG_MST_WRAP_APB_PCLK_DISABLE_DATA                   0
#define CLK_U1_JTAG_MST_WRAP_APB_PCLK_EN_SHIFT                       31
#define CLK_U1_JTAG_MST_WRAP_APB_PCLK_EN_MASK                        0x80000000U
#define CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_ENABLE_DATA                 1
#define CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_DISABLE_DATA                0
#define CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_EN_SHIFT                    31
#define CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_EN_MASK                     0x80000000U
#define CLK_HOSTUSB_100_DIV_SHIFT                                    0
#define CLK_HOSTUSB_100_DIV_MASK                                     0xFU
#define CLK_HOSTUSBCMN_500_DIV_SHIFT                                 0
#define CLK_HOSTUSBCMN_500_DIV_MASK                                  0x7U
#define CLK_BMCPER1_200_DIV_SHIFT                                    0
#define CLK_BMCPER1_200_DIV_MASK                                     0x7U
#define CLK_BMCPER1_250_DIV_SHIFT                                    0
#define CLK_BMCPER1_250_DIV_MASK                                     0x7U
#define CLK_BMCPER1_143_DFT_DIV_SHIFT                                0
#define CLK_BMCPER1_143_DFT_DIV_MASK                                 0xFU
#define CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_ENABLE_DATA 1
#define CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_DISABLE_DATA 0
#define CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_EN_SHIFT 31
#define CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_EN_MASK 0x80000000U
#define CLK_BMCPER0_200_DIV_SHIFT                                    0
#define CLK_BMCPER0_200_DIV_MASK                                     0x7U
#define CLK_GPU0_100_DIV_SHIFT                                       0
#define CLK_GPU0_100_DIV_MASK                                        0xFU
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_ENABLE_DATA           1
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_DISABLE_DATA          0
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_SHIFT              31
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_MASK               0x80000000U
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_ENABLE_DATA           1
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_DISABLE_DATA          0
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_SHIFT              31
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_MASK               0x80000000U
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_ENABLE_DATA           1
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_DISABLE_DATA          0
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_SHIFT              31
#define CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_MASK               0x80000000U
#define CLK_GPU1_100_DIV_SHIFT                                       0
#define CLK_GPU1_100_DIV_MASK                                        0xFU
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_ENABLE_DATA           1
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_DISABLE_DATA          0
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_SHIFT              31
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_MASK               0x80000000U
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_ENABLE_DATA           1
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_DISABLE_DATA          0
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_SHIFT              31
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_MASK               0x80000000U
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_ENABLE_DATA           1
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_DISABLE_DATA          0
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_SHIFT              31
#define CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_MASK               0x80000000U

#define MAIN_ICG_EN_JTAG0_ENABLE_DATA                                1
#define MAIN_ICG_EN_JTAG0_DISABLE_DATA                               0
#define MAIN_ICG_EN_JTAG0_EN_SHIFT                                   31
#define MAIN_ICG_EN_JTAG0_EN_MASK                                    0x80000000U
#define MAIN_ICG_EN_JTAG1_ENABLE_DATA                                1
#define MAIN_ICG_EN_JTAG1_DISABLE_DATA                               0
#define MAIN_ICG_EN_JTAG1_EN_SHIFT                                   31
#define MAIN_ICG_EN_JTAG1_EN_MASK                                    0x80000000U



#define RSTN_U0_SYS2_SYSCON_PRESETN_SHIFT                            0
#define RSTN_U0_SYS2_SYSCON_PRESETN_MASK                             (0x1 << 0)
#define RSTN_U0_SYS2_SYSCON_PRESETN_ASSERT                           1
#define RSTN_U0_SYS2_SYSCON_PRESETN_CLEAR                            0
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SHIFT                         1
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_MASK                          (0x1 << 1)
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_ASSERT                        1
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_CLEAR                         0
#define RSTN_U0_JTAG_MST_WRAP_HRESETN_SHIFT                          2
#define RSTN_U0_JTAG_MST_WRAP_HRESETN_MASK                           (0x1 << 2)
#define RSTN_U0_JTAG_MST_WRAP_HRESETN_ASSERT                         1
#define RSTN_U0_JTAG_MST_WRAP_HRESETN_CLEAR                          0
#define RSTN_U0_JTAG_MST_WRAP_APB_PRESETN_SHIFT                      3
#define RSTN_U0_JTAG_MST_WRAP_APB_PRESETN_MASK                       (0x1 << 3)
#define RSTN_U0_JTAG_MST_WRAP_APB_PRESETN_ASSERT                     1
#define RSTN_U0_JTAG_MST_WRAP_APB_PRESETN_CLEAR                      0
#define RSTN_U1_JTAG_MST_WRAP_HRESETN_SHIFT                          4
#define RSTN_U1_JTAG_MST_WRAP_HRESETN_MASK                           (0x1 << 4)
#define RSTN_U1_JTAG_MST_WRAP_HRESETN_ASSERT                         1
#define RSTN_U1_JTAG_MST_WRAP_HRESETN_CLEAR                          0
#define RSTN_U1_JTAG_MST_WRAP_APB_PRESETN_SHIFT                      5
#define RSTN_U1_JTAG_MST_WRAP_APB_PRESETN_MASK                       (0x1 << 5)
#define RSTN_U1_JTAG_MST_WRAP_APB_PRESETN_ASSERT                     1
#define RSTN_U1_JTAG_MST_WRAP_APB_PRESETN_CLEAR                      0
#define RSTN_U0_DEBUG_SUBSYS_RELEASE_RSTN_JTAG_CERTIFICATION_SHIFT   6
#define RSTN_U0_DEBUG_SUBSYS_RELEASE_RSTN_JTAG_CERTIFICATION_MASK    (0x1 << 6)
#define RSTN_U0_DEBUG_SUBSYS_RELEASE_RSTN_JTAG_CERTIFICATION_ASSERT  1
#define RSTN_U0_DEBUG_SUBSYS_RELEASE_RSTN_JTAG_CERTIFICATION_CLEAR   0
#define RST_U0_DEBUG_SUBSYS_RELEASE_POR_RESET_SHIFT                  7
#define RST_U0_DEBUG_SUBSYS_RELEASE_POR_RESET_MASK                   (0x1 << 7)
#define RST_U0_DEBUG_SUBSYS_RELEASE_POR_RESET_ASSERT                 1
#define RST_U0_DEBUG_SUBSYS_RELEASE_POR_RESET_CLEAR                  0
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTCMN_RSTN_BUS_NCNOC_INIT_SHIFT 8
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTCMN_RSTN_BUS_NCNOC_INIT_MASK (0x1 << 8)
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTCMN_RSTN_BUS_NCNOC_INIT_ASSERT 1
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTCMN_RSTN_BUS_NCNOC_INIT_CLEAR 0
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTCMN_CRG_SHIFT 9
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTCMN_CRG_MASK (0x1 << 9)
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTCMN_CRG_ASSERT 1
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTCMN_CRG_CLEAR 0
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_BMC_TARG_SHIFT 10
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_BMC_TARG_MASK (0x1 << 10)
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_BMC_TARG_ASSERT 1
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_BMC_TARG_CLEAR 0
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_HOST_TARG_SHIFT 11
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_HOST_TARG_MASK (0x1 << 11)
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_HOST_TARG_ASSERT 1
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_HOST_TARG_CLEAR 0
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_BMC_CRG_SHIFT 12
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_BMC_CRG_MASK (0x1 << 12)
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_BMC_CRG_ASSERT 1
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_BMC_CRG_CLEAR 0
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB0_CRG_SHIFT 13
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB0_CRG_MASK (0x1 << 13)
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB0_CRG_ASSERT 1
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB0_CRG_CLEAR 0
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_BMC_TARG_SHIFT 14
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_BMC_TARG_MASK (0x1 << 14)
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_BMC_TARG_ASSERT 1
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_BMC_TARG_CLEAR 0
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_HOST_TARG_SHIFT 15
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_HOST_TARG_MASK (0x1 << 15)
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_HOST_TARG_ASSERT 1
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_HOST_TARG_CLEAR 0
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB1_CRG_SHIFT 16
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB1_CRG_MASK (0x1 << 16)
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB1_CRG_ASSERT 1
#define RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB1_CRG_CLEAR 0
#define RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_CRG_SHIFT    17
#define RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_CRG_MASK     (0x1 << 17)
#define RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_CRG_ASSERT   1
#define RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_CRG_CLEAR    0
#define RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_BUS_SHIFT    18
#define RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_BUS_MASK     (0x1 << 18)
#define RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_BUS_ASSERT   1
#define RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_BUS_CLEAR    0
#define RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_CRG_SHIFT 19
#define RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_CRG_MASK (0x1 << 19)
#define RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_CRG_ASSERT 1
#define RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_CRG_CLEAR 0
#define RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_BUS_SHIFT 20
#define RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_BUS_MASK (0x1 << 20)
#define RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_BUS_ASSERT 1
#define RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_BUS_CLEAR 0
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_SHIFT                  21
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_MASK                   (0x1 << 21)
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_ASSERT                 1
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_CLEAR                  0
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_SHIFT                  22
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_MASK                   (0x1 << 22)
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_ASSERT                 1
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_CLEAR                  0
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_SHIFT           23
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_MASK            (0x1 << 23)
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_ASSERT          1
#define RSTN_U0_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_CLEAR           0
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_SHIFT                  24
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_MASK                   (0x1 << 24)
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_ASSERT                 1
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_CLEAR                  0
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_SHIFT                  25
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_MASK                   (0x1 << 25)
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_ASSERT                 1
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_CLEAR                  0
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_SHIFT           26
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_MASK            (0x1 << 26)
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_ASSERT          1
#define RSTN_U1_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_CLEAR           0

#define _DIVIDE_CLOCK_CLK_APB_MAIN_SYS2_(div) 			itg_set_reg(CLK_APB_MAIN_SYS2_CTRL_REG_ADDR, div, CLK_APB_MAIN_SYS2_DIV_SHIFT, CLK_APB_MAIN_SYS2_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_MAIN_SYS2_ 		itg_get_reg(CLK_APB_MAIN_SYS2_CTRL_REG_ADDR, CLK_APB_MAIN_SYS2_DIV_SHIFT, CLK_APB_MAIN_SYS2_DIV_MASK)
#define _DIVIDE_CLOCK_DFT_GPIO_50_(div) 			itg_set_reg(DFT_GPIO_50_CTRL_REG_ADDR, div, DFT_GPIO_50_DIV_SHIFT, DFT_GPIO_50_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_DFT_GPIO_50_ 		itg_get_reg(DFT_GPIO_50_CTRL_REG_ADDR, DFT_GPIO_50_DIV_SHIFT, DFT_GPIO_50_DIV_MASK)
#define _SWITCH_CLOCK_CLK_DEBUG_JTAG_SOURCE_SECJTAG_TCK_EXT_ 	itg_set_reg(CLK_DEBUG_JTAG_CTRL_REG_ADDR, CLK_DEBUG_JTAG_SW_SECJTAG_TCK_EXT_DATA, CLK_DEBUG_JTAG_SW_SHIFT, CLK_DEBUG_JTAG_SW_MASK)
#define _SWITCH_CLOCK_CLK_DEBUG_JTAG_SOURCE_DFT_GPIO_50_ 	itg_set_reg(CLK_DEBUG_JTAG_CTRL_REG_ADDR, CLK_DEBUG_JTAG_SW_DFT_GPIO_50_DATA, CLK_DEBUG_JTAG_SW_SHIFT, CLK_DEBUG_JTAG_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_DEBUG_JTAG_ 		itg_get_reg(CLK_DEBUG_JTAG_CTRL_REG_ADDR, CLK_DEBUG_JTAG_SW_SHIFT, CLK_DEBUG_JTAG_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_DEBUG_JTAG_(x) 		itg_set_reg(CLK_DEBUG_JTAG_CTRL_REG_ADDR, x, CLK_DEBUG_JTAG_SW_SHIFT, CLK_DEBUG_JTAG_SW_MASK)
#define _DIVIDE_CLOCK_CLK_JTAGM0_200_(div) 			itg_set_reg(CLK_JTAGM0_200_CTRL_REG_ADDR, div, CLK_JTAGM0_200_DIV_SHIFT, CLK_JTAGM0_200_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_JTAGM0_200_ 		itg_get_reg(CLK_JTAGM0_200_CTRL_REG_ADDR, CLK_JTAGM0_200_DIV_SHIFT, CLK_JTAGM0_200_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_JTAGM1_200_(div) 			itg_set_reg(CLK_JTAGM1_200_CTRL_REG_ADDR, div, CLK_JTAGM1_200_DIV_SHIFT, CLK_JTAGM1_200_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_JTAGM1_200_ 		itg_get_reg(CLK_JTAGM1_200_CTRL_REG_ADDR, CLK_JTAGM1_200_DIV_SHIFT, CLK_JTAGM1_200_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_JTAGM0_100_(div) 			itg_set_reg(CLK_JTAGM0_100_CTRL_REG_ADDR, div, CLK_JTAGM0_100_DIV_SHIFT, CLK_JTAGM0_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_JTAGM0_100_ 		itg_get_reg(CLK_JTAGM0_100_CTRL_REG_ADDR, CLK_JTAGM0_100_DIV_SHIFT, CLK_JTAGM0_100_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_JTAGM1_100_(div) 			itg_set_reg(CLK_JTAGM1_100_CTRL_REG_ADDR, div, CLK_JTAGM1_100_DIV_SHIFT, CLK_JTAGM1_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_JTAGM1_100_ 		itg_get_reg(CLK_JTAGM1_100_CTRL_REG_ADDR, CLK_JTAGM1_100_DIV_SHIFT, CLK_JTAGM1_100_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_JTAGM0_ATPG_TCLOCK_(div) 			itg_set_reg(CLK_JTAGM0_ATPG_TCLOCK_CTRL_REG_ADDR, div, CLK_JTAGM0_ATPG_TCLOCK_DIV_SHIFT, CLK_JTAGM0_ATPG_TCLOCK_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_JTAGM0_ATPG_TCLOCK_ 		itg_get_reg(CLK_JTAGM0_ATPG_TCLOCK_CTRL_REG_ADDR, CLK_JTAGM0_ATPG_TCLOCK_DIV_SHIFT, CLK_JTAGM0_ATPG_TCLOCK_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_JTAGM1_ATPG_TCLOCK_(div) 			itg_set_reg(CLK_JTAGM1_ATPG_TCLOCK_CTRL_REG_ADDR, div, CLK_JTAGM1_ATPG_TCLOCK_DIV_SHIFT, CLK_JTAGM1_ATPG_TCLOCK_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_JTAGM1_ATPG_TCLOCK_ 		itg_get_reg(CLK_JTAGM1_ATPG_TCLOCK_CTRL_REG_ADDR, CLK_JTAGM1_ATPG_TCLOCK_DIV_SHIFT, CLK_JTAGM1_ATPG_TCLOCK_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_JTAG_MST_WRAP_HCLK_ 			itg_set_reg(CLK_U0_JTAG_MST_WRAP_HCLK_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_HCLK_ENABLE_DATA, CLK_U0_JTAG_MST_WRAP_HCLK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_HCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_JTAG_MST_WRAP_HCLK_ 			itg_set_reg(CLK_U0_JTAG_MST_WRAP_HCLK_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_HCLK_DISABLE_DATA, CLK_U0_JTAG_MST_WRAP_HCLK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_HCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_JTAG_MST_WRAP_HCLK_ 		itg_get_reg(CLK_U0_JTAG_MST_WRAP_HCLK_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_HCLK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_HCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_JTAG_MST_WRAP_HCLK_(x) 		itg_set_reg(CLK_U0_JTAG_MST_WRAP_HCLK_CTRL_REG_ADDR, x, CLK_U0_JTAG_MST_WRAP_HCLK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_HCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_JTAG_MST_WRAP_CLK_JTAG_ 			itg_set_reg(CLK_U0_JTAG_MST_WRAP_CLK_JTAG_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_CLK_JTAG_ENABLE_DATA, CLK_U0_JTAG_MST_WRAP_CLK_JTAG_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_CLK_JTAG_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_JTAG_MST_WRAP_CLK_JTAG_ 			itg_set_reg(CLK_U0_JTAG_MST_WRAP_CLK_JTAG_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_CLK_JTAG_DISABLE_DATA, CLK_U0_JTAG_MST_WRAP_CLK_JTAG_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_CLK_JTAG_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_JTAG_MST_WRAP_CLK_JTAG_ 		itg_get_reg(CLK_U0_JTAG_MST_WRAP_CLK_JTAG_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_CLK_JTAG_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_CLK_JTAG_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_JTAG_MST_WRAP_CLK_JTAG_(x) 		itg_set_reg(CLK_U0_JTAG_MST_WRAP_CLK_JTAG_CTRL_REG_ADDR, x, CLK_U0_JTAG_MST_WRAP_CLK_JTAG_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_CLK_JTAG_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_JTAG_MST_WRAP_APB_PCLK_ 			itg_set_reg(CLK_U0_JTAG_MST_WRAP_APB_PCLK_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_APB_PCLK_ENABLE_DATA, CLK_U0_JTAG_MST_WRAP_APB_PCLK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_APB_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_JTAG_MST_WRAP_APB_PCLK_ 			itg_set_reg(CLK_U0_JTAG_MST_WRAP_APB_PCLK_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_APB_PCLK_DISABLE_DATA, CLK_U0_JTAG_MST_WRAP_APB_PCLK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_APB_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_JTAG_MST_WRAP_APB_PCLK_ 		itg_get_reg(CLK_U0_JTAG_MST_WRAP_APB_PCLK_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_APB_PCLK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_APB_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_JTAG_MST_WRAP_APB_PCLK_(x) 		itg_set_reg(CLK_U0_JTAG_MST_WRAP_APB_PCLK_CTRL_REG_ADDR, x, CLK_U0_JTAG_MST_WRAP_APB_PCLK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_APB_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_ 			itg_set_reg(CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_ENABLE_DATA, CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_ 			itg_set_reg(CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_DISABLE_DATA, CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_ 		itg_get_reg(CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_CTRL_REG_ADDR, CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_(x) 		itg_set_reg(CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_CTRL_REG_ADDR, x, CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_EN_SHIFT, CLK_U0_JTAG_MST_WRAP_ATPG_TCLOCK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_JTAG_MST_WRAP_HCLK_ 			itg_set_reg(CLK_U1_JTAG_MST_WRAP_HCLK_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_HCLK_ENABLE_DATA, CLK_U1_JTAG_MST_WRAP_HCLK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_HCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_JTAG_MST_WRAP_HCLK_ 			itg_set_reg(CLK_U1_JTAG_MST_WRAP_HCLK_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_HCLK_DISABLE_DATA, CLK_U1_JTAG_MST_WRAP_HCLK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_HCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_JTAG_MST_WRAP_HCLK_ 		itg_get_reg(CLK_U1_JTAG_MST_WRAP_HCLK_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_HCLK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_HCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_JTAG_MST_WRAP_HCLK_(x) 		itg_set_reg(CLK_U1_JTAG_MST_WRAP_HCLK_CTRL_REG_ADDR, x, CLK_U1_JTAG_MST_WRAP_HCLK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_HCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_JTAG_MST_WRAP_CLK_JTAG_ 			itg_set_reg(CLK_U1_JTAG_MST_WRAP_CLK_JTAG_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_CLK_JTAG_ENABLE_DATA, CLK_U1_JTAG_MST_WRAP_CLK_JTAG_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_CLK_JTAG_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_JTAG_MST_WRAP_CLK_JTAG_ 			itg_set_reg(CLK_U1_JTAG_MST_WRAP_CLK_JTAG_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_CLK_JTAG_DISABLE_DATA, CLK_U1_JTAG_MST_WRAP_CLK_JTAG_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_CLK_JTAG_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_JTAG_MST_WRAP_CLK_JTAG_ 		itg_get_reg(CLK_U1_JTAG_MST_WRAP_CLK_JTAG_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_CLK_JTAG_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_CLK_JTAG_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_JTAG_MST_WRAP_CLK_JTAG_(x) 		itg_set_reg(CLK_U1_JTAG_MST_WRAP_CLK_JTAG_CTRL_REG_ADDR, x, CLK_U1_JTAG_MST_WRAP_CLK_JTAG_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_CLK_JTAG_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_JTAG_MST_WRAP_APB_PCLK_ 			itg_set_reg(CLK_U1_JTAG_MST_WRAP_APB_PCLK_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_APB_PCLK_ENABLE_DATA, CLK_U1_JTAG_MST_WRAP_APB_PCLK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_APB_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_JTAG_MST_WRAP_APB_PCLK_ 			itg_set_reg(CLK_U1_JTAG_MST_WRAP_APB_PCLK_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_APB_PCLK_DISABLE_DATA, CLK_U1_JTAG_MST_WRAP_APB_PCLK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_APB_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_JTAG_MST_WRAP_APB_PCLK_ 		itg_get_reg(CLK_U1_JTAG_MST_WRAP_APB_PCLK_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_APB_PCLK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_APB_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_JTAG_MST_WRAP_APB_PCLK_(x) 		itg_set_reg(CLK_U1_JTAG_MST_WRAP_APB_PCLK_CTRL_REG_ADDR, x, CLK_U1_JTAG_MST_WRAP_APB_PCLK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_APB_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_ 			itg_set_reg(CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_ENABLE_DATA, CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_ 			itg_set_reg(CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_DISABLE_DATA, CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_ 		itg_get_reg(CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_CTRL_REG_ADDR, CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_(x) 		itg_set_reg(CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_CTRL_REG_ADDR, x, CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_EN_SHIFT, CLK_U1_JTAG_MST_WRAP_ATPG_TCLOCK_EN_MASK)
#define _DIVIDE_CLOCK_CLK_HOSTUSB_100_(div) 			itg_set_reg(CLK_HOSTUSB_100_CTRL_REG_ADDR, div, CLK_HOSTUSB_100_DIV_SHIFT, CLK_HOSTUSB_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_HOSTUSB_100_ 		itg_get_reg(CLK_HOSTUSB_100_CTRL_REG_ADDR, CLK_HOSTUSB_100_DIV_SHIFT, CLK_HOSTUSB_100_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_HOSTUSBCMN_500_(div) 			itg_set_reg(CLK_HOSTUSBCMN_500_CTRL_REG_ADDR, div, CLK_HOSTUSBCMN_500_DIV_SHIFT, CLK_HOSTUSBCMN_500_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_HOSTUSBCMN_500_ 		itg_get_reg(CLK_HOSTUSBCMN_500_CTRL_REG_ADDR, CLK_HOSTUSBCMN_500_DIV_SHIFT, CLK_HOSTUSBCMN_500_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPER1_200_(div) 			itg_set_reg(CLK_BMCPER1_200_CTRL_REG_ADDR, div, CLK_BMCPER1_200_DIV_SHIFT, CLK_BMCPER1_200_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPER1_200_ 		itg_get_reg(CLK_BMCPER1_200_CTRL_REG_ADDR, CLK_BMCPER1_200_DIV_SHIFT, CLK_BMCPER1_200_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPER1_250_(div) 			itg_set_reg(CLK_BMCPER1_250_CTRL_REG_ADDR, div, CLK_BMCPER1_250_DIV_SHIFT, CLK_BMCPER1_250_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPER1_250_ 		itg_get_reg(CLK_BMCPER1_250_CTRL_REG_ADDR, CLK_BMCPER1_250_DIV_SHIFT, CLK_BMCPER1_250_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPER1_143_DFT_(div) 			itg_set_reg(CLK_BMCPER1_143_DFT_CTRL_REG_ADDR, div, CLK_BMCPER1_143_DFT_DIV_SHIFT, CLK_BMCPER1_143_DFT_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPER1_143_DFT_ 		itg_get_reg(CLK_BMCPER1_143_DFT_CTRL_REG_ADDR, CLK_BMCPER1_143_DFT_DIV_SHIFT, CLK_BMCPER1_143_DFT_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_ 			itg_set_reg(CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_CTRL_REG_ADDR, CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_ENABLE_DATA, CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_EN_SHIFT, CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_ 			itg_set_reg(CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_CTRL_REG_ADDR, CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_DISABLE_DATA, CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_EN_SHIFT, CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_ 		itg_get_reg(CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_CTRL_REG_ADDR, CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_EN_SHIFT, CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_(x) 		itg_set_reg(CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_CTRL_REG_ADDR, x, CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_EN_SHIFT, CLK_U0_DOM_BMCPERIPH1_CLK_DOM_BMCPERIPH1_CLK_BMCPERIPH1_143_EN_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPER0_200_(div) 			itg_set_reg(CLK_BMCPER0_200_CTRL_REG_ADDR, div, CLK_BMCPER0_200_DIV_SHIFT, CLK_BMCPER0_200_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPER0_200_ 		itg_get_reg(CLK_BMCPER0_200_CTRL_REG_ADDR, CLK_BMCPER0_200_DIV_SHIFT, CLK_BMCPER0_200_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_GPU0_100_(div) 			itg_set_reg(CLK_GPU0_100_CTRL_REG_ADDR, div, CLK_GPU0_100_DIV_SHIFT, CLK_GPU0_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_GPU0_100_ 		itg_get_reg(CLK_GPU0_100_CTRL_REG_ADDR, CLK_GPU0_100_DIV_SHIFT, CLK_GPU0_100_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_ 			itg_set_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_CTRL_REG_ADDR, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_ENABLE_DATA, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_ 			itg_set_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_CTRL_REG_ADDR, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_DISABLE_DATA, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_ 		itg_get_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_CTRL_REG_ADDR, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_(x) 		itg_set_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_CTRL_REG_ADDR, x, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_ 			itg_set_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_CTRL_REG_ADDR, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_ENABLE_DATA, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_ 			itg_set_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_CTRL_REG_ADDR, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_DISABLE_DATA, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_ 		itg_get_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_CTRL_REG_ADDR, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_(x) 		itg_set_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_CTRL_REG_ADDR, x, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_ 			itg_set_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_CTRL_REG_ADDR, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_ENABLE_DATA, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_ 			itg_set_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_CTRL_REG_ADDR, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_DISABLE_DATA, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_ 		itg_get_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_CTRL_REG_ADDR, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_(x) 		itg_set_reg(CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_CTRL_REG_ADDR, x, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_SHIFT, CLK_U0_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_MASK)
#define _DIVIDE_CLOCK_CLK_GPU1_100_(div) 			itg_set_reg(CLK_GPU1_100_CTRL_REG_ADDR, div, CLK_GPU1_100_DIV_SHIFT, CLK_GPU1_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_GPU1_100_ 		itg_get_reg(CLK_GPU1_100_CTRL_REG_ADDR, CLK_GPU1_100_DIV_SHIFT, CLK_GPU1_100_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_ 			itg_set_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_CTRL_REG_ADDR, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_ENABLE_DATA, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_ 			itg_set_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_CTRL_REG_ADDR, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_DISABLE_DATA, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_ 		itg_get_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_CTRL_REG_ADDR, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_(x) 		itg_set_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_CTRL_REG_ADDR, x, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_BUS_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_ 			itg_set_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_CTRL_REG_ADDR, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_ENABLE_DATA, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_ 			itg_set_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_CTRL_REG_ADDR, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_DISABLE_DATA, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_ 		itg_get_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_CTRL_REG_ADDR, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_(x) 		itg_set_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_CTRL_REG_ADDR, x, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_APB_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_ 			itg_set_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_CTRL_REG_ADDR, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_ENABLE_DATA, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_ 			itg_set_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_CTRL_REG_ADDR, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_DISABLE_DATA, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_ 		itg_get_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_CTRL_REG_ADDR, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_(x) 		itg_set_reg(CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_CTRL_REG_ADDR, x, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_SHIFT, CLK_U1_DOM_GPU_CLK_DOM_GPU_GPU_OSC_CLK_EN_MASK)

#define _ENABLE_CLOCK_MAIN_ICG_EN_JTAG0_ 			itg_set_reg(MAIN_ICG_EN_JTAG0_CTRL_REG_ADDR, MAIN_ICG_EN_JTAG0_ENABLE_DATA, MAIN_ICG_EN_JTAG0_EN_SHIFT, MAIN_ICG_EN_JTAG0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_JTAG0_ 			itg_set_reg(MAIN_ICG_EN_JTAG0_CTRL_REG_ADDR, MAIN_ICG_EN_JTAG0_DISABLE_DATA, MAIN_ICG_EN_JTAG0_EN_SHIFT, MAIN_ICG_EN_JTAG0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_JTAG0_ 		itg_get_reg(MAIN_ICG_EN_JTAG0_CTRL_REG_ADDR, MAIN_ICG_EN_JTAG0_EN_SHIFT, MAIN_ICG_EN_JTAG0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_JTAG0_(x) 		itg_set_reg(MAIN_ICG_EN_JTAG0_CTRL_REG_ADDR, x, MAIN_ICG_EN_JTAG0_EN_SHIFT, MAIN_ICG_EN_JTAG0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_JTAG1_ 			itg_set_reg(MAIN_ICG_EN_JTAG1_CTRL_REG_ADDR, MAIN_ICG_EN_JTAG1_ENABLE_DATA, MAIN_ICG_EN_JTAG1_EN_SHIFT, MAIN_ICG_EN_JTAG1_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_JTAG1_ 			itg_set_reg(MAIN_ICG_EN_JTAG1_CTRL_REG_ADDR, MAIN_ICG_EN_JTAG1_DISABLE_DATA, MAIN_ICG_EN_JTAG1_EN_SHIFT, MAIN_ICG_EN_JTAG1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_JTAG1_ 		itg_get_reg(MAIN_ICG_EN_JTAG1_CTRL_REG_ADDR, MAIN_ICG_EN_JTAG1_EN_SHIFT, MAIN_ICG_EN_JTAG1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_JTAG1_(x) 		itg_set_reg(MAIN_ICG_EN_JTAG1_CTRL_REG_ADDR, x, MAIN_ICG_EN_JTAG1_EN_SHIFT, MAIN_ICG_EN_JTAG1_EN_MASK)


#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_SYS2_SYSCON_PRESETN_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS2_SYSCON_PRESETN_SHIFT, RSTN_U0_SYS2_SYSCON_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_SYS2_SYSCON_PRESETN_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS2_SYSCON_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_SYS2_SYSCON_PRESETN_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS2_SYSCON_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SHIFT, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_JTAG_MST_WRAP_HRESETN_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_JTAG_MST_WRAP_HRESETN_SHIFT, RSTN_U0_JTAG_MST_WRAP_HRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_JTAG_MST_WRAP_HRESETN_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_JTAG_MST_WRAP_HRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_JTAG_MST_WRAP_HRESETN_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_JTAG_MST_WRAP_HRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_JTAG_MST_WRAP_APB_PRESETN_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_JTAG_MST_WRAP_APB_PRESETN_SHIFT, RSTN_U0_JTAG_MST_WRAP_APB_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_JTAG_MST_WRAP_APB_PRESETN_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_JTAG_MST_WRAP_APB_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_JTAG_MST_WRAP_APB_PRESETN_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_JTAG_MST_WRAP_APB_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_JTAG_MST_WRAP_HRESETN_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_JTAG_MST_WRAP_HRESETN_SHIFT, RSTN_U1_JTAG_MST_WRAP_HRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_JTAG_MST_WRAP_HRESETN_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_JTAG_MST_WRAP_HRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_JTAG_MST_WRAP_HRESETN_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_JTAG_MST_WRAP_HRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_JTAG_MST_WRAP_APB_PRESETN_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_JTAG_MST_WRAP_APB_PRESETN_SHIFT, RSTN_U1_JTAG_MST_WRAP_APB_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_JTAG_MST_WRAP_APB_PRESETN_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_JTAG_MST_WRAP_APB_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_JTAG_MST_WRAP_APB_PRESETN_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_JTAG_MST_WRAP_APB_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DEBUG_SUBSYS_RELEASE_RSTN_JTAG_CERTIFICATION_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DEBUG_SUBSYS_RELEASE_RSTN_JTAG_CERTIFICATION_SHIFT, RSTN_U0_DEBUG_SUBSYS_RELEASE_RSTN_JTAG_CERTIFICATION_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DEBUG_SUBSYS_RELEASE_RSTN_JTAG_CERTIFICATION_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DEBUG_SUBSYS_RELEASE_RSTN_JTAG_CERTIFICATION_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DEBUG_SUBSYS_RELEASE_RSTN_JTAG_CERTIFICATION_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DEBUG_SUBSYS_RELEASE_RSTN_JTAG_CERTIFICATION_MASK)
#define _READ_RESET_STATUS_RSTGEN_RST_U0_DEBUG_SUBSYS_RELEASE_POR_RESET_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_DEBUG_SUBSYS_RELEASE_POR_RESET_SHIFT, RST_U0_DEBUG_SUBSYS_RELEASE_POR_RESET_MASK)
#define _ASSERT_RESET_RSTGEN_RST_U0_DEBUG_SUBSYS_RELEASE_POR_RESET_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_DEBUG_SUBSYS_RELEASE_POR_RESET_MASK)
#define _CLEAR_RESET_RSTGEN_RST_U0_DEBUG_SUBSYS_RELEASE_POR_RESET_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_DEBUG_SUBSYS_RELEASE_POR_RESET_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTCMN_RSTN_BUS_NCNOC_INIT_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTCMN_RSTN_BUS_NCNOC_INIT_SHIFT, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTCMN_RSTN_BUS_NCNOC_INIT_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTCMN_RSTN_BUS_NCNOC_INIT_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTCMN_RSTN_BUS_NCNOC_INIT_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTCMN_RSTN_BUS_NCNOC_INIT_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTCMN_RSTN_BUS_NCNOC_INIT_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTCMN_CRG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTCMN_CRG_SHIFT, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTCMN_CRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTCMN_CRG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTCMN_CRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTCMN_CRG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTCMN_CRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_BMC_TARG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_BMC_TARG_SHIFT, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_BMC_TARG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_BMC_TARG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_BMC_TARG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_BMC_TARG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_BMC_TARG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_HOST_TARG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_HOST_TARG_SHIFT, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_HOST_TARG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_HOST_TARG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_HOST_TARG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_HOST_TARG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB0_RSTN_BUS_NCNOC_HOST_TARG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_BMC_CRG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_BMC_CRG_SHIFT, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_BMC_CRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_BMC_CRG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_BMC_CRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_BMC_CRG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_BMC_CRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB0_CRG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB0_CRG_SHIFT, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB0_CRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB0_CRG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB0_CRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB0_CRG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB0_CRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_BMC_TARG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_BMC_TARG_SHIFT, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_BMC_TARG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_BMC_TARG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_BMC_TARG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_BMC_TARG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_BMC_TARG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_HOST_TARG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_HOST_TARG_SHIFT, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_HOST_TARG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_HOST_TARG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_HOST_TARG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_HOST_TARG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_HOSTUSB1_RSTN_BUS_NCNOC_HOST_TARG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB1_CRG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB1_CRG_SHIFT, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB1_CRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB1_CRG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB1_CRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB1_CRG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_HOSTUSBCMN_RSTN_DOM_HOSTUSBCMN_RSTN_HOSTUSB1_CRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_CRG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_CRG_SHIFT, RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_CRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_CRG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_CRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_CRG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_CRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_BUS_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_BUS_SHIFT, RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_BUS_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_BUS_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_BUS_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_BUS_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH1_RSTN_DOM_BMCPERIPH1_RSTN_BUS_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_CRG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_CRG_SHIFT, RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_CRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_CRG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_CRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_CRG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_CRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_BUS_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_BUS_SHIFT, RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_BUS_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_BUS_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_BUS_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_BUS_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_BMCPERIPH0_RSTN_DOM_BMCPERIPH0_DOM_BMCPERIPH0_RSTN_BUS_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_SHIFT, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_SHIFT, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_SHIFT, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_SHIFT, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_CRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_SHIFT, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_RSTN_BUS_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_ 	itg_get_reg(SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_SHIFT, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_ 	itg_assert_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_ 	itg_clear_rst(SYS2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_DOM_GPU_RSTN_DOM_GPU_HOST_PCIE_RST_N_MASK)


#endif //_SYS2_CRG_MACRO_H_
