//RTL tag v0.5.1

#define SYS2_SYSCONITG__SYSCFG_0_ADDR                      (U0_SYS2_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define U0_BOOT_CTRL_BOOT_DEV_SEL_REG_WIDTH                0x3U
#define U0_BOOT_CTRL_BOOT_DEV_SEL_REG_SHIFT                0x0U
#define U0_BOOT_CTRL_BOOT_DEV_SEL_REG_MASK                 0x7U
#define U0_BOOT_CTRL_SEC_BOOT_EN_REG_WIDTH                 0x1U
#define U0_BOOT_CTRL_SEC_BOOT_EN_REG_SHIFT                 0x4U
#define U0_BOOT_CTRL_SEC_BOOT_EN_REG_MASK                  0x10U
#define U0_BOOT_CTRL_BOOT_CLK_SEL_REG_WIDTH                0x1U
#define U0_BOOT_CTRL_BOOT_CLK_SEL_REG_SHIFT                0x5U
#define U0_BOOT_CTRL_BOOT_CLK_SEL_REG_MASK                 0x20U
#define GET_U0_BOOT_CTRL_BOOT_DEV_SEL_REG                  itg_get_reg(SYS2_SYSCONITG__SYSCFG_0_ADDR,U0_BOOT_CTRL_BOOT_DEV_SEL_REG_SHIFT,U0_BOOT_CTRL_BOOT_DEV_SEL_REG_MASK)
#define GET_U0_BOOT_CTRL_SEC_BOOT_EN_REG                   itg_get_reg(SYS2_SYSCONITG__SYSCFG_0_ADDR,U0_BOOT_CTRL_SEC_BOOT_EN_REG_SHIFT,U0_BOOT_CTRL_SEC_BOOT_EN_REG_MASK)
#define GET_U0_BOOT_CTRL_BOOT_CLK_SEL_REG                  itg_get_reg(SYS2_SYSCONITG__SYSCFG_0_ADDR,U0_BOOT_CTRL_BOOT_CLK_SEL_REG_SHIFT,U0_BOOT_CTRL_BOOT_CLK_SEL_REG_MASK)
