
#ifndef _SYS2_SECURE_CRG_MACRO_H_
#define _SYS2_SECURE_CRG_MACRO_H_

//#define SYS2_SECURE_CRG_BASE_ADDR 0x0
#define CLK_APB_MAIN_SYS2_SEC_CTRL_REG_ADDR                          (U0_SYS2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_SEC_200_CTRL_REG_ADDR                                    (U0_SYS2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)


#define SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR       (U0_SYS2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)

#define SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR       (U0_SYS2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)


#define CLK_APB_MAIN_SYS2_SEC_DIV_SHIFT                              0
#define CLK_APB_MAIN_SYS2_SEC_DIV_MASK                               0xFU
#define CLK_SEC_200_DIV_SHIFT                                        0
#define CLK_SEC_200_DIV_MASK                                         0x7U




#define RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_SHIFT                     0
#define RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_MASK                      (0x1 << 0)
#define RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_ASSERT                    1
#define RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_CLEAR                     0
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_SHIFT                  1
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_MASK                   (0x1 << 1)
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_ASSERT                 1
#define RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_CLEAR                  0
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_BUS_SHIFT                  2
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_BUS_MASK                   (0x1 << 2)
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_BUS_ASSERT                 1
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_BUS_CLEAR                  0
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CRG_SHIFT                  3
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CRG_MASK                   (0x1 << 3)
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CRG_ASSERT                 1
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CRG_CLEAR                  0
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CORE_SHIFT                 4
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CORE_MASK                  (0x1 << 4)
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CORE_ASSERT                1
#define RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CORE_CLEAR                 0

#define _DIVIDE_CLOCK_CLK_APB_MAIN_SYS2_SEC_(div) 			itg_set_reg(CLK_APB_MAIN_SYS2_SEC_CTRL_REG_ADDR, div, CLK_APB_MAIN_SYS2_SEC_DIV_SHIFT, CLK_APB_MAIN_SYS2_SEC_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_MAIN_SYS2_SEC_ 		itg_get_reg(CLK_APB_MAIN_SYS2_SEC_CTRL_REG_ADDR, CLK_APB_MAIN_SYS2_SEC_DIV_SHIFT, CLK_APB_MAIN_SYS2_SEC_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_SEC_200_(div) 			itg_set_reg(CLK_SEC_200_CTRL_REG_ADDR, div, CLK_SEC_200_DIV_SHIFT, CLK_SEC_200_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_SEC_200_ 		itg_get_reg(CLK_SEC_200_CTRL_REG_ADDR, CLK_SEC_200_DIV_SHIFT, CLK_SEC_200_DIV_MASK)



#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_ 	itg_get_reg(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_SHIFT, RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_ 	itg_assert_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_ 	itg_clear_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SYS2_SECURE_SYSCON_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_ 	itg_get_reg(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_SHIFT, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_ 	itg_assert_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_ 	itg_clear_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_NCNOC_SYSTOP_RSTN_CSR2_SECURE_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_BUS_ 	itg_get_reg(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_BUS_SHIFT, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_BUS_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_BUS_ 	itg_assert_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_BUS_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_BUS_ 	itg_clear_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_BUS_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CRG_ 	itg_get_reg(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CRG_SHIFT, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CRG_ 	itg_assert_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CRG_ 	itg_clear_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CORE_ 	itg_get_reg(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CORE_SHIFT, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CORE_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CORE_ 	itg_assert_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CORE_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CORE_ 	itg_clear_rst(SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, SYS2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DOM_SEC_RSTN_DOM_SEC_RSTN_CORE_MASK)


#endif //_SYS2_SECURE_CRG_MACRO_H_
