# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2021 Shanghai StarFive Technology Co., Ltd.
# Micheal Zhu <michael.zhu@starfivetech.com>

obj-y	+= jh7100.o
obj-y	+= jh_ptc.o

obj-$(CONFIG_ID_EEPROM) += jh7100-i2c-eeprom.o
