/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (C) 2024 Ventana Micro Systems Ltd.
 */

#ifndef _ASM_RISCV_RPMI_H
#define _ASM_RISCV_RPMI_H

#define RPMI_MAJOR_VER				(0x0001)
#define RPMI_MINOR_VER				(0x0000)
#define RPMI_MSGPROTO_VERSION(major, minor)	(((major) << 16) | (minor))

/**
 * RPMI Error Codes
 */
enum rpmi_error_codes {
	RPMI_SUCCESS = 0,
	RPMI_ERROR_FAILED = -1,
	RPMI_ERROR_NOT_SUPPORTED = -2,
	RPMI_ERROR_INVALID_PARAM = -3,
	RPMI_ERROR_DENIED = -4,
	RPMI_ERROR_NOT_FOUND = -5,
	RPMI_ERROR_OUT_OF_RANGE = -6,
	RPMI_ERROR_OUT_OF_RESOURCE = -7,
	RPMI_ERROR_HW_FAULT = -8,
	RPMI_ERROR_BUSY = -9,
	RPMI_ERROR_TIMEOUT = -10,
	RPMI_ERROR_COMMS = -11,
	RPMI_ERROR_ALREADY = -12,
	RPMI_ERROR_EXTENSION = -13,
};

#define RPMI_SRVGRP_VOLTAGE		0x6
#define RPMI_SRVGRP_CLOCK		0x7
#define RPMI_SRVGRP_DEVICE_POWER	0x8
#define RPMI_SRVGRP_PERFORMANCE		0x9
#define RPMI_SRVGRP_VENDOR_SECURE	0x8000

/* RPMI Voltage Service IDs */
enum rpmi_voltage_service_id {
	RPMI_VOLTAGE_SRV_ENABLE_NOTIFICATION = 0x01,
	RPMI_VOLTAGE_SRV_GET_NUM_DOMAINS = 0x02,
	RPMI_VOLTAGE_SRV_GET_ATTRIBUTES = 0x03,
	RPMI_VOLTAGE_SRV_GET_SUPPORTED_LEVELS = 0x04,
	RPMI_VOLTAGE_SRV_SET_DOMAIN_CONFIG = 0x05,
	RPMI_VOLTAGE_SRV_GET_DOMAIN_CONFIG = 0x06,
	RPMI_VOLTAGE_SRV_SET_LEVEL = 0x07,
	RPMI_VOLTAGE_SRV_GET_LEVEL = 0x08,
	RPMI_VOLTAGE_SRV_ID_MAX_COUNT,
};

/* RPMI Clock Service IDs */
enum rpmi_clock_service_id {
	RPMI_CLK_SRV_ENABLE_NOTIFICATION = 0x01,
	RPMI_CLK_SRV_GET_SYSTEM_CLOCKS = 0x02,
	RPMI_CLK_SRV_GET_ATTRIBUTES = 0x03,
	RPMI_CLK_SRV_GET_SUPPORTED_RATES = 0x04,
	RPMI_CLK_SRV_SET_CONFIG = 0x05,
	RPMI_CLK_SRV_GET_CONFIG = 0x06,
	RPMI_CLK_SRV_SET_RATE = 0x07,
	RPMI_CLK_SRV_GET_RATE = 0x08,
	RPMI_CLK_SRV_ID_MAX_COUNT,
};

/* RPMI Device Power Service IDs */
enum rpmi_device_power_service_id {
	RPMI_DP_SRV_ENABLE_NOTIFICATION = 0x01,	/* PuC event notification */
	RPMI_DP_SRV_GET_NUM_DOMAINS  = 0x02,	/* get number of power domains */
	RPMI_DP_SRV_GET_ATTRS = 0x03,		/* get power domain attributes */
	RPMI_DP_SRV_SET_STATE = 0x04,		/* set power domain state */
	RPMI_DP_SRV_GET_STATE = 0x05,		/* get power domain state */
	RPMI_DP_SRV_ID_MAX_COUNT,
};

/* RPMI Perf Service IDs */
enum rpmi_perf_service_id {
	RPMI_PERF_SRV_ENABLE_NOTIFICATION = 0x01,
	RPMI_PERF_SRV_GET_NUM_DOMAINS = 0x02,
	RPMI_PERF_SRV_GET_DOMAIN_ATTRIBUTES = 0x03,
	RPMI_PERF_SRV_GET_DOMAIN_LEVELS = 0x04,
	RPMI_PERF_SRV_GET_PERF_LEVEL = 0x05,
	RPMI_PERF_SRV_SET_PERF_LEVEL = 0x06,
	RPMI_PERF_SRV_GET_PERF_LIMIT = 0x07,
	RPMI_PERF_SRV_SET_PERF_LIMIT = 0x08,
	RPMI_PERF_SRV_GET_FAST_CHANNEL_ADDR = 0x09,
	RPMI_PERF_SRV_GET_PERF_HART_LIST = 0x0a,
	RPMI_PERF_SRV_ID_MAX_COUNT,
};

#endif /* _ASM_RISCV_RPMI_H */
