# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2026 StarFive Technology Co., Ltd.
#

obj-$(CONFIG_VIDEO_STARFIVE_JHB100_DC8000) += jhb100_dc8000.o jhb100_dc8000_tables.o
obj-$(CONFIG_DISPLAY_STARFIVE_JHB100_DW_DP) += jhb100_dw_dp.o
