#define BMCPERIPH2_SYSCONITG__SYSCFG_0_ADDR                (U0_BMCPERIPH2_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0__WIDTH     0x20U
#define U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0__SHIFT     0x0U
#define U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0__MASK      0xFFFFFFFFU
#define BMCPERIPH2_SYSCONITG__SYSCFG_4_ADDR                (U0_BMCPERIPH2_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32__WIDTH    0x20U
#define U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32__SHIFT    0x0U
#define U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32__MASK     0xFFFFFFFFU
#define BMCPERIPH2_SYSCONITG__SYSCFG_8_ADDR                (U0_BMCPERIPH2_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_31_0__WIDTH 0x20U
#define U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_31_0__SHIFT 0x0U
#define U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_31_0__MASK 0xFFFFFFFFU
#define BMCPERIPH2_SYSCONITG__SYSCFG_12_ADDR               (U0_BMCPERIPH2_SYSCON__ITG_BD_APBS__BASE_ADDR + 0xcU)
#define U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_63_32__WIDTH 0x20U
#define U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_63_32__SHIFT 0x0U
#define U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_63_32__MASK 0xFFFFFFFFU
#define BMCPERIPH2_SYSCONITG__SYSCFG_16_ADDR               (U0_BMCPERIPH2_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define U1_CAN_CTRL_HOST_IF_WIDTH                          0x13U
#define U1_CAN_CTRL_HOST_IF_SHIFT                          0x0U
#define U1_CAN_CTRL_HOST_IF_MASK                           0x7FFFFU
#define BMCPERIPH2_SYSCONITG__SYSCFG_20_ADDR               (U0_BMCPERIPH2_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define U0_CAN_CTRL_HOST_IF_WIDTH                          0x13U
#define U0_CAN_CTRL_HOST_IF_SHIFT                          0x0U
#define U0_CAN_CTRL_HOST_IF_MASK                           0x7FFFFU
#define U1_DWC_ETHER_SGMII_PHY_INTF_SEL_I_WIDTH            0x4U
#define U1_DWC_ETHER_SGMII_PHY_INTF_SEL_I_SHIFT            0x14U
#define U1_DWC_ETHER_SGMII_PHY_INTF_SEL_I_MASK             0xF00000U
#define U0_DWC_ETHER_RMIIANDRGMII_PHY_INTF_SEL_I_WIDTH     0x4U
#define U0_DWC_ETHER_RMIIANDRGMII_PHY_INTF_SEL_I_SHIFT     0x18U
#define U0_DWC_ETHER_RMIIANDRGMII_PHY_INTF_SEL_I_MASK      0xF000000U
#define U1_DWC_ETHER_SGMII_MAC_SPEED_O_WIDTH               0x2U
#define U1_DWC_ETHER_SGMII_MAC_SPEED_O_SHIFT               0x1CU
#define U1_DWC_ETHER_SGMII_MAC_SPEED_O_MASK                0x30000000U
#define BMCPERIPH2_SYSCONITG__SYSCFG_24_ADDR               (U0_BMCPERIPH2_SYSCON__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define U0_DWC_ETHER_RMIIANDRGMII_MAC_SPEED_O_WIDTH        0x2U
#define U0_DWC_ETHER_RMIIANDRGMII_MAC_SPEED_O_SHIFT        0x0U
#define U0_DWC_ETHER_RMIIANDRGMII_MAC_SPEED_O_MASK         0x3U
#define U1_CAN_CTRL_CAN_FD_ENABLE_WIDTH                    0x1U
#define U1_CAN_CTRL_CAN_FD_ENABLE_SHIFT                    0x4U
#define U1_CAN_CTRL_CAN_FD_ENABLE_MASK                     0x10U
#define U0_CAN_CTRL_CAN_FD_ENABLE_WIDTH                    0x1U
#define U0_CAN_CTRL_CAN_FD_ENABLE_SHIFT                    0x5U
#define U0_CAN_CTRL_CAN_FD_ENABLE_MASK                     0x20U
#define GET_U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0_       itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_0_ADDR,U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0__SHIFT,U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_31_0__MASK)
#define GET_U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32_      itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_4_ADDR,U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32__SHIFT,U1_DWC_ETHER_SGMII_PTP_TIMESTAMP_O_63_32__MASK)
#define GET_U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_31_0_ itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_8_ADDR,U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_31_0__SHIFT,U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_31_0__MASK)
#define GET_U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_63_32_ itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_12_ADDR,U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_63_32__SHIFT,U0_DWC_ETHER_RMIIANDRGMII_PTP_TIMESTAMP_O_63_32__MASK)
#define GET_U1_CAN_CTRL_HOST_IF                            itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_16_ADDR,U1_CAN_CTRL_HOST_IF_SHIFT,U1_CAN_CTRL_HOST_IF_MASK)
#define GET_U0_CAN_CTRL_HOST_IF                            itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_20_ADDR,U0_CAN_CTRL_HOST_IF_SHIFT,U0_CAN_CTRL_HOST_IF_MASK)
#define GET_U1_DWC_ETHER_SGMII_PHY_INTF_SEL_I              itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_20_ADDR,U1_DWC_ETHER_SGMII_PHY_INTF_SEL_I_SHIFT,U1_DWC_ETHER_SGMII_PHY_INTF_SEL_I_MASK)
#define SET_U1_DWC_ETHER_SGMII_PHY_INTF_SEL_I(data)        itg_set_reg(BMCPERIPH2_SYSCONITG__SYSCFG_20_ADDR,data,U1_DWC_ETHER_SGMII_PHY_INTF_SEL_I_SHIFT,U1_DWC_ETHER_SGMII_PHY_INTF_SEL_I_MASK)
#define GET_U0_DWC_ETHER_RMIIANDRGMII_PHY_INTF_SEL_I       itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_20_ADDR,U0_DWC_ETHER_RMIIANDRGMII_PHY_INTF_SEL_I_SHIFT,U0_DWC_ETHER_RMIIANDRGMII_PHY_INTF_SEL_I_MASK)
#define SET_U0_DWC_ETHER_RMIIANDRGMII_PHY_INTF_SEL_I(data) itg_set_reg(BMCPERIPH2_SYSCONITG__SYSCFG_20_ADDR,data,U0_DWC_ETHER_RMIIANDRGMII_PHY_INTF_SEL_I_SHIFT,U0_DWC_ETHER_RMIIANDRGMII_PHY_INTF_SEL_I_MASK)
#define GET_U1_DWC_ETHER_SGMII_MAC_SPEED_O                 itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_20_ADDR,U1_DWC_ETHER_SGMII_MAC_SPEED_O_SHIFT,U1_DWC_ETHER_SGMII_MAC_SPEED_O_MASK)
#define GET_U0_DWC_ETHER_RMIIANDRGMII_MAC_SPEED_O          itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_24_ADDR,U0_DWC_ETHER_RMIIANDRGMII_MAC_SPEED_O_SHIFT,U0_DWC_ETHER_RMIIANDRGMII_MAC_SPEED_O_MASK)
#define GET_U1_CAN_CTRL_CAN_FD_ENABLE                      itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_24_ADDR,U1_CAN_CTRL_CAN_FD_ENABLE_SHIFT,U1_CAN_CTRL_CAN_FD_ENABLE_MASK)
#define SET_U1_CAN_CTRL_CAN_FD_ENABLE(data)                itg_set_reg(BMCPERIPH2_SYSCONITG__SYSCFG_24_ADDR,data,U1_CAN_CTRL_CAN_FD_ENABLE_SHIFT,U1_CAN_CTRL_CAN_FD_ENABLE_MASK)
#define GET_U0_CAN_CTRL_CAN_FD_ENABLE                      itg_get_reg(BMCPERIPH2_SYSCONITG__SYSCFG_24_ADDR,U0_CAN_CTRL_CAN_FD_ENABLE_SHIFT,U0_CAN_CTRL_CAN_FD_ENABLE_MASK)
#define SET_U0_CAN_CTRL_CAN_FD_ENABLE(data)                itg_set_reg(BMCPERIPH2_SYSCONITG__SYSCFG_24_ADDR,data,U0_CAN_CTRL_CAN_FD_ENABLE_SHIFT,U0_CAN_CTRL_CAN_FD_ENABLE_MASK)
