//commit:8ece02821 (HEAD -> b0.8.1_dv, origin/b0.8.1_dv)

#ifndef _BMCPERIPH2_CRG_MACRO_H_
#define _BMCPERIPH2_CRG_MACRO_H_

//#define BMCPERIPH2_CRG_BASE_ADDR 0x0
#define CLK_BMCPERIPH2_300_CTRL_REG_ADDR                             (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_BMCPERIPH2_100_CTRL_REG_ADDR                             (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)
#define CLK_BMCPERIPH2_50_CTRL_REG_ADDR                              (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)
#define CLK_BMCPERIPH2_GMAC2_RMII_50_CTRL_REG_ADDR                   (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)
#define CLK_BMCPERIPH2_CAN0_CORE_DIV_CTRL_REG_ADDR                   (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x10U)
#define CLK_BMCPERIPH2_CAN1_CORE_DIV_CTRL_REG_ADDR                   (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x14U)
#define CLK_BMCPERIPH2_CAN0_TIMER_CTRL_REG_ADDR                      (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x18U)
#define CLK_BMCPERIPH2_CAN1_TIMER_CTRL_REG_ADDR                      (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x1CU)
#define CLK_BMCPERIPH2_RTC_CORE_DIV_CTRL_REG_ADDR                    (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x2CU)
#define CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_CTRL_REG_ADDR              (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x30U)
#define CLK_BMCPERIPH2_GMAC2_RMII_DIV_CTRL_REG_ADDR                  (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x34U)
#define CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_CTRL_REG_ADDR            (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x38U)
#define CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_CTRL_REG_ADDR             (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x3CU)
#define CLK_BMCPERIPH2_GMAC2_RGMII_DIV_CTRL_REG_ADDR                 (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x40U)
#define CLK_BMCPERIPH2_GMAC2_TX_MUX_CTRL_REG_ADDR                    (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x44U)
#define CLK_BMCPERIPH2_GMAC2_TX_180_BUF_CTRL_REG_ADDR                (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x48U)
#define CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_CTRL_REG_ADDR                (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x4CU)
#define CLK_BMCPERIPH2_GMAC2_RX_180_BUF_CTRL_REG_ADDR                (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x50U)
#define CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_CTRL_REG_ADDR              (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x54U)
#define CLK_BMCPERIPH2_GMAC3_TX_125_MUX_CTRL_REG_ADDR                (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x58U)
#define CLK_BMCPERIPH2_GMAC3_RX_125_MUX_CTRL_REG_ADDR                (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x5CU)
#define CLK_BMCPERIPH2_GMAC3_TX_DIV_CTRL_REG_ADDR                    (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x60U)
#define CLK_BMCPERIPH2_GMAC3_RX_DIV_CTRL_REG_ADDR                    (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x64U)
#define CLK_U10_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR                 (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x68U)
#define CLK_U0_CAN_CTRL_PCLK_CTRL_REG_ADDR                           (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x6CU)
#define CLK_U0_CAN_CTRL_CAN_CLK_CTRL_REG_ADDR                        (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x70U)
#define CLK_U0_CAN_CTRL_TIMER_CLK_CTRL_REG_ADDR                      (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x74U)
#define CLK_U1_CAN_CTRL_PCLK_CTRL_REG_ADDR                           (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x78U)
#define CLK_U1_CAN_CTRL_CAN_CLK_CTRL_REG_ADDR                        (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x7CU)
#define CLK_U1_CAN_CTRL_TIMER_CLK_CTRL_REG_ADDR                      (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x80U)
#define CLK_U0_FAN_TACH_PCLK_CTRL_REG_ADDR                           (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x84U)
#define CLK_U0_DW_AXI_DMAC_8CH_PCLK_CTRL_REG_ADDR                    (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x94U)
#define CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR         (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x98U)
#define CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_CTRL_REG_ADDR                  (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x9CU)
#define CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_CTRL_REG_ADDR                 (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xA0U)
#define CLK_U0_RTC_HMS_SCAN_CLK_I_CTRL_REG_ADDR                      (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xA4U)
#define CLK_U0_ADC_PCLK_CTRL_REG_ADDR                                (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xA8U)
#define CLK_U1_ADC_PCLK_CTRL_REG_ADDR                                (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xACU)
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_CTRL_REG_ADDR         (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xB0U)
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_CTRL_REG_ADDR         (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xB4U)
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_CTRL_REG_ADDR     (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xB8U)
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_CTRL_REG_ADDR     (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xBCU)
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_CTRL_REG_ADDR    (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xC0U)
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_CTRL_REG_ADDR       (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xC4U)
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_CTRL_REG_ADDR        (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xC8U)
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_CTRL_REG_ADDR           (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xCCU)
#define CLK_GMAC2_TXCK_CTRL_REG_ADDR                                 (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xD0U)
#define CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_CTRL_REG_ADDR                (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xD4U)
#define CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_CTRL_REG_ADDR                (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xD8U)
#define CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR            (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xDCU)
#define CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_CTRL_REG_ADDR            (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xE0U)
#define CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_CTRL_REG_ADDR           (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xE4U)
#define CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_CTRL_REG_ADDR            (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xE8U)
#define CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR               (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xECU)
#define CLK_U1_DWC_ETHER_SGMII_ACLK_I_CTRL_REG_ADDR                  (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xF0U)
#define CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_CTRL_REG_ADDR        (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xF4U)


#define MAIN_ICG_EN_CAN0_CTRL_REG_ADDR                               (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xF8U)
#define MAIN_ICG_EN_CAN1_CTRL_REG_ADDR                               (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0xFCU)
#define MAIN_ICG_EN_DMAC_1CH_CTRL_REG_ADDR                           (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x104U)
#define MAIN_ICG_EN_RTC_SCAN_CTRL_REG_ADDR                           (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x108U)
#define MAIN_ICG_EN_ADC0_CTRL_REG_ADDR                               (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x10CU)
#define MAIN_ICG_EN_ADC1_CTRL_REG_ADDR                               (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x110U)
#define MAIN_ICG_EN_GMAC2_CTRL_REG_ADDR                              (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x114U)
#define MAIN_ICG_EN_GMAC3_CTRL_REG_ADDR                              (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x118U)


#define BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR        (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x11CU)

#define BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR        (U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR + 0x120U)


#define CLK_BMCPERIPH2_300_DIV_SHIFT                                 0
#define CLK_BMCPERIPH2_300_DIV_MASK                                  0x3U
#define CLK_BMCPERIPH2_100_DIV_SHIFT                                 0
#define CLK_BMCPERIPH2_100_DIV_MASK                                  0x7U
#define CLK_BMCPERIPH2_50_DIV_SHIFT                                  0
#define CLK_BMCPERIPH2_50_DIV_MASK                                   0x3U
#define CLK_BMCPERIPH2_GMAC2_RMII_50_DIV_SHIFT                       0
#define CLK_BMCPERIPH2_GMAC2_RMII_50_DIV_MASK                        0x3U
#define CLK_BMCPERIPH2_CAN0_CORE_DIV_DIV_SHIFT                       0
#define CLK_BMCPERIPH2_CAN0_CORE_DIV_DIV_MASK                        0x1FU
#define CLK_BMCPERIPH2_CAN1_CORE_DIV_DIV_SHIFT                       0
#define CLK_BMCPERIPH2_CAN1_CORE_DIV_DIV_MASK                        0x1FU
#define CLK_BMCPERIPH2_CAN0_TIMER_DIV_SHIFT                          0
#define CLK_BMCPERIPH2_CAN0_TIMER_DIV_MASK                           0x7FU
#define CLK_BMCPERIPH2_CAN1_TIMER_DIV_SHIFT                          0
#define CLK_BMCPERIPH2_CAN1_TIMER_DIV_MASK                           0x7FU
#define CLK_BMCPERIPH2_RTC_CORE_DIV_DIV_SHIFT                        0
#define CLK_BMCPERIPH2_RTC_CORE_DIV_DIV_MASK                         0x3FFU
#define CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_SHIFT                   24
#define CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_MASK                    0x1000000U
#define CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RMII_REFIN_DATA 0
#define CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RMII_50_DATA 1
#define CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_DLY_SHIFT                  0
#define CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_DLY_MASK                   0x1FU
#define CLK_BMCPERIPH2_GMAC2_RMII_DIV_DIV_SHIFT                      0
#define CLK_BMCPERIPH2_GMAC2_RMII_DIV_DIV_MASK                       0x1FU
#define CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_DLY_SHIFT                0
#define CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_DLY_MASK                 0x1FU
#define CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_SHIFT                  24
#define CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_MASK                   0x1000000U
#define CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_DATA 0
#define CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_CLK_BMCPERIPH2_GMAC2_RGMII_DFT_DATA 1
#define CLK_BMCPERIPH2_GMAC2_RGMII_DIV_DIV_SHIFT                     0
#define CLK_BMCPERIPH2_GMAC2_RGMII_DIV_DIV_MASK                      0x3FU
#define CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_SHIFT                         24
#define CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_MASK                          0x1000000U
#define CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_CLK_BMCPERIPH2_GMAC2_RMII_DIV_DATA 0
#define CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_CLK_BMCPERIPH2_GMAC2_RGMII_DIV_DATA 1
#define CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_DATA                1
#define CLK_BMCPERIPH2_GMAC2_TX_180_BUF_UN_POLARITY_DATA             0
#define CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_SHIFT               30
#define CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_MASK                0x40000000U
#define CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_SHIFT                     24
#define CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_MASK                      0x1000000U
#define CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RMII_DIV_DATA 0
#define CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_DATA 1
#define CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_DLY_SHIFT                    0
#define CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_DLY_MASK                     0x1FU
#define CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_DATA                1
#define CLK_BMCPERIPH2_GMAC2_RX_180_BUF_UN_POLARITY_DATA             0
#define CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_SHIFT               30
#define CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_MASK                0x40000000U
#define CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_SHIFT                   24
#define CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_MASK                    0x1000000U
#define CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RMII_50_DATA 0
#define CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RGMII_TXCK_DATA 1
#define CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_DLY_SHIFT                  0
#define CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_DLY_MASK                   0x1FU
#define CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_SHIFT                     24
#define CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_MASK                      0x1000000U
#define CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_CLK_BMCPERIPH2_GMAC3_TX_125_DATA 0
#define CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_CLK_BMCPERIPH2_GMAC3_PLL_TX125_DATA 1
#define CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_SHIFT                     24
#define CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_MASK                      0x1000000U
#define CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_CLK_BMCPERIPH2_GMAC3_RX_125_DATA 0
#define CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_CLK_BMCPERIPH2_GMAC3_PLL_RX125_DATA 1
#define CLK_BMCPERIPH2_GMAC3_TX_DIV_DIV_SHIFT                        0
#define CLK_BMCPERIPH2_GMAC3_TX_DIV_DIV_MASK                         0x3FU
#define CLK_BMCPERIPH2_GMAC3_RX_DIV_DIV_SHIFT                        0
#define CLK_BMCPERIPH2_GMAC3_RX_DIV_DIV_MASK                         0x3FU
#define CLK_U10_DWC_SENSORS_PD_CLK_SYS_ENABLE_DATA                   1
#define CLK_U10_DWC_SENSORS_PD_CLK_SYS_DISABLE_DATA                  0
#define CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT                      31
#define CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_MASK                       0x80000000U
#define CLK_U0_CAN_CTRL_PCLK_ENABLE_DATA                             1
#define CLK_U0_CAN_CTRL_PCLK_DISABLE_DATA                            0
#define CLK_U0_CAN_CTRL_PCLK_EN_SHIFT                                31
#define CLK_U0_CAN_CTRL_PCLK_EN_MASK                                 0x80000000U
#define CLK_U0_CAN_CTRL_CAN_CLK_ENABLE_DATA                          1
#define CLK_U0_CAN_CTRL_CAN_CLK_DISABLE_DATA                         0
#define CLK_U0_CAN_CTRL_CAN_CLK_EN_SHIFT                             31
#define CLK_U0_CAN_CTRL_CAN_CLK_EN_MASK                              0x80000000U
#define CLK_U0_CAN_CTRL_TIMER_CLK_ENABLE_DATA                        1
#define CLK_U0_CAN_CTRL_TIMER_CLK_DISABLE_DATA                       0
#define CLK_U0_CAN_CTRL_TIMER_CLK_EN_SHIFT                           31
#define CLK_U0_CAN_CTRL_TIMER_CLK_EN_MASK                            0x80000000U
#define CLK_U1_CAN_CTRL_PCLK_ENABLE_DATA                             1
#define CLK_U1_CAN_CTRL_PCLK_DISABLE_DATA                            0
#define CLK_U1_CAN_CTRL_PCLK_EN_SHIFT                                31
#define CLK_U1_CAN_CTRL_PCLK_EN_MASK                                 0x80000000U
#define CLK_U1_CAN_CTRL_CAN_CLK_ENABLE_DATA                          1
#define CLK_U1_CAN_CTRL_CAN_CLK_DISABLE_DATA                         0
#define CLK_U1_CAN_CTRL_CAN_CLK_EN_SHIFT                             31
#define CLK_U1_CAN_CTRL_CAN_CLK_EN_MASK                              0x80000000U
#define CLK_U1_CAN_CTRL_TIMER_CLK_ENABLE_DATA                        1
#define CLK_U1_CAN_CTRL_TIMER_CLK_DISABLE_DATA                       0
#define CLK_U1_CAN_CTRL_TIMER_CLK_EN_SHIFT                           31
#define CLK_U1_CAN_CTRL_TIMER_CLK_EN_MASK                            0x80000000U
#define CLK_U0_FAN_TACH_PCLK_ENABLE_DATA                             1
#define CLK_U0_FAN_TACH_PCLK_DISABLE_DATA                            0
#define CLK_U0_FAN_TACH_PCLK_EN_SHIFT                                31
#define CLK_U0_FAN_TACH_PCLK_EN_MASK                                 0x80000000U
#define CLK_U0_DW_AXI_DMAC_8CH_PCLK_ENABLE_DATA                      1
#define CLK_U0_DW_AXI_DMAC_8CH_PCLK_DISABLE_DATA                     0
#define CLK_U0_DW_AXI_DMAC_8CH_PCLK_EN_SHIFT                         31
#define CLK_U0_DW_AXI_DMAC_8CH_PCLK_EN_MASK                          0x80000000U
#define CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_ENABLE_DATA           1
#define CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_DISABLE_DATA          0
#define CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_EN_SHIFT              31
#define CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_EN_MASK               0x80000000U
#define CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_ENABLE_DATA                    1
#define CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_DISABLE_DATA                   0
#define CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_EN_SHIFT                       31
#define CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_EN_MASK                        0x80000000U
#define CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_ENABLE_DATA                   1
#define CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_DISABLE_DATA                  0
#define CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_EN_SHIFT                      31
#define CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_EN_MASK                       0x80000000U
#define CLK_U0_RTC_HMS_SCAN_CLK_I_ENABLE_DATA                        1
#define CLK_U0_RTC_HMS_SCAN_CLK_I_DISABLE_DATA                       0
#define CLK_U0_RTC_HMS_SCAN_CLK_I_EN_SHIFT                           31
#define CLK_U0_RTC_HMS_SCAN_CLK_I_EN_MASK                            0x80000000U
#define CLK_U0_ADC_PCLK_ENABLE_DATA                                  1
#define CLK_U0_ADC_PCLK_DISABLE_DATA                                 0
#define CLK_U0_ADC_PCLK_EN_SHIFT                                     31
#define CLK_U0_ADC_PCLK_EN_MASK                                      0x80000000U
#define CLK_U1_ADC_PCLK_ENABLE_DATA                                  1
#define CLK_U1_ADC_PCLK_DISABLE_DATA                                 0
#define CLK_U1_ADC_PCLK_EN_SHIFT                                     31
#define CLK_U1_ADC_PCLK_EN_MASK                                      0x80000000U
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_ENABLE_DATA           1
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_DISABLE_DATA          0
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_EN_SHIFT              31
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_EN_MASK               0x80000000U
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_ENABLE_DATA           1
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_DISABLE_DATA          0
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_EN_SHIFT              31
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_EN_MASK               0x80000000U
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_ENABLE_DATA       1
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_DISABLE_DATA      0
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_EN_SHIFT          31
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_EN_MASK           0x80000000U
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_ENABLE_DATA       1
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_DISABLE_DATA      0
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_EN_SHIFT          31
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_EN_MASK           0x80000000U
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_ENABLE_DATA      1
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_DISABLE_DATA     0
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_EN_SHIFT         31
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_EN_MASK          0x80000000U
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_ENABLE_DATA         1
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_DISABLE_DATA        0
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_EN_SHIFT            31
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_EN_MASK             0x80000000U
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_ENABLE_DATA          1
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_DISABLE_DATA         0
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_EN_SHIFT             31
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_EN_MASK              0x80000000U
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_ENABLE_DATA             1
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_DISABLE_DATA            0
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_EN_SHIFT                31
#define CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_EN_MASK                 0x80000000U
#define CLK_GMAC2_TXCK_ENABLE_DATA                                   1
#define CLK_GMAC2_TXCK_DISABLE_DATA                                  0
#define CLK_GMAC2_TXCK_EN_SHIFT                                      31
#define CLK_GMAC2_TXCK_EN_MASK                                       0x80000000U
#define CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_ENABLE_DATA                  1
#define CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_DISABLE_DATA                 0
#define CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_EN_SHIFT                     31
#define CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_EN_MASK                      0x80000000U
#define CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_ENABLE_DATA                  1
#define CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_DISABLE_DATA                 0
#define CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_EN_SHIFT                     31
#define CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_EN_MASK                      0x80000000U
#define CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_ENABLE_DATA              1
#define CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_DISABLE_DATA             0
#define CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_EN_SHIFT                 31
#define CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_EN_MASK                  0x80000000U
#define CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_ENABLE_DATA              1
#define CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_DISABLE_DATA             0
#define CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_EN_SHIFT                 31
#define CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_EN_MASK                  0x80000000U
#define CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_ENABLE_DATA             1
#define CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_DISABLE_DATA            0
#define CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_SHIFT                31
#define CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_MASK                 0x80000000U
#define CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_ENABLE_DATA              1
#define CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_DISABLE_DATA             0
#define CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_EN_SHIFT                 31
#define CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_EN_MASK                  0x80000000U
#define CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_ENABLE_DATA                 1
#define CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_DISABLE_DATA                0
#define CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_EN_SHIFT                    31
#define CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_EN_MASK                     0x80000000U
#define CLK_U1_DWC_ETHER_SGMII_ACLK_I_ENABLE_DATA                    1
#define CLK_U1_DWC_ETHER_SGMII_ACLK_I_DISABLE_DATA                   0
#define CLK_U1_DWC_ETHER_SGMII_ACLK_I_EN_SHIFT                       31
#define CLK_U1_DWC_ETHER_SGMII_ACLK_I_EN_MASK                        0x80000000U
#define CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_ENABLE_DATA          1
#define CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_DISABLE_DATA         0
#define CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_SHIFT             31
#define CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_MASK              0x80000000U

#define MAIN_ICG_EN_CAN0_ENABLE_DATA                                 1
#define MAIN_ICG_EN_CAN0_DISABLE_DATA                                0
#define MAIN_ICG_EN_CAN0_EN_SHIFT                                    31
#define MAIN_ICG_EN_CAN0_EN_MASK                                     0x80000000U
#define MAIN_ICG_EN_CAN1_ENABLE_DATA                                 1
#define MAIN_ICG_EN_CAN1_DISABLE_DATA                                0
#define MAIN_ICG_EN_CAN1_EN_SHIFT                                    31
#define MAIN_ICG_EN_CAN1_EN_MASK                                     0x80000000U
#define MAIN_ICG_EN_DMAC_1CH_ENABLE_DATA                             1
#define MAIN_ICG_EN_DMAC_1CH_DISABLE_DATA                            0
#define MAIN_ICG_EN_DMAC_1CH_EN_SHIFT                                31
#define MAIN_ICG_EN_DMAC_1CH_EN_MASK                                 0x80000000U
#define MAIN_ICG_EN_RTC_SCAN_ENABLE_DATA                             1
#define MAIN_ICG_EN_RTC_SCAN_DISABLE_DATA                            0
#define MAIN_ICG_EN_RTC_SCAN_EN_SHIFT                                31
#define MAIN_ICG_EN_RTC_SCAN_EN_MASK                                 0x80000000U
#define MAIN_ICG_EN_ADC0_ENABLE_DATA                                 1
#define MAIN_ICG_EN_ADC0_DISABLE_DATA                                0
#define MAIN_ICG_EN_ADC0_EN_SHIFT                                    31
#define MAIN_ICG_EN_ADC0_EN_MASK                                     0x80000000U
#define MAIN_ICG_EN_ADC1_ENABLE_DATA                                 1
#define MAIN_ICG_EN_ADC1_DISABLE_DATA                                0
#define MAIN_ICG_EN_ADC1_EN_SHIFT                                    31
#define MAIN_ICG_EN_ADC1_EN_MASK                                     0x80000000U
#define MAIN_ICG_EN_GMAC2_ENABLE_DATA                                1
#define MAIN_ICG_EN_GMAC2_DISABLE_DATA                               0
#define MAIN_ICG_EN_GMAC2_EN_SHIFT                                   31
#define MAIN_ICG_EN_GMAC2_EN_MASK                                    0x80000000U
#define MAIN_ICG_EN_GMAC3_ENABLE_DATA                                1
#define MAIN_ICG_EN_GMAC3_DISABLE_DATA                               0
#define MAIN_ICG_EN_GMAC3_EN_SHIFT                                   31
#define MAIN_ICG_EN_GMAC3_EN_MASK                                    0x80000000U



#define RSTN_U0_BMCPERIPH2_IOMUX_PRESETN_SHIFT                       0
#define RSTN_U0_BMCPERIPH2_IOMUX_PRESETN_MASK                        (0x1 << 0)
#define RSTN_U0_BMCPERIPH2_IOMUX_PRESETN_ASSERT                      1
#define RSTN_U0_BMCPERIPH2_IOMUX_PRESETN_CLEAR                       0
#define RSTN_U0_BMCPERIPH2_POK_IOMUX_PRESETN_SHIFT                   1
#define RSTN_U0_BMCPERIPH2_POK_IOMUX_PRESETN_MASK                    (0x1 << 1)
#define RSTN_U0_BMCPERIPH2_POK_IOMUX_PRESETN_ASSERT                  1
#define RSTN_U0_BMCPERIPH2_POK_IOMUX_PRESETN_CLEAR                   0
#define RSTN_U0_BMCPERIPH2_SYSREG_RSTN_SHIFT                         2
#define RSTN_U0_BMCPERIPH2_SYSREG_RSTN_MASK                          (0x1 << 2)
#define RSTN_U0_BMCPERIPH2_SYSREG_RSTN_ASSERT                        1
#define RSTN_U0_BMCPERIPH2_SYSREG_RSTN_CLEAR                         0
#define MAIN_RSTN_CAN0_SHIFT                                         3
#define MAIN_RSTN_CAN0_MASK                                          (0x1 << 3)
#define MAIN_RSTN_CAN0_ASSERT                                        1
#define MAIN_RSTN_CAN0_CLEAR                                         0
#define MAIN_RSTN_CAN1_SHIFT                                         4
#define MAIN_RSTN_CAN1_MASK                                          (0x1 << 4)
#define MAIN_RSTN_CAN1_ASSERT                                        1
#define MAIN_RSTN_CAN1_CLEAR                                         0
#define RSTN_U0_FAN_TACH_PRESETN_SHIFT                               5
#define RSTN_U0_FAN_TACH_PRESETN_MASK                                (0x1 << 5)
#define RSTN_U0_FAN_TACH_PRESETN_ASSERT                              1
#define RSTN_U0_FAN_TACH_PRESETN_CLEAR                               0
#define MAIN_RSTN_GMAC2_SHIFT                                        7
#define MAIN_RSTN_GMAC2_MASK                                         (0x1 << 7)
#define MAIN_RSTN_GMAC2_ASSERT                                       1
#define MAIN_RSTN_GMAC2_CLEAR                                        0
#define MAIN_RSTN_GMAC3_SHIFT                                        8
#define MAIN_RSTN_GMAC3_MASK                                         (0x1 << 8)
#define MAIN_RSTN_GMAC3_ASSERT                                       1
#define MAIN_RSTN_GMAC3_CLEAR                                        0
#define MAIN_RSTN_DMAC_8CH_SHIFT                                     9
#define MAIN_RSTN_DMAC_8CH_MASK                                      (0x1 << 9)
#define MAIN_RSTN_DMAC_8CH_ASSERT                                    1
#define MAIN_RSTN_DMAC_8CH_CLEAR                                     0
#define MAIN_RSTN_RTC_SHIFT                                          10
#define MAIN_RSTN_RTC_MASK                                           (0x1 << 10)
#define MAIN_RSTN_RTC_ASSERT                                         1
#define MAIN_RSTN_RTC_CLEAR                                          0
#define RSTN_U0_ADC_PRESETN_SHIFT                                    11
#define RSTN_U0_ADC_PRESETN_MASK                                     (0x1 << 11)
#define RSTN_U0_ADC_PRESETN_ASSERT                                   1
#define RSTN_U0_ADC_PRESETN_CLEAR                                    0
#define RSTN_U0_ADC_IOMUX_PRESETN_SHIFT                              12
#define RSTN_U0_ADC_IOMUX_PRESETN_MASK                               (0x1 << 12)
#define RSTN_U0_ADC_IOMUX_PRESETN_ASSERT                             1
#define RSTN_U0_ADC_IOMUX_PRESETN_CLEAR                              0
#define RSTN_U1_ADC_PRESETN_SHIFT                                    13
#define RSTN_U1_ADC_PRESETN_MASK                                     (0x1 << 13)
#define RSTN_U1_ADC_PRESETN_ASSERT                                   1
#define RSTN_U1_ADC_PRESETN_CLEAR                                    0
#define RSTN_U1_ADC_IOMUX_PRESETN_SHIFT                              14
#define RSTN_U1_ADC_IOMUX_PRESETN_MASK                               (0x1 << 14)
#define RSTN_U1_ADC_IOMUX_PRESETN_ASSERT                             1
#define RSTN_U1_ADC_IOMUX_PRESETN_CLEAR                              0
// #define MAIN_RSTN_SENSOR_SHIFT                                       15
// #define MAIN_RSTN_SENSOR_MASK                                        (0x1 << 15)
#define MAIN_RSTN_SENSOR_ASSERT                                      1
#define MAIN_RSTN_SENSOR_CLEAR                                       0

#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_300_(div) 			itg_set_reg(CLK_BMCPERIPH2_300_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_300_DIV_SHIFT, CLK_BMCPERIPH2_300_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_300_ 		itg_get_reg(CLK_BMCPERIPH2_300_CTRL_REG_ADDR, CLK_BMCPERIPH2_300_DIV_SHIFT, CLK_BMCPERIPH2_300_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_100_(div) 			itg_set_reg(CLK_BMCPERIPH2_100_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_100_DIV_SHIFT, CLK_BMCPERIPH2_100_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_100_ 		itg_get_reg(CLK_BMCPERIPH2_100_CTRL_REG_ADDR, CLK_BMCPERIPH2_100_DIV_SHIFT, CLK_BMCPERIPH2_100_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_50_(div) 			itg_set_reg(CLK_BMCPERIPH2_50_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_50_DIV_SHIFT, CLK_BMCPERIPH2_50_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_50_ 		itg_get_reg(CLK_BMCPERIPH2_50_CTRL_REG_ADDR, CLK_BMCPERIPH2_50_DIV_SHIFT, CLK_BMCPERIPH2_50_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_GMAC2_RMII_50_(div) 			itg_set_reg(CLK_BMCPERIPH2_GMAC2_RMII_50_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_GMAC2_RMII_50_DIV_SHIFT, CLK_BMCPERIPH2_GMAC2_RMII_50_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_GMAC2_RMII_50_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_RMII_50_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RMII_50_DIV_SHIFT, CLK_BMCPERIPH2_GMAC2_RMII_50_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_CAN0_CORE_DIV_(div) 			itg_set_reg(CLK_BMCPERIPH2_CAN0_CORE_DIV_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_CAN0_CORE_DIV_DIV_SHIFT, CLK_BMCPERIPH2_CAN0_CORE_DIV_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_CAN0_CORE_DIV_ 		itg_get_reg(CLK_BMCPERIPH2_CAN0_CORE_DIV_CTRL_REG_ADDR, CLK_BMCPERIPH2_CAN0_CORE_DIV_DIV_SHIFT, CLK_BMCPERIPH2_CAN0_CORE_DIV_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_CAN1_CORE_DIV_(div) 			itg_set_reg(CLK_BMCPERIPH2_CAN1_CORE_DIV_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_CAN1_CORE_DIV_DIV_SHIFT, CLK_BMCPERIPH2_CAN1_CORE_DIV_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_CAN1_CORE_DIV_ 		itg_get_reg(CLK_BMCPERIPH2_CAN1_CORE_DIV_CTRL_REG_ADDR, CLK_BMCPERIPH2_CAN1_CORE_DIV_DIV_SHIFT, CLK_BMCPERIPH2_CAN1_CORE_DIV_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_CAN0_TIMER_(div) 			itg_set_reg(CLK_BMCPERIPH2_CAN0_TIMER_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_CAN0_TIMER_DIV_SHIFT, CLK_BMCPERIPH2_CAN0_TIMER_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_CAN0_TIMER_ 		itg_get_reg(CLK_BMCPERIPH2_CAN0_TIMER_CTRL_REG_ADDR, CLK_BMCPERIPH2_CAN0_TIMER_DIV_SHIFT, CLK_BMCPERIPH2_CAN0_TIMER_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_CAN1_TIMER_(div) 			itg_set_reg(CLK_BMCPERIPH2_CAN1_TIMER_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_CAN1_TIMER_DIV_SHIFT, CLK_BMCPERIPH2_CAN1_TIMER_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_CAN1_TIMER_ 		itg_get_reg(CLK_BMCPERIPH2_CAN1_TIMER_CTRL_REG_ADDR, CLK_BMCPERIPH2_CAN1_TIMER_DIV_SHIFT, CLK_BMCPERIPH2_CAN1_TIMER_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_RTC_CORE_DIV_(div) 			itg_set_reg(CLK_BMCPERIPH2_RTC_CORE_DIV_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_RTC_CORE_DIV_DIV_SHIFT, CLK_BMCPERIPH2_RTC_CORE_DIV_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_RTC_CORE_DIV_ 		itg_get_reg(CLK_BMCPERIPH2_RTC_CORE_DIV_CTRL_REG_ADDR, CLK_BMCPERIPH2_RTC_CORE_DIV_DIV_SHIFT, CLK_BMCPERIPH2_RTC_CORE_DIV_DIV_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SOURCE_CLK_BMCPERIPH2_GMAC2_RMII_REFIN_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RMII_REFIN_DATA, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SOURCE_CLK_BMCPERIPH2_GMAC2_RMII_50_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RMII_50_DATA, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_(x) 		itg_set_reg(CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_CTRL_REG_ADDR, x, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_SW_MASK)
#define _SET_CLOCK_CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_(dly) 			itg_set_reg(CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_CTRL_REG_ADDR, dly, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_DLY_SHIFT, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_DLY_MASK)
#define _GET_CLOCK_DELAY_STATUS_CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_DLY_SHIFT, CLK_BMCPERIPH2_GMAC2_RMII_MUX_DLY_DLY_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_GMAC2_RMII_DIV_(div) 			itg_set_reg(CLK_BMCPERIPH2_GMAC2_RMII_DIV_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_GMAC2_RMII_DIV_DIV_SHIFT, CLK_BMCPERIPH2_GMAC2_RMII_DIV_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_GMAC2_RMII_DIV_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_RMII_DIV_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RMII_DIV_DIV_SHIFT, CLK_BMCPERIPH2_GMAC2_RMII_DIV_DIV_MASK)
#define _SET_CLOCK_CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_(dly) 			itg_set_reg(CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_CTRL_REG_ADDR, dly, CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_DLY_SHIFT, CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_DLY_MASK)
#define _GET_CLOCK_DELAY_STATUS_CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_DLY_SHIFT, CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_DLY_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SOURCE_CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_CLK_BMCPERIPH2_GMAC2_RGMII_FUNC_DLY_DATA, CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SOURCE_CLK_BMCPERIPH2_GMAC2_RGMII_DFT_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_CLK_BMCPERIPH2_GMAC2_RGMII_DFT_DATA, CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_(x) 		itg_set_reg(CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_CTRL_REG_ADDR, x, CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_SW_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_GMAC2_RGMII_DIV_(div) 			itg_set_reg(CLK_BMCPERIPH2_GMAC2_RGMII_DIV_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_GMAC2_RGMII_DIV_DIV_SHIFT, CLK_BMCPERIPH2_GMAC2_RGMII_DIV_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_GMAC2_RGMII_DIV_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_RGMII_DIV_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RGMII_DIV_DIV_SHIFT, CLK_BMCPERIPH2_GMAC2_RGMII_DIV_DIV_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC2_TX_MUX_SOURCE_CLK_BMCPERIPH2_GMAC2_RMII_DIV_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC2_TX_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_CLK_BMCPERIPH2_GMAC2_RMII_DIV_DATA, CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC2_TX_MUX_SOURCE_CLK_BMCPERIPH2_GMAC2_RGMII_DIV_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC2_TX_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_CLK_BMCPERIPH2_GMAC2_RGMII_DIV_DATA, CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC2_TX_MUX_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_TX_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC2_TX_MUX_(x) 		itg_set_reg(CLK_BMCPERIPH2_GMAC2_TX_MUX_CTRL_REG_ADDR, x, CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_TX_MUX_SW_MASK)
#define _SET_CLOCK_CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_ 		itg_set_reg(CLK_BMCPERIPH2_GMAC2_TX_180_BUF_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_DATA, CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_SHIFT, CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_MASK)
#define _UNSET_CLOCK_CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_ 		itg_set_reg(CLK_BMCPERIPH2_GMAC2_TX_180_BUF_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_TX_180_BUF_UN_POLARITY_DATA, CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_SHIFT, CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_MASK)
#define _GET_CLOCK_POLARITY_STATUS_CLK_BMCPERIPH2_GMAC2_TX_180_BUF_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_TX_180_BUF_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_SHIFT, CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_MASK)
#define _SET_CLOCK_POLARITY_STATUS_CLK_BMCPERIPH2_GMAC2_TX_180_BUF_(x) 		itg_set_reg(CLK_BMCPERIPH2_GMAC2_TX_180_BUF_CTRL_REG_ADDR, x, CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_SHIFT, CLK_BMCPERIPH2_GMAC2_TX_180_BUF_POLARITY_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SOURCE_CLK_BMCPERIPH2_GMAC2_RMII_DIV_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RMII_DIV_DATA, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SOURCE_CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RGMII_125_MUX_DATA, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_(x) 		itg_set_reg(CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_CTRL_REG_ADDR, x, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_SW_MASK)
#define _SET_CLOCK_CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_(dly) 			itg_set_reg(CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_CTRL_REG_ADDR, dly, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_DLY_SHIFT, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_DLY_MASK)
#define _GET_CLOCK_DELAY_STATUS_CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_DLY_SHIFT, CLK_BMCPERIPH2_GMAC2_RX_MUX_DLY_DLY_MASK)
#define _SET_CLOCK_CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_ 		itg_set_reg(CLK_BMCPERIPH2_GMAC2_RX_180_BUF_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_DATA, CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_SHIFT, CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_MASK)
#define _UNSET_CLOCK_CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_ 		itg_set_reg(CLK_BMCPERIPH2_GMAC2_RX_180_BUF_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RX_180_BUF_UN_POLARITY_DATA, CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_SHIFT, CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_MASK)
#define _GET_CLOCK_POLARITY_STATUS_CLK_BMCPERIPH2_GMAC2_RX_180_BUF_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_RX_180_BUF_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_SHIFT, CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_MASK)
#define _SET_CLOCK_POLARITY_STATUS_CLK_BMCPERIPH2_GMAC2_RX_180_BUF_(x) 		itg_set_reg(CLK_BMCPERIPH2_GMAC2_RX_180_BUF_CTRL_REG_ADDR, x, CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_SHIFT, CLK_BMCPERIPH2_GMAC2_RX_180_BUF_POLARITY_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SOURCE_CLK_BMCPERIPH2_GMAC2_RMII_50_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RMII_50_DATA, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SOURCE_CLK_BMCPERIPH2_GMAC2_RGMII_TXCK_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_CLK_BMCPERIPH2_GMAC2_RGMII_TXCK_DATA, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_(x) 		itg_set_reg(CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_CTRL_REG_ADDR, x, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_SHIFT, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_SW_MASK)
#define _SET_CLOCK_CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_(dly) 			itg_set_reg(CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_CTRL_REG_ADDR, dly, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_DLY_SHIFT, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_DLY_MASK)
#define _GET_CLOCK_DELAY_STATUS_CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_DLY_SHIFT, CLK_BMCPERIPH2_GMAC2_TXCK_MUX_DLY_DLY_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SOURCE_CLK_BMCPERIPH2_GMAC3_TX_125_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC3_TX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_CLK_BMCPERIPH2_GMAC3_TX_125_DATA, CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SOURCE_CLK_BMCPERIPH2_GMAC3_PLL_TX125_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC3_TX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_CLK_BMCPERIPH2_GMAC3_PLL_TX125_DATA, CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC3_TX_125_MUX_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC3_TX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC3_TX_125_MUX_(x) 		itg_set_reg(CLK_BMCPERIPH2_GMAC3_TX_125_MUX_CTRL_REG_ADDR, x, CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC3_TX_125_MUX_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SOURCE_CLK_BMCPERIPH2_GMAC3_RX_125_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC3_RX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_CLK_BMCPERIPH2_GMAC3_RX_125_DATA, CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_MASK)
#define _SWITCH_CLOCK_CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SOURCE_CLK_BMCPERIPH2_GMAC3_PLL_RX125_ 	itg_set_reg(CLK_BMCPERIPH2_GMAC3_RX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_CLK_BMCPERIPH2_GMAC3_PLL_RX125_DATA, CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC3_RX_125_MUX_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC3_RX_125_MUX_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_BMCPERIPH2_GMAC3_RX_125_MUX_(x) 		itg_set_reg(CLK_BMCPERIPH2_GMAC3_RX_125_MUX_CTRL_REG_ADDR, x, CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_SHIFT, CLK_BMCPERIPH2_GMAC3_RX_125_MUX_SW_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_GMAC3_TX_DIV_(div) 			itg_set_reg(CLK_BMCPERIPH2_GMAC3_TX_DIV_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_GMAC3_TX_DIV_DIV_SHIFT, CLK_BMCPERIPH2_GMAC3_TX_DIV_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_GMAC3_TX_DIV_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC3_TX_DIV_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC3_TX_DIV_DIV_SHIFT, CLK_BMCPERIPH2_GMAC3_TX_DIV_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_BMCPERIPH2_GMAC3_RX_DIV_(div) 			itg_set_reg(CLK_BMCPERIPH2_GMAC3_RX_DIV_CTRL_REG_ADDR, div, CLK_BMCPERIPH2_GMAC3_RX_DIV_DIV_SHIFT, CLK_BMCPERIPH2_GMAC3_RX_DIV_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_BMCPERIPH2_GMAC3_RX_DIV_ 		itg_get_reg(CLK_BMCPERIPH2_GMAC3_RX_DIV_CTRL_REG_ADDR, CLK_BMCPERIPH2_GMAC3_RX_DIV_DIV_SHIFT, CLK_BMCPERIPH2_GMAC3_RX_DIV_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U10_DWC_SENSORS_PD_CLK_SYS_ 			itg_set_reg(CLK_U10_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U10_DWC_SENSORS_PD_CLK_SYS_ENABLE_DATA, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _DISABLE_CLOCK_CLK_U10_DWC_SENSORS_PD_CLK_SYS_ 			itg_set_reg(CLK_U10_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U10_DWC_SENSORS_PD_CLK_SYS_DISABLE_DATA, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U10_DWC_SENSORS_PD_CLK_SYS_ 		itg_get_reg(CLK_U10_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U10_DWC_SENSORS_PD_CLK_SYS_(x) 		itg_set_reg(CLK_U10_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, x, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_CAN_CTRL_PCLK_ 			itg_set_reg(CLK_U0_CAN_CTRL_PCLK_CTRL_REG_ADDR, CLK_U0_CAN_CTRL_PCLK_ENABLE_DATA, CLK_U0_CAN_CTRL_PCLK_EN_SHIFT, CLK_U0_CAN_CTRL_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CAN_CTRL_PCLK_ 			itg_set_reg(CLK_U0_CAN_CTRL_PCLK_CTRL_REG_ADDR, CLK_U0_CAN_CTRL_PCLK_DISABLE_DATA, CLK_U0_CAN_CTRL_PCLK_EN_SHIFT, CLK_U0_CAN_CTRL_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CAN_CTRL_PCLK_ 		itg_get_reg(CLK_U0_CAN_CTRL_PCLK_CTRL_REG_ADDR, CLK_U0_CAN_CTRL_PCLK_EN_SHIFT, CLK_U0_CAN_CTRL_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CAN_CTRL_PCLK_(x) 		itg_set_reg(CLK_U0_CAN_CTRL_PCLK_CTRL_REG_ADDR, x, CLK_U0_CAN_CTRL_PCLK_EN_SHIFT, CLK_U0_CAN_CTRL_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_CAN_CTRL_CAN_CLK_ 			itg_set_reg(CLK_U0_CAN_CTRL_CAN_CLK_CTRL_REG_ADDR, CLK_U0_CAN_CTRL_CAN_CLK_ENABLE_DATA, CLK_U0_CAN_CTRL_CAN_CLK_EN_SHIFT, CLK_U0_CAN_CTRL_CAN_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CAN_CTRL_CAN_CLK_ 			itg_set_reg(CLK_U0_CAN_CTRL_CAN_CLK_CTRL_REG_ADDR, CLK_U0_CAN_CTRL_CAN_CLK_DISABLE_DATA, CLK_U0_CAN_CTRL_CAN_CLK_EN_SHIFT, CLK_U0_CAN_CTRL_CAN_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CAN_CTRL_CAN_CLK_ 		itg_get_reg(CLK_U0_CAN_CTRL_CAN_CLK_CTRL_REG_ADDR, CLK_U0_CAN_CTRL_CAN_CLK_EN_SHIFT, CLK_U0_CAN_CTRL_CAN_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CAN_CTRL_CAN_CLK_(x) 		itg_set_reg(CLK_U0_CAN_CTRL_CAN_CLK_CTRL_REG_ADDR, x, CLK_U0_CAN_CTRL_CAN_CLK_EN_SHIFT, CLK_U0_CAN_CTRL_CAN_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_CAN_CTRL_TIMER_CLK_ 			itg_set_reg(CLK_U0_CAN_CTRL_TIMER_CLK_CTRL_REG_ADDR, CLK_U0_CAN_CTRL_TIMER_CLK_ENABLE_DATA, CLK_U0_CAN_CTRL_TIMER_CLK_EN_SHIFT, CLK_U0_CAN_CTRL_TIMER_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CAN_CTRL_TIMER_CLK_ 			itg_set_reg(CLK_U0_CAN_CTRL_TIMER_CLK_CTRL_REG_ADDR, CLK_U0_CAN_CTRL_TIMER_CLK_DISABLE_DATA, CLK_U0_CAN_CTRL_TIMER_CLK_EN_SHIFT, CLK_U0_CAN_CTRL_TIMER_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CAN_CTRL_TIMER_CLK_ 		itg_get_reg(CLK_U0_CAN_CTRL_TIMER_CLK_CTRL_REG_ADDR, CLK_U0_CAN_CTRL_TIMER_CLK_EN_SHIFT, CLK_U0_CAN_CTRL_TIMER_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CAN_CTRL_TIMER_CLK_(x) 		itg_set_reg(CLK_U0_CAN_CTRL_TIMER_CLK_CTRL_REG_ADDR, x, CLK_U0_CAN_CTRL_TIMER_CLK_EN_SHIFT, CLK_U0_CAN_CTRL_TIMER_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_CAN_CTRL_PCLK_ 			itg_set_reg(CLK_U1_CAN_CTRL_PCLK_CTRL_REG_ADDR, CLK_U1_CAN_CTRL_PCLK_ENABLE_DATA, CLK_U1_CAN_CTRL_PCLK_EN_SHIFT, CLK_U1_CAN_CTRL_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_CAN_CTRL_PCLK_ 			itg_set_reg(CLK_U1_CAN_CTRL_PCLK_CTRL_REG_ADDR, CLK_U1_CAN_CTRL_PCLK_DISABLE_DATA, CLK_U1_CAN_CTRL_PCLK_EN_SHIFT, CLK_U1_CAN_CTRL_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_CAN_CTRL_PCLK_ 		itg_get_reg(CLK_U1_CAN_CTRL_PCLK_CTRL_REG_ADDR, CLK_U1_CAN_CTRL_PCLK_EN_SHIFT, CLK_U1_CAN_CTRL_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_CAN_CTRL_PCLK_(x) 		itg_set_reg(CLK_U1_CAN_CTRL_PCLK_CTRL_REG_ADDR, x, CLK_U1_CAN_CTRL_PCLK_EN_SHIFT, CLK_U1_CAN_CTRL_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_CAN_CTRL_CAN_CLK_ 			itg_set_reg(CLK_U1_CAN_CTRL_CAN_CLK_CTRL_REG_ADDR, CLK_U1_CAN_CTRL_CAN_CLK_ENABLE_DATA, CLK_U1_CAN_CTRL_CAN_CLK_EN_SHIFT, CLK_U1_CAN_CTRL_CAN_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_CAN_CTRL_CAN_CLK_ 			itg_set_reg(CLK_U1_CAN_CTRL_CAN_CLK_CTRL_REG_ADDR, CLK_U1_CAN_CTRL_CAN_CLK_DISABLE_DATA, CLK_U1_CAN_CTRL_CAN_CLK_EN_SHIFT, CLK_U1_CAN_CTRL_CAN_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_CAN_CTRL_CAN_CLK_ 		itg_get_reg(CLK_U1_CAN_CTRL_CAN_CLK_CTRL_REG_ADDR, CLK_U1_CAN_CTRL_CAN_CLK_EN_SHIFT, CLK_U1_CAN_CTRL_CAN_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_CAN_CTRL_CAN_CLK_(x) 		itg_set_reg(CLK_U1_CAN_CTRL_CAN_CLK_CTRL_REG_ADDR, x, CLK_U1_CAN_CTRL_CAN_CLK_EN_SHIFT, CLK_U1_CAN_CTRL_CAN_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_CAN_CTRL_TIMER_CLK_ 			itg_set_reg(CLK_U1_CAN_CTRL_TIMER_CLK_CTRL_REG_ADDR, CLK_U1_CAN_CTRL_TIMER_CLK_ENABLE_DATA, CLK_U1_CAN_CTRL_TIMER_CLK_EN_SHIFT, CLK_U1_CAN_CTRL_TIMER_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_CAN_CTRL_TIMER_CLK_ 			itg_set_reg(CLK_U1_CAN_CTRL_TIMER_CLK_CTRL_REG_ADDR, CLK_U1_CAN_CTRL_TIMER_CLK_DISABLE_DATA, CLK_U1_CAN_CTRL_TIMER_CLK_EN_SHIFT, CLK_U1_CAN_CTRL_TIMER_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_CAN_CTRL_TIMER_CLK_ 		itg_get_reg(CLK_U1_CAN_CTRL_TIMER_CLK_CTRL_REG_ADDR, CLK_U1_CAN_CTRL_TIMER_CLK_EN_SHIFT, CLK_U1_CAN_CTRL_TIMER_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_CAN_CTRL_TIMER_CLK_(x) 		itg_set_reg(CLK_U1_CAN_CTRL_TIMER_CLK_CTRL_REG_ADDR, x, CLK_U1_CAN_CTRL_TIMER_CLK_EN_SHIFT, CLK_U1_CAN_CTRL_TIMER_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_FAN_TACH_PCLK_ 			itg_set_reg(CLK_U0_FAN_TACH_PCLK_CTRL_REG_ADDR, CLK_U0_FAN_TACH_PCLK_ENABLE_DATA, CLK_U0_FAN_TACH_PCLK_EN_SHIFT, CLK_U0_FAN_TACH_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_FAN_TACH_PCLK_ 			itg_set_reg(CLK_U0_FAN_TACH_PCLK_CTRL_REG_ADDR, CLK_U0_FAN_TACH_PCLK_DISABLE_DATA, CLK_U0_FAN_TACH_PCLK_EN_SHIFT, CLK_U0_FAN_TACH_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_FAN_TACH_PCLK_ 		itg_get_reg(CLK_U0_FAN_TACH_PCLK_CTRL_REG_ADDR, CLK_U0_FAN_TACH_PCLK_EN_SHIFT, CLK_U0_FAN_TACH_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_FAN_TACH_PCLK_(x) 		itg_set_reg(CLK_U0_FAN_TACH_PCLK_CTRL_REG_ADDR, x, CLK_U0_FAN_TACH_PCLK_EN_SHIFT, CLK_U0_FAN_TACH_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DW_AXI_DMAC_8CH_PCLK_ 			itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_PCLK_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_PCLK_ENABLE_DATA, CLK_U0_DW_AXI_DMAC_8CH_PCLK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DW_AXI_DMAC_8CH_PCLK_ 			itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_PCLK_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_PCLK_DISABLE_DATA, CLK_U0_DW_AXI_DMAC_8CH_PCLK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DW_AXI_DMAC_8CH_PCLK_ 		itg_get_reg(CLK_U0_DW_AXI_DMAC_8CH_PCLK_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_PCLK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DW_AXI_DMAC_8CH_PCLK_(x) 		itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_PCLK_CTRL_REG_ADDR, x, CLK_U0_DW_AXI_DMAC_8CH_PCLK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_ 			itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_ENABLE_DATA, CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_ 			itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_DISABLE_DATA, CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_ 		itg_get_reg(CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_(x) 		itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_CTRL_REG_ADDR, x, CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_DMAC_CORE_CLOCK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_ 			itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_ENABLE_DATA, CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_ 			itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_DISABLE_DATA, CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_ 		itg_get_reg(CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_(x) 		itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_CTRL_REG_ADDR, x, CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_HS_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_ 			itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_ENABLE_DATA, CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_ 			itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_DISABLE_DATA, CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_ 		itg_get_reg(CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_CTRL_REG_ADDR, CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_(x) 		itg_set_reg(CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_CTRL_REG_ADDR, x, CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_EN_SHIFT, CLK_U0_DW_AXI_DMAC_8CH_ACLK_M1_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_RTC_HMS_SCAN_CLK_I_ 			itg_set_reg(CLK_U0_RTC_HMS_SCAN_CLK_I_CTRL_REG_ADDR, CLK_U0_RTC_HMS_SCAN_CLK_I_ENABLE_DATA, CLK_U0_RTC_HMS_SCAN_CLK_I_EN_SHIFT, CLK_U0_RTC_HMS_SCAN_CLK_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_RTC_HMS_SCAN_CLK_I_ 			itg_set_reg(CLK_U0_RTC_HMS_SCAN_CLK_I_CTRL_REG_ADDR, CLK_U0_RTC_HMS_SCAN_CLK_I_DISABLE_DATA, CLK_U0_RTC_HMS_SCAN_CLK_I_EN_SHIFT, CLK_U0_RTC_HMS_SCAN_CLK_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_RTC_HMS_SCAN_CLK_I_ 		itg_get_reg(CLK_U0_RTC_HMS_SCAN_CLK_I_CTRL_REG_ADDR, CLK_U0_RTC_HMS_SCAN_CLK_I_EN_SHIFT, CLK_U0_RTC_HMS_SCAN_CLK_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_RTC_HMS_SCAN_CLK_I_(x) 		itg_set_reg(CLK_U0_RTC_HMS_SCAN_CLK_I_CTRL_REG_ADDR, x, CLK_U0_RTC_HMS_SCAN_CLK_I_EN_SHIFT, CLK_U0_RTC_HMS_SCAN_CLK_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_ADC_PCLK_ 			itg_set_reg(CLK_U0_ADC_PCLK_CTRL_REG_ADDR, CLK_U0_ADC_PCLK_ENABLE_DATA, CLK_U0_ADC_PCLK_EN_SHIFT, CLK_U0_ADC_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_ADC_PCLK_ 			itg_set_reg(CLK_U0_ADC_PCLK_CTRL_REG_ADDR, CLK_U0_ADC_PCLK_DISABLE_DATA, CLK_U0_ADC_PCLK_EN_SHIFT, CLK_U0_ADC_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_ADC_PCLK_ 		itg_get_reg(CLK_U0_ADC_PCLK_CTRL_REG_ADDR, CLK_U0_ADC_PCLK_EN_SHIFT, CLK_U0_ADC_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_ADC_PCLK_(x) 		itg_set_reg(CLK_U0_ADC_PCLK_CTRL_REG_ADDR, x, CLK_U0_ADC_PCLK_EN_SHIFT, CLK_U0_ADC_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_ADC_PCLK_ 			itg_set_reg(CLK_U1_ADC_PCLK_CTRL_REG_ADDR, CLK_U1_ADC_PCLK_ENABLE_DATA, CLK_U1_ADC_PCLK_EN_SHIFT, CLK_U1_ADC_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_ADC_PCLK_ 			itg_set_reg(CLK_U1_ADC_PCLK_CTRL_REG_ADDR, CLK_U1_ADC_PCLK_DISABLE_DATA, CLK_U1_ADC_PCLK_EN_SHIFT, CLK_U1_ADC_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_ADC_PCLK_ 		itg_get_reg(CLK_U1_ADC_PCLK_CTRL_REG_ADDR, CLK_U1_ADC_PCLK_EN_SHIFT, CLK_U1_ADC_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_ADC_PCLK_(x) 		itg_set_reg(CLK_U1_ADC_PCLK_CTRL_REG_ADDR, x, CLK_U1_ADC_PCLK_EN_SHIFT, CLK_U1_ADC_PCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_TX_180_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RX_180_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_PTP_REF_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_RMII_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_CLK_CSR_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_ENABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_ 			itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_DISABLE_DATA, CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_ 		itg_get_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_CTRL_REG_ADDR, CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_(x) 		itg_set_reg(CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_CTRL_REG_ADDR, x, CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_EN_SHIFT, CLK_U0_DWC_ETHER_RMIIANDRGMII_ACLK_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_GMAC2_TXCK_ 			itg_set_reg(CLK_GMAC2_TXCK_CTRL_REG_ADDR, CLK_GMAC2_TXCK_ENABLE_DATA, CLK_GMAC2_TXCK_EN_SHIFT, CLK_GMAC2_TXCK_EN_MASK)
#define _DISABLE_CLOCK_CLK_GMAC2_TXCK_ 			itg_set_reg(CLK_GMAC2_TXCK_CTRL_REG_ADDR, CLK_GMAC2_TXCK_DISABLE_DATA, CLK_GMAC2_TXCK_EN_SHIFT, CLK_GMAC2_TXCK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_GMAC2_TXCK_ 		itg_get_reg(CLK_GMAC2_TXCK_CTRL_REG_ADDR, CLK_GMAC2_TXCK_EN_SHIFT, CLK_GMAC2_TXCK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_GMAC2_TXCK_(x) 		itg_set_reg(CLK_GMAC2_TXCK_CTRL_REG_ADDR, x, CLK_GMAC2_TXCK_EN_SHIFT, CLK_GMAC2_TXCK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_ENABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_DISABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_ 		itg_get_reg(CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_(x) 		itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_CTRL_REG_ADDR, x, CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_TX_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_ENABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_DISABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_ 		itg_get_reg(CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_(x) 		itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_CTRL_REG_ADDR, x, CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_RX_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_ENABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_DISABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_ 		itg_get_reg(CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_(x) 		itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_CTRL_REG_ADDR, x, CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_TX_125_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_ENABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_DISABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_ 		itg_get_reg(CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_(x) 		itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_CTRL_REG_ADDR, x, CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_RX_125_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_ENABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_DISABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_ 		itg_get_reg(CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_(x) 		itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_CTRL_REG_ADDR, x, CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_PTP_REF_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_ENABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_DISABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_ 		itg_get_reg(CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_(x) 		itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_CTRL_REG_ADDR, x, CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_REF_25_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_ENABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_DISABLE_DATA, CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_ 		itg_get_reg(CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_(x) 		itg_set_reg(CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_CTRL_REG_ADDR, x, CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_CLK_CSR_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_ACLK_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_ACLK_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_ACLK_I_ENABLE_DATA, CLK_U1_DWC_ETHER_SGMII_ACLK_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_ACLK_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_ACLK_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_ACLK_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_ACLK_I_DISABLE_DATA, CLK_U1_DWC_ETHER_SGMII_ACLK_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_ACLK_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_ACLK_I_ 		itg_get_reg(CLK_U1_DWC_ETHER_SGMII_ACLK_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_ACLK_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_ACLK_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_ACLK_I_(x) 		itg_set_reg(CLK_U1_DWC_ETHER_SGMII_ACLK_I_CTRL_REG_ADDR, x, CLK_U1_DWC_ETHER_SGMII_ACLK_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_ACLK_I_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_ENABLE_DATA, CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_ 			itg_set_reg(CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_DISABLE_DATA, CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_ 		itg_get_reg(CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_CTRL_REG_ADDR, CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_(x) 		itg_set_reg(CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_CTRL_REG_ADDR, x, CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_SHIFT, CLK_U1_DWC_ETHER_SGMII_SGMII_PHY_PCLK_I_EN_MASK)

#define _ENABLE_CLOCK_MAIN_ICG_EN_CAN0_ 			itg_set_reg(MAIN_ICG_EN_CAN0_CTRL_REG_ADDR, MAIN_ICG_EN_CAN0_ENABLE_DATA, MAIN_ICG_EN_CAN0_EN_SHIFT, MAIN_ICG_EN_CAN0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_CAN0_ 			itg_set_reg(MAIN_ICG_EN_CAN0_CTRL_REG_ADDR, MAIN_ICG_EN_CAN0_DISABLE_DATA, MAIN_ICG_EN_CAN0_EN_SHIFT, MAIN_ICG_EN_CAN0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CAN0_ 		itg_get_reg(MAIN_ICG_EN_CAN0_CTRL_REG_ADDR, MAIN_ICG_EN_CAN0_EN_SHIFT, MAIN_ICG_EN_CAN0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CAN0_(x) 		itg_set_reg(MAIN_ICG_EN_CAN0_CTRL_REG_ADDR, x, MAIN_ICG_EN_CAN0_EN_SHIFT, MAIN_ICG_EN_CAN0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_CAN1_ 			itg_set_reg(MAIN_ICG_EN_CAN1_CTRL_REG_ADDR, MAIN_ICG_EN_CAN1_ENABLE_DATA, MAIN_ICG_EN_CAN1_EN_SHIFT, MAIN_ICG_EN_CAN1_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_CAN1_ 			itg_set_reg(MAIN_ICG_EN_CAN1_CTRL_REG_ADDR, MAIN_ICG_EN_CAN1_DISABLE_DATA, MAIN_ICG_EN_CAN1_EN_SHIFT, MAIN_ICG_EN_CAN1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CAN1_ 		itg_get_reg(MAIN_ICG_EN_CAN1_CTRL_REG_ADDR, MAIN_ICG_EN_CAN1_EN_SHIFT, MAIN_ICG_EN_CAN1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_CAN1_(x) 		itg_set_reg(MAIN_ICG_EN_CAN1_CTRL_REG_ADDR, x, MAIN_ICG_EN_CAN1_EN_SHIFT, MAIN_ICG_EN_CAN1_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_DMAC_1CH_ 			itg_set_reg(MAIN_ICG_EN_DMAC_1CH_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_1CH_ENABLE_DATA, MAIN_ICG_EN_DMAC_1CH_EN_SHIFT, MAIN_ICG_EN_DMAC_1CH_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_DMAC_1CH_ 			itg_set_reg(MAIN_ICG_EN_DMAC_1CH_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_1CH_DISABLE_DATA, MAIN_ICG_EN_DMAC_1CH_EN_SHIFT, MAIN_ICG_EN_DMAC_1CH_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_DMAC_1CH_ 		itg_get_reg(MAIN_ICG_EN_DMAC_1CH_CTRL_REG_ADDR, MAIN_ICG_EN_DMAC_1CH_EN_SHIFT, MAIN_ICG_EN_DMAC_1CH_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_DMAC_1CH_(x) 		itg_set_reg(MAIN_ICG_EN_DMAC_1CH_CTRL_REG_ADDR, x, MAIN_ICG_EN_DMAC_1CH_EN_SHIFT, MAIN_ICG_EN_DMAC_1CH_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_RTC_SCAN_ 			itg_set_reg(MAIN_ICG_EN_RTC_SCAN_CTRL_REG_ADDR, MAIN_ICG_EN_RTC_SCAN_ENABLE_DATA, MAIN_ICG_EN_RTC_SCAN_EN_SHIFT, MAIN_ICG_EN_RTC_SCAN_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_RTC_SCAN_ 			itg_set_reg(MAIN_ICG_EN_RTC_SCAN_CTRL_REG_ADDR, MAIN_ICG_EN_RTC_SCAN_DISABLE_DATA, MAIN_ICG_EN_RTC_SCAN_EN_SHIFT, MAIN_ICG_EN_RTC_SCAN_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_RTC_SCAN_ 		itg_get_reg(MAIN_ICG_EN_RTC_SCAN_CTRL_REG_ADDR, MAIN_ICG_EN_RTC_SCAN_EN_SHIFT, MAIN_ICG_EN_RTC_SCAN_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_RTC_SCAN_(x) 		itg_set_reg(MAIN_ICG_EN_RTC_SCAN_CTRL_REG_ADDR, x, MAIN_ICG_EN_RTC_SCAN_EN_SHIFT, MAIN_ICG_EN_RTC_SCAN_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_ADC0_ 			itg_set_reg(MAIN_ICG_EN_ADC0_CTRL_REG_ADDR, MAIN_ICG_EN_ADC0_ENABLE_DATA, MAIN_ICG_EN_ADC0_EN_SHIFT, MAIN_ICG_EN_ADC0_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_ADC0_ 			itg_set_reg(MAIN_ICG_EN_ADC0_CTRL_REG_ADDR, MAIN_ICG_EN_ADC0_DISABLE_DATA, MAIN_ICG_EN_ADC0_EN_SHIFT, MAIN_ICG_EN_ADC0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_ADC0_ 		itg_get_reg(MAIN_ICG_EN_ADC0_CTRL_REG_ADDR, MAIN_ICG_EN_ADC0_EN_SHIFT, MAIN_ICG_EN_ADC0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_ADC0_(x) 		itg_set_reg(MAIN_ICG_EN_ADC0_CTRL_REG_ADDR, x, MAIN_ICG_EN_ADC0_EN_SHIFT, MAIN_ICG_EN_ADC0_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_ADC1_ 			itg_set_reg(MAIN_ICG_EN_ADC1_CTRL_REG_ADDR, MAIN_ICG_EN_ADC1_ENABLE_DATA, MAIN_ICG_EN_ADC1_EN_SHIFT, MAIN_ICG_EN_ADC1_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_ADC1_ 			itg_set_reg(MAIN_ICG_EN_ADC1_CTRL_REG_ADDR, MAIN_ICG_EN_ADC1_DISABLE_DATA, MAIN_ICG_EN_ADC1_EN_SHIFT, MAIN_ICG_EN_ADC1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_ADC1_ 		itg_get_reg(MAIN_ICG_EN_ADC1_CTRL_REG_ADDR, MAIN_ICG_EN_ADC1_EN_SHIFT, MAIN_ICG_EN_ADC1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_ADC1_(x) 		itg_set_reg(MAIN_ICG_EN_ADC1_CTRL_REG_ADDR, x, MAIN_ICG_EN_ADC1_EN_SHIFT, MAIN_ICG_EN_ADC1_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_GMAC2_ 			itg_set_reg(MAIN_ICG_EN_GMAC2_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC2_ENABLE_DATA, MAIN_ICG_EN_GMAC2_EN_SHIFT, MAIN_ICG_EN_GMAC2_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_GMAC2_ 			itg_set_reg(MAIN_ICG_EN_GMAC2_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC2_DISABLE_DATA, MAIN_ICG_EN_GMAC2_EN_SHIFT, MAIN_ICG_EN_GMAC2_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC2_ 		itg_get_reg(MAIN_ICG_EN_GMAC2_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC2_EN_SHIFT, MAIN_ICG_EN_GMAC2_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC2_(x) 		itg_set_reg(MAIN_ICG_EN_GMAC2_CTRL_REG_ADDR, x, MAIN_ICG_EN_GMAC2_EN_SHIFT, MAIN_ICG_EN_GMAC2_EN_MASK)
#define _ENABLE_CLOCK_MAIN_ICG_EN_GMAC3_ 			itg_set_reg(MAIN_ICG_EN_GMAC3_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC3_ENABLE_DATA, MAIN_ICG_EN_GMAC3_EN_SHIFT, MAIN_ICG_EN_GMAC3_EN_MASK)
#define _DISABLE_CLOCK_MAIN_ICG_EN_GMAC3_ 			itg_set_reg(MAIN_ICG_EN_GMAC3_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC3_DISABLE_DATA, MAIN_ICG_EN_GMAC3_EN_SHIFT, MAIN_ICG_EN_GMAC3_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC3_ 		itg_get_reg(MAIN_ICG_EN_GMAC3_CTRL_REG_ADDR, MAIN_ICG_EN_GMAC3_EN_SHIFT, MAIN_ICG_EN_GMAC3_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_MAIN_ICG_EN_GMAC3_(x) 		itg_set_reg(MAIN_ICG_EN_GMAC3_CTRL_REG_ADDR, x, MAIN_ICG_EN_GMAC3_EN_SHIFT, MAIN_ICG_EN_GMAC3_EN_MASK)


#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BMCPERIPH2_IOMUX_PRESETN_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH2_IOMUX_PRESETN_SHIFT, RSTN_U0_BMCPERIPH2_IOMUX_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BMCPERIPH2_IOMUX_PRESETN_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH2_IOMUX_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BMCPERIPH2_IOMUX_PRESETN_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH2_IOMUX_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BMCPERIPH2_POK_IOMUX_PRESETN_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH2_POK_IOMUX_PRESETN_SHIFT, RSTN_U0_BMCPERIPH2_POK_IOMUX_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BMCPERIPH2_POK_IOMUX_PRESETN_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH2_POK_IOMUX_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BMCPERIPH2_POK_IOMUX_PRESETN_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH2_POK_IOMUX_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_BMCPERIPH2_SYSREG_RSTN_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH2_SYSREG_RSTN_SHIFT, RSTN_U0_BMCPERIPH2_SYSREG_RSTN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_BMCPERIPH2_SYSREG_RSTN_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH2_SYSREG_RSTN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_BMCPERIPH2_SYSREG_RSTN_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_BMCPERIPH2_SYSREG_RSTN_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_CAN0_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_CAN0_SHIFT, MAIN_RSTN_CAN0_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_CAN0_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_CAN0_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_CAN0_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_CAN0_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_CAN1_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_CAN1_SHIFT, MAIN_RSTN_CAN1_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_CAN1_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_CAN1_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_CAN1_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_CAN1_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_FAN_TACH_PRESETN_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_FAN_TACH_PRESETN_SHIFT, RSTN_U0_FAN_TACH_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_FAN_TACH_PRESETN_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_FAN_TACH_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_FAN_TACH_PRESETN_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_FAN_TACH_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_GMAC2_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC2_SHIFT, MAIN_RSTN_GMAC2_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_GMAC2_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC2_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_GMAC2_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC2_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_GMAC3_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC3_SHIFT, MAIN_RSTN_GMAC3_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_GMAC3_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC3_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_GMAC3_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_GMAC3_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_DMAC_8CH_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_8CH_SHIFT, MAIN_RSTN_DMAC_8CH_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_DMAC_8CH_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_8CH_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_DMAC_8CH_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_DMAC_8CH_MASK)
#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_RTC_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_RTC_SHIFT, MAIN_RSTN_RTC_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_RTC_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_RTC_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_RTC_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_RTC_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_ADC_PRESETN_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_ADC_PRESETN_SHIFT, RSTN_U0_ADC_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_ADC_PRESETN_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_ADC_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_ADC_PRESETN_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_ADC_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_ADC_IOMUX_PRESETN_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_ADC_IOMUX_PRESETN_SHIFT, RSTN_U0_ADC_IOMUX_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_ADC_IOMUX_PRESETN_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_ADC_IOMUX_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_ADC_IOMUX_PRESETN_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_ADC_IOMUX_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_ADC_PRESETN_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_ADC_PRESETN_SHIFT, RSTN_U1_ADC_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_ADC_PRESETN_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_ADC_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_ADC_PRESETN_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_ADC_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_ADC_IOMUX_PRESETN_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_ADC_IOMUX_PRESETN_SHIFT, RSTN_U1_ADC_IOMUX_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_ADC_IOMUX_PRESETN_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_ADC_IOMUX_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_ADC_IOMUX_PRESETN_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_ADC_IOMUX_PRESETN_MASK)
// #define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_SENSOR_ 	itg_get_reg(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SENSOR_SHIFT, MAIN_RSTN_SENSOR_MASK)
// #define _ASSERT_RESET_RSTGEN_MAIN_RSTN_SENSOR_ 	itg_assert_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SENSOR_MASK)
// #define _CLEAR_RESET_RSTGEN_MAIN_RSTN_SENSOR_ 	itg_clear_rst(BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SENSOR_MASK)


#endif //_BMCPERIPH2_CRG_MACRO_H_
