
#ifndef _BMCPERIPH2_SECURE_CRG_MACRO_H_
#define _BMCPERIPH2_SECURE_CRG_MACRO_H_

//#define BMCPERIPH2_SECURE_CRG_BASE_ADDR 0x0
#define CLK_U10_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR                 (U0_BMCPERIPH2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_U0_PWM_8CH_PCLK_CTRL_REG_ADDR                            (U0_BMCPERIPH2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x4U)


#define BMCPERIPH2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR (U0_BMCPERIPH2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0x8U)

#define BMCPERIPH2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR (U0_BMCPERIPH2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR + 0xCU)


#define CLK_U10_DWC_SENSORS_PD_CLK_SYS_ENABLE_DATA                   1
#define CLK_U10_DWC_SENSORS_PD_CLK_SYS_DISABLE_DATA                  0
#define CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT                      31
#define CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_MASK                       0x80000000U
#define CLK_U0_PWM_8CH_PCLK_ENABLE_DATA                              1
#define CLK_U0_PWM_8CH_PCLK_DISABLE_DATA                             0
#define CLK_U0_PWM_8CH_PCLK_EN_SHIFT                                 31
#define CLK_U0_PWM_8CH_PCLK_EN_MASK                                  0x80000000U




#define MAIN_RSTN_SENSOR_SHIFT                                       0
#define MAIN_RSTN_SENSOR_MASK                                        (0x1 << 0)
#define MAIN_RSTN_SENSOR_ASSERT                                      1
#define MAIN_RSTN_SENSOR_CLEAR                                       0

#define _ENABLE_CLOCK_CLK_U10_DWC_SENSORS_PD_CLK_SYS_ 			itg_set_reg(CLK_U10_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U10_DWC_SENSORS_PD_CLK_SYS_ENABLE_DATA, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _DISABLE_CLOCK_CLK_U10_DWC_SENSORS_PD_CLK_SYS_ 			itg_set_reg(CLK_U10_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U10_DWC_SENSORS_PD_CLK_SYS_DISABLE_DATA, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U10_DWC_SENSORS_PD_CLK_SYS_ 		itg_get_reg(CLK_U10_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U10_DWC_SENSORS_PD_CLK_SYS_(x) 		itg_set_reg(CLK_U10_DWC_SENSORS_PD_CLK_SYS_CTRL_REG_ADDR, x, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_SHIFT, CLK_U10_DWC_SENSORS_PD_CLK_SYS_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_PWM_8CH_PCLK_ 			itg_set_reg(CLK_U0_PWM_8CH_PCLK_CTRL_REG_ADDR, CLK_U0_PWM_8CH_PCLK_ENABLE_DATA, CLK_U0_PWM_8CH_PCLK_EN_SHIFT, CLK_U0_PWM_8CH_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_PWM_8CH_PCLK_ 			itg_set_reg(CLK_U0_PWM_8CH_PCLK_CTRL_REG_ADDR, CLK_U0_PWM_8CH_PCLK_DISABLE_DATA, CLK_U0_PWM_8CH_PCLK_EN_SHIFT, CLK_U0_PWM_8CH_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_PWM_8CH_PCLK_ 		itg_get_reg(CLK_U0_PWM_8CH_PCLK_CTRL_REG_ADDR, CLK_U0_PWM_8CH_PCLK_EN_SHIFT, CLK_U0_PWM_8CH_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_PWM_8CH_PCLK_(x) 		itg_set_reg(CLK_U0_PWM_8CH_PCLK_CTRL_REG_ADDR, x, CLK_U0_PWM_8CH_PCLK_EN_SHIFT, CLK_U0_PWM_8CH_PCLK_EN_MASK)



#define _READ_RESET_STATUS_RSTGEN_MAIN_RSTN_SENSOR_ 	itg_get_reg(BMCPERIPH2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SENSOR_SHIFT, MAIN_RSTN_SENSOR_MASK)
#define _ASSERT_RESET_RSTGEN_MAIN_RSTN_SENSOR_ 	itg_assert_rst(BMCPERIPH2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SENSOR_MASK)
#define _CLEAR_RESET_RSTGEN_MAIN_RSTN_SENSOR_ 	itg_clear_rst(BMCPERIPH2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, BMCPERIPH2_SECURE_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, MAIN_RSTN_SENSOR_MASK)


#endif //_BMCPERIPH2_SECURE_CRG_MACRO_H_
