#define  U0_DWC_ETHER_RMIIANDRGMII__ITG_BD_APB__BASE_ADDR                                                     0x0011B80000
#define  U1_DWC_ETHER_SGMII__ITG_BD_APB__BASE_ADDR                                                            0x0011B84000
#define  U10_DWC_SENSORS_PD__ITG_BD_APBS__BASE_ADDR                                                           0x0011B88000
#define  U0_BMCPERIPH2_CRG__ITG_BD_APBS__BASE_ADDR                                                            0x0011BC0000
#define  U0_BMCPERIPH2_SYSCON__ITG_BD_APBS__BASE_ADDR                                                         0x0011BC1000
#define  U0_BMCPERIPH2_IOMUX__ITG_BD_APBS__BASE_ADDR                                                          0x0011BC2000
#define  U0_FAN_TACH__ITG_BD_APB__BASE_ADDR                                                                   0x0011BE0000
#define  U0_PWM_8CH__ITG_BD_APB__BASE_ADDR                                                                    0x0011BE0400
#define  U0_DW_AXI_DMAC_8CH__ITG_BD_APB__BASE_ADDR                                                            0x0011BE0C00
#define  U0_CAN_CTRL__ITG_BD_APB__BASE_ADDR                                                                   0x0011BE1100
#define  U1_CAN_CTRL__ITG_BD_APB__BASE_ADDR                                                                   0x0011BE1200
#define  U0_RTC_HMS__ITG_BD_APB__BASE_ADDR                                                                    0x0011BE1300
#define  U0_ADC__ITG_BD_APB__BASE_ADDR                                                                        0x0011BE1400
#define  U0_BMCPERIPH2_SECURE_CRG__ITG_BD_APBS__BASE_ADDR                                                     0x001413C000
#define  U0_BMCPERIPH2_SECURE_SYSCON__ITG_BD_APBS__BASE_ADDR                                                  0x001413D000


#define  U0_DWC_ETHER_RMIIANDRGMII__ITG_BD_APB__END_ADDR                                                      0x0011B83FFF
#define  U1_DWC_ETHER_SGMII__ITG_BD_APB__END_ADDR                                                             0x0011B87FFF
#define  U10_DWC_SENSORS_PD__ITG_BD_APBS__END_ADDR                                                            0x0011B8BFFF
#define  U0_BMCPERIPH2_CRG__ITG_BD_APBS__END_ADDR                                                             0x0011BC0FFF
#define  U0_BMCPERIPH2_SYSCON__ITG_BD_APBS__END_ADDR                                                          0x0011BC1FFF
#define  U0_BMCPERIPH2_IOMUX__ITG_BD_APBS__END_ADDR                                                           0x0011BC2FFF
#define  U0_FAN_TACH__ITG_BD_APB__END_ADDR                                                                    0x0011BE03FF
#define  U0_PWM_8CH__ITG_BD_APB__END_ADDR                                                                     0x0011BE07FF
#define  U0_DW_AXI_DMAC_8CH__ITG_BD_APB__END_ADDR                                                             0x0011BE0FFF
#define  U0_CAN_CTRL__ITG_BD_APB__END_ADDR                                                                    0x0011BE11FF
#define  U1_CAN_CTRL__ITG_BD_APB__END_ADDR                                                                    0x0011BE12FF
#define  U0_RTC_HMS__ITG_BD_APB__END_ADDR                                                                     0x0011BE13FF
#define  U0_ADC__ITG_BD_APB__END_ADDR                                                                         0x0011BE17FF
#define  U0_BMCPERIPH2_SECURE_CRG__ITG_BD_APBS__END_ADDR                                                      0x001413CFFF
#define  U0_BMCPERIPH2_SECURE_SYSCON__ITG_BD_APBS__END_ADDR                                                   0x001413DFFF
